/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
int sub_8048C70();
// int strcmp(const char *s1, const char *s2);
// int __cdecl open64(_DWORD, _DWORD); weak
// int printf(const char *format, ...);
// int fflush(FILE *stream);
// void _exit(int status);
// void free(void *ptr);
// void *memcpy(void *dest, const void *src, size_t n);
// int mbsinit(const mbstate_t *ps);
// int fclose(FILE *stream);
// int getc_unlocked(FILE *stream);
// int __cdecl fseeko64(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int memcmp(const void *s1, const void *s2, size_t n);
// char *textdomain(const char *domainname);
// int iswprint(wint_t wc);
// int __cdecl fopen64(_DWORD, _DWORD); weak
// int ferror_unlocked(FILE *stream);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// size_t __ctype_get_mb_cur_max(void);
// char *strcpy(char *dest, const char *src);
// size_t __fpending(FILE *fp);
// size_t mbrtowc(wchar_t *pwc, const char *s, size_t n, mbstate_t *p);
// int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD); weak
// void error(int status, int errnum, const char *format, ...);
// char *getenv(const char *name);
// void *realloc(void *ptr, size_t size);
// void *malloc(size_t size);
// int __freading(FILE *fp);
// void exit(int status);
// char *gettext(const char *msgid);
// FILE *fdopen(int fd, const char *modes);
// int __cdecl fputs_unlocked(_DWORD, _DWORD); weak
// int getopt_long(int argc, char *const *argv, const char *shortopts, const struct option *longopts, int *longind);
// int fscanf(FILE *stream, const char *format, ...);
// size_t strlen(const char *s);
// int fprintf(FILE *stream, const char *format, ...);
// void *memset(void *s, int c, size_t n);
// int ungetc(int c, FILE *stream);
// int *__errno_location(void);
// int fileno(FILE *stream);
// int __cdecl strndup(_DWORD, _DWORD); weak
// char *nl_langinfo(nl_item item);
// char *setlocale(int category, const char *locale);
// void clearerr_unlocked(FILE *stream);
// char *strrchr(const char *s, int c);
// int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD); weak
// char *bindtextdomain(const char *domainname, const char *dirname);
// int __cdecl posix_fadvise64(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int strncmp(const char *s1, const char *s2, size_t n);
// void abort(void);
// int close(int fd);
// size_t strspn(const char *s, const char *accept);
// void __assert_fail(const char *assertion, const char *file, unsigned int line, const char *function);
// const unsigned __int16 **__ctype_b_loc(void);
// int putchar_unlocked(int c);
// int _gmon_start__(void); weak
void sub_8049053();
void sub_8049070();
int sub_8049080();
int sub_80490F0();
int sub_8049110();
void sub_804916F();
void sub_804918A();
int sub_804919A();
int sub_804924A();
int sub_8049275();
int __cdecl sub_80492A0(char *s1); // idb
void __cdecl __noreturn sub_8049426(int status); // idb
char sub_804951C();
int __cdecl main(int argc, char **argv);
int __cdecl sub_804992D(unsigned __int8 a1);
int __cdecl sub_804993F(unsigned __int64 a1);
int __cdecl sub_8049A65(__int64 a1);
int __cdecl sub_8049ACB(__int64 a1);
int __cdecl sub_8049B31(unsigned __int8 *a1);
void __cdecl sub_8049EF3(int a1, unsigned int a2);
int sub_804A00A();
int __cdecl sub_804A0E6(unsigned __int64 a1, _DWORD *a2, _BYTE *a3);
int __cdecl sub_804A2C6(int a1);
FILE *__cdecl sub_804A2EC(FILE *stream);
void sub_804A4E6();
int sub_804A529();
int sub_804A596();
int __cdecl sub_804A67A(int a1, int a2, int a3, int a4, int a5, int a6);
void __cdecl sub_804A6CB(FILE *stream, int a2);
char *__cdecl sub_804A713(char *s);
int __cdecl sub_804A85F(int *a1, unsigned __int8 a2, char a3);
int *__cdecl sub_804A909(int *a1, int a2, int a3);
// _DWORD *__userpurge sub_804A94A@<eax>(_DWORD *a1, int a2);
const char *__cdecl sub_804A9CC(char *msgid, int a2);
unsigned int __cdecl sub_804AA67(int a1, unsigned int a2, int a3, size_t a4, signed int a5, int a6, int a7, char *a8, char *a9);
void *__cdecl sub_804B6FE(int a1, size_t a2, _DWORD *a3, int *a4);
void *__cdecl sub_804B8A5(signed int a1, int a2, size_t a3, int a4);
void *__cdecl sub_804BACE(signed int a1, int a2);
void *__cdecl sub_804BAF8(signed int a1, int a2, size_t a3);
void *__cdecl sub_804BB5E(signed int a1, int a2, int a3);
void *__cdecl sub_804BB9C(signed int a1, int a2, int a3, size_t a4);
void *__cdecl sub_804BC24(int a1, size_t a2, unsigned __int8 a3);
void *__cdecl sub_804BCCE(int a1, unsigned __int8 a2);
void *__cdecl sub_804BCF7(int a1);
void *__cdecl sub_804BD34(signed int a1, int a2, int a3);
void *__cdecl sub_804BDD5(signed int a1, int a2, int a3, int a4);
void *__cdecl sub_804BE05(signed int a1, int a2, int a3, int a4, size_t a5);
void *__cdecl sub_804BEFF(signed int a1, int a2, size_t a3);
void *__cdecl sub_804BF4A(signed int a1, int a2);
void *__cdecl sub_804BF6C(int a1);
int __cdecl sub_804BF87(FILE *stream, int, int, int, int, int); // idb
int __cdecl sub_804C4EC(FILE *stream, int, int, int, int); // idb
int sub_804C552(FILE *stream, int a2, int a3, int a4, ...);
void *__cdecl sub_804C655(void *ptr, int a2, int a3);
void *__cdecl sub_804C6EC(size_t size);
void *__cdecl sub_804C6FF(size_t size);
void *__cdecl sub_804C729(void *ptr, size_t size);
void *__cdecl sub_804C801(void *src, size_t n);
void __noreturn sub_804C84F();
int __cdecl sub_804C888(int a1, int a2);
int __cdecl sub_804C8B3(FILE *stream); // idb
int __cdecl sub_804C976(FILE *stream); // idb
int __cdecl sub_804C9AF(FILE *fp); // idb
int __cdecl sub_804C9EF(FILE *stream, int, int, int); // idb
size_t __cdecl sub_804CAC1(wchar_t *pwc, char *s, size_t n, mbstate_t *p);
int __cdecl sub_804CB33(unsigned __int8 *a1, unsigned __int8 *a2);
int __cdecl sub_804CB98(FILE *fp); // idb
int __cdecl sub_804CC19(int category); // idb
void *sub_804CC77();
const char *sub_804D0EF();
int __cdecl sub_804D364(int a1);
int __cdecl sub_804D3A4(unsigned __int64 a1, __int64 a2);
int __cdecl sub_804D567(int a1);
int (**sub_804D590())();
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

char locale = '\0'; // idb
struct option longopts = { "tabs", 1, NULL, 116 }; // idb
_UNKNOWN unk_804DF3E; // weak
_UNKNOWN unk_804DF42; // weak
_UNKNOWN unk_804DF4E; // weak
_UNKNOWN unk_804DF52; // weak
_UNKNOWN unk_804DF55; // weak
_UNKNOWN unk_804E673; // weak
int (*off_8050F04[2])() = { &sub_8049110, &sub_80490F0 }; // weak
int (*off_8050F08)() = &sub_80490F0; // weak
int (*dword_8051008)(void) = NULL; // weak
int dword_8051100 = 0; // weak
char *off_8051104 = "-"; // weak
int off_805110C = 134536699; // idb
int status = 1; // idb
int dword_805111C = 1; // weak
int dword_8051120 = 256; // weak
void *off_8051124 = &unk_80512AD; // weak
int *off_8051128 = &dword_8051120; // weak
_UNKNOWN unk_805113C; // weak
_UNKNOWN unk_805116C; // weak
_UNKNOWN unk_805116F; // weak
_UNKNOWN unk_8051170; // weak
_UNKNOWN unk_8051173; // weak
int program_invocation_short_name; // weak
FILE *stderr; // idb
int program_invocation_name; // weak
int optind; // weak
FILE *stdin; // idb
FILE *stdout; // idb
int optarg; // weak
char byte_80511CC; // weak
char byte_805121D; // weak
int dword_8051221; // weak
__int64 qword_8051225; // weak
__int64 qword_805122D; // weak
__int64 qword_8051235; // weak
void *ptr; // idb
int dword_8051241; // weak
int dword_8051245; // weak
int dword_8051249; // weak
char byte_805124D; // weak
char *s1; // idb
int dword_8051255; // weak
char byte_8051259; // weak
int dword_805125D; // weak
int dword_805126D; // weak
int dword_8051271; // weak
int dword_8051275; // weak
int dword_8051279; // weak
int dword_805127D; // weak
int dword_8051281; // weak
int dword_8051285; // weak
int dword_8051289; // weak
int dword_805128D; // weak
int dword_8051291; // weak
int dword_8051295; // weak
int dword_8051299; // weak
_UNKNOWN unk_80512AD; // weak
int dword_80513AD; // weak
int dword_80513B1; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (08048C4C) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 8049010: using guessed type int _gmon_start__(void);

//----- (08048C70) --------------------------------------------------------
int sub_8048C70()
{
  return dword_8051008();
}
// 8051008: using guessed type int (*dword_8051008)(void);

//----- (08049020) --------------------------------------------------------
#error "8049023: positive sp value has been found (funcsize=2)"

//----- (08049053) --------------------------------------------------------
void sub_8049053()
{
  ;
}

//----- (08049070) --------------------------------------------------------
void sub_8049070()
{
  ;
}

//----- (08049080) --------------------------------------------------------
int sub_8049080()
{
  int result; // eax

  result = &unk_805116F - &unk_805116C;
  if ( (unsigned int)(&unk_805116F - &unk_805116C) > 6 )
    result = 0;
  return result;
}
// 8049080: could not find valid save-restore pair for ebp

//----- (080490F0) --------------------------------------------------------
int sub_80490F0()
{
  int result; // eax

  if ( !byte_80511CC )
  {
    result = sub_8049080();
    byte_80511CC = 1;
  }
  return result;
}
// 80490F0: could not find valid save-restore pair for ebp
// 80511CC: using guessed type char byte_80511CC;

//----- (08049110) --------------------------------------------------------
int sub_8049110()
{
  return 0;
}
// 8049110: could not find valid save-restore pair for ebp

//----- (0804916F) --------------------------------------------------------
void sub_804916F()
{
  ;
}

//----- (0804918A) --------------------------------------------------------
void sub_804918A()
{
  ;
}

//----- (0804919A) --------------------------------------------------------
int sub_804919A()
{
  int result; // eax

  result = &unk_8051173 - &unk_8051170;
  if ( (unsigned int)(&unk_8051173 - &unk_8051170) > 6 )
    result = 0;
  return result;
}
// 804919A: could not find valid save-restore pair for ebp

//----- (0804924A) --------------------------------------------------------
int sub_804924A()
{
  FILE *v0; // ebx
  char *v1; // eax

  v0 = stdout;
  v1 = gettext("\nWith no FILE, or when FILE is -, read standard input.\n");
  return fputs_unlocked(v1, v0);
}
// 8048E70: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);

//----- (08049275) --------------------------------------------------------
int sub_8049275()
{
  FILE *v0; // ebx
  char *v1; // eax

  v0 = stdout;
  v1 = gettext("\nMandatory arguments to long options are mandatory for short options too.\n");
  return fputs_unlocked(v1, v0);
}
// 8048E70: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);

//----- (080492A0) --------------------------------------------------------
int __cdecl sub_80492A0(char *s1)
{
  char *v1; // eax
  char *v2; // eax
  char *v3; // eax
  char *v4; // ebx
  char *v5; // eax
  char *v7; // [esp+1Ch] [ebp-4Ch]
  const char **i; // [esp+20h] [ebp-48h]
  const char *v9; // [esp+24h] [ebp-44h]
  const char *v10; // [esp+28h] [ebp-40h]
  const char *v11; // [esp+2Ch] [ebp-3Ch]
  const char *v12; // [esp+30h] [ebp-38h]
  const char *v13; // [esp+34h] [ebp-34h]
  const char *v14; // [esp+38h] [ebp-30h]
  const char *v15; // [esp+3Ch] [ebp-2Ch]
  const char *v16; // [esp+40h] [ebp-28h]
  const char *v17; // [esp+44h] [ebp-24h]
  const char *v18; // [esp+48h] [ebp-20h]
  const char *v19; // [esp+4Ch] [ebp-1Ch]
  const char *v20; // [esp+50h] [ebp-18h]
  const char *v21; // [esp+54h] [ebp-14h]
  int v22; // [esp+58h] [ebp-10h]
  int v23; // [esp+5Ch] [ebp-Ch]

  v10 = "[";
  v11 = "test invocation";
  v12 = "coreutils";
  v13 = "Multi-call invocation";
  v14 = "sha224sum";
  v15 = "sha2 utilities";
  v16 = "sha256sum";
  v17 = "sha2 utilities";
  v18 = "sha384sum";
  v19 = "sha2 utilities";
  v20 = "sha512sum";
  v21 = "sha2 utilities";
  v22 = 0;
  v23 = 0;
  v7 = s1;
  for ( i = &v10; *i && strcmp(s1, *i); i += 2 )
    ;
  if ( i[1] )
    v7 = (char *)i[1];
  v1 = gettext("\n%s online help: <%s>\n");
  printf(v1, "GNU coreutils", "http://www.gnu.org/software/coreutils/");
  v9 = setlocale(5, 0);
  if ( v9 && strncmp(v9, "en_", 3u) )
  {
    v2 = gettext("Report %s translation bugs to <http://translationproject.org/team/>\n");
    printf(v2, s1);
  }
  v3 = gettext("Full documentation at: <%s%s>\n");
  printf(v3, "http://www.gnu.org/software/coreutils/", s1);
  if ( v7 == s1 )
    v4 = " invocation";
  else
    v4 = &locale;
  v5 = gettext("or available locally via: info '(coreutils) %s%s'\n");
  return printf(v5, v7, v4);
}

//----- (08049426) --------------------------------------------------------
void __cdecl __noreturn sub_8049426(int status)
{
  int v1; // ebx
  char *v2; // eax
  int v3; // ebx
  char *v4; // eax
  FILE *v5; // ebx
  char *v6; // eax
  FILE *v7; // ebx
  char *v8; // eax
  FILE *v9; // ebx
  char *v10; // eax
  FILE *v11; // ebx
  char *v12; // eax

  if ( status )
  {
    v1 = dword_805125D;
    v2 = gettext("Try '%s --help' for more information.\n");
    fprintf(stderr, v2, v1);
  }
  else
  {
    v3 = dword_805125D;
    v4 = gettext("Usage: %s [OPTION]... [FILE]...\n");
    printf(v4, v3);
    v5 = stdout;
    v6 = gettext("Convert tabs in each FILE to spaces, writing to standard output.\n");
    fputs_unlocked(v6, v5);
    sub_804924A();
    sub_8049275();
    v7 = stdout;
    v8 = gettext(
           "  -i, --initial    do not convert tabs after non blanks\n"
           "  -t, --tabs=N     have tabs N characters apart, not 8\n");
    fputs_unlocked(v8, v7);
    sub_804A529();
    v9 = stdout;
    v10 = gettext("      --help     display this help and exit\n");
    fputs_unlocked(v10, v9);
    v11 = stdout;
    v12 = gettext("      --version  output version information and exit\n");
    fputs_unlocked(v12, v11);
    sub_80492A0("expand");
  }
  exit(status);
}
// 8048E70: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);
// 805125D: using guessed type int dword_805125D;

//----- (0804951C) --------------------------------------------------------
char sub_804951C()
{
  int v0; // eax
  unsigned __int64 v1; // rax
  char *v2; // eax
  char *v3; // ebx
  int *v4; // eax
  char *v5; // eax
  int v6; // ebx
  char *v7; // ebx
  int *v8; // eax
  char v10; // [esp+12h] [ebp-26h]
  unsigned __int8 v11; // [esp+13h] [ebp-25h]
  int v12; // [esp+14h] [ebp-24h]
  FILE *stream; // [esp+18h] [ebp-20h]
  int c; // [esp+1Ch] [ebp-1Ch]
  unsigned __int64 v15; // [esp+20h] [ebp-18h]
  unsigned __int64 v16; // [esp+28h] [ebp-10h]

  v0 = (int)sub_804A2EC(0);
  stream = (FILE *)v0;
  if ( v0 )
  {
LABEL_2:
    v11 = 1;
    v15 = 0LL;
    v12 = 0;
    while ( 1 )
    {
      do
      {
        v0 = getc_unlocked(stream);
        c = v0;
        if ( v0 >= 0 )
          break;
        v0 = (int)sub_804A2EC(stream);
        stream = (FILE *)v0;
      }
      while ( v0 );
      if ( v11 )
      {
        if ( c == 9 )
        {
          LODWORD(v1) = sub_804A0E6(v15, &v12, &v10);
          v16 = v1;
          if ( v10 )
            v16 = v15 + 1;
          if ( v16 < v15 )
          {
            v2 = gettext("input line is too long");
            error(1, 0, v2);
            goto LABEL_11;
          }
          while ( ++v15 < v16 )
          {
LABEL_11:
            if ( putchar_unlocked(32) < 0 )
            {
              v3 = gettext("write error");
              v4 = __errno_location();
              error(1, *v4, v3);
            }
          }
          c = 32;
        }
        else if ( c == 8 )
        {
          v15 -= v15 != 0;
          v12 -= v12 != 0;
        }
        else if ( !++v15 )
        {
          v5 = gettext("input line is too long");
          error(1, 0, v5);
        }
        v6 = v11;
        v0 = byte_805121D || (*__ctype_b_loc())[c] & 1;
        LOBYTE(v0) = (v6 & v0) != 0;
        v11 = v0;
      }
      if ( c < 0 )
        break;
      if ( putchar_unlocked(c) < 0 )
      {
        v7 = gettext("write error");
        v8 = __errno_location();
        error(1, *v8, v7);
      }
      if ( c == 10 )
        goto LABEL_2;
    }
  }
  return v0;
}
// 805121D: using guessed type char byte_805121D;

//----- (08049773) --------------------------------------------------------
int __cdecl main(int argc, char **argv)
{
  char **v2; // eax
  char v4; // [esp+2Ah] [ebp-6h]
  char v5; // [esp+2Bh] [ebp-5h]
  int v6; // [esp+2Ch] [ebp-4h]

  sub_804A713(*argv);
  setlocale(6, &locale);
  bindtextdomain("coreutils", "/home/hwangdz/coreutils/coreutils-8.28/install_m32/share/locale");
  textdomain("coreutils");
  sub_804D567((int)sub_804A596);
  byte_805121D = 1;
  while ( 1 )
  {
    v6 = getopt_long(argc, argv, "it:0::1::2::3::4::5::6::7::8::9::", &longopts, 0);
    if ( v6 == -1 )
      break;
    if ( v6 > 57 )
    {
      if ( v6 == 105 )
      {
        byte_805121D = 0;
      }
      else
      {
        if ( v6 != 116 )
          goto LABEL_18;
        sub_8049B31((unsigned __int8 *)optarg);
      }
    }
    else
    {
      if ( v6 < 48 )
      {
        if ( v6 == -131 )
        {
          sub_804C552(stdout, (int)"expand", (int)"GNU coreutils", off_805110C, "David MacKenzie", 0);
          exit(0);
        }
        if ( v6 == -130 )
          sub_8049426(0);
LABEL_18:
        sub_8049426(1);
      }
      if ( optarg )
      {
        sub_8049B31((unsigned __int8 *)(optarg - 1));
      }
      else
      {
        v4 = v6;
        v5 = 0;
        sub_8049B31((unsigned __int8 *)&v4);
      }
    }
  }
  sub_804A00A();
  if ( optind >= argc )
    v2 = 0;
  else
    v2 = &argv[optind];
  sub_804A2C6((int)v2);
  sub_804951C();
  sub_804A4E6();
  return dword_8051221;
}
// 80511A0: using guessed type int optind;
// 80511C8: using guessed type int optarg;
// 805121D: using guessed type char byte_805121D;
// 8051221: using guessed type int dword_8051221;

//----- (0804992D) --------------------------------------------------------
int __cdecl sub_804992D(unsigned __int8 a1)
{
  return a1;
}

//----- (0804993F) --------------------------------------------------------
int __cdecl sub_804993F(unsigned __int64 a1)
{
  unsigned __int64 v1; // rax
  unsigned __int64 v2; // rax
  int v3; // eax
  int result; // eax
  char *v5; // eax
  unsigned __int64 v6; // [esp+28h] [ebp-10h]

  if ( dword_8051245 )
    v1 = *((_QWORD *)ptr + dword_8051245 + 0x1FFFFFFF);
  else
    v1 = 0LL;
  if ( v1 > a1 )
    v2 = 0LL;
  else
    v2 = a1 - v1;
  v6 = v2;
  if ( dword_8051245 == dword_8051241 )
    ptr = sub_804C655(ptr, (int)&dword_8051241, 8);
  v3 = dword_8051245++;
  *((_QWORD *)ptr + v3) = a1;
  result = dword_80513B1;
  if ( (unsigned int)dword_80513B1 < v6 )
  {
    if ( HIDWORD(v6) )
    {
      v5 = gettext("tabs are too far apart");
      error(1, 0, v5);
    }
    result = v6;
    dword_80513B1 = v6;
  }
  return result;
}
// 8051241: using guessed type int dword_8051241;
// 8051245: using guessed type int dword_8051245;
// 80513B1: using guessed type int dword_80513B1;

//----- (08049A65) --------------------------------------------------------
int __cdecl sub_8049A65(__int64 a1)
{
  char *v1; // eax
  unsigned __int8 v3; // [esp+2Fh] [ebp-9h]

  v3 = 1;
  if ( qword_805122D )
  {
    v1 = gettext("'/' specifier only allowed with the last value");
    error(0, 0, v1);
    v3 = 0;
  }
  qword_805122D = a1;
  return v3;
}
// 805122D: using guessed type __int64 qword_805122D;

//----- (08049ACB) --------------------------------------------------------
int __cdecl sub_8049ACB(__int64 a1)
{
  char *v1; // eax
  unsigned __int8 v3; // [esp+2Fh] [ebp-9h]

  v3 = 1;
  if ( qword_8051235 )
  {
    v1 = gettext("'+' specifier only allowed with the last value");
    error(0, 0, v1);
    v3 = 0;
  }
  qword_8051235 = a1;
  return v3;
}
// 805122D: using guessed type __int64 qword_805122D;
// 8051235: using guessed type __int64 qword_8051235;

//----- (08049B31) --------------------------------------------------------
int __cdecl sub_8049B31(unsigned __int8 *a1)
{
  const unsigned __int16 *v1; // ebx
  void *v2; // ebx
  char *v3; // eax
  void *v4; // ebx
  char *v5; // eax
  char v6; // al
  int v7; // ST20_4
  void *ptr; // ST24_4
  void *v9; // ebx
  char *v10; // eax
  void *v11; // ebx
  char *v12; // eax
  int result; // eax
  char v14; // [esp+18h] [ebp-20h]
  char v15; // [esp+19h] [ebp-1Fh]
  char v16; // [esp+1Ah] [ebp-1Eh]
  bool v17; // [esp+1Bh] [ebp-1Dh]
  char *s; // [esp+1Ch] [ebp-1Ch]
  unsigned __int64 v19; // [esp+28h] [ebp-10h]

  v14 = 0;
  v19 = 0LL;
  v15 = 0;
  v16 = 0;
  s = 0;
  v17 = 1;
  while ( *a1 )
  {
    if ( *a1 == 44 || (v1 = *__ctype_b_loc(), v1[(unsigned __int8)sub_804992D(*a1)] & 1) )
    {
      if ( v14 )
      {
        if ( v15 )
        {
          if ( (unsigned __int8)sub_8049A65(v19) ^ 1 )
          {
            v17 = 0;
            break;
          }
        }
        else if ( v16 )
        {
          if ( (unsigned __int8)sub_8049ACB(v19) ^ 1 )
          {
            v17 = 0;
            break;
          }
        }
        else
        {
          sub_804993F(v19);
        }
      }
      v14 = 0;
    }
    else if ( *a1 == 47 )
    {
      if ( v14 )
      {
        v2 = sub_804BF6C((int)a1);
        v3 = gettext("'/' specifier not at start of number: %s");
        error(0, 0, v3, v2);
        v17 = 0;
      }
      v15 = 1;
      v16 = 0;
    }
    else if ( *a1 == 43 )
    {
      if ( v14 )
      {
        v4 = sub_804BF6C((int)a1);
        v5 = gettext("'+' specifier not at start of number: %s");
        error(0, 0, v5, v4);
        v17 = 0;
      }
      v16 = 1;
      v15 = 0;
    }
    else
    {
      if ( (unsigned int)((char)*a1 - 48) > 9 )
      {
        v11 = sub_804BF6C((int)a1);
        v12 = gettext("tab size contains invalid character(s): %s");
        error(0, 0, v12, v11);
        v17 = 0;
        break;
      }
      if ( v14 != 1 )
      {
        v19 = 0LL;
        v14 = 1;
        s = (char *)a1;
      }
      if ( v19 > 0x1999999999999999LL || 10 * v19 + (char)*a1 - 48 < v19 )
      {
        v6 = 1;
      }
      else
      {
        v19 = (char)*a1 - 48 + 10 * v19;
        v6 = 0;
      }
      if ( v6 )
      {
        v7 = strspn(s, "0123456789");
        ptr = (void *)sub_804C888((int)s, v7);
        v9 = sub_804BF6C((int)ptr);
        v10 = gettext("tab stop is too large %s");
        error(0, 0, v10, v9);
        free(ptr);
        v17 = 0;
        a1 = (unsigned __int8 *)&s[v7 - 1];
      }
    }
    ++a1;
  }
  if ( v17 && v14 )
  {
    if ( v15 )
    {
      v17 = (v17 & (unsigned __int8)sub_8049A65(v19)) != 0;
    }
    else if ( v16 )
    {
      v17 = (v17 & (unsigned __int8)sub_8049ACB(v19)) != 0;
    }
    else
    {
      sub_804993F(v19);
    }
  }
  result = !v17;
  if ( v17 != 1 )
    exit(1);
  return result;
}

//----- (08049EF3) --------------------------------------------------------
void __cdecl sub_8049EF3(int a1, unsigned int a2)
{
  char *v2; // eax
  char *v3; // eax
  char *v4; // eax
  unsigned int i; // [esp+14h] [ebp-14h]
  unsigned __int64 v6; // [esp+18h] [ebp-10h]

  v6 = 0LL;
  for ( i = 0; i < a2; ++i )
  {
    if ( !*(_QWORD *)(8 * i + a1) )
    {
      v2 = gettext("tab size cannot be 0");
      error(1, 0, v2);
    }
    if ( *(_QWORD *)(8 * i + a1) <= v6 )
    {
      v3 = gettext("tab sizes must be ascending");
      error(1, 0, v3);
    }
    v6 = *(_QWORD *)(8 * i + a1);
  }
  if ( qword_8051235 )
  {
    if ( qword_805122D )
    {
      v4 = gettext("'/' specifier is mutually exclusive with '+'");
      error(1, 0, v4);
    }
  }
}
// 805122D: using guessed type __int64 qword_805122D;
// 8051235: using guessed type __int64 qword_8051235;

//----- (0804A00A) --------------------------------------------------------
int sub_804A00A()
{
  signed int v0; // eax
  int result; // eax
  int v2; // edx

  sub_8049EF3((int)ptr, dword_8051245);
  if ( dword_8051245 )
  {
    result = dword_8051245;
    if ( dword_8051245 != 1
      || (result = HIDWORD(qword_805122D) | qword_805122D, qword_805122D)
      || (result = HIDWORD(qword_8051235) | qword_8051235, qword_8051235) )
    {
      qword_8051225 = 0LL;
    }
    else
    {
      v2 = *((_DWORD *)ptr + 1);
      result = *(_DWORD *)ptr;
      LODWORD(qword_8051225) = *(_DWORD *)ptr;
      HIDWORD(qword_8051225) = v2;
    }
  }
  else
  {
    if ( qword_805122D )
    {
      v0 = qword_805122D;
    }
    else if ( qword_8051235 )
    {
      v0 = qword_8051235;
    }
    else
    {
      v0 = 8;
    }
    dword_80513B1 = v0;
    result = dword_80513B1;
    qword_8051225 = (unsigned int)dword_80513B1;
  }
  return result;
}
// 8051225: using guessed type __int64 qword_8051225;
// 805122D: using guessed type __int64 qword_805122D;
// 8051235: using guessed type __int64 qword_8051235;
// 8051245: using guessed type int dword_8051245;
// 80513B1: using guessed type int dword_80513B1;

//----- (0804A0E6) --------------------------------------------------------
int __cdecl sub_804A0E6(unsigned __int64 a1, _DWORD *a2, _BYTE *a3)
{
  __int64 v3; // ST10_8
  __int64 v4; // rax
  unsigned __int64 v5; // rax
  _DWORD *v6; // eax
  __int64 v7; // ST10_8
  __int64 v8; // rax
  __int64 v9; // ST10_8
  __int64 v10; // rax

  *a3 = 0;
  if ( qword_8051225 )
  {
    v3 = qword_8051225;
    LODWORD(v4) = sub_804D3A4(a1, qword_8051225);
    v5 = v3 - v4 + a1;
  }
  else
  {
    while ( *a2 < (unsigned int)dword_8051245 )
    {
      v6 = (char *)ptr + 8 * *a2;
      if ( a1 < *(_QWORD *)v6 )
      {
        LODWORD(v5) = *v6;
        return v5;
      }
      ++*a2;
    }
    if ( qword_805122D )
    {
      v7 = qword_805122D;
      LODWORD(v8) = sub_804D3A4(a1, qword_805122D);
      v5 = v7 - v8 + a1;
    }
    else if ( qword_8051235 )
    {
      v9 = qword_8051235;
      LODWORD(v10) = sub_804D3A4(a1 - *((_QWORD *)ptr + dword_8051245 + 0x1FFFFFFF), qword_8051235);
      v5 = v9 - v10 + a1;
    }
    else
    {
      *a3 = 1;
      LODWORD(v5) = 0;
    }
  }
  return v5;
}
// 8051225: using guessed type __int64 qword_8051225;
// 805122D: using guessed type __int64 qword_805122D;
// 8051235: using guessed type __int64 qword_8051235;
// 8051245: using guessed type int dword_8051245;

//----- (0804A2C6) --------------------------------------------------------
int __cdecl sub_804A2C6(int a1)
{
  int result; // eax

  byte_805124D = 0;
  if ( a1 )
  {
    result = a1;
    dword_8051249 = a1;
  }
  else
  {
    dword_8051249 = (int)&off_8051104;
  }
  return result;
}
// 8051104: using guessed type char *off_8051104;
// 8051249: using guessed type int dword_8051249;
// 805124D: using guessed type char byte_805124D;

//----- (0804A2EC) --------------------------------------------------------
FILE *__cdecl sub_804A2EC(FILE *stream)
{
  void *v1; // ebx
  int *v2; // eax
  void *v3; // ebx
  int *v4; // eax
  void *v6; // ebx
  int *v7; // eax
  char **v8; // eax
  char *s1; // [esp+1Ch] [ebp-Ch]
  FILE *streama; // [esp+30h] [ebp+8h]

  if ( stream )
  {
    if ( !::s1 )
      __assert_fail("prev_file", "src/expand-common.c", 0x155u, "next_file");
    if ( ferror_unlocked(stream) )
    {
      v1 = sub_804BD34(0, 3, (int)::s1);
      v2 = __errno_location();
      error(0, *v2, "%s", v1);
      dword_8051221 = 1;
    }
    if ( !strcmp(::s1, "-") )
    {
      clearerr_unlocked(stream);
    }
    else if ( sub_804C8B3(stream) )
    {
      v3 = sub_804BD34(0, 3, (int)::s1);
      v4 = __errno_location();
      error(0, *v4, "%s", v3);
      dword_8051221 = 1;
    }
  }
  while ( 1 )
  {
    v8 = (char **)dword_8051249;
    dword_8051249 += 4;
    s1 = *v8;
    if ( !*v8 )
      break;
    if ( !strcmp(s1, "-") )
    {
      byte_805124D = 1;
      streama = stdin;
    }
    else
    {
      streama = (FILE *)fopen64(s1, "r");
    }
    if ( streama )
    {
      ::s1 = s1;
      sub_804A6CB(streama, 2);
      return streama;
    }
    v6 = sub_804BD34(0, 3, (int)s1);
    v7 = __errno_location();
    error(0, *v7, "%s", v6);
    dword_8051221 = 1;
  }
  return 0;
}
// 8048D70: using guessed type int __cdecl fopen64(_DWORD, _DWORD);
// 8051221: using guessed type int dword_8051221;
// 8051249: using guessed type int dword_8051249;
// 805124D: using guessed type char byte_805124D;

//----- (0804A4E6) --------------------------------------------------------
void sub_804A4E6()
{
  int *v0; // eax

  if ( byte_805124D )
  {
    if ( sub_804C8B3(stdin) )
    {
      v0 = __errno_location();
      error(1, *v0, "-");
    }
  }
}
// 805124D: using guessed type char byte_805124D;

//----- (0804A529) --------------------------------------------------------
int sub_804A529()
{
  FILE *v0; // ebx
  char *v1; // eax
  FILE *v2; // ebx
  char *v3; // eax

  v0 = stdout;
  v1 = gettext("  -t, --tabs=LIST  use comma separated list of tab positions\n");
  fputs_unlocked(v1, v0);
  v2 = stdout;
  v3 = gettext(
         "                     The last specified position can be prefixed with '/'\n"
         "                     to specify a tab size to use after the last\n"
         "                     explicitly specified tab stop.  Also a prefix of '+'\n"
         "                     can be used to align remaining tab stops relative to\n"
         "                     the last specified tab stop instead of the first column\n");
  return fputs_unlocked(v3, v2);
}
// 8048E70: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);

//----- (0804A596) --------------------------------------------------------
int sub_804A596()
{
  void *v0; // ebx
  int *v1; // eax
  int *v2; // eax
  int result; // eax
  char *v4; // [esp+2Ch] [ebp-Ch]

  if ( sub_804CB98(stdout) && (byte_8051259 != 1 || *__errno_location() != 32) )
  {
    v4 = gettext("write error");
    if ( dword_8051255 )
    {
      v0 = sub_804BCF7(dword_8051255);
      v1 = __errno_location();
      error(0, *v1, "%s: %s", v0, v4);
    }
    else
    {
      v2 = __errno_location();
      error(0, *v2, "%s", v4);
    }
    _exit(status);
  }
  result = sub_804CB98(stderr);
  if ( result )
    _exit(status);
  return result;
}
// 8051255: using guessed type int dword_8051255;
// 8051259: using guessed type char byte_8051259;

//----- (0804A67A) --------------------------------------------------------
int __cdecl sub_804A67A(int a1, int a2, int a3, int a4, int a5, int a6)
{
  return posix_fadvise64(a1, a2, a3, a4, a5, a6);
}
// 8048F80: using guessed type int __cdecl posix_fadvise64(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804A6CB) --------------------------------------------------------
void __cdecl sub_804A6CB(FILE *stream, int a2)
{
  int v2; // eax

  if ( stream )
  {
    v2 = fileno(stream);
    sub_804A67A(v2, 0, 0, 0, 0, a2);
  }
}

//----- (0804A713) --------------------------------------------------------
char *__cdecl sub_804A713(char *s)
{
  char *v1; // eax
  char *result; // eax
  char *v3; // [esp+18h] [ebp-10h]
  char *s1; // [esp+1Ch] [ebp-Ch]

  if ( !s )
  {
    fwrite("A NULL argv[0] was passed through an exec system call.\n", 1u, 0x37u, stderr);
    abort();
  }
  v3 = strrchr(s, 47);
  if ( v3 )
    v1 = v3 + 1;
  else
    v1 = s;
  s1 = v1;
  if ( v1 - s > 6 && !strncmp(v1 - 7, "/.libs/", 7u) )
  {
    s = s1;
    if ( !strncmp(s1, "lt-", 3u) )
    {
      s = s1 + 3;
      program_invocation_short_name = (int)(s1 + 3);
    }
  }
  dword_805125D = (int)s;
  result = s;
  program_invocation_name = (int)s;
  return result;
}
// 8051180: using guessed type int program_invocation_short_name;
// 8051190: using guessed type int program_invocation_name;
// 805125D: using guessed type int dword_805125D;

//----- (0804A85F) --------------------------------------------------------
int __cdecl sub_804A85F(int *a1, unsigned __int8 a2, char a3)
{
  int *v3; // eax
  int v4; // ST10_4

  if ( a1 )
    v3 = a1;
  else
    v3 = &dword_805126D;
  v4 = ((unsigned int)v3[(a2 >> 5) + 2] >> (a2 & 0x1F)) & 1;
  v3[(a2 >> 5) + 2] ^= (v4 ^ a3 & 1) << (a2 & 0x1F);
  return v4;
}
// 805126D: using guessed type int dword_805126D;

//----- (0804A909) --------------------------------------------------------
int *__cdecl sub_804A909(int *a1, int a2, int a3)
{
  int *result; // eax

  if ( !a1 )
    a1 = &dword_805126D;
  *a1 = 10;
  if ( !a2 || !a3 )
    abort();
  a1[10] = a2;
  result = a1;
  a1[11] = a3;
  return result;
}
// 805126D: using guessed type int dword_805126D;

//----- (0804A94A) --------------------------------------------------------
_DWORD *__userpurge sub_804A94A@<eax>(_DWORD *a1, int a2)
{
  int v3; // [esp+0h] [ebp-38h]
  int v4; // [esp+4h] [ebp-34h]
  int v5; // [esp+8h] [ebp-30h]
  int v6; // [esp+Ch] [ebp-2Ch]
  int v7; // [esp+10h] [ebp-28h]
  int v8; // [esp+14h] [ebp-24h]
  int v9; // [esp+18h] [ebp-20h]
  int v10; // [esp+1Ch] [ebp-1Ch]
  int v11; // [esp+20h] [ebp-18h]
  int v12; // [esp+24h] [ebp-14h]
  int v13; // [esp+28h] [ebp-10h]
  int v14; // [esp+2Ch] [ebp-Ch]

  memset(&v3, 0, 0x30u);
  if ( a2 == 10 )
    abort();
  *a1 = a2;
  a1[1] = v4;
  a1[2] = v5;
  a1[3] = v6;
  a1[4] = v7;
  a1[5] = v8;
  a1[6] = v9;
  a1[7] = v10;
  a1[8] = v11;
  a1[9] = v12;
  a1[10] = v13;
  a1[11] = v14;
  return a1;
}

//----- (0804A9CC) --------------------------------------------------------
const char *__cdecl sub_804A9CC(char *msgid, int a2)
{
  const char *result; // eax
  char *v3; // [esp+18h] [ebp-10h]
  unsigned __int8 *v4; // [esp+1Ch] [ebp-Ch]

  v3 = gettext(msgid);
  if ( v3 != msgid )
    return v3;
  v4 = (unsigned __int8 *)sub_804D0EF();
  if ( sub_804CB33(v4, "UTF-8") )
  {
    if ( sub_804CB33(v4, "GB18030") )
    {
      if ( a2 == 9 )
        result = (const char *)&unk_804DF55;
      else
        result = "'";
    }
    else if ( *msgid == 96 )
    {
      result = (const char *)&unk_804DF4E;
    }
    else
    {
      result = (const char *)&unk_804DF52;
    }
  }
  else if ( *msgid == 96 )
  {
    result = (const char *)&unk_804DF3E;
  }
  else
  {
    result = (const char *)&unk_804DF42;
  }
  return result;
}

//----- (0804AA67) --------------------------------------------------------
unsigned int __cdecl sub_804AA67(int a1, unsigned int a2, int a3, size_t a4, signed int a5, int a6, int a7, char *a8, char *a9)
{
  size_t v9; // ebx
  size_t v10; // eax
  bool v11; // al
  bool v12; // al
  unsigned int result; // eax
  char *v14; // [esp+2Ch] [ebp-5Ch]
  char *v15; // [esp+30h] [ebp-58h]
  char v16; // [esp+40h] [ebp-48h]
  bool v17; // [esp+41h] [ebp-47h]
  char v18; // [esp+42h] [ebp-46h]
  char v19; // [esp+43h] [ebp-45h]
  char v20; // [esp+44h] [ebp-44h]
  unsigned __int8 v21; // [esp+45h] [ebp-43h]
  char v22; // [esp+46h] [ebp-42h]
  char v23; // [esp+47h] [ebp-41h]
  char v24; // [esp+48h] [ebp-40h]
  char v25; // [esp+49h] [ebp-3Fh]
  bool v26; // [esp+4Ah] [ebp-3Eh]
  bool v27; // [esp+4Bh] [ebp-3Dh]
  wint_t wc; // [esp+4Ch] [ebp-3Ch]
  int v29; // [esp+50h] [ebp-38h]
  unsigned int v30; // [esp+54h] [ebp-34h]
  unsigned int v31; // [esp+58h] [ebp-30h]
  char *s; // [esp+5Ch] [ebp-2Ch]
  size_t n; // [esp+60h] [ebp-28h]
  unsigned int v34; // [esp+64h] [ebp-24h]
  unsigned int v35; // [esp+68h] [ebp-20h]
  size_t v36; // [esp+6Ch] [ebp-1Ch]
  unsigned int v37; // [esp+70h] [ebp-18h]
  mbstate_t ps; // [esp+74h] [ebp-14h]
  unsigned int v39; // [esp+7Ch] [ebp-Ch]

  v15 = a8;
  v14 = a9;
  v39 = __readgsdword(0x14u);
  v30 = 0;
  v31 = 0;
  s = 0;
  n = 0;
  v16 = 0;
  v27 = __ctype_get_mb_cur_max() == 1;
  v17 = (a6 & 2) != 0;
  v18 = 0;
  v19 = 0;
  v20 = 1;
  while ( 1 )
  {
    switch ( a5 )
    {
      case 0:
        v17 = 0;
        break;
      case 1:
        goto LABEL_20;
      case 2:
        goto LABEL_23;
      case 3:
        v16 = 1;
LABEL_20:
        v17 = 1;
        goto LABEL_21;
      case 4:
LABEL_21:
        if ( v17 != 1 )
          v16 = 1;
LABEL_23:
        a5 = 2;
        if ( v17 != 1 )
        {
          if ( v30 < a2 )
            *(_BYTE *)(a1 + v30) = 39;
          ++v30;
        }
        s = "'";
        n = 1;
        break;
      case 5:
        goto LABEL_4;
      case 6:
        a5 = 5;
        v17 = 1;
LABEL_4:
        if ( v17 != 1 )
        {
          if ( v30 < a2 )
            *(_BYTE *)(a1 + v30) = 34;
          ++v30;
        }
        v16 = 1;
        s = (char *)&unk_804DF55;
        n = 1;
        break;
      case 7:
        v16 = 1;
        v17 = 0;
        break;
      case 8:
      case 9:
      case 10:
        if ( a5 != 10 )
        {
          v15 = (char *)sub_804A9CC("`", a5);
          v14 = (char *)sub_804A9CC("'", a5);
        }
        if ( v17 != 1 )
        {
          for ( s = v15; *s; ++s )
          {
            if ( v30 < a2 )
              *(_BYTE *)(v30 + a1) = *s;
            ++v30;
          }
        }
        v16 = 1;
        s = v14;
        n = strlen(v14);
        break;
      default:
        abort();
        return result;
    }
    v29 = 0;
    while ( 1 )
    {
      v12 = a4 == -1 ? *(_BYTE *)(a3 + v29) != 0 : v29 != a4;
      if ( !v12 )
        break;
      v23 = 0;
      v24 = 0;
      v25 = 0;
      if ( v16 && a5 != 2 && n )
      {
        v9 = v29 + n;
        if ( a4 != -1 || n <= 1 )
        {
          v10 = a4;
        }
        else
        {
          v10 = strlen((const char *)a3);
          a4 = v10;
        }
        if ( v9 <= v10 && !memcmp((const void *)(v29 + a3), s, n) )
        {
          if ( v17 )
            goto LABEL_245;
          v23 = 1;
        }
      }
      v21 = *(_BYTE *)(a3 + v29);
      switch ( v21 )
      {
        case 0u:
          if ( v16 )
          {
            if ( v17 )
              goto LABEL_245;
            v24 = 1;
            if ( a5 == 2 && v18 != 1 )
            {
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 36;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              ++v30;
              v18 = 1;
            }
            if ( v30 < a2 )
              *(_BYTE *)(a1 + v30) = 92;
            ++v30;
            if ( a5 != 2 && v29 + 1 < a4 && *(_BYTE *)(v29 + 1 + a3) > 47 && *(_BYTE *)(v29 + 1 + a3) <= 57 )
            {
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 48;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 48;
              ++v30;
            }
            v21 = 48;
          }
          else if ( a6 & 1 )
          {
            goto LABEL_219;
          }
          goto LABEL_189;
        case 7u:
          v22 = 97;
          goto LABEL_103;
        case 8u:
          v22 = 98;
          goto LABEL_103;
        case 9u:
          v22 = 116;
          goto LABEL_101;
        case 0xAu:
          v22 = 110;
          goto LABEL_101;
        case 0xBu:
          v22 = 118;
          goto LABEL_103;
        case 0xCu:
          v22 = 102;
          goto LABEL_103;
        case 0xDu:
          v22 = 114;
          goto LABEL_101;
        case 0x20u:
          goto LABEL_111;
        case 0x21u:
        case 0x22u:
        case 0x24u:
        case 0x26u:
        case 0x28u:
        case 0x29u:
        case 0x2Au:
        case 0x3Bu:
        case 0x3Cu:
        case 0x3Du:
        case 0x3Eu:
        case 0x5Bu:
        case 0x5Eu:
        case 0x60u:
        case 0x7Cu:
          goto LABEL_112;
        case 0x23u:
        case 0x7Eu:
          goto LABEL_110;
        case 0x25u:
        case 0x2Bu:
        case 0x2Cu:
        case 0x2Du:
        case 0x2Eu:
        case 0x2Fu:
        case 0x30u:
        case 0x31u:
        case 0x32u:
        case 0x33u:
        case 0x34u:
        case 0x35u:
        case 0x36u:
        case 0x37u:
        case 0x38u:
        case 0x39u:
        case 0x3Au:
        case 0x41u:
        case 0x42u:
        case 0x43u:
        case 0x44u:
        case 0x45u:
        case 0x46u:
        case 0x47u:
        case 0x48u:
        case 0x49u:
        case 0x4Au:
        case 0x4Bu:
        case 0x4Cu:
        case 0x4Du:
        case 0x4Eu:
        case 0x4Fu:
        case 0x50u:
        case 0x51u:
        case 0x52u:
        case 0x53u:
        case 0x54u:
        case 0x55u:
        case 0x56u:
        case 0x57u:
        case 0x58u:
        case 0x59u:
        case 0x5Au:
        case 0x5Du:
        case 0x5Fu:
        case 0x61u:
        case 0x62u:
        case 0x63u:
        case 0x64u:
        case 0x65u:
        case 0x66u:
        case 0x67u:
        case 0x68u:
        case 0x69u:
        case 0x6Au:
        case 0x6Bu:
        case 0x6Cu:
        case 0x6Du:
        case 0x6Eu:
        case 0x6Fu:
        case 0x70u:
        case 0x71u:
        case 0x72u:
        case 0x73u:
        case 0x74u:
        case 0x75u:
        case 0x76u:
        case 0x77u:
        case 0x78u:
        case 0x79u:
        case 0x7Au:
          v25 = 1;
          goto LABEL_189;
        case 0x27u:
          v19 = 1;
          v25 = 1;
          if ( a5 != 2 )
            goto LABEL_189;
          if ( v17 )
            goto LABEL_245;
          if ( a2 && !v31 )
          {
            v31 = a2;
            a2 = 0;
          }
          if ( v30 < a2 )
            *(_BYTE *)(a1 + v30) = 39;
          if ( ++v30 < a2 )
            *(_BYTE *)(a1 + v30) = 92;
          if ( ++v30 < a2 )
            *(_BYTE *)(a1 + v30) = 39;
          ++v30;
          v18 = 0;
          goto LABEL_189;
        case 0x3Fu:
          if ( a5 == 2 )
          {
            if ( v17 )
              goto LABEL_245;
          }
          else if ( a5 == 5 && a6 & 4 && v29 + 2 < a4 && *(_BYTE *)(v29 + 1 + a3) == 63 )
          {
            switch ( *(char *)(v29 + 2 + a3) )
            {
              case 33:
              case 39:
              case 40:
              case 41:
              case 45:
              case 47:
              case 60:
              case 61:
              case 62:
                if ( v17 )
                  goto LABEL_245;
                v21 = *(_BYTE *)(v29 + 2 + a3);
                v29 += 2;
                if ( v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 63;
                if ( ++v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 34;
                if ( ++v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 34;
                if ( ++v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 63;
                ++v30;
                break;
              default:
                goto LABEL_189;
            }
          }
          goto LABEL_189;
        case 0x5Cu:
          v22 = *(_BYTE *)(a3 + v29);
          if ( a5 == 2 )
          {
            if ( v17 )
              goto LABEL_245;
          }
          else
          {
            if ( v16 && v17 && n )
              goto LABEL_208;
LABEL_101:
            if ( a5 == 2 && v17 )
              goto LABEL_245;
LABEL_103:
            if ( v16 )
            {
              v21 = v22;
            }
            else
            {
LABEL_189:
              if ( ((v16 != 1 || a5 == 2) && v17 != 1 || !a7
                                                      || !((*(_DWORD *)(4 * (v21 >> 5) + a7) >> (v21 & 0x1F)) & 1))
                && v23 != 1 )
              {
                goto LABEL_208;
              }
            }
            if ( v17 )
              goto LABEL_245;
            v24 = 1;
            if ( a5 == 2 && v18 != 1 )
            {
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 36;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              ++v30;
              v18 = 1;
            }
            if ( v30 < a2 )
              *(_BYTE *)(a1 + v30) = 92;
            ++v30;
          }
LABEL_208:
          if ( v18 && v24 != 1 )
          {
            if ( v30 < a2 )
              *(_BYTE *)(a1 + v30) = 39;
            if ( ++v30 < a2 )
              *(_BYTE *)(a1 + v30) = 39;
            ++v30;
            v18 = 0;
          }
          if ( v30 < a2 )
            *(_BYTE *)(v30 + a1) = v21;
          ++v30;
          if ( v25 != 1 )
            v20 = 0;
LABEL_219:
          ++v29;
          break;
        case 0x7Bu:
        case 0x7Du:
          if ( a4 == -1 )
            v11 = *(_BYTE *)(a3 + 1) != 0;
          else
            v11 = a4 != 1;
          if ( v11 )
            goto LABEL_189;
LABEL_110:
          if ( v29 )
            goto LABEL_189;
LABEL_111:
          v25 = 1;
LABEL_112:
          if ( a5 != 2 || !v17 )
            goto LABEL_189;
          goto LABEL_245;
        default:
          if ( v27 )
          {
            v34 = 1;
            v26 = ((*__ctype_b_loc())[v21] & 0x4000) != 0;
            goto LABEL_151;
          }
          memset(&ps, 0, 8u);
          v34 = 0;
          v26 = 1;
          if ( a4 == -1 )
            a4 = strlen((const char *)a3);
          while ( 2 )
          {
            v36 = sub_804CAC1((wchar_t *)&wc, (char *)(a3 + v34 + v29), a4 - (v34 + v29), &ps);
            if ( v36 )
            {
              if ( v36 == -1 )
              {
                v26 = 0;
              }
              else
              {
                if ( v36 != -2 )
                {
                  if ( v17 && a5 == 2 )
                  {
                    v35 = 1;
                    while ( v35 < v36 )
                    {
                      switch ( *(char *)(v35 + v34 + v29 + a3) )
                      {
                        case 91:
                        case 92:
                        case 94:
                        case 96:
                        case 124:
                          goto LABEL_245;
                        default:
                          ++v35;
                          break;
                      }
                    }
                  }
                  if ( !iswprint(wc) )
                    v26 = 0;
                  v34 += v36;
                  if ( mbsinit(&ps) )
                    break;
                  continue;
                }
                v26 = 0;
                while ( v29 + v34 < a4 && *(_BYTE *)(v34 + v29 + a3) )
                  ++v34;
              }
            }
            break;
          }
LABEL_151:
          v25 = v26;
          if ( v34 <= 1 && (!v16 || v26 == 1) )
            goto LABEL_189;
          v37 = v29 + v34;
          while ( 1 )
          {
            if ( v16 && v26 != 1 )
            {
              if ( v17 )
                goto LABEL_245;
              v24 = 1;
              if ( a5 == 2 && v18 != 1 )
              {
                if ( v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 39;
                if ( ++v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 36;
                if ( ++v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 39;
                ++v30;
                v18 = 1;
              }
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 92;
              if ( ++v30 < a2 )
                *(_BYTE *)(v30 + a1) = (v21 >> 6) + 48;
              if ( ++v30 < a2 )
                *(_BYTE *)(v30 + a1) = ((v21 >> 3) & 7) + 48;
              ++v30;
              v21 = (v21 & 7) + 48;
            }
            else if ( v23 )
            {
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 92;
              ++v30;
              v23 = 0;
            }
            if ( v29 + 1 >= v37 )
              goto LABEL_208;
            if ( v18 && v24 != 1 )
            {
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              ++v30;
              v18 = 0;
            }
            if ( v30 < a2 )
              *(_BYTE *)(v30 + a1) = v21;
            ++v30;
            v21 = *(_BYTE *)(a3 + ++v29);
          }
      }
    }
    if ( !v30 && a5 == 2 && v17 )
      break;
    if ( a5 != 2 || v17 == 1 || !v19 )
      goto LABEL_251;
    if ( v20 )
      return sub_804AA67(a1, v31, a3, a4, 5, a6, a7, v15, v14);
    if ( a2 || !v31 )
    {
LABEL_251:
      if ( s && v17 != 1 )
      {
        while ( *s )
        {
          if ( v30 < a2 )
            *(_BYTE *)(v30 + a1) = *s;
          ++v30;
          ++s;
        }
      }
      if ( v30 < a2 )
        *(_BYTE *)(a1 + v30) = 0;
      return v30;
    }
    a2 = v31;
    v30 = 0;
  }
LABEL_245:
  if ( a5 == 2 && v16 )
    a5 = 4;
  return sub_804AA67(a1, a2, a3, a4, a5, a6 & 0xFFFFFFFD, 0, v15, v14);
}

//----- (0804B6FE) --------------------------------------------------------
void *__cdecl sub_804B6FE(int a1, size_t a2, _DWORD *a3, int *a4)
{
  int *v4; // eax
  int *v5; // ST3C_4
  int v6; // ST40_4
  int v7; // ST44_4
  unsigned int size; // [esp+48h] [ebp-10h]
  void *v10; // [esp+4Ch] [ebp-Ch]

  if ( a4 )
    v4 = a4;
  else
    v4 = &dword_805126D;
  v5 = v4;
  v6 = *__errno_location();
  v7 = v5[1] | (a3 == 0);
  size = sub_804AA67(0, 0, a1, a2, *v5, v7, (int)(v5 + 2), (char *)v5[10], (char *)v5[11]) + 1;
  v10 = sub_804C6EC(size);
  sub_804AA67((int)v10, size, a1, a2, *v5, v7, (int)(v5 + 2), (char *)v5[10], (char *)v5[11]);
  *__errno_location() = v6;
  if ( a3 )
    *a3 = size - 1;
  return v10;
}
// 805126D: using guessed type int dword_805126D;

//----- (0804B8A5) --------------------------------------------------------
void *__cdecl sub_804B8A5(signed int a1, int a2, size_t a3, int a4)
{
  int *v4; // eax
  void *v5; // edx
  size_t v6; // ST44_4
  bool v8; // [esp+37h] [ebp-21h]
  int *v9; // [esp+38h] [ebp-20h]
  void *ptr; // [esp+3Ch] [ebp-1Ch]
  int v11; // [esp+40h] [ebp-18h]
  int size; // [esp+44h] [ebp-14h]
  int v13; // [esp+48h] [ebp-10h]
  unsigned int v14; // [esp+4Ch] [ebp-Ch]

  v11 = *__errno_location();
  v9 = off_8051128;
  if ( a1 < 0 )
    abort();
  if ( dword_805111C <= a1 )
  {
    v8 = off_8051128 == &dword_8051120;
    if ( (unsigned int)a1 > 0xFFFFFFE )
      sub_804C84F();
    if ( v8 )
      v4 = 0;
    else
      v4 = off_8051128;
    v9 = (int *)sub_804C729(v4, 8 * (a1 + 1));
    off_8051128 = v9;
    if ( v8 )
    {
      v5 = off_8051124;
      *v9 = dword_8051120;
      v9[1] = (int)v5;
    }
    memset(&v9[2 * dword_805111C], 0, 8 * (a1 + 1 - dword_805111C));
    dword_805111C = a1 + 1;
  }
  v6 = v9[2 * a1];
  ptr = (void *)v9[2 * a1 + 1];
  v13 = *(_DWORD *)(a4 + 4) | 1;
  v14 = sub_804AA67(
          v9[2 * a1 + 1],
          v9[2 * a1],
          a2,
          a3,
          *(_DWORD *)a4,
          v13,
          a4 + 8,
          *(char **)(a4 + 40),
          *(char **)(a4 + 44));
  if ( v6 <= v14 )
  {
    size = v14 + 1;
    v9[2 * a1] = v14 + 1;
    if ( ptr != &unk_80512AD )
      free(ptr);
    ptr = sub_804C6EC(size);
    v9[2 * a1 + 1] = (int)ptr;
    sub_804AA67((int)ptr, size, a2, a3, *(_DWORD *)a4, v13, a4 + 8, *(char **)(a4 + 40), *(char **)(a4 + 44));
  }
  *__errno_location() = v11;
  return ptr;
}
// 805111C: using guessed type int dword_805111C;
// 8051120: using guessed type int dword_8051120;
// 8051124: using guessed type void *off_8051124;
// 8051128: using guessed type int *off_8051128;

//----- (0804BACE) --------------------------------------------------------
void *__cdecl sub_804BACE(signed int a1, int a2)
{
  return sub_804B8A5(a1, a2, 0xFFFFFFFF, (int)&dword_805126D);
}
// 805126D: using guessed type int dword_805126D;

//----- (0804BAF8) --------------------------------------------------------
void *__cdecl sub_804BAF8(signed int a1, int a2, size_t a3)
{
  return sub_804B8A5(a1, a2, a3, (int)&dword_805126D);
}
// 805126D: using guessed type int dword_805126D;

//----- (0804BB5E) --------------------------------------------------------
void *__cdecl sub_804BB5E(signed int a1, int a2, int a3)
{
  char v4; // [esp+10h] [ebp-38h]

  sub_804A94A(&v4, a2);
  return sub_804B8A5(a1, a3, 0xFFFFFFFF, (int)&v4);
}

//----- (0804BB9C) --------------------------------------------------------
void *__cdecl sub_804BB9C(signed int a1, int a2, int a3, size_t a4)
{
  char v5; // [esp+10h] [ebp-38h]

  sub_804A94A(&v5, a2);
  return sub_804B8A5(a1, a3, a4, (int)&v5);
}

//----- (0804BC24) --------------------------------------------------------
void *__cdecl sub_804BC24(int a1, size_t a2, unsigned __int8 a3)
{
  int v4; // [esp+20h] [ebp-38h]
  int v5; // [esp+24h] [ebp-34h]
  int v6; // [esp+28h] [ebp-30h]
  int v7; // [esp+2Ch] [ebp-2Ch]
  int v8; // [esp+30h] [ebp-28h]
  int v9; // [esp+34h] [ebp-24h]
  int v10; // [esp+38h] [ebp-20h]
  int v11; // [esp+3Ch] [ebp-1Ch]
  int v12; // [esp+40h] [ebp-18h]
  int v13; // [esp+44h] [ebp-14h]
  int v14; // [esp+48h] [ebp-10h]
  int v15; // [esp+4Ch] [ebp-Ch]

  v4 = dword_805126D;
  v5 = dword_8051271;
  v6 = dword_8051275;
  v7 = dword_8051279;
  v8 = dword_805127D;
  v9 = dword_8051281;
  v10 = dword_8051285;
  v11 = dword_8051289;
  v12 = dword_805128D;
  v13 = dword_8051291;
  v14 = dword_8051295;
  v15 = dword_8051299;
  sub_804A85F(&v4, a3, 1);
  return sub_804B8A5(0, a1, a2, (int)&v4);
}
// 805126D: using guessed type int dword_805126D;
// 8051271: using guessed type int dword_8051271;
// 8051275: using guessed type int dword_8051275;
// 8051279: using guessed type int dword_8051279;
// 805127D: using guessed type int dword_805127D;
// 8051281: using guessed type int dword_8051281;
// 8051285: using guessed type int dword_8051285;
// 8051289: using guessed type int dword_8051289;
// 805128D: using guessed type int dword_805128D;
// 8051291: using guessed type int dword_8051291;
// 8051295: using guessed type int dword_8051295;
// 8051299: using guessed type int dword_8051299;

//----- (0804BCCE) --------------------------------------------------------
void *__cdecl sub_804BCCE(int a1, unsigned __int8 a2)
{
  return sub_804BC24(a1, 0xFFFFFFFF, a2);
}

//----- (0804BCF7) --------------------------------------------------------
void *__cdecl sub_804BCF7(int a1)
{
  return sub_804BCCE(a1, 0x3Au);
}

//----- (0804BD34) --------------------------------------------------------
void *__cdecl sub_804BD34(signed int a1, int a2, int a3)
{
  int v4; // [esp+10h] [ebp-68h]
  int v5; // [esp+14h] [ebp-64h]
  int v6; // [esp+18h] [ebp-60h]
  int v7; // [esp+1Ch] [ebp-5Ch]
  int v8; // [esp+20h] [ebp-58h]
  int v9; // [esp+24h] [ebp-54h]
  int v10; // [esp+28h] [ebp-50h]
  int v11; // [esp+2Ch] [ebp-4Ch]
  int v12; // [esp+30h] [ebp-48h]
  int v13; // [esp+34h] [ebp-44h]
  int v14; // [esp+38h] [ebp-40h]
  int v15; // [esp+3Ch] [ebp-3Ch]
  int v16; // [esp+40h] [ebp-38h]
  int v17; // [esp+44h] [ebp-34h]
  int v18; // [esp+48h] [ebp-30h]
  int v19; // [esp+4Ch] [ebp-2Ch]
  int v20; // [esp+50h] [ebp-28h]
  int v21; // [esp+54h] [ebp-24h]
  int v22; // [esp+58h] [ebp-20h]
  int v23; // [esp+5Ch] [ebp-1Ch]
  int v24; // [esp+60h] [ebp-18h]
  int v25; // [esp+64h] [ebp-14h]
  int v26; // [esp+68h] [ebp-10h]
  int v27; // [esp+6Ch] [ebp-Ch]

  sub_804A94A(&v4, a2);
  v16 = v4;
  v17 = v5;
  v18 = v6;
  v19 = v7;
  v20 = v8;
  v21 = v9;
  v22 = v10;
  v23 = v11;
  v24 = v12;
  v25 = v13;
  v26 = v14;
  v27 = v15;
  sub_804A85F(&v16, 0x3Au, 1);
  return sub_804B8A5(a1, a3, 0xFFFFFFFF, (int)&v16);
}

//----- (0804BDD5) --------------------------------------------------------
void *__cdecl sub_804BDD5(signed int a1, int a2, int a3, int a4)
{
  return sub_804BE05(a1, a2, a3, a4, 0xFFFFFFFF);
}

//----- (0804BE05) --------------------------------------------------------
void *__cdecl sub_804BE05(signed int a1, int a2, int a3, int a4, size_t a5)
{
  int v6; // [esp+10h] [ebp-38h]
  int v7; // [esp+14h] [ebp-34h]
  int v8; // [esp+18h] [ebp-30h]
  int v9; // [esp+1Ch] [ebp-2Ch]
  int v10; // [esp+20h] [ebp-28h]
  int v11; // [esp+24h] [ebp-24h]
  int v12; // [esp+28h] [ebp-20h]
  int v13; // [esp+2Ch] [ebp-1Ch]
  int v14; // [esp+30h] [ebp-18h]
  int v15; // [esp+34h] [ebp-14h]
  int v16; // [esp+38h] [ebp-10h]
  int v17; // [esp+3Ch] [ebp-Ch]

  v6 = dword_805126D;
  v7 = dword_8051271;
  v8 = dword_8051275;
  v9 = dword_8051279;
  v10 = dword_805127D;
  v11 = dword_8051281;
  v12 = dword_8051285;
  v13 = dword_8051289;
  v14 = dword_805128D;
  v15 = dword_8051291;
  v16 = dword_8051295;
  v17 = dword_8051299;
  sub_804A909(&v6, a2, a3);
  return sub_804B8A5(a1, a4, a5, (int)&v6);
}
// 805126D: using guessed type int dword_805126D;
// 8051271: using guessed type int dword_8051271;
// 8051275: using guessed type int dword_8051275;
// 8051279: using guessed type int dword_8051279;
// 805127D: using guessed type int dword_805127D;
// 8051281: using guessed type int dword_8051281;
// 8051285: using guessed type int dword_8051285;
// 8051289: using guessed type int dword_8051289;
// 805128D: using guessed type int dword_805128D;
// 8051291: using guessed type int dword_8051291;
// 8051295: using guessed type int dword_8051295;
// 8051299: using guessed type int dword_8051299;

//----- (0804BEFF) --------------------------------------------------------
void *__cdecl sub_804BEFF(signed int a1, int a2, size_t a3)
{
  return sub_804B8A5(a1, a2, a3, (int)&unk_805113C);
}

//----- (0804BF4A) --------------------------------------------------------
void *__cdecl sub_804BF4A(signed int a1, int a2)
{
  return sub_804BEFF(a1, a2, 0xFFFFFFFF);
}

//----- (0804BF6C) --------------------------------------------------------
void *__cdecl sub_804BF6C(int a1)
{
  return sub_804BF4A(0, a1);
}

//----- (0804BF87) --------------------------------------------------------
int __cdecl sub_804BF87(FILE *stream, int a2, int a3, int a4, int a5, int a6)
{
  char *v6; // eax
  char *v7; // eax
  int v8; // ebx
  char *v9; // eax
  int result; // eax
  int v11; // esi
  int v12; // ebx
  char *v13; // eax
  int v14; // edi
  int v15; // esi
  int v16; // ebx
  char *v17; // eax
  int v18; // ST4C_4
  int v19; // edi
  int v20; // esi
  int v21; // ebx
  char *v22; // eax
  int v23; // ST4C_4
  int v24; // ST48_4
  int v25; // edi
  int v26; // esi
  int v27; // ebx
  char *v28; // eax
  int v29; // ST4C_4
  int v30; // ST48_4
  int v31; // ST44_4
  int v32; // edi
  int v33; // esi
  int v34; // ebx
  char *v35; // eax
  int v36; // esi
  int v37; // ST4C_4
  int v38; // ST48_4
  int v39; // ST44_4
  int v40; // ST40_4
  int v41; // edi
  int v42; // ebx
  char *v43; // eax
  int v44; // edi
  int v45; // ST4C_4
  int v46; // ST48_4
  int v47; // ST44_4
  int v48; // ST40_4
  int v49; // ST3C_4
  int v50; // esi
  int v51; // ebx
  char *v52; // eax
  int v53; // edi
  int v54; // ST4C_4
  int v55; // ST48_4
  int v56; // ST44_4
  int v57; // ST40_4
  int v58; // ST3C_4
  int v59; // ST38_4
  int v60; // esi
  int v61; // ebx
  char *v62; // eax
  int v63; // edi
  int v64; // ST4C_4
  int v65; // ST48_4
  int v66; // ST44_4
  int v67; // ST40_4
  int v68; // ST3C_4
  int v69; // ST38_4
  int v70; // esi
  int v71; // ebx
  char *v72; // eax

  if ( a2 )
    fprintf(stream, "%s (%s) %s\n", a2, a3, a4);
  else
    fprintf(stream, "%s %s\n", a3, a4);
  v6 = gettext("(C)");
  fprintf(stream, "Copyright %s %d Free Software Foundation, Inc.", v6, 2017);
  v7 = gettext(
         "\n"
         "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.\n"
         "This is free software: you are free to change and redistribute it.\n"
         "There is NO WARRANTY, to the extent permitted by law.\n"
         "\n");
  fputs_unlocked(v7, stream);
  switch ( a6 )
  {
    case 0:
      abort();
      return result;
    case 1:
      v8 = *(_DWORD *)a5;
      v9 = gettext("Written by %s.\n");
      result = fprintf(stream, v9, v8);
      break;
    case 2:
      v11 = *(_DWORD *)(a5 + 4);
      v12 = *(_DWORD *)a5;
      v13 = gettext("Written by %s and %s.\n");
      result = fprintf(stream, v13, v12, v11);
      break;
    case 3:
      v14 = *(_DWORD *)(a5 + 8);
      v15 = *(_DWORD *)(a5 + 4);
      v16 = *(_DWORD *)a5;
      v17 = gettext("Written by %s, %s, and %s.\n");
      result = fprintf(stream, v17, v16, v15, v14);
      break;
    case 4:
      v18 = *(_DWORD *)(a5 + 12);
      v19 = *(_DWORD *)(a5 + 8);
      v20 = *(_DWORD *)(a5 + 4);
      v21 = *(_DWORD *)a5;
      v22 = gettext("Written by %s, %s, %s,\nand %s.\n");
      result = fprintf(stream, v22, v21, v20, v19, v18);
      break;
    case 5:
      v23 = *(_DWORD *)(a5 + 16);
      v24 = *(_DWORD *)(a5 + 12);
      v25 = *(_DWORD *)(a5 + 8);
      v26 = *(_DWORD *)(a5 + 4);
      v27 = *(_DWORD *)a5;
      v28 = gettext("Written by %s, %s, %s,\n%s, and %s.\n");
      result = fprintf(stream, v28, v27, v26, v25, v24, v23);
      break;
    case 6:
      v29 = *(_DWORD *)(a5 + 20);
      v30 = *(_DWORD *)(a5 + 16);
      v31 = *(_DWORD *)(a5 + 12);
      v32 = *(_DWORD *)(a5 + 8);
      v33 = *(_DWORD *)(a5 + 4);
      v34 = *(_DWORD *)a5;
      v35 = gettext("Written by %s, %s, %s,\n%s, %s, and %s.\n");
      result = fprintf(stream, v35, v34, v33, v32, v31, v30, v29);
      break;
    case 7:
      v36 = *(_DWORD *)(a5 + 24);
      v37 = *(_DWORD *)(a5 + 20);
      v38 = *(_DWORD *)(a5 + 16);
      v39 = *(_DWORD *)(a5 + 12);
      v40 = *(_DWORD *)(a5 + 8);
      v41 = *(_DWORD *)(a5 + 4);
      v42 = *(_DWORD *)a5;
      v43 = gettext("Written by %s, %s, %s,\n%s, %s, %s, and %s.\n");
      result = fprintf(stream, v43, v42, v41, v40, v39, v38, v37, v36);
      break;
    case 8:
      v44 = *(_DWORD *)(a5 + 28);
      v45 = *(_DWORD *)(a5 + 24);
      v46 = *(_DWORD *)(a5 + 20);
      v47 = *(_DWORD *)(a5 + 16);
      v48 = *(_DWORD *)(a5 + 12);
      v49 = *(_DWORD *)(a5 + 8);
      v50 = *(_DWORD *)(a5 + 4);
      v51 = *(_DWORD *)a5;
      v52 = gettext("Written by %s, %s, %s,\n%s, %s, %s, %s,\nand %s.\n");
      result = fprintf(stream, v52, v51, v50, v49, v48, v47, v46, v45, v44);
      break;
    case 9:
      v53 = *(_DWORD *)(a5 + 32);
      v54 = *(_DWORD *)(a5 + 28);
      v55 = *(_DWORD *)(a5 + 24);
      v56 = *(_DWORD *)(a5 + 20);
      v57 = *(_DWORD *)(a5 + 16);
      v58 = *(_DWORD *)(a5 + 12);
      v59 = *(_DWORD *)(a5 + 8);
      v60 = *(_DWORD *)(a5 + 4);
      v61 = *(_DWORD *)a5;
      v62 = gettext("Written by %s, %s, %s,\n%s, %s, %s, %s,\n%s, and %s.\n");
      result = fprintf(stream, v62, v61, v60, v59, v58, v57, v56, v55, v54, v53);
      break;
    default:
      v63 = *(_DWORD *)(a5 + 32);
      v64 = *(_DWORD *)(a5 + 28);
      v65 = *(_DWORD *)(a5 + 24);
      v66 = *(_DWORD *)(a5 + 20);
      v67 = *(_DWORD *)(a5 + 16);
      v68 = *(_DWORD *)(a5 + 12);
      v69 = *(_DWORD *)(a5 + 8);
      v70 = *(_DWORD *)(a5 + 4);
      v71 = *(_DWORD *)a5;
      v72 = gettext("Written by %s, %s, %s,\n%s, %s, %s, %s,\n%s, %s, and others.\n");
      result = fprintf(stream, v72, v71, v70, v69, v68, v67, v66, v65, v64, v63);
      break;
  }
  return result;
}
// 8048E70: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);

//----- (0804C4EC) --------------------------------------------------------
int __cdecl sub_804C4EC(FILE *stream, int a2, int a3, int a4, int a5)
{
  int *v5; // eax
  unsigned int i; // [esp+24h] [ebp-34h]
  int v8[12]; // [esp+28h] [ebp-30h]

  for ( i = 0; i <= 9; ++i )
  {
    v5 = (int *)a5;
    a5 += 4;
    v8[i] = *v5;
    if ( !v8[i] )
      break;
  }
  return sub_804BF87(stream, a2, a3, a4, (int)v8, i);
}
// 804C4EC: using guessed type int var_30[12];

//----- (0804C552) --------------------------------------------------------
int sub_804C552(FILE *stream, int a2, int a3, int a4, ...)
{
  va_list va; // [esp+50h] [ebp+18h]

  va_start(va, a4);
  return sub_804C4EC(stream, a2, a3, a4, (int)va);
}

//----- (0804C655) --------------------------------------------------------
void *__cdecl sub_804C655(void *ptr, int a2, int a3)
{
  unsigned int v4; // [esp+1Ch] [ebp-Ch]

  v4 = *(_DWORD *)a2;
  if ( ptr )
  {
    if ( 0x55555554u / a3 <= v4 )
      sub_804C84F();
    v4 += (v4 >> 1) + 1;
  }
  else
  {
    if ( !v4 )
      v4 = (0x40u / a3 == 0) + 0x40u / a3;
    if ( 0x7FFFFFFFu / a3 < v4 )
      sub_804C84F();
  }
  *(_DWORD *)a2 = v4;
  return sub_804C729(ptr, a3 * v4);
}

//----- (0804C6EC) --------------------------------------------------------
void *__cdecl sub_804C6EC(size_t size)
{
  return sub_804C6FF(size);
}

//----- (0804C6FF) --------------------------------------------------------
void *__cdecl sub_804C6FF(size_t size)
{
  void *v2; // [esp+1Ch] [ebp-Ch]

  v2 = malloc(size);
  if ( !v2 && size )
    sub_804C84F();
  return v2;
}

//----- (0804C729) --------------------------------------------------------
void *__cdecl sub_804C729(void *ptr, size_t size)
{
  void *result; // eax
  void *ptra; // [esp+20h] [ebp+8h]

  if ( size || !ptr )
  {
    ptra = realloc(ptr, size);
    if ( !ptra )
    {
      if ( size )
        sub_804C84F();
    }
    result = ptra;
  }
  else
  {
    free(ptr);
    result = 0;
  }
  return result;
}

//----- (0804C801) --------------------------------------------------------
void *__cdecl sub_804C801(void *src, size_t n)
{
  void *v2; // eax

  v2 = sub_804C6FF(n);
  return memcpy(v2, src, n);
}

//----- (0804C84F) --------------------------------------------------------
void __noreturn sub_804C84F()
{
  char *v0; // eax

  v0 = gettext("memory exhausted");
  error(status, 0, "%s", v0);
  abort();
}

//----- (0804C888) --------------------------------------------------------
int __cdecl sub_804C888(int a1, int a2)
{
  int v3; // [esp+1Ch] [ebp-Ch]

  v3 = strndup(a1, a2);
  if ( !v3 )
    sub_804C84F();
  return v3;
}
// 8048F10: using guessed type int __cdecl strndup(_DWORD, _DWORD);

//----- (0804C8B3) --------------------------------------------------------
int __cdecl sub_804C8B3(FILE *stream)
{
  int v2; // eax
  __int64 v3; // rax
  int v4; // [esp+14h] [ebp-14h]
  int v5; // [esp+18h] [ebp-10h]

  v4 = 0;
  if ( fileno(stream) < 0 )
    return fclose(stream);
  if ( !__freading(stream) || (v2 = fileno(stream), LODWORD(v3) = lseek64(v2, 0, 0, 1), v3 != -1) )
  {
    if ( sub_804C9AF(stream) )
      v4 = *__errno_location();
  }
  v5 = fclose(stream);
  if ( v4 )
  {
    *__errno_location() = v4;
    v5 = -1;
  }
  return v5;
}
// 8048F60: using guessed type int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804C976) --------------------------------------------------------
int __cdecl sub_804C976(FILE *stream)
{
  int result; // eax

  result = stream->_flags & 0x100;
  if ( result )
    result = sub_804C9EF(stream, 0, 0, 1);
  return result;
}

//----- (0804C9AF) --------------------------------------------------------
int __cdecl sub_804C9AF(FILE *fp)
{
  if ( !fp || !__freading(fp) )
    return fflush(fp);
  sub_804C976(fp);
  return fflush(fp);
}

//----- (0804C9EF) --------------------------------------------------------
int __cdecl sub_804C9EF(FILE *stream, int a2, int a3, int a4)
{
  int v4; // eax
  __off64_t v5; // rax

  if ( stream->_IO_read_end != stream->_IO_read_ptr
    || stream->_IO_write_ptr != stream->_IO_write_base
    || stream->_IO_save_base )
  {
    return fseeko64(stream, a2, a3, a4);
  }
  v4 = fileno(stream);
  LODWORD(v5) = lseek64(v4, a2, a3, a4);
  if ( v5 == -1 )
    return -1;
  stream->_flags &= 0xFFFFFFEF;
  stream->_offset = v5;
  return 0;
}
// 8048D20: using guessed type int __cdecl fseeko64(_DWORD, _DWORD, _DWORD, _DWORD);
// 8048F60: using guessed type int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804CAC1) --------------------------------------------------------
size_t __cdecl sub_804CAC1(wchar_t *pwc, char *s, size_t n, mbstate_t *p)
{
  char v5; // [esp+18h] [ebp-10h]
  size_t v6; // [esp+1Ch] [ebp-Ch]

  if ( !pwc )
    pwc = (wchar_t *)&v5;
  v6 = mbrtowc(pwc, s, n, p);
  if ( v6 <= 0xFFFFFFFD || !n || !((unsigned __int8)sub_804CC19(0) ^ 1) )
    return v6;
  *pwc = (unsigned __int8)*s;
  return 1;
}

//----- (0804CB33) --------------------------------------------------------
int __cdecl sub_804CB33(unsigned __int8 *a1, unsigned __int8 *a2)
{
  unsigned __int8 *v2; // esi
  unsigned __int8 *v3; // ebx
  unsigned __int8 v5; // [esp+1Eh] [ebp-Ah]
  unsigned __int8 v6; // [esp+1Fh] [ebp-9h]

  v2 = a1;
  v3 = a2;
  if ( a1 == a2 )
    return 0;
  do
  {
    v5 = sub_804D364(*v2);
    v6 = sub_804D364(*v3);
    if ( !v5 )
      break;
    ++v2;
    ++v3;
  }
  while ( v5 == v6 );
  return v5 - v6;
}

//----- (0804CB98) --------------------------------------------------------
int __cdecl sub_804CB98(FILE *fp)
{
  bool v1; // ST1E_1
  bool v3; // [esp+1Dh] [ebp-Bh]
  bool v4; // [esp+1Fh] [ebp-9h]

  v3 = __fpending(fp) != 0;
  v1 = ferror_unlocked(fp) != 0;
  v4 = sub_804C8B3(fp) != 0;
  if ( !v1 && (!v4 || !v3 && *__errno_location() == 9) )
    return 0;
  if ( v4 != 1 )
    *__errno_location() = 0;
  return -1;
}

//----- (0804CC19) --------------------------------------------------------
int __cdecl sub_804CC19(int category)
{
  unsigned __int8 v2; // [esp+1Bh] [ebp-Dh]
  const char *s1; // [esp+1Ch] [ebp-Ch]

  v2 = 1;
  s1 = setlocale(category, 0);
  if ( s1 && (!strcmp(s1, "C") || !strcmp(s1, "POSIX")) )
    v2 = 0;
  return v2;
}

//----- (0804CC77) --------------------------------------------------------
void *sub_804CC77()
{
  _BOOL4 v0; // eax
  void *v2; // [esp+18h] [ebp-B0h]
  const char *s; // [esp+1Ch] [ebp-ACh]
  void *v4; // [esp+20h] [ebp-A8h]
  int v5; // [esp+24h] [ebp-A4h]
  size_t n; // [esp+2Ch] [ebp-9Ch]
  size_t v7; // [esp+30h] [ebp-98h]
  _BOOL4 v8; // [esp+34h] [ebp-94h]
  char *dest; // [esp+38h] [ebp-90h]
  int fd; // [esp+3Ch] [ebp-8Ch]
  FILE *stream; // [esp+40h] [ebp-88h]
  int c; // [esp+44h] [ebp-84h]
  int ca; // [esp+44h] [ebp-84h]
  size_t v14; // [esp+48h] [ebp-80h]
  size_t v15; // [esp+4Ch] [ebp-7Ch]
  void *v16; // [esp+50h] [ebp-78h]
  char src; // [esp+56h] [ebp-72h]
  char v18; // [esp+89h] [ebp-3Fh]
  unsigned int v19; // [esp+BCh] [ebp-Ch]

  v19 = __readgsdword(0x14u);
  v2 = (void *)dword_80513AD;
  if ( !dword_80513AD )
  {
    s = getenv("CHARSETALIASDIR");
    if ( !s || !*s )
      s = "/home/hwangdz/coreutils/coreutils-8.28/install_m32/lib";
    n = strlen(s);
    v7 = strlen("charset.alias");
    v0 = n && s[n - 1] != 47;
    v8 = v0;
    dest = (char *)malloc(n + v0 + v7 + 1);
    if ( dest )
    {
      memcpy(dest, s, n);
      if ( v8 )
        dest[n] = 47;
      memcpy(&dest[n + v8], "charset.alias", v7 + 1);
    }
    free(0);
    if ( dest )
    {
      fd = open64(dest, 0x20000);
      if ( fd >= 0 )
      {
        stream = fdopen(fd, "r");
        if ( stream )
        {
          v4 = 0;
          v5 = 0;
          while ( 1 )
          {
            c = getc_unlocked(stream);
            if ( c == -1 )
              break;
            if ( c != 10 && c != 32 && c != 9 )
            {
              if ( c == 35 )
              {
                do
                  ca = getc_unlocked(stream);
                while ( ca != -1 && ca != 10 );
                if ( ca == -1 )
                  break;
              }
              else
              {
                ungetc(c, stream);
                if ( fscanf(stream, "%50s %50s", &src, &v18) <= 1 )
                  break;
                v14 = strlen(&src);
                v15 = strlen(&v18);
                v16 = v4;
                if ( v5 )
                {
                  v5 += v15 + v14 + 2;
                  v4 = realloc(v4, v5 + 1);
                }
                else
                {
                  v5 = v14 + v15 + 2;
                  v4 = malloc(v14 + v15 + 3);
                }
                if ( !v4 )
                {
                  v5 = 0;
                  free(v16);
                  break;
                }
                strcpy((char *)v4 + v5 - v15 - v14 - 2, &src);
                strcpy((char *)v4 + v5 - v15 - 1, &v18);
              }
            }
          }
          sub_804C8B3(stream);
          if ( v5 )
          {
            *((_BYTE *)v4 + v5) = 0;
            v2 = v4;
          }
          else
          {
            v2 = &unk_804E673;
          }
        }
        else
        {
          close(fd);
          v2 = &unk_804E673;
        }
      }
      else
      {
        v2 = &unk_804E673;
      }
      free(dest);
    }
    else
    {
      v2 = &unk_804E673;
    }
    dword_80513AD = (int)v2;
  }
  return v2;
}
// 8048C90: using guessed type int __cdecl open64(_DWORD, _DWORD);
// 80513AD: using guessed type int dword_80513AD;

//----- (0804D0EF) --------------------------------------------------------
const char *sub_804D0EF()
{
  char *v0; // ST1C_4
  const char *s1; // [esp+18h] [ebp-10h]
  char *s2; // [esp+1Ch] [ebp-Ch]

  s1 = nl_langinfo(14);
  if ( !s1 )
    s1 = (const char *)&unk_804E673;
  for ( s2 = (char *)sub_804CC77(); *s2; s2 = &v0[strlen(v0) + 1] )
  {
    if ( !strcmp(s1, s2) || *s2 == 42 && !s2[1] )
    {
      s1 = &s2[strlen(s2) + 1];
      break;
    }
    v0 = &s2[strlen(s2) + 1];
  }
  if ( !*s1 )
    s1 = "ASCII";
  return s1;
}

//----- (0804D364) --------------------------------------------------------
int __cdecl sub_804D364(int a1)
{
  int result; // eax

  if ( (unsigned int)(a1 - 65) > 0x19 )
    result = a1;
  else
    result = a1 + 32;
  return result;
}

//----- (0804D3A4) --------------------------------------------------------
int __cdecl sub_804D3A4(unsigned __int64 a1, __int64 a2)
{
  int v2; // edx
  int result; // eax
  int v4; // ebp
  int v5; // ebp
  unsigned int v6; // ebp
  unsigned __int64 v7; // rtt
  unsigned __int64 v8; // rax
  unsigned int v9; // edi
  unsigned __int64 v10; // rax
  unsigned int v11; // ecx
  unsigned int v12; // [esp+4h] [ebp-1Ch]
  __int64 v13; // [esp+8h] [ebp-18h]
  unsigned int v14; // [esp+Ch] [ebp-14h]

  LODWORD(v13) = a1;
  if ( HIDWORD(a2) )
  {
    if ( HIDWORD(a2) > HIDWORD(a1) )
    {
      result = a1;
    }
    else
    {
      _BitScanReverse((unsigned int *)&v4, HIDWORD(a2));
      v5 = v4 ^ 0x1F;
      if ( v5 )
      {
        v12 = (HIDWORD(a2) << v5) | ((unsigned int)a2 >> (32 - v5));
        HIDWORD(v8) = HIDWORD(a1) >> (32 - v5);
        LODWORD(v8) = (HIDWORD(a1) << v5) | ((unsigned int)a1 >> (32 - v5));
        v14 = (_DWORD)a1 << v5;
        v9 = v8 % v12;
        v10 = (unsigned int)((_DWORD)a2 << v5) * (unsigned __int64)(unsigned int)(v8 / v12);
        v11 = v10;
        if ( v9 < HIDWORD(v10) || v14 < (unsigned int)v10 && v9 == HIDWORD(v10) )
        {
          HIDWORD(v10) = (v10 - __PAIR__(v12, (_DWORD)a2 << v5)) >> 32;
          v11 = v10 - ((_DWORD)a2 << v5);
        }
        result = ((__PAIR__(v9, v14) - __PAIR__(HIDWORD(v10), v11)) >> 32 << (32 - (unsigned __int8)v5)) | ((v14 - v11) >> v5);
      }
      else
      {
        if ( (unsigned int)a2 <= (unsigned int)a1 || HIDWORD(a2) < HIDWORD(a1) )
          LODWORD(v13) = a1 - a2;
        result = v13;
      }
    }
  }
  else
  {
    if ( (unsigned int)a2 <= HIDWORD(a1) )
    {
      v6 = a2;
      if ( !(_DWORD)a2 )
        v6 = 1 / 0u;
      LODWORD(v7) = a1;
      HIDWORD(v7) = HIDWORD(a1) % v6;
      v2 = v7 % v6;
    }
    else
    {
      v2 = a1 % (unsigned int)a2;
    }
    result = v2;
  }
  return result;
}

//----- (0804D567) --------------------------------------------------------
int __cdecl sub_804D567(int a1)
{
  return __cxa_atexit(a1, 0, dword_8051100);
}
// 8048DE0: using guessed type int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD);
// 8051100: using guessed type int dword_8051100;

//----- (0804D590) --------------------------------------------------------
int (**sub_804D590())()
{
  int (**result)(); // eax
  int v1; // esi
  int v2; // edi

  init_proc();
  result = off_8050F04;
  v1 = &off_8050F08 - off_8050F04;
  if ( v1 )
  {
    v2 = 0;
    do
      result = (int (**)())off_8050F04[v2++]();
    while ( v1 != v2 );
  }
  return result;
}
// 8050F04: using guessed type int (*off_8050F04[2])();
// 8050F08: using guessed type int (*off_8050F08)();

//----- (0804D5F4) --------------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 78 function(s)"
