/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
int sub_8048D10();
// int strcmp(const char *s1, const char *s2);
// int __cdecl open64(_DWORD, _DWORD); weak
// int printf(const char *format, ...);
// int fflush(FILE *stream);
// void _exit(int status);
// void *memmove(void *dest, const void *src, size_t n);
// void free(void *ptr);
// uintmax_t strtoumax(const char *nptr, char **endptr, int base);
// void *memcpy(void *dest, const void *src, size_t n);
// int mbsinit(const mbstate_t *ps);
// int fclose(FILE *stream);
// int getc_unlocked(FILE *stream);
// int __cdecl fseeko64(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int memcmp(const void *s1, const void *s2, size_t n);
// int fputc_unlocked(int c, FILE *stream);
// char *textdomain(const char *domainname);
// int iswprint(wint_t wc);
// int __cdecl fopen64(_DWORD, _DWORD); weak
// int ferror_unlocked(FILE *stream);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// size_t __ctype_get_mb_cur_max(void);
// char *strcpy(char *dest, const char *src);
// size_t __fpending(FILE *fp);
// size_t mbrtowc(wchar_t *pwc, const char *s, size_t n, mbstate_t *p);
// int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD); weak
// void error(int status, int errnum, const char *format, ...);
// size_t fread_unlocked(void *ptr, size_t size, size_t n, FILE *stream);
// char *getenv(const char *name);
// void *realloc(void *ptr, size_t size);
// void *malloc(size_t size);
// int __freading(FILE *fp);
// void exit(int status);
// char *gettext(const char *msgid);
// FILE *fdopen(int fd, const char *modes);
// int __cdecl fputs_unlocked(_DWORD, _DWORD); weak
// int getopt_long(int argc, char *const *argv, const char *shortopts, const struct option *longopts, int *longind);
// char *strchr(const char *s, int c);
// int fscanf(FILE *stream, const char *format, ...);
// size_t strlen(const char *s);
// int fprintf(FILE *stream, const char *format, ...);
// void *memset(void *s, int c, size_t n);
// int ungetc(int c, FILE *stream);
// int *__errno_location(void);
// void *memchr(const void *s, int c, size_t n);
// int fileno(FILE *stream);
// size_t fwrite_unlocked(const void *ptr, size_t size, size_t n, FILE *stream);
// char *nl_langinfo(nl_item item);
// char *setlocale(int category, const char *locale);
// char *strrchr(const char *s, int c);
// int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD); weak
// char *bindtextdomain(const char *domainname, const char *dirname);
// int __cdecl posix_fadvise64(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int strncmp(const char *s1, const char *s2, size_t n);
// int feof_unlocked(FILE *stream);
// void abort(void);
// int close(int fd);
// void __assert_fail(const char *assertion, const char *file, unsigned int line, const char *function);
// const unsigned __int16 **__ctype_b_loc(void);
// int _gmon_start__(void); weak
void sub_8049133();
void sub_8049150();
int sub_8049160();
int sub_80491D0();
int sub_80491F0();
void sub_804924F();
void sub_804926B();
int sub_804927B();
int sub_804932C();
int sub_8049357();
int __cdecl sub_8049382(char *s1); // idb
void __cdecl __noreturn sub_8049508(int status); // idb
size_t __cdecl sub_8049607(void *ptr, size_t n, int a3, int a4, int a5, FILE *stream);
unsigned int __cdecl sub_804979D(FILE *a1, FILE *a2, __int64 a3);
unsigned int __cdecl sub_80499EB(FILE *a1, FILE *a2, char a3);
int __cdecl main(int argc, char **argv);
int __cdecl sub_804A0ED(unsigned __int8 a1);
void __cdecl sub_804A0FF(unsigned __int8 *a1, int a2, int a3);
void __cdecl sub_804A213(unsigned __int8 *a1, int a2, char *a3, unsigned int a4);
char __cdecl sub_804A474(unsigned __int8 a1);
_DWORD *__cdecl sub_804A49D(_DWORD *a1);
int __cdecl sub_804A4AB(_DWORD *a1, char **a2, unsigned int a3, _DWORD *a4);
signed int __cdecl sub_804A585(unsigned __int8 *a1, unsigned int a2, _DWORD *a3, _DWORD *a4);
bool __cdecl sub_804A826(int *a1, unsigned __int8 *a2, unsigned int a3, int a4, int *a5);
int sub_804AA8F();
int __cdecl sub_804AB73(int a1, int a2, int a3, int a4, int a5, int a6);
void __cdecl sub_804ABC4(FILE *stream, int a2);
char *__cdecl sub_804AC0C(char *s);
int __cdecl sub_804AD58(int *a1, unsigned __int8 a2, char a3);
int *__cdecl sub_804AE02(int *a1, int a2, int a3);
// _DWORD *__userpurge sub_804AE43@<eax>(_DWORD *a1, int a2);
const char *__cdecl sub_804AEC5(char *msgid, int a2);
unsigned int __cdecl sub_804AF60(int a1, unsigned int a2, int a3, size_t a4, signed int a5, int a6, int a7, char *a8, char *a9);
void *__cdecl sub_804BBFD(int a1, size_t a2, _DWORD *a3, int *a4);
void *__cdecl sub_804BDA4(signed int a1, int a2, size_t a3, int a4);
void *__cdecl sub_804BFCD(signed int a1, int a2);
void *__cdecl sub_804BFF7(signed int a1, int a2, size_t a3);
void *__cdecl sub_804C05D(signed int a1, int a2, int a3);
void *__cdecl sub_804C09B(signed int a1, int a2, int a3, size_t a4);
void *__cdecl sub_804C123(int a1, size_t a2, unsigned __int8 a3);
void *__cdecl sub_804C1CD(int a1, unsigned __int8 a2);
void *__cdecl sub_804C1F6(int a1);
void *__cdecl sub_804C233(signed int a1, int a2, int a3);
void *__cdecl sub_804C2D4(signed int a1, int a2, int a3, int a4);
void *__cdecl sub_804C304(signed int a1, int a2, int a3, int a4, size_t a5);
void *__cdecl sub_804C3FE(signed int a1, int a2, size_t a3);
void *__cdecl sub_804C449(signed int a1, int a2);
void *__cdecl sub_804C46B(int a1);
int __cdecl sub_804C486(FILE *stream, int, int, int, int, int); // idb
int __cdecl sub_804C9EC(FILE *stream, int, int, int, int); // idb
int sub_804CA52(FILE *stream, int a2, int a3, int a4, ...);
void *__cdecl sub_804CB55(void *ptr, int a2, int a3);
void *__cdecl sub_804CBEC(size_t size);
void *__cdecl sub_804CBFF(size_t size);
void *__cdecl sub_804CC29(void *ptr, size_t size);
void *__cdecl sub_804CD01(void *src, size_t n);
void __noreturn sub_804CD4F();
void sub_804CD88();
void sub_804CD8D();
unsigned __int64 __cdecl sub_804CDB0(char *nptr, int base, int a3, int a4, int a5, int a6, char *s, int a8, int status);
unsigned __int64 __cdecl sub_804CEEE(char *nptr, int a2, int a3, int a4, int a5, char *s, int a7, int status);
signed int __cdecl sub_804CF52(int a1, signed int a2);
int __cdecl sub_804CFDE(int a1, signed int a2, int a3);
int __cdecl sub_804D014(char *nptr, int, int base, int, char *s); // idb
int __cdecl sub_804D40C(FILE *stream); // idb
int __cdecl sub_804D4CF(FILE *stream); // idb
int __cdecl sub_804D508(FILE *fp); // idb
int __cdecl sub_804D548(FILE *stream, int, int, int); // idb
size_t __cdecl sub_804D61A(wchar_t *pwc, char *s, size_t n, mbstate_t *p);
int sub_804D68C();
int sub_804D696();
int sub_804D6A0();
int __cdecl sub_804D6D3(unsigned __int8 *a1, unsigned __int8 *a2);
int __cdecl sub_804D738(FILE *fp); // idb
int __cdecl sub_804D7B9(int category); // idb
void *sub_804D817();
const char *sub_804DC8F();
int __cdecl sub_804DF04(int a1);
signed __int64 __cdecl sub_804DF3F(unsigned __int64 a1, unsigned int a2, unsigned int a3);
int __cdecl sub_804E0CD(int a1);
int (**sub_804E100())();
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

char s = '\0'; // idb
struct option longopts = { "decode", 0, NULL, 100 }; // idb
char byte_804E7E0[64] =
{
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '+',
  '/'
}; // idb
char byte_804E820[256] =
{
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '>',
  '\xFF',
  '\xFF',
  '\xFF',
  '?',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  ':',
  ';',
  '<',
  '=',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\0',
  '\x01',
  '\x02',
  '\x03',
  '\x04',
  '\x05',
  '\x06',
  '\a',
  '\b',
  '\t',
  '\n',
  '\v',
  '\f',
  '\r',
  '\x0E',
  '\x0F',
  '\x10',
  '\x11',
  '\x12',
  '\x13',
  '\x14',
  '\x15',
  '\x16',
  '\x17',
  '\x18',
  '\x19',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\x1A',
  '\x1B',
  '\x1C',
  '\x1D',
  '\x1E',
  '\x1F',
  ' ',
  '!',
  '\"',
  '#',
  '$',
  '%',
  '&',
  '\'',
  '(',
  ')',
  '*',
  '+',
  ',',
  '-',
  '.',
  '/',
  '0',
  '1',
  '2',
  '3',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF',
  '\xFF'
}; // idb
_UNKNOWN unk_804EA4E; // weak
_UNKNOWN unk_804EA52; // weak
_UNKNOWN unk_804EA5E; // weak
_UNKNOWN unk_804EA62; // weak
_UNKNOWN unk_804EA65; // weak
_UNKNOWN unk_804F367; // weak
int (*off_8051F04[2])() = { &sub_80491F0, &sub_80491D0 }; // weak
int (*off_8051F08)() = &sub_80491D0; // weak
int (*dword_8052008)(void) = NULL; // weak
int dword_8052110 = 0; // weak
int off_8052114 = 134539223; // idb
int status = 1; // idb
int dword_805212C = 1; // weak
int dword_8052130 = 256; // weak
void *off_8052134 = &unk_805226D; // weak
int *off_8052138 = &dword_8052130; // weak
_UNKNOWN unk_805214C; // weak
_UNKNOWN unk_8052170; // weak
_UNKNOWN unk_8052173; // weak
_UNKNOWN unk_805217C; // weak
_UNKNOWN unk_805217F; // weak
int program_invocation_short_name; // weak
FILE *stderr; // idb
int program_invocation_name; // weak
int optind; // weak
int stdin; // weak
FILE *stdout; // idb
char *optarg; // idb
char byte_80521CC; // weak
int dword_805221D; // weak
char byte_8052221; // weak
int dword_8052225; // weak
int dword_805222D; // weak
int dword_8052231; // weak
int dword_8052235; // weak
int dword_8052239; // weak
int dword_805223D; // weak
int dword_8052241; // weak
int dword_8052245; // weak
int dword_8052249; // weak
int dword_805224D; // weak
int dword_8052251; // weak
int dword_8052255; // weak
int dword_8052259; // weak
_UNKNOWN unk_805226D; // weak
int dword_805236D; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (08048CE0) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 80490F0: using guessed type int _gmon_start__(void);

//----- (08048D10) --------------------------------------------------------
int sub_8048D10()
{
  return dword_8052008();
}
// 8052008: using guessed type int (*dword_8052008)(void);

//----- (08049100) --------------------------------------------------------
#error "8049103: positive sp value has been found (funcsize=2)"

//----- (08049133) --------------------------------------------------------
void sub_8049133()
{
  ;
}

//----- (08049150) --------------------------------------------------------
void sub_8049150()
{
  ;
}

//----- (08049160) --------------------------------------------------------
int sub_8049160()
{
  int result; // eax

  result = &unk_805217F - &unk_805217C;
  if ( (unsigned int)(&unk_805217F - &unk_805217C) > 6 )
    result = 0;
  return result;
}
// 8049160: could not find valid save-restore pair for ebp

//----- (080491D0) --------------------------------------------------------
int sub_80491D0()
{
  int result; // eax

  if ( !byte_80521CC )
  {
    result = sub_8049160();
    byte_80521CC = 1;
  }
  return result;
}
// 80491D0: could not find valid save-restore pair for ebp
// 80521CC: using guessed type char byte_80521CC;

//----- (080491F0) --------------------------------------------------------
int sub_80491F0()
{
  return 0;
}
// 80491F0: could not find valid save-restore pair for ebp

//----- (0804924F) --------------------------------------------------------
void sub_804924F()
{
  ;
}

//----- (0804926B) --------------------------------------------------------
void sub_804926B()
{
  ;
}

//----- (0804927B) --------------------------------------------------------
int sub_804927B()
{
  int result; // eax

  result = &unk_8052173 - &unk_8052170;
  if ( (unsigned int)(&unk_8052173 - &unk_8052170) > 6 )
    result = 0;
  return result;
}
// 804927B: could not find valid save-restore pair for ebp

//----- (0804932C) --------------------------------------------------------
int sub_804932C()
{
  FILE *v0; // ebx
  char *v1; // eax

  v0 = stdout;
  v1 = gettext("\nWith no FILE, or when FILE is -, read standard input.\n");
  return fputs_unlocked(v1, v0);
}
// 8048F50: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);

//----- (08049357) --------------------------------------------------------
int sub_8049357()
{
  FILE *v0; // ebx
  char *v1; // eax

  v0 = stdout;
  v1 = gettext("\nMandatory arguments to long options are mandatory for short options too.\n");
  return fputs_unlocked(v1, v0);
}
// 8048F50: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);

//----- (08049382) --------------------------------------------------------
int __cdecl sub_8049382(char *s1)
{
  char *v1; // eax
  char *v2; // eax
  char *v3; // eax
  char *v4; // ebx
  char *v5; // eax
  char *v7; // [esp+1Ch] [ebp-4Ch]
  const char **i; // [esp+20h] [ebp-48h]
  const char *v9; // [esp+24h] [ebp-44h]
  const char *v10; // [esp+28h] [ebp-40h]
  const char *v11; // [esp+2Ch] [ebp-3Ch]
  const char *v12; // [esp+30h] [ebp-38h]
  const char *v13; // [esp+34h] [ebp-34h]
  const char *v14; // [esp+38h] [ebp-30h]
  const char *v15; // [esp+3Ch] [ebp-2Ch]
  const char *v16; // [esp+40h] [ebp-28h]
  const char *v17; // [esp+44h] [ebp-24h]
  const char *v18; // [esp+48h] [ebp-20h]
  const char *v19; // [esp+4Ch] [ebp-1Ch]
  const char *v20; // [esp+50h] [ebp-18h]
  const char *v21; // [esp+54h] [ebp-14h]
  int v22; // [esp+58h] [ebp-10h]
  int v23; // [esp+5Ch] [ebp-Ch]

  v10 = "[";
  v11 = "test invocation";
  v12 = "coreutils";
  v13 = "Multi-call invocation";
  v14 = "sha224sum";
  v15 = "sha2 utilities";
  v16 = "sha256sum";
  v17 = "sha2 utilities";
  v18 = "sha384sum";
  v19 = "sha2 utilities";
  v20 = "sha512sum";
  v21 = "sha2 utilities";
  v22 = 0;
  v23 = 0;
  v7 = s1;
  for ( i = &v10; *i && strcmp(s1, *i); i += 2 )
    ;
  if ( i[1] )
    v7 = (char *)i[1];
  v1 = gettext("\n%s online help: <%s>\n");
  printf(v1, "GNU coreutils", "http://www.gnu.org/software/coreutils/");
  v9 = setlocale(5, 0);
  if ( v9 && strncmp(v9, "en_", 3u) )
  {
    v2 = gettext("Report %s translation bugs to <http://translationproject.org/team/>\n");
    printf(v2, s1);
  }
  v3 = gettext("Full documentation at: <%s%s>\n");
  printf(v3, "http://www.gnu.org/software/coreutils/", s1);
  if ( v7 == s1 )
    v4 = " invocation";
  else
    v4 = &s;
  v5 = gettext("or available locally via: info '(coreutils) %s%s'\n");
  return printf(v5, v7, v4);
}

//----- (08049508) --------------------------------------------------------
void __cdecl __noreturn sub_8049508(int status)
{
  int v1; // ebx
  char *v2; // eax
  int v3; // ebx
  char *v4; // eax
  FILE *v5; // ebx
  char *v6; // eax
  FILE *v7; // ebx
  char *v8; // eax
  FILE *v9; // ebx
  char *v10; // eax
  char *v11; // eax

  if ( status )
  {
    v1 = dword_8052225;
    v2 = gettext("Try '%s --help' for more information.\n");
    fprintf(stderr, v2, v1);
  }
  else
  {
    v3 = dword_8052225;
    v4 = gettext("Usage: %s [OPTION]... [FILE]\nBase%d encode or decode FILE, or standard input, to standard output.\n");
    printf(v4, v3, 64);
    sub_804932C();
    sub_8049357();
    v5 = stdout;
    v6 = gettext(
           "  -d, --decode          decode data\n"
           "  -i, --ignore-garbage  when decoding, ignore non-alphabet characters\n"
           "  -w, --wrap=COLS       wrap encoded lines after COLS character (default 76).\n"
           "                          Use 0 to disable line wrapping\n"
           "\n");
    fputs_unlocked(v6, v5);
    v7 = stdout;
    v8 = gettext("      --help     display this help and exit\n");
    fputs_unlocked(v8, v7);
    v9 = stdout;
    v10 = gettext("      --version  output version information and exit\n");
    fputs_unlocked(v10, v9);
    v11 = gettext(
            "\n"
            "The data are encoded as described for the %s alphabet in RFC 4648.\n"
            "When decoding, the input may contain newlines in addition to the bytes of\n"
            "the formal %s alphabet.  Use --ignore-garbage to attempt to recover\n"
            "from any other non-alphabet bytes in the encoded stream.\n");
    printf(v11, "base64", "base64");
    sub_8049382("base64");
  }
  exit(status);
}
// 8048F50: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);
// 8052225: using guessed type int dword_8052225;

//----- (08049607) --------------------------------------------------------
size_t __cdecl sub_8049607(void *ptr, size_t n, int a3, int a4, int a5, FILE *stream)
{
  size_t result; // eax
  char *v7; // ebx
  int *v8; // eax
  __int64 v9; // rcx
  size_t v10; // eax
  char *v11; // ebx
  int *v12; // eax
  char *v13; // ebx
  int *v14; // eax
  size_t v15; // [esp+20h] [ebp-18h]
  size_t v16; // [esp+24h] [ebp-14h]

  if ( !__PAIR__(a4, a3) )
  {
    result = fwrite_unlocked(ptr, 1u, n, stdout);
    if ( result >= n )
      return result;
    v7 = gettext("write error");
    v8 = __errno_location();
    error(1, *v8, v7);
  }
  v15 = 0;
  while ( 1 )
  {
    result = v15;
    if ( v15 >= n )
      break;
    v9 = *(unsigned int *)a5;
    v10 = a3 - v9;
    if ( (__PAIR__((unsigned int)a4, a3) - v9) >> 32 )
      v10 = -1;
    if ( n - v15 <= v10 )
      v10 = n - v15;
    v16 = v10;
    if ( v10 )
    {
      if ( fwrite_unlocked((char *)ptr + v15, 1u, v10, stdout) < v10 )
      {
        v13 = gettext("write error");
        v14 = __errno_location();
        error(1, *v14, v13);
      }
      *(_DWORD *)a5 += v16;
      v15 += v16;
    }
    else
    {
      if ( fputc_unlocked(10, stream) == -1 )
      {
        v11 = gettext("write error");
        v12 = __errno_location();
        error(1, *v12, v11);
      }
      *(_DWORD *)a5 = 0;
    }
  }
  return result;
}

//----- (0804979D) --------------------------------------------------------
unsigned int __cdecl sub_804979D(FILE *a1, FILE *a2, __int64 a3)
{
  char *v3; // ebx
  int *v4; // eax
  char *v5; // ebx
  int *v6; // eax
  int v8; // [esp+30h] [ebp-11818h]
  unsigned int v9; // [esp+34h] [ebp-11814h]
  size_t v10; // [esp+38h] [ebp-11810h]
  char v11[30720]; // [esp+3Ch] [ebp-1180Ch]
  char ptr; // [esp+783Ch] [ebp-A00Ch]
  unsigned int v13; // [esp+1183Ch] [ebp-Ch]

  v13 = __readgsdword(0x14u);
  v8 = 0;
  do
  {
    v9 = 0;
    do
    {
      v10 = fread_unlocked(&v11[v9], 1u, 30720 - v9, a1);
      v9 += v10;
    }
    while ( !feof_unlocked(a1) && !ferror_unlocked(a1) && v9 <= 0x77FF );
    if ( v9 )
    {
      sub_804A213((unsigned __int8 *)v11, v9, &ptr, 4 * ((v9 + 2) / 3));
      sub_8049607(&ptr, 4 * ((v9 + 2) / 3), a3, SHIDWORD(a3), (int)&v8, a2);
    }
  }
  while ( !feof_unlocked(a1) && !ferror_unlocked(a1) && v9 == 30720 );
  if ( a3 && v8 && fputc_unlocked(10, a2) == -1 )
  {
    v3 = gettext("write error");
    v4 = __errno_location();
    error(1, *v4, v3);
  }
  if ( ferror_unlocked(a1) )
  {
    v5 = gettext("read error");
    v6 = __errno_location();
    error(1, *v6, v5);
  }
  return __readgsdword(0x14u) ^ v13;
}
// 804979D: using guessed type char var_1180C[30720];

//----- (080499EB) --------------------------------------------------------
unsigned int __cdecl sub_80499EB(FILE *a1, FILE *a2, char a3)
{
  char *v3; // ebx
  int *v4; // eax
  unsigned int v5; // eax
  size_t v6; // eax
  char *v7; // ebx
  int *v8; // eax
  char *v9; // eax
  unsigned int v10; // eax
  bool v12; // [esp+23h] [ebp-1C25h]
  size_t n; // [esp+24h] [ebp-1C24h]
  unsigned int v14; // [esp+28h] [ebp-1C20h]
  unsigned int i; // [esp+2Ch] [ebp-1C1Ch]
  size_t v16; // [esp+30h] [ebp-1C18h]
  int v17; // [esp+34h] [ebp-1C14h]
  char ptr; // [esp+3Ch] [ebp-1C0Ch]
  char v19[4096]; // [esp+C3Ch] [ebp-100Ch]
  unsigned int v20; // [esp+1C3Ch] [ebp-Ch]

  v20 = __readgsdword(0x14u);
  sub_804A49D(&v17);
  do
  {
    v14 = 0;
    do
    {
      n = fread_unlocked(&v19[v14], 1u, 4096 - v14, a1);
      if ( a3 )
      {
        v16 = 0;
        while ( n && v16 < n )
        {
          if ( sub_804A474(v19[v14 + v16]) || v19[v14 + v16] == 61 )
            ++v16;
          else
            memmove(&v19[v16 + v14], &v19[v14 + 1 + v16], --n - v16);
        }
      }
      v14 += n;
      if ( ferror_unlocked(a1) )
      {
        v3 = gettext("read error");
        v4 = __errno_location();
        error(1, *v4, v3);
      }
    }
    while ( v14 <= 0xFFF && !feof_unlocked(a1) );
    for ( i = 0; ; ++i )
    {
      v10 = feof_unlocked(a1) ? 2 : 1;
      if ( v10 <= i || i == 1 && !v17 )
        break;
      n = 3072;
      if ( i )
        v5 = 0;
      else
        v5 = v14;
      v12 = sub_804A826(&v17, (unsigned __int8 *)v19, v5, (int)&ptr, (int *)&n);
      v6 = fwrite_unlocked(&ptr, 1u, n, a2);
      if ( v6 < n )
      {
        v7 = gettext("write error");
        v8 = __errno_location();
        error(1, *v8, v7);
      }
      if ( v12 != 1 )
      {
        v9 = gettext("invalid input");
        error(1, 0, v9);
      }
    }
  }
  while ( !feof_unlocked(a1) );
  return __readgsdword(0x14u) ^ v20;
}
// 80499EB: using guessed type char var_100C[4096];

//----- (08049D20) --------------------------------------------------------
int __cdecl main(int argc, char **argv)
{
  char *v2; // eax
  void *v3; // ebx
  char *v4; // eax
  int v5; // eax
  void *v6; // ebx
  int *v7; // eax
  char *v8; // ebx
  int *v9; // eax
  void *v10; // ebx
  int *v11; // eax
  char v13; // [esp+2Ah] [ebp-1Ah]
  char v14; // [esp+2Bh] [ebp-19h]
  FILE *v15; // [esp+2Ch] [ebp-18h]
  const char *v16; // [esp+30h] [ebp-14h]
  int v17; // [esp+34h] [ebp-10h]
  __int64 v18; // [esp+38h] [ebp-Ch]

  v13 = 0;
  v14 = 0;
  v18 = 76LL;
  sub_804AC0C(*argv);
  setlocale(6, &s);
  bindtextdomain("coreutils", "/home/hwangdz/coreutils/coreutils-8.28/install_m32/share/locale");
  textdomain("coreutils");
  sub_804E0CD((int)sub_804AA8F);
  while ( 1 )
  {
    v17 = getopt_long(argc, argv, "diw:", &longopts, 0);
    if ( v17 == -1 )
      break;
    if ( v17 == 100 )
    {
      v13 = 1;
    }
    else
    {
      if ( v17 <= 100 )
      {
        if ( v17 == -131 )
        {
          sub_804CA52(stdout, (int)"base64", (int)"GNU coreutils", off_8052114, "Simon Josefsson", 0);
          exit(0);
        }
        if ( v17 == -130 )
          sub_8049508(0);
LABEL_16:
        sub_8049508(1);
      }
      if ( v17 == 105 )
      {
        v14 = 1;
      }
      else
      {
        if ( v17 != 119 )
          goto LABEL_16;
        v2 = gettext("invalid wrap size");
        v18 = sub_804CEEE(optarg, 0, 0, -1, -1, &s, (int)v2, 0);
      }
    }
  }
  if ( argc - optind > 1 )
  {
    v3 = sub_804C46B((int)argv[optind]);
    v4 = gettext("extra operand %s");
    error(0, 0, v4, v3);
    sub_8049508(1);
  }
  if ( optind >= argc )
  {
    v16 = "-";
    v5 = strcmp("-", "-");
  }
  else
  {
    v16 = argv[optind];
    v5 = strcmp(v16, "-");
  }
  if ( v5 )
  {
    v15 = (FILE *)fopen64(v16, "rb");
    if ( !v15 )
    {
      v6 = sub_804C233(0, 3, (int)v16);
      v7 = __errno_location();
      error(1, *v7, "%s", v6);
    }
    sub_804ABC4(v15, 2);
  }
  else
  {
    sub_804CD8D();
    v15 = (FILE *)stdin;
    sub_804ABC4((FILE *)stdin, 2);
  }
  if ( v13 )
    sub_80499EB(v15, stdout, v14);
  else
    sub_804979D(v15, stdout, v18);
  if ( sub_804D40C(v15) == -1 )
  {
    if ( !strcmp(v16, "-") )
    {
      v8 = gettext("closing standard input");
      v9 = __errno_location();
      error(1, *v9, v8);
    }
    v10 = sub_804C233(0, 3, (int)v16);
    v11 = __errno_location();
    error(1, *v11, "%s", v10);
  }
  return 0;
}
// 8048E40: using guessed type int __cdecl fopen64(_DWORD, _DWORD);
// 80521A0: using guessed type int optind;
// 80521C0: using guessed type int stdin;

//----- (0804A0ED) --------------------------------------------------------
int __cdecl sub_804A0ED(unsigned __int8 a1)
{
  return a1;
}

//----- (0804A0FF) --------------------------------------------------------
void __cdecl sub_804A0FF(unsigned __int8 *a1, int a2, int a3)
{
  _BYTE *v3; // ebx
  _BYTE *v4; // ebx
  char v5; // si
  char v6; // si
  _BYTE *v7; // ebx
  _BYTE *v8; // [esp+1Ch] [ebp+10h]

  while ( a2 )
  {
    v3 = (_BYTE *)a3;
    v8 = (_BYTE *)(a3 + 1);
    *v3 = byte_804E7E0[(unsigned __int8)sub_804A0ED(*a1) >> 2];
    v4 = v8++;
    v5 = 16 * sub_804A0ED(*a1);
    *v4 = byte_804E7E0[(v5 + ((unsigned __int8)sub_804A0ED(a1[1]) >> 4)) & 0x3F];
    v6 = 4 * sub_804A0ED(a1[1]);
    *v8 = byte_804E7E0[(v6 + ((unsigned __int8)sub_804A0ED(a1[2]) >> 6)) & 0x3F];
    v7 = v8 + 1;
    a3 = (int)(v8 + 2);
    *v7 = byte_804E7E0[sub_804A0ED(a1[2]) & 0x3F];
    a2 -= 3;
    a1 += 3;
  }
}

//----- (0804A213) --------------------------------------------------------
void __cdecl sub_804A213(unsigned __int8 *a1, int a2, char *a3, unsigned int a4)
{
  char *v4; // ebx
  char *v5; // ebx
  char v6; // si
  char v7; // al
  char *v8; // ebx
  char v9; // si
  char v10; // al
  char v11; // al
  char *v12; // ebx
  int v13; // eax

  if ( a4 & 3 || 3 * (a4 >> 2) != a2 )
  {
    while ( a2 )
    {
      if ( !a4 )
        break;
      v4 = a3++;
      *v4 = byte_804E7E0[(unsigned __int8)sub_804A0ED(*a1) >> 2];
      if ( !--a4 )
        break;
      v5 = a3++;
      v6 = 16 * sub_804A0ED(*a1);
      v7 = --a2 ? (unsigned __int8)sub_804A0ED(a1[1]) >> 4 : 0;
      *v5 = byte_804E7E0[(v6 + v7) & 0x3F];
      if ( !--a4 )
        break;
      v8 = a3++;
      if ( a2 )
      {
        v9 = 4 * sub_804A0ED(a1[1]);
        v10 = --a2 ? (unsigned __int8)sub_804A0ED(a1[2]) >> 6 : 0;
        v11 = byte_804E7E0[(v9 + v10) & 0x3F];
      }
      else
      {
        v11 = 61;
      }
      *v8 = v11;
      if ( !--a4 )
        break;
      v12 = a3++;
      if ( a2 )
        v13 = (unsigned __int8)byte_804E7E0[sub_804A0ED(a1[2]) & 0x3F];
      else
        LOBYTE(v13) = 61;
      *v12 = v13;
      if ( !--a4 )
        break;
      if ( a2 )
        --a2;
      if ( a2 )
        a1 += 3;
    }
    if ( a4 )
      *a3 = 0;
  }
  else
  {
    sub_804A0FF(a1, a2, (int)a3);
  }
}

//----- (0804A474) --------------------------------------------------------
char __cdecl sub_804A474(unsigned __int8 a1)
{
  return (unsigned __int8)~byte_804E820[(unsigned __int8)sub_804A0ED(a1)] >> 7;
}

//----- (0804A49D) --------------------------------------------------------
_DWORD *__cdecl sub_804A49D(_DWORD *a1)
{
  _DWORD *result; // eax

  result = a1;
  *a1 = 0;
  return result;
}

//----- (0804A4AB) --------------------------------------------------------
int __cdecl sub_804A4AB(_DWORD *a1, char **a2, unsigned int a3, _DWORD *a4)
{
  int result; // eax
  char *v5; // eax
  int v6; // eax
  char v7; // [esp+17h] [ebp-11h]
  char *v8; // [esp+18h] [ebp-10h]
  char *s; // [esp+1Ch] [ebp-Ch]

  if ( *a1 == 4 )
    *a1 = 0;
  if ( *a1 || (s = *a2, (signed int)(a3 - (_DWORD)*a2) <= 3) || memchr(s, 10, 4u) )
  {
    v8 = *a2;
    while ( (unsigned int)v8 < a3 )
    {
      v5 = v8++;
      v7 = *v5;
      if ( *v5 != 10 )
      {
        v6 = (*a1)++;
        *((_BYTE *)a1 + v6 + 4) = v7;
        if ( *a1 == 4 )
          break;
      }
    }
    *a2 = v8;
    *a4 = *a1;
    result = (int)(a1 + 1);
  }
  else
  {
    *a2 += 4;
    *a4 = 4;
    result = (int)s;
  }
  return result;
}

//----- (0804A585) --------------------------------------------------------
signed int __cdecl sub_804A585(unsigned __int8 *a1, unsigned int a2, _DWORD *a3, _DWORD *a4)
{
  _BYTE *v5; // ebx
  int v6; // esi
  _BYTE *v7; // ebx
  int v8; // esi
  _BYTE *v9; // ebx
  int v10; // esi
  _BYTE *v11; // [esp+10h] [ebp-Ch]

  v11 = (_BYTE *)*a3;
  if ( a2 <= 1 )
    return 0;
  if ( (unsigned __int8)sub_804A474(*a1) ^ 1 || (unsigned __int8)sub_804A474(a1[1]) ^ 1 )
    return 0;
  if ( *a4 )
  {
    v5 = v11++;
    v6 = 4 * byte_804E820[(unsigned __int8)sub_804A0ED(*a1)];
    *v5 = v6 | (byte_804E820[(unsigned __int8)sub_804A0ED(a1[1])] >> 4);
    --*a4;
  }
  if ( a2 == 2 )
  {
    *a3 = v11;
    return 0;
  }
  if ( a1[2] == 61 )
  {
    if ( a2 != 4 )
    {
      *a3 = v11;
      return 0;
    }
    if ( a1[3] != 61 )
    {
      *a3 = v11;
      return 0;
    }
  }
  else
  {
    if ( (unsigned __int8)sub_804A474(a1[2]) ^ 1 )
    {
      *a3 = v11;
      return 0;
    }
    if ( *a4 )
    {
      v7 = v11++;
      v8 = 16 * byte_804E820[(unsigned __int8)sub_804A0ED(a1[1])];
      *v7 = v8 | (byte_804E820[(unsigned __int8)sub_804A0ED(a1[2])] >> 2);
      --*a4;
    }
    if ( a2 == 3 )
    {
      *a3 = v11;
      return 0;
    }
    if ( a1[3] == 61 )
    {
      if ( a2 != 4 )
      {
        *a3 = v11;
        return 0;
      }
    }
    else
    {
      if ( (unsigned __int8)sub_804A474(a1[3]) ^ 1 )
      {
        *a3 = v11;
        return 0;
      }
      if ( *a4 )
      {
        v9 = v11++;
        v10 = byte_804E820[(unsigned __int8)sub_804A0ED(a1[2])] << 6;
        *v9 = v10 | byte_804E820[(unsigned __int8)sub_804A0ED(a1[3])];
        --*a4;
      }
    }
  }
  *a3 = v11;
  return 1;
}

//----- (0804A826) --------------------------------------------------------
bool __cdecl sub_804A826(int *a1, unsigned __int8 *a2, unsigned int a3, int a4, int *a5)
{
  bool v6; // [esp+1Ah] [ebp-1Eh]
  bool v7; // [esp+1Bh] [ebp-1Dh]
  int v8; // [esp+1Ch] [ebp-1Ch]
  int v9; // [esp+20h] [ebp-18h]
  int v10; // [esp+24h] [ebp-14h]
  unsigned __int8 *v11; // [esp+28h] [ebp-10h]
  unsigned int v12; // [esp+2Ch] [ebp-Ch]

  v8 = *a5;
  v7 = a1 != 0;
  v6 = 0;
  v9 = 0;
  if ( a1 )
  {
    v9 = *a1;
    v6 = a3 == 0;
  }
  while ( 1 )
  {
    v10 = v8;
    if ( !v9 && v6 != 1 )
    {
      while ( 1 )
      {
        v10 = v8;
        if ( (unsigned __int8)sub_804A585(a2, a3, &a4, &v8) ^ 1 )
          break;
        a2 += 4;
        a3 -= 4;
      }
    }
    if ( !a3 && v6 != 1 )
      break;
    if ( a3 && *a2 == 10 && v7 )
    {
      ++a2;
      --a3;
    }
    else
    {
      a4 += v8 - v10;
      v8 = v10;
      v12 = (unsigned int)&a2[a3];
      if ( v7 )
        v11 = (unsigned __int8 *)sub_804A4AB(a1, (char **)&a2, v12, &a3);
      else
        v11 = a2;
      if ( !a3 || a3 <= 3 && v6 != 1 && v7 )
      {
        a3 = 0;
        break;
      }
      if ( (unsigned __int8)sub_804A585(v11, a3, &a4, &v8) ^ 1 )
        break;
      a3 = v12 - (_DWORD)a2;
    }
  }
  *a5 -= v8;
  return a3 == 0;
}

//----- (0804AA8F) --------------------------------------------------------
int sub_804AA8F()
{
  void *v0; // ebx
  int *v1; // eax
  int *v2; // eax
  int result; // eax
  char *v4; // [esp+2Ch] [ebp-Ch]

  if ( sub_804D738(stdout) && (byte_8052221 != 1 || *__errno_location() != 32) )
  {
    v4 = gettext("write error");
    if ( dword_805221D )
    {
      v0 = sub_804C1F6(dword_805221D);
      v1 = __errno_location();
      error(0, *v1, "%s: %s", v0, v4);
    }
    else
    {
      v2 = __errno_location();
      error(0, *v2, "%s", v4);
    }
    _exit(status);
  }
  result = sub_804D738(stderr);
  if ( result )
    _exit(status);
  return result;
}
// 805221D: using guessed type int dword_805221D;
// 8052221: using guessed type char byte_8052221;

//----- (0804AB73) --------------------------------------------------------
int __cdecl sub_804AB73(int a1, int a2, int a3, int a4, int a5, int a6)
{
  return posix_fadvise64(a1, a2, a3, a4, a5, a6);
}
// 8049070: using guessed type int __cdecl posix_fadvise64(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804ABC4) --------------------------------------------------------
void __cdecl sub_804ABC4(FILE *stream, int a2)
{
  int v2; // eax

  if ( stream )
  {
    v2 = fileno(stream);
    sub_804AB73(v2, 0, 0, 0, 0, a2);
  }
}

//----- (0804AC0C) --------------------------------------------------------
char *__cdecl sub_804AC0C(char *s)
{
  char *v1; // eax
  char *result; // eax
  char *v3; // [esp+18h] [ebp-10h]
  char *s1; // [esp+1Ch] [ebp-Ch]

  if ( !s )
  {
    fwrite("A NULL argv[0] was passed through an exec system call.\n", 1u, 0x37u, stderr);
    abort();
  }
  v3 = strrchr(s, 47);
  if ( v3 )
    v1 = v3 + 1;
  else
    v1 = s;
  s1 = v1;
  if ( v1 - s > 6 && !strncmp(v1 - 7, "/.libs/", 7u) )
  {
    s = s1;
    if ( !strncmp(s1, "lt-", 3u) )
    {
      s = s1 + 3;
      program_invocation_short_name = (int)(s1 + 3);
    }
  }
  dword_8052225 = (int)s;
  result = s;
  program_invocation_name = (int)s;
  return result;
}
// 8052180: using guessed type int program_invocation_short_name;
// 8052190: using guessed type int program_invocation_name;
// 8052225: using guessed type int dword_8052225;

//----- (0804AD58) --------------------------------------------------------
int __cdecl sub_804AD58(int *a1, unsigned __int8 a2, char a3)
{
  int *v3; // eax
  int v4; // ST10_4

  if ( a1 )
    v3 = a1;
  else
    v3 = &dword_805222D;
  v4 = ((unsigned int)v3[(a2 >> 5) + 2] >> (a2 & 0x1F)) & 1;
  v3[(a2 >> 5) + 2] ^= (v4 ^ a3 & 1) << (a2 & 0x1F);
  return v4;
}
// 805222D: using guessed type int dword_805222D;

//----- (0804AE02) --------------------------------------------------------
int *__cdecl sub_804AE02(int *a1, int a2, int a3)
{
  int *result; // eax

  if ( !a1 )
    a1 = &dword_805222D;
  *a1 = 10;
  if ( !a2 || !a3 )
    abort();
  a1[10] = a2;
  result = a1;
  a1[11] = a3;
  return result;
}
// 805222D: using guessed type int dword_805222D;

//----- (0804AE43) --------------------------------------------------------
_DWORD *__userpurge sub_804AE43@<eax>(_DWORD *a1, int a2)
{
  int v3; // [esp+0h] [ebp-38h]
  int v4; // [esp+4h] [ebp-34h]
  int v5; // [esp+8h] [ebp-30h]
  int v6; // [esp+Ch] [ebp-2Ch]
  int v7; // [esp+10h] [ebp-28h]
  int v8; // [esp+14h] [ebp-24h]
  int v9; // [esp+18h] [ebp-20h]
  int v10; // [esp+1Ch] [ebp-1Ch]
  int v11; // [esp+20h] [ebp-18h]
  int v12; // [esp+24h] [ebp-14h]
  int v13; // [esp+28h] [ebp-10h]
  int v14; // [esp+2Ch] [ebp-Ch]

  memset(&v3, 0, 0x30u);
  if ( a2 == 10 )
    abort();
  *a1 = a2;
  a1[1] = v4;
  a1[2] = v5;
  a1[3] = v6;
  a1[4] = v7;
  a1[5] = v8;
  a1[6] = v9;
  a1[7] = v10;
  a1[8] = v11;
  a1[9] = v12;
  a1[10] = v13;
  a1[11] = v14;
  return a1;
}

//----- (0804AEC5) --------------------------------------------------------
const char *__cdecl sub_804AEC5(char *msgid, int a2)
{
  const char *result; // eax
  char *v3; // [esp+18h] [ebp-10h]
  unsigned __int8 *v4; // [esp+1Ch] [ebp-Ch]

  v3 = gettext(msgid);
  if ( v3 != msgid )
    return v3;
  v4 = (unsigned __int8 *)sub_804DC8F();
  if ( sub_804D6D3(v4, "UTF-8") )
  {
    if ( sub_804D6D3(v4, "GB18030") )
    {
      if ( a2 == 9 )
        result = (const char *)&unk_804EA65;
      else
        result = "'";
    }
    else if ( *msgid == 96 )
    {
      result = (const char *)&unk_804EA5E;
    }
    else
    {
      result = (const char *)&unk_804EA62;
    }
  }
  else if ( *msgid == 96 )
  {
    result = (const char *)&unk_804EA4E;
  }
  else
  {
    result = (const char *)&unk_804EA52;
  }
  return result;
}

//----- (0804AF60) --------------------------------------------------------
unsigned int __cdecl sub_804AF60(int a1, unsigned int a2, int a3, size_t a4, signed int a5, int a6, int a7, char *a8, char *a9)
{
  size_t v9; // ebx
  size_t v10; // eax
  bool v11; // al
  bool v12; // al
  unsigned int result; // eax
  char *v14; // [esp+2Ch] [ebp-5Ch]
  char *v15; // [esp+30h] [ebp-58h]
  char v16; // [esp+40h] [ebp-48h]
  bool v17; // [esp+41h] [ebp-47h]
  char v18; // [esp+42h] [ebp-46h]
  char v19; // [esp+43h] [ebp-45h]
  char v20; // [esp+44h] [ebp-44h]
  unsigned __int8 v21; // [esp+45h] [ebp-43h]
  char v22; // [esp+46h] [ebp-42h]
  char v23; // [esp+47h] [ebp-41h]
  char v24; // [esp+48h] [ebp-40h]
  char v25; // [esp+49h] [ebp-3Fh]
  bool v26; // [esp+4Ah] [ebp-3Eh]
  bool v27; // [esp+4Bh] [ebp-3Dh]
  wint_t wc; // [esp+4Ch] [ebp-3Ch]
  int v29; // [esp+50h] [ebp-38h]
  unsigned int v30; // [esp+54h] [ebp-34h]
  unsigned int v31; // [esp+58h] [ebp-30h]
  char *s; // [esp+5Ch] [ebp-2Ch]
  size_t n; // [esp+60h] [ebp-28h]
  unsigned int v34; // [esp+64h] [ebp-24h]
  unsigned int v35; // [esp+68h] [ebp-20h]
  size_t v36; // [esp+6Ch] [ebp-1Ch]
  unsigned int v37; // [esp+70h] [ebp-18h]
  mbstate_t ps; // [esp+74h] [ebp-14h]
  unsigned int v39; // [esp+7Ch] [ebp-Ch]

  v15 = a8;
  v14 = a9;
  v39 = __readgsdword(0x14u);
  v30 = 0;
  v31 = 0;
  s = 0;
  n = 0;
  v16 = 0;
  v27 = __ctype_get_mb_cur_max() == 1;
  v17 = (a6 & 2) != 0;
  v18 = 0;
  v19 = 0;
  v20 = 1;
  while ( 1 )
  {
    switch ( a5 )
    {
      case 0:
        v17 = 0;
        break;
      case 1:
        goto LABEL_20;
      case 2:
        goto LABEL_23;
      case 3:
        v16 = 1;
LABEL_20:
        v17 = 1;
        goto LABEL_21;
      case 4:
LABEL_21:
        if ( v17 != 1 )
          v16 = 1;
LABEL_23:
        a5 = 2;
        if ( v17 != 1 )
        {
          if ( v30 < a2 )
            *(_BYTE *)(a1 + v30) = 39;
          ++v30;
        }
        s = "'";
        n = 1;
        break;
      case 5:
        goto LABEL_4;
      case 6:
        a5 = 5;
        v17 = 1;
LABEL_4:
        if ( v17 != 1 )
        {
          if ( v30 < a2 )
            *(_BYTE *)(a1 + v30) = 34;
          ++v30;
        }
        v16 = 1;
        s = (char *)&unk_804EA65;
        n = 1;
        break;
      case 7:
        v16 = 1;
        v17 = 0;
        break;
      case 8:
      case 9:
      case 10:
        if ( a5 != 10 )
        {
          v15 = (char *)sub_804AEC5("`", a5);
          v14 = (char *)sub_804AEC5("'", a5);
        }
        if ( v17 != 1 )
        {
          for ( s = v15; *s; ++s )
          {
            if ( v30 < a2 )
              *(_BYTE *)(v30 + a1) = *s;
            ++v30;
          }
        }
        v16 = 1;
        s = v14;
        n = strlen(v14);
        break;
      default:
        abort();
        return result;
    }
    v29 = 0;
    while ( 1 )
    {
      v12 = a4 == -1 ? *(_BYTE *)(a3 + v29) != 0 : v29 != a4;
      if ( !v12 )
        break;
      v23 = 0;
      v24 = 0;
      v25 = 0;
      if ( v16 && a5 != 2 && n )
      {
        v9 = v29 + n;
        if ( a4 != -1 || n <= 1 )
        {
          v10 = a4;
        }
        else
        {
          v10 = strlen((const char *)a3);
          a4 = v10;
        }
        if ( v9 <= v10 && !memcmp((const void *)(v29 + a3), s, n) )
        {
          if ( v17 )
            goto LABEL_245;
          v23 = 1;
        }
      }
      v21 = *(_BYTE *)(a3 + v29);
      switch ( v21 )
      {
        case 0u:
          if ( v16 )
          {
            if ( v17 )
              goto LABEL_245;
            v24 = 1;
            if ( a5 == 2 && v18 != 1 )
            {
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 36;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              ++v30;
              v18 = 1;
            }
            if ( v30 < a2 )
              *(_BYTE *)(a1 + v30) = 92;
            ++v30;
            if ( a5 != 2 && v29 + 1 < a4 && *(_BYTE *)(v29 + 1 + a3) > 47 && *(_BYTE *)(v29 + 1 + a3) <= 57 )
            {
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 48;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 48;
              ++v30;
            }
            v21 = 48;
          }
          else if ( a6 & 1 )
          {
            goto LABEL_219;
          }
          goto LABEL_189;
        case 7u:
          v22 = 97;
          goto LABEL_103;
        case 8u:
          v22 = 98;
          goto LABEL_103;
        case 9u:
          v22 = 116;
          goto LABEL_101;
        case 0xAu:
          v22 = 110;
          goto LABEL_101;
        case 0xBu:
          v22 = 118;
          goto LABEL_103;
        case 0xCu:
          v22 = 102;
          goto LABEL_103;
        case 0xDu:
          v22 = 114;
          goto LABEL_101;
        case 0x20u:
          goto LABEL_111;
        case 0x21u:
        case 0x22u:
        case 0x24u:
        case 0x26u:
        case 0x28u:
        case 0x29u:
        case 0x2Au:
        case 0x3Bu:
        case 0x3Cu:
        case 0x3Du:
        case 0x3Eu:
        case 0x5Bu:
        case 0x5Eu:
        case 0x60u:
        case 0x7Cu:
          goto LABEL_112;
        case 0x23u:
        case 0x7Eu:
          goto LABEL_110;
        case 0x25u:
        case 0x2Bu:
        case 0x2Cu:
        case 0x2Du:
        case 0x2Eu:
        case 0x2Fu:
        case 0x30u:
        case 0x31u:
        case 0x32u:
        case 0x33u:
        case 0x34u:
        case 0x35u:
        case 0x36u:
        case 0x37u:
        case 0x38u:
        case 0x39u:
        case 0x3Au:
        case 0x41u:
        case 0x42u:
        case 0x43u:
        case 0x44u:
        case 0x45u:
        case 0x46u:
        case 0x47u:
        case 0x48u:
        case 0x49u:
        case 0x4Au:
        case 0x4Bu:
        case 0x4Cu:
        case 0x4Du:
        case 0x4Eu:
        case 0x4Fu:
        case 0x50u:
        case 0x51u:
        case 0x52u:
        case 0x53u:
        case 0x54u:
        case 0x55u:
        case 0x56u:
        case 0x57u:
        case 0x58u:
        case 0x59u:
        case 0x5Au:
        case 0x5Du:
        case 0x5Fu:
        case 0x61u:
        case 0x62u:
        case 0x63u:
        case 0x64u:
        case 0x65u:
        case 0x66u:
        case 0x67u:
        case 0x68u:
        case 0x69u:
        case 0x6Au:
        case 0x6Bu:
        case 0x6Cu:
        case 0x6Du:
        case 0x6Eu:
        case 0x6Fu:
        case 0x70u:
        case 0x71u:
        case 0x72u:
        case 0x73u:
        case 0x74u:
        case 0x75u:
        case 0x76u:
        case 0x77u:
        case 0x78u:
        case 0x79u:
        case 0x7Au:
          v25 = 1;
          goto LABEL_189;
        case 0x27u:
          v19 = 1;
          v25 = 1;
          if ( a5 != 2 )
            goto LABEL_189;
          if ( v17 )
            goto LABEL_245;
          if ( a2 && !v31 )
          {
            v31 = a2;
            a2 = 0;
          }
          if ( v30 < a2 )
            *(_BYTE *)(a1 + v30) = 39;
          if ( ++v30 < a2 )
            *(_BYTE *)(a1 + v30) = 92;
          if ( ++v30 < a2 )
            *(_BYTE *)(a1 + v30) = 39;
          ++v30;
          v18 = 0;
          goto LABEL_189;
        case 0x3Fu:
          if ( a5 == 2 )
          {
            if ( v17 )
              goto LABEL_245;
          }
          else if ( a5 == 5 && a6 & 4 && v29 + 2 < a4 && *(_BYTE *)(v29 + 1 + a3) == 63 )
          {
            switch ( *(char *)(v29 + 2 + a3) )
            {
              case 33:
              case 39:
              case 40:
              case 41:
              case 45:
              case 47:
              case 60:
              case 61:
              case 62:
                if ( v17 )
                  goto LABEL_245;
                v21 = *(_BYTE *)(v29 + 2 + a3);
                v29 += 2;
                if ( v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 63;
                if ( ++v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 34;
                if ( ++v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 34;
                if ( ++v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 63;
                ++v30;
                break;
              default:
                goto LABEL_189;
            }
          }
          goto LABEL_189;
        case 0x5Cu:
          v22 = *(_BYTE *)(a3 + v29);
          if ( a5 == 2 )
          {
            if ( v17 )
              goto LABEL_245;
          }
          else
          {
            if ( v16 && v17 && n )
              goto LABEL_208;
LABEL_101:
            if ( a5 == 2 && v17 )
              goto LABEL_245;
LABEL_103:
            if ( v16 )
            {
              v21 = v22;
            }
            else
            {
LABEL_189:
              if ( ((v16 != 1 || a5 == 2) && v17 != 1 || !a7
                                                      || !((*(_DWORD *)(4 * (v21 >> 5) + a7) >> (v21 & 0x1F)) & 1))
                && v23 != 1 )
              {
                goto LABEL_208;
              }
            }
            if ( v17 )
              goto LABEL_245;
            v24 = 1;
            if ( a5 == 2 && v18 != 1 )
            {
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 36;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              ++v30;
              v18 = 1;
            }
            if ( v30 < a2 )
              *(_BYTE *)(a1 + v30) = 92;
            ++v30;
          }
LABEL_208:
          if ( v18 && v24 != 1 )
          {
            if ( v30 < a2 )
              *(_BYTE *)(a1 + v30) = 39;
            if ( ++v30 < a2 )
              *(_BYTE *)(a1 + v30) = 39;
            ++v30;
            v18 = 0;
          }
          if ( v30 < a2 )
            *(_BYTE *)(v30 + a1) = v21;
          ++v30;
          if ( v25 != 1 )
            v20 = 0;
LABEL_219:
          ++v29;
          break;
        case 0x7Bu:
        case 0x7Du:
          if ( a4 == -1 )
            v11 = *(_BYTE *)(a3 + 1) != 0;
          else
            v11 = a4 != 1;
          if ( v11 )
            goto LABEL_189;
LABEL_110:
          if ( v29 )
            goto LABEL_189;
LABEL_111:
          v25 = 1;
LABEL_112:
          if ( a5 != 2 || !v17 )
            goto LABEL_189;
          goto LABEL_245;
        default:
          if ( v27 )
          {
            v34 = 1;
            v26 = ((*__ctype_b_loc())[v21] & 0x4000) != 0;
            goto LABEL_151;
          }
          memset(&ps, 0, 8u);
          v34 = 0;
          v26 = 1;
          if ( a4 == -1 )
            a4 = strlen((const char *)a3);
          while ( 2 )
          {
            v36 = sub_804D61A((wchar_t *)&wc, (char *)(a3 + v34 + v29), a4 - (v34 + v29), &ps);
            if ( v36 )
            {
              if ( v36 == -1 )
              {
                v26 = 0;
              }
              else
              {
                if ( v36 != -2 )
                {
                  if ( v17 && a5 == 2 )
                  {
                    v35 = 1;
                    while ( v35 < v36 )
                    {
                      switch ( *(char *)(v35 + v34 + v29 + a3) )
                      {
                        case 91:
                        case 92:
                        case 94:
                        case 96:
                        case 124:
                          goto LABEL_245;
                        default:
                          ++v35;
                          break;
                      }
                    }
                  }
                  if ( !iswprint(wc) )
                    v26 = 0;
                  v34 += v36;
                  if ( mbsinit(&ps) )
                    break;
                  continue;
                }
                v26 = 0;
                while ( v29 + v34 < a4 && *(_BYTE *)(v34 + v29 + a3) )
                  ++v34;
              }
            }
            break;
          }
LABEL_151:
          v25 = v26;
          if ( v34 <= 1 && (!v16 || v26 == 1) )
            goto LABEL_189;
          v37 = v29 + v34;
          while ( 1 )
          {
            if ( v16 && v26 != 1 )
            {
              if ( v17 )
                goto LABEL_245;
              v24 = 1;
              if ( a5 == 2 && v18 != 1 )
              {
                if ( v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 39;
                if ( ++v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 36;
                if ( ++v30 < a2 )
                  *(_BYTE *)(a1 + v30) = 39;
                ++v30;
                v18 = 1;
              }
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 92;
              if ( ++v30 < a2 )
                *(_BYTE *)(v30 + a1) = (v21 >> 6) + 48;
              if ( ++v30 < a2 )
                *(_BYTE *)(v30 + a1) = ((v21 >> 3) & 7) + 48;
              ++v30;
              v21 = (v21 & 7) + 48;
            }
            else if ( v23 )
            {
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 92;
              ++v30;
              v23 = 0;
            }
            if ( v29 + 1 >= v37 )
              goto LABEL_208;
            if ( v18 && v24 != 1 )
            {
              if ( v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              if ( ++v30 < a2 )
                *(_BYTE *)(a1 + v30) = 39;
              ++v30;
              v18 = 0;
            }
            if ( v30 < a2 )
              *(_BYTE *)(v30 + a1) = v21;
            ++v30;
            v21 = *(_BYTE *)(a3 + ++v29);
          }
      }
    }
    if ( !v30 && a5 == 2 && v17 )
      break;
    if ( a5 != 2 || v17 == 1 || !v19 )
      goto LABEL_251;
    if ( v20 )
      return sub_804AF60(a1, v31, a3, a4, 5, a6, a7, v15, v14);
    if ( a2 || !v31 )
    {
LABEL_251:
      if ( s && v17 != 1 )
      {
        while ( *s )
        {
          if ( v30 < a2 )
            *(_BYTE *)(v30 + a1) = *s;
          ++v30;
          ++s;
        }
      }
      if ( v30 < a2 )
        *(_BYTE *)(a1 + v30) = 0;
      return v30;
    }
    a2 = v31;
    v30 = 0;
  }
LABEL_245:
  if ( a5 == 2 && v16 )
    a5 = 4;
  return sub_804AF60(a1, a2, a3, a4, a5, a6 & 0xFFFFFFFD, 0, v15, v14);
}

//----- (0804BBFD) --------------------------------------------------------
void *__cdecl sub_804BBFD(int a1, size_t a2, _DWORD *a3, int *a4)
{
  int *v4; // eax
  int *v5; // ST3C_4
  int v6; // ST40_4
  int v7; // ST44_4
  unsigned int size; // [esp+48h] [ebp-10h]
  void *v10; // [esp+4Ch] [ebp-Ch]

  if ( a4 )
    v4 = a4;
  else
    v4 = &dword_805222D;
  v5 = v4;
  v6 = *__errno_location();
  v7 = v5[1] | (a3 == 0);
  size = sub_804AF60(0, 0, a1, a2, *v5, v7, (int)(v5 + 2), (char *)v5[10], (char *)v5[11]) + 1;
  v10 = sub_804CBEC(size);
  sub_804AF60((int)v10, size, a1, a2, *v5, v7, (int)(v5 + 2), (char *)v5[10], (char *)v5[11]);
  *__errno_location() = v6;
  if ( a3 )
    *a3 = size - 1;
  return v10;
}
// 805222D: using guessed type int dword_805222D;

//----- (0804BDA4) --------------------------------------------------------
void *__cdecl sub_804BDA4(signed int a1, int a2, size_t a3, int a4)
{
  int *v4; // eax
  void *v5; // edx
  size_t v6; // ST44_4
  bool v8; // [esp+37h] [ebp-21h]
  int *v9; // [esp+38h] [ebp-20h]
  void *ptr; // [esp+3Ch] [ebp-1Ch]
  int v11; // [esp+40h] [ebp-18h]
  int size; // [esp+44h] [ebp-14h]
  int v13; // [esp+48h] [ebp-10h]
  unsigned int v14; // [esp+4Ch] [ebp-Ch]

  v11 = *__errno_location();
  v9 = off_8052138;
  if ( a1 < 0 )
    abort();
  if ( dword_805212C <= a1 )
  {
    v8 = off_8052138 == &dword_8052130;
    if ( (unsigned int)a1 > 0xFFFFFFE )
      sub_804CD4F();
    if ( v8 )
      v4 = 0;
    else
      v4 = off_8052138;
    v9 = (int *)sub_804CC29(v4, 8 * (a1 + 1));
    off_8052138 = v9;
    if ( v8 )
    {
      v5 = off_8052134;
      *v9 = dword_8052130;
      v9[1] = (int)v5;
    }
    memset(&v9[2 * dword_805212C], 0, 8 * (a1 + 1 - dword_805212C));
    dword_805212C = a1 + 1;
  }
  v6 = v9[2 * a1];
  ptr = (void *)v9[2 * a1 + 1];
  v13 = *(_DWORD *)(a4 + 4) | 1;
  v14 = sub_804AF60(
          v9[2 * a1 + 1],
          v9[2 * a1],
          a2,
          a3,
          *(_DWORD *)a4,
          v13,
          a4 + 8,
          *(char **)(a4 + 40),
          *(char **)(a4 + 44));
  if ( v6 <= v14 )
  {
    size = v14 + 1;
    v9[2 * a1] = v14 + 1;
    if ( ptr != &unk_805226D )
      free(ptr);
    ptr = sub_804CBEC(size);
    v9[2 * a1 + 1] = (int)ptr;
    sub_804AF60((int)ptr, size, a2, a3, *(_DWORD *)a4, v13, a4 + 8, *(char **)(a4 + 40), *(char **)(a4 + 44));
  }
  *__errno_location() = v11;
  return ptr;
}
// 805212C: using guessed type int dword_805212C;
// 8052130: using guessed type int dword_8052130;
// 8052134: using guessed type void *off_8052134;
// 8052138: using guessed type int *off_8052138;

//----- (0804BFCD) --------------------------------------------------------
void *__cdecl sub_804BFCD(signed int a1, int a2)
{
  return sub_804BDA4(a1, a2, 0xFFFFFFFF, (int)&dword_805222D);
}
// 805222D: using guessed type int dword_805222D;

//----- (0804BFF7) --------------------------------------------------------
void *__cdecl sub_804BFF7(signed int a1, int a2, size_t a3)
{
  return sub_804BDA4(a1, a2, a3, (int)&dword_805222D);
}
// 805222D: using guessed type int dword_805222D;

//----- (0804C05D) --------------------------------------------------------
void *__cdecl sub_804C05D(signed int a1, int a2, int a3)
{
  char v4; // [esp+10h] [ebp-38h]

  sub_804AE43(&v4, a2);
  return sub_804BDA4(a1, a3, 0xFFFFFFFF, (int)&v4);
}

//----- (0804C09B) --------------------------------------------------------
void *__cdecl sub_804C09B(signed int a1, int a2, int a3, size_t a4)
{
  char v5; // [esp+10h] [ebp-38h]

  sub_804AE43(&v5, a2);
  return sub_804BDA4(a1, a3, a4, (int)&v5);
}

//----- (0804C123) --------------------------------------------------------
void *__cdecl sub_804C123(int a1, size_t a2, unsigned __int8 a3)
{
  int v4; // [esp+20h] [ebp-38h]
  int v5; // [esp+24h] [ebp-34h]
  int v6; // [esp+28h] [ebp-30h]
  int v7; // [esp+2Ch] [ebp-2Ch]
  int v8; // [esp+30h] [ebp-28h]
  int v9; // [esp+34h] [ebp-24h]
  int v10; // [esp+38h] [ebp-20h]
  int v11; // [esp+3Ch] [ebp-1Ch]
  int v12; // [esp+40h] [ebp-18h]
  int v13; // [esp+44h] [ebp-14h]
  int v14; // [esp+48h] [ebp-10h]
  int v15; // [esp+4Ch] [ebp-Ch]

  v4 = dword_805222D;
  v5 = dword_8052231;
  v6 = dword_8052235;
  v7 = dword_8052239;
  v8 = dword_805223D;
  v9 = dword_8052241;
  v10 = dword_8052245;
  v11 = dword_8052249;
  v12 = dword_805224D;
  v13 = dword_8052251;
  v14 = dword_8052255;
  v15 = dword_8052259;
  sub_804AD58(&v4, a3, 1);
  return sub_804BDA4(0, a1, a2, (int)&v4);
}
// 805222D: using guessed type int dword_805222D;
// 8052231: using guessed type int dword_8052231;
// 8052235: using guessed type int dword_8052235;
// 8052239: using guessed type int dword_8052239;
// 805223D: using guessed type int dword_805223D;
// 8052241: using guessed type int dword_8052241;
// 8052245: using guessed type int dword_8052245;
// 8052249: using guessed type int dword_8052249;
// 805224D: using guessed type int dword_805224D;
// 8052251: using guessed type int dword_8052251;
// 8052255: using guessed type int dword_8052255;
// 8052259: using guessed type int dword_8052259;

//----- (0804C1CD) --------------------------------------------------------
void *__cdecl sub_804C1CD(int a1, unsigned __int8 a2)
{
  return sub_804C123(a1, 0xFFFFFFFF, a2);
}

//----- (0804C1F6) --------------------------------------------------------
void *__cdecl sub_804C1F6(int a1)
{
  return sub_804C1CD(a1, 0x3Au);
}

//----- (0804C233) --------------------------------------------------------
void *__cdecl sub_804C233(signed int a1, int a2, int a3)
{
  int v4; // [esp+10h] [ebp-68h]
  int v5; // [esp+14h] [ebp-64h]
  int v6; // [esp+18h] [ebp-60h]
  int v7; // [esp+1Ch] [ebp-5Ch]
  int v8; // [esp+20h] [ebp-58h]
  int v9; // [esp+24h] [ebp-54h]
  int v10; // [esp+28h] [ebp-50h]
  int v11; // [esp+2Ch] [ebp-4Ch]
  int v12; // [esp+30h] [ebp-48h]
  int v13; // [esp+34h] [ebp-44h]
  int v14; // [esp+38h] [ebp-40h]
  int v15; // [esp+3Ch] [ebp-3Ch]
  int v16; // [esp+40h] [ebp-38h]
  int v17; // [esp+44h] [ebp-34h]
  int v18; // [esp+48h] [ebp-30h]
  int v19; // [esp+4Ch] [ebp-2Ch]
  int v20; // [esp+50h] [ebp-28h]
  int v21; // [esp+54h] [ebp-24h]
  int v22; // [esp+58h] [ebp-20h]
  int v23; // [esp+5Ch] [ebp-1Ch]
  int v24; // [esp+60h] [ebp-18h]
  int v25; // [esp+64h] [ebp-14h]
  int v26; // [esp+68h] [ebp-10h]
  int v27; // [esp+6Ch] [ebp-Ch]

  sub_804AE43(&v4, a2);
  v16 = v4;
  v17 = v5;
  v18 = v6;
  v19 = v7;
  v20 = v8;
  v21 = v9;
  v22 = v10;
  v23 = v11;
  v24 = v12;
  v25 = v13;
  v26 = v14;
  v27 = v15;
  sub_804AD58(&v16, 0x3Au, 1);
  return sub_804BDA4(a1, a3, 0xFFFFFFFF, (int)&v16);
}

//----- (0804C2D4) --------------------------------------------------------
void *__cdecl sub_804C2D4(signed int a1, int a2, int a3, int a4)
{
  return sub_804C304(a1, a2, a3, a4, 0xFFFFFFFF);
}

//----- (0804C304) --------------------------------------------------------
void *__cdecl sub_804C304(signed int a1, int a2, int a3, int a4, size_t a5)
{
  int v6; // [esp+10h] [ebp-38h]
  int v7; // [esp+14h] [ebp-34h]
  int v8; // [esp+18h] [ebp-30h]
  int v9; // [esp+1Ch] [ebp-2Ch]
  int v10; // [esp+20h] [ebp-28h]
  int v11; // [esp+24h] [ebp-24h]
  int v12; // [esp+28h] [ebp-20h]
  int v13; // [esp+2Ch] [ebp-1Ch]
  int v14; // [esp+30h] [ebp-18h]
  int v15; // [esp+34h] [ebp-14h]
  int v16; // [esp+38h] [ebp-10h]
  int v17; // [esp+3Ch] [ebp-Ch]

  v6 = dword_805222D;
  v7 = dword_8052231;
  v8 = dword_8052235;
  v9 = dword_8052239;
  v10 = dword_805223D;
  v11 = dword_8052241;
  v12 = dword_8052245;
  v13 = dword_8052249;
  v14 = dword_805224D;
  v15 = dword_8052251;
  v16 = dword_8052255;
  v17 = dword_8052259;
  sub_804AE02(&v6, a2, a3);
  return sub_804BDA4(a1, a4, a5, (int)&v6);
}
// 805222D: using guessed type int dword_805222D;
// 8052231: using guessed type int dword_8052231;
// 8052235: using guessed type int dword_8052235;
// 8052239: using guessed type int dword_8052239;
// 805223D: using guessed type int dword_805223D;
// 8052241: using guessed type int dword_8052241;
// 8052245: using guessed type int dword_8052245;
// 8052249: using guessed type int dword_8052249;
// 805224D: using guessed type int dword_805224D;
// 8052251: using guessed type int dword_8052251;
// 8052255: using guessed type int dword_8052255;
// 8052259: using guessed type int dword_8052259;

//----- (0804C3FE) --------------------------------------------------------
void *__cdecl sub_804C3FE(signed int a1, int a2, size_t a3)
{
  return sub_804BDA4(a1, a2, a3, (int)&unk_805214C);
}

//----- (0804C449) --------------------------------------------------------
void *__cdecl sub_804C449(signed int a1, int a2)
{
  return sub_804C3FE(a1, a2, 0xFFFFFFFF);
}

//----- (0804C46B) --------------------------------------------------------
void *__cdecl sub_804C46B(int a1)
{
  return sub_804C449(0, a1);
}

//----- (0804C486) --------------------------------------------------------
int __cdecl sub_804C486(FILE *stream, int a2, int a3, int a4, int a5, int a6)
{
  char *v6; // eax
  char *v7; // eax
  int v8; // ebx
  char *v9; // eax
  int result; // eax
  int v11; // esi
  int v12; // ebx
  char *v13; // eax
  int v14; // edi
  int v15; // esi
  int v16; // ebx
  char *v17; // eax
  int v18; // ST4C_4
  int v19; // edi
  int v20; // esi
  int v21; // ebx
  char *v22; // eax
  int v23; // ST4C_4
  int v24; // ST48_4
  int v25; // edi
  int v26; // esi
  int v27; // ebx
  char *v28; // eax
  int v29; // ST4C_4
  int v30; // ST48_4
  int v31; // ST44_4
  int v32; // edi
  int v33; // esi
  int v34; // ebx
  char *v35; // eax
  int v36; // esi
  int v37; // ST4C_4
  int v38; // ST48_4
  int v39; // ST44_4
  int v40; // ST40_4
  int v41; // edi
  int v42; // ebx
  char *v43; // eax
  int v44; // edi
  int v45; // ST4C_4
  int v46; // ST48_4
  int v47; // ST44_4
  int v48; // ST40_4
  int v49; // ST3C_4
  int v50; // esi
  int v51; // ebx
  char *v52; // eax
  int v53; // edi
  int v54; // ST4C_4
  int v55; // ST48_4
  int v56; // ST44_4
  int v57; // ST40_4
  int v58; // ST3C_4
  int v59; // ST38_4
  int v60; // esi
  int v61; // ebx
  char *v62; // eax
  int v63; // edi
  int v64; // ST4C_4
  int v65; // ST48_4
  int v66; // ST44_4
  int v67; // ST40_4
  int v68; // ST3C_4
  int v69; // ST38_4
  int v70; // esi
  int v71; // ebx
  char *v72; // eax

  if ( a2 )
    fprintf(stream, "%s (%s) %s\n", a2, a3, a4);
  else
    fprintf(stream, "%s %s\n", a3, a4);
  v6 = gettext("(C)");
  fprintf(stream, "Copyright %s %d Free Software Foundation, Inc.", v6, 2017);
  v7 = gettext(
         "\n"
         "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.\n"
         "This is free software: you are free to change and redistribute it.\n"
         "There is NO WARRANTY, to the extent permitted by law.\n"
         "\n");
  fputs_unlocked(v7, stream);
  switch ( a6 )
  {
    case 0:
      abort();
      return result;
    case 1:
      v8 = *(_DWORD *)a5;
      v9 = gettext("Written by %s.\n");
      result = fprintf(stream, v9, v8);
      break;
    case 2:
      v11 = *(_DWORD *)(a5 + 4);
      v12 = *(_DWORD *)a5;
      v13 = gettext("Written by %s and %s.\n");
      result = fprintf(stream, v13, v12, v11);
      break;
    case 3:
      v14 = *(_DWORD *)(a5 + 8);
      v15 = *(_DWORD *)(a5 + 4);
      v16 = *(_DWORD *)a5;
      v17 = gettext("Written by %s, %s, and %s.\n");
      result = fprintf(stream, v17, v16, v15, v14);
      break;
    case 4:
      v18 = *(_DWORD *)(a5 + 12);
      v19 = *(_DWORD *)(a5 + 8);
      v20 = *(_DWORD *)(a5 + 4);
      v21 = *(_DWORD *)a5;
      v22 = gettext("Written by %s, %s, %s,\nand %s.\n");
      result = fprintf(stream, v22, v21, v20, v19, v18);
      break;
    case 5:
      v23 = *(_DWORD *)(a5 + 16);
      v24 = *(_DWORD *)(a5 + 12);
      v25 = *(_DWORD *)(a5 + 8);
      v26 = *(_DWORD *)(a5 + 4);
      v27 = *(_DWORD *)a5;
      v28 = gettext("Written by %s, %s, %s,\n%s, and %s.\n");
      result = fprintf(stream, v28, v27, v26, v25, v24, v23);
      break;
    case 6:
      v29 = *(_DWORD *)(a5 + 20);
      v30 = *(_DWORD *)(a5 + 16);
      v31 = *(_DWORD *)(a5 + 12);
      v32 = *(_DWORD *)(a5 + 8);
      v33 = *(_DWORD *)(a5 + 4);
      v34 = *(_DWORD *)a5;
      v35 = gettext("Written by %s, %s, %s,\n%s, %s, and %s.\n");
      result = fprintf(stream, v35, v34, v33, v32, v31, v30, v29);
      break;
    case 7:
      v36 = *(_DWORD *)(a5 + 24);
      v37 = *(_DWORD *)(a5 + 20);
      v38 = *(_DWORD *)(a5 + 16);
      v39 = *(_DWORD *)(a5 + 12);
      v40 = *(_DWORD *)(a5 + 8);
      v41 = *(_DWORD *)(a5 + 4);
      v42 = *(_DWORD *)a5;
      v43 = gettext("Written by %s, %s, %s,\n%s, %s, %s, and %s.\n");
      result = fprintf(stream, v43, v42, v41, v40, v39, v38, v37, v36);
      break;
    case 8:
      v44 = *(_DWORD *)(a5 + 28);
      v45 = *(_DWORD *)(a5 + 24);
      v46 = *(_DWORD *)(a5 + 20);
      v47 = *(_DWORD *)(a5 + 16);
      v48 = *(_DWORD *)(a5 + 12);
      v49 = *(_DWORD *)(a5 + 8);
      v50 = *(_DWORD *)(a5 + 4);
      v51 = *(_DWORD *)a5;
      v52 = gettext("Written by %s, %s, %s,\n%s, %s, %s, %s,\nand %s.\n");
      result = fprintf(stream, v52, v51, v50, v49, v48, v47, v46, v45, v44);
      break;
    case 9:
      v53 = *(_DWORD *)(a5 + 32);
      v54 = *(_DWORD *)(a5 + 28);
      v55 = *(_DWORD *)(a5 + 24);
      v56 = *(_DWORD *)(a5 + 20);
      v57 = *(_DWORD *)(a5 + 16);
      v58 = *(_DWORD *)(a5 + 12);
      v59 = *(_DWORD *)(a5 + 8);
      v60 = *(_DWORD *)(a5 + 4);
      v61 = *(_DWORD *)a5;
      v62 = gettext("Written by %s, %s, %s,\n%s, %s, %s, %s,\n%s, and %s.\n");
      result = fprintf(stream, v62, v61, v60, v59, v58, v57, v56, v55, v54, v53);
      break;
    default:
      v63 = *(_DWORD *)(a5 + 32);
      v64 = *(_DWORD *)(a5 + 28);
      v65 = *(_DWORD *)(a5 + 24);
      v66 = *(_DWORD *)(a5 + 20);
      v67 = *(_DWORD *)(a5 + 16);
      v68 = *(_DWORD *)(a5 + 12);
      v69 = *(_DWORD *)(a5 + 8);
      v70 = *(_DWORD *)(a5 + 4);
      v71 = *(_DWORD *)a5;
      v72 = gettext("Written by %s, %s, %s,\n%s, %s, %s, %s,\n%s, %s, and others.\n");
      result = fprintf(stream, v72, v71, v70, v69, v68, v67, v66, v65, v64, v63);
      break;
  }
  return result;
}
// 8048F50: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);

//----- (0804C9EC) --------------------------------------------------------
int __cdecl sub_804C9EC(FILE *stream, int a2, int a3, int a4, int a5)
{
  int *v5; // eax
  unsigned int i; // [esp+24h] [ebp-34h]
  int v8[12]; // [esp+28h] [ebp-30h]

  for ( i = 0; i <= 9; ++i )
  {
    v5 = (int *)a5;
    a5 += 4;
    v8[i] = *v5;
    if ( !v8[i] )
      break;
  }
  return sub_804C486(stream, a2, a3, a4, (int)v8, i);
}
// 804C9EC: using guessed type int var_30[12];

//----- (0804CA52) --------------------------------------------------------
int sub_804CA52(FILE *stream, int a2, int a3, int a4, ...)
{
  va_list va; // [esp+50h] [ebp+18h]

  va_start(va, a4);
  return sub_804C9EC(stream, a2, a3, a4, (int)va);
}

//----- (0804CB55) --------------------------------------------------------
void *__cdecl sub_804CB55(void *ptr, int a2, int a3)
{
  unsigned int v4; // [esp+1Ch] [ebp-Ch]

  v4 = *(_DWORD *)a2;
  if ( ptr )
  {
    if ( 0x55555554u / a3 <= v4 )
      sub_804CD4F();
    v4 += (v4 >> 1) + 1;
  }
  else
  {
    if ( !v4 )
      v4 = (0x40u / a3 == 0) + 0x40u / a3;
    if ( 0x7FFFFFFFu / a3 < v4 )
      sub_804CD4F();
  }
  *(_DWORD *)a2 = v4;
  return sub_804CC29(ptr, a3 * v4);
}

//----- (0804CBEC) --------------------------------------------------------
void *__cdecl sub_804CBEC(size_t size)
{
  return sub_804CBFF(size);
}

//----- (0804CBFF) --------------------------------------------------------
void *__cdecl sub_804CBFF(size_t size)
{
  void *v2; // [esp+1Ch] [ebp-Ch]

  v2 = malloc(size);
  if ( !v2 && size )
    sub_804CD4F();
  return v2;
}

//----- (0804CC29) --------------------------------------------------------
void *__cdecl sub_804CC29(void *ptr, size_t size)
{
  void *result; // eax
  void *ptra; // [esp+20h] [ebp+8h]

  if ( size || !ptr )
  {
    ptra = realloc(ptr, size);
    if ( !ptra )
    {
      if ( size )
        sub_804CD4F();
    }
    result = ptra;
  }
  else
  {
    free(ptr);
    result = 0;
  }
  return result;
}

//----- (0804CD01) --------------------------------------------------------
void *__cdecl sub_804CD01(void *src, size_t n)
{
  void *v2; // eax

  v2 = sub_804CBFF(n);
  return memcpy(v2, src, n);
}

//----- (0804CD4F) --------------------------------------------------------
void __noreturn sub_804CD4F()
{
  char *v0; // eax

  v0 = gettext("memory exhausted");
  error(status, 0, "%s", v0);
  abort();
}

//----- (0804CD88) --------------------------------------------------------
void sub_804CD88()
{
  ;
}

//----- (0804CD8D) --------------------------------------------------------
void sub_804CD8D()
{
  if ( sub_804D6A0() < 0 )
    sub_804CD88();
}

//----- (0804CDB0) --------------------------------------------------------
unsigned __int64 __cdecl sub_804CDB0(char *nptr, int base, int a3, int a4, int a5, int a6, char *s, int a8, int status)
{
  void *v9; // ebx
  int v10; // edx
  signed int v11; // eax
  int v13; // [esp+34h] [ebp-14h]
  unsigned __int64 v14; // [esp+38h] [ebp-10h]

  v13 = sub_804D014(nptr, 0, base, (int)&v14, s);
  if ( v13 )
  {
    if ( v13 == 1 )
    {
      *__errno_location() = 75;
    }
    else if ( v13 == 3 )
    {
      *__errno_location() = 0;
    }
  }
  else if ( v14 < __PAIR__((unsigned int)a4, a3) || __PAIR__((unsigned int)a6, a5) < v14 )
  {
    v13 = 1;
    if ( v14 <= 0x3FFFFFFF )
      *__errno_location() = 34;
    else
      *__errno_location() = 75;
  }
  if ( v13 )
  {
    v9 = sub_804C46B((int)nptr);
    if ( *__errno_location() == 22 )
      v10 = 0;
    else
      v10 = *__errno_location();
    if ( status )
      v11 = status;
    else
      v11 = 1;
    error(v11, v10, "%s: %s", a8, v9);
  }
  return v14;
}

//----- (0804CEEE) --------------------------------------------------------
unsigned __int64 __cdecl sub_804CEEE(char *nptr, int a2, int a3, int a4, int a5, char *s, int a7, int status)
{
  return sub_804CDB0(nptr, 10, a2, a3, a4, a5, s, a7, status);
}

//----- (0804CF52) --------------------------------------------------------
signed int __cdecl sub_804CF52(int a1, signed int a2)
{
  signed int result; // eax
  int v3; // ebx

  if ( (unsigned __int64)sub_804DF3F(0xFFFFFFFFFFFFFFFFLL, a2, a2 >> 31) >= *(_QWORD *)a1 )
  {
    v3 = *(_DWORD *)(a1 + 4);
    *(_QWORD *)a1 *= a2;
    result = 0;
  }
  else
  {
    *(_DWORD *)a1 = -1;
    *(_DWORD *)(a1 + 4) = -1;
    result = 1;
  }
  return result;
}

//----- (0804CFDE) --------------------------------------------------------
int __cdecl sub_804CFDE(int a1, signed int a2, int a3)
{
  int v3; // eax
  int i; // [esp+1Ch] [ebp-Ch]

  for ( i = 0; ; i |= sub_804CF52(a1, a2) )
  {
    v3 = a3--;
    if ( !v3 )
      break;
  }
  return i;
}

//----- (0804D014) --------------------------------------------------------
int __cdecl sub_804D014(char *nptr, int a2, int base, int a4, char *s)
{
  char **v5; // eax
  int result; // eax
  int v7; // edx
  int v8; // edx
  int v9; // eax
  int v10; // edx
  int v11; // edx
  unsigned __int8 i; // [esp+1Bh] [ebp-2Dh]
  char v13; // [esp+1Ch] [ebp-2Ch]
  int v14; // [esp+20h] [ebp-28h]
  char *v15; // [esp+24h] [ebp-24h]
  int v16; // [esp+28h] [ebp-20h]
  int v17; // [esp+2Ch] [ebp-1Ch]
  int v18; // [esp+30h] [ebp-18h]
  char **endptr; // [esp+34h] [ebp-14h]
  uintmax_t v20; // [esp+38h] [ebp-10h]

  v14 = 0;
  if ( base < 0 || base > 36 )
    __assert_fail("0 <= strtol_base && strtol_base <= 36", "lib/xstrtol.c", 0x60u, "xstrtoumax");
  if ( a2 )
    v5 = (char **)a2;
  else
    v5 = (char **)&v13;
  endptr = v5;
  *__errno_location() = 0;
  v15 = nptr;
  for ( i = *nptr; (*__ctype_b_loc())[i] & 0x2000; i = *v15 )
    ++v15;
  if ( i == 45 )
    return 4;
  v20 = strtoumax(nptr, endptr, base);
  if ( *endptr == nptr )
  {
    if ( !s || !**endptr || !strchr(s, **endptr) )
      return 4;
    v20 = 1LL;
  }
  else if ( *__errno_location() )
  {
    if ( *__errno_location() != 34 )
      return 4;
    v14 = 1;
  }
  if ( !s )
  {
    v7 = HIDWORD(v20);
    *(_DWORD *)a4 = v20;
    *(_DWORD *)(a4 + 4) = v7;
    return v14;
  }
  if ( !**endptr )
  {
LABEL_53:
    v11 = HIDWORD(v20);
    *(_DWORD *)a4 = v20;
    *(_DWORD *)(a4 + 4) = v11;
    return v14;
  }
  v16 = 1024;
  v17 = 1;
  if ( !strchr(s, **endptr) )
  {
    v8 = HIDWORD(v20);
    *(_DWORD *)a4 = v20;
    *(_DWORD *)(a4 + 4) = v8;
    return v14 | 2;
  }
  switch ( **endptr )
  {
    case 69:
    case 71:
    case 75:
    case 77:
    case 80:
    case 84:
    case 89:
    case 90:
    case 103:
    case 107:
    case 109:
    case 116:
      if ( strchr(s, 48) )
      {
        v9 = (*endptr)[1];
        switch ( v9 )
        {
          case 68:
            goto LABEL_56;
          case 105:
            if ( (*endptr)[2] == 66 )
              v17 += 2;
            goto LABEL_37;
          case 66:
LABEL_56:
            v16 = 1000;
            ++v17;
            break;
        }
      }
      break;
    default:
      break;
  }
LABEL_37:
  switch ( **endptr )
  {
    case 66:
      v18 = sub_804CF52((int)&v20, 1024);
      goto LABEL_51;
    case 69:
      v18 = sub_804CFDE((int)&v20, v16, 6);
      goto LABEL_51;
    case 71:
    case 103:
      v18 = sub_804CFDE((int)&v20, v16, 3);
      goto LABEL_51;
    case 75:
    case 107:
      v18 = sub_804CFDE((int)&v20, v16, 1);
      goto LABEL_51;
    case 77:
    case 109:
      v18 = sub_804CFDE((int)&v20, v16, 2);
      goto LABEL_51;
    case 80:
      v18 = sub_804CFDE((int)&v20, v16, 5);
      goto LABEL_51;
    case 84:
    case 116:
      v18 = sub_804CFDE((int)&v20, v16, 4);
      goto LABEL_51;
    case 89:
      v18 = sub_804CFDE((int)&v20, v16, 8);
      goto LABEL_51;
    case 90:
      v18 = sub_804CFDE((int)&v20, v16, 7);
      goto LABEL_51;
    case 98:
      v18 = sub_804CF52((int)&v20, 512);
      goto LABEL_51;
    case 99:
      v18 = 0;
      goto LABEL_51;
    case 119:
      v18 = sub_804CF52((int)&v20, 2);
LABEL_51:
      v14 |= v18;
      *endptr += v17;
      if ( **endptr )
        v14 |= 2u;
      goto LABEL_53;
    default:
      v10 = HIDWORD(v20);
      *(_DWORD *)a4 = v20;
      *(_DWORD *)(a4 + 4) = v10;
      result = v14 | 2;
      break;
  }
  return result;
}

//----- (0804D40C) --------------------------------------------------------
int __cdecl sub_804D40C(FILE *stream)
{
  int v2; // eax
  __int64 v3; // rax
  int v4; // [esp+14h] [ebp-14h]
  int v5; // [esp+18h] [ebp-10h]

  v4 = 0;
  if ( fileno(stream) < 0 )
    return fclose(stream);
  if ( !__freading(stream) || (v2 = fileno(stream), LODWORD(v3) = lseek64(v2, 0, 0, 1), v3 != -1) )
  {
    if ( sub_804D508(stream) )
      v4 = *__errno_location();
  }
  v5 = fclose(stream);
  if ( v4 )
  {
    *__errno_location() = v4;
    v5 = -1;
  }
  return v5;
}
// 8049050: using guessed type int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804D4CF) --------------------------------------------------------
int __cdecl sub_804D4CF(FILE *stream)
{
  int result; // eax

  result = stream->_flags & 0x100;
  if ( result )
    result = sub_804D548(stream, 0, 0, 1);
  return result;
}

//----- (0804D508) --------------------------------------------------------
int __cdecl sub_804D508(FILE *fp)
{
  if ( !fp || !__freading(fp) )
    return fflush(fp);
  sub_804D4CF(fp);
  return fflush(fp);
}

//----- (0804D548) --------------------------------------------------------
int __cdecl sub_804D548(FILE *stream, int a2, int a3, int a4)
{
  int v4; // eax
  __off64_t v5; // rax

  if ( stream->_IO_read_end != stream->_IO_read_ptr
    || stream->_IO_write_ptr != stream->_IO_write_base
    || stream->_IO_save_base )
  {
    return fseeko64(stream, a2, a3, a4);
  }
  v4 = fileno(stream);
  LODWORD(v5) = lseek64(v4, a2, a3, a4);
  if ( v5 == -1 )
    return -1;
  stream->_flags &= 0xFFFFFFEF;
  stream->_offset = v5;
  return 0;
}
// 8048DE0: using guessed type int __cdecl fseeko64(_DWORD, _DWORD, _DWORD, _DWORD);
// 8049050: using guessed type int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804D61A) --------------------------------------------------------
size_t __cdecl sub_804D61A(wchar_t *pwc, char *s, size_t n, mbstate_t *p)
{
  char v5; // [esp+18h] [ebp-10h]
  size_t v6; // [esp+1Ch] [ebp-Ch]

  if ( !pwc )
    pwc = (wchar_t *)&v5;
  v6 = mbrtowc(pwc, s, n, p);
  if ( v6 <= 0xFFFFFFFD || !n || !((unsigned __int8)sub_804D7B9(0) ^ 1) )
    return v6;
  *pwc = (unsigned __int8)*s;
  return 1;
}

//----- (0804D68C) --------------------------------------------------------
int sub_804D68C()
{
  return 0;
}

//----- (0804D696) --------------------------------------------------------
int sub_804D696()
{
  return 0;
}

//----- (0804D6A0) --------------------------------------------------------
int sub_804D6A0()
{
  int result; // eax
  int v1; // [esp+14h] [ebp-4h]

  v1 = sub_804D696();
  if ( v1 )
    result = v1;
  else
    result = sub_804D68C();
  return result;
}

//----- (0804D6D3) --------------------------------------------------------
int __cdecl sub_804D6D3(unsigned __int8 *a1, unsigned __int8 *a2)
{
  unsigned __int8 *v2; // esi
  unsigned __int8 *v3; // ebx
  unsigned __int8 v5; // [esp+1Eh] [ebp-Ah]
  unsigned __int8 v6; // [esp+1Fh] [ebp-9h]

  v2 = a1;
  v3 = a2;
  if ( a1 == a2 )
    return 0;
  do
  {
    v5 = sub_804DF04(*v2);
    v6 = sub_804DF04(*v3);
    if ( !v5 )
      break;
    ++v2;
    ++v3;
  }
  while ( v5 == v6 );
  return v5 - v6;
}

//----- (0804D738) --------------------------------------------------------
int __cdecl sub_804D738(FILE *fp)
{
  bool v1; // ST1E_1
  bool v3; // [esp+1Dh] [ebp-Bh]
  bool v4; // [esp+1Fh] [ebp-9h]

  v3 = __fpending(fp) != 0;
  v1 = ferror_unlocked(fp) != 0;
  v4 = sub_804D40C(fp) != 0;
  if ( !v1 && (!v4 || !v3 && *__errno_location() == 9) )
    return 0;
  if ( v4 != 1 )
    *__errno_location() = 0;
  return -1;
}

//----- (0804D7B9) --------------------------------------------------------
int __cdecl sub_804D7B9(int category)
{
  unsigned __int8 v2; // [esp+1Bh] [ebp-Dh]
  const char *s1; // [esp+1Ch] [ebp-Ch]

  v2 = 1;
  s1 = setlocale(category, 0);
  if ( s1 && (!strcmp(s1, "C") || !strcmp(s1, "POSIX")) )
    v2 = 0;
  return v2;
}

//----- (0804D817) --------------------------------------------------------
void *sub_804D817()
{
  _BOOL4 v0; // eax
  void *v2; // [esp+18h] [ebp-B0h]
  const char *s; // [esp+1Ch] [ebp-ACh]
  void *v4; // [esp+20h] [ebp-A8h]
  int v5; // [esp+24h] [ebp-A4h]
  size_t n; // [esp+2Ch] [ebp-9Ch]
  size_t v7; // [esp+30h] [ebp-98h]
  _BOOL4 v8; // [esp+34h] [ebp-94h]
  char *dest; // [esp+38h] [ebp-90h]
  int fd; // [esp+3Ch] [ebp-8Ch]
  FILE *stream; // [esp+40h] [ebp-88h]
  int c; // [esp+44h] [ebp-84h]
  int ca; // [esp+44h] [ebp-84h]
  size_t v14; // [esp+48h] [ebp-80h]
  size_t v15; // [esp+4Ch] [ebp-7Ch]
  void *v16; // [esp+50h] [ebp-78h]
  char src; // [esp+56h] [ebp-72h]
  char v18; // [esp+89h] [ebp-3Fh]
  unsigned int v19; // [esp+BCh] [ebp-Ch]

  v19 = __readgsdword(0x14u);
  v2 = (void *)dword_805236D;
  if ( !dword_805236D )
  {
    s = getenv("CHARSETALIASDIR");
    if ( !s || !*s )
      s = "/home/hwangdz/coreutils/coreutils-8.28/install_m32/lib";
    n = strlen(s);
    v7 = strlen("charset.alias");
    v0 = n && s[n - 1] != 47;
    v8 = v0;
    dest = (char *)malloc(n + v0 + v7 + 1);
    if ( dest )
    {
      memcpy(dest, s, n);
      if ( v8 )
        dest[n] = 47;
      memcpy(&dest[n + v8], "charset.alias", v7 + 1);
    }
    free(0);
    if ( dest )
    {
      fd = open64(dest, 0x20000);
      if ( fd >= 0 )
      {
        stream = fdopen(fd, "r");
        if ( stream )
        {
          v4 = 0;
          v5 = 0;
          while ( 1 )
          {
            c = getc_unlocked(stream);
            if ( c == -1 )
              break;
            if ( c != 10 && c != 32 && c != 9 )
            {
              if ( c == 35 )
              {
                do
                  ca = getc_unlocked(stream);
                while ( ca != -1 && ca != 10 );
                if ( ca == -1 )
                  break;
              }
              else
              {
                ungetc(c, stream);
                if ( fscanf(stream, "%50s %50s", &src, &v18) <= 1 )
                  break;
                v14 = strlen(&src);
                v15 = strlen(&v18);
                v16 = v4;
                if ( v5 )
                {
                  v5 += v15 + v14 + 2;
                  v4 = realloc(v4, v5 + 1);
                }
                else
                {
                  v5 = v14 + v15 + 2;
                  v4 = malloc(v14 + v15 + 3);
                }
                if ( !v4 )
                {
                  v5 = 0;
                  free(v16);
                  break;
                }
                strcpy((char *)v4 + v5 - v15 - v14 - 2, &src);
                strcpy((char *)v4 + v5 - v15 - 1, &v18);
              }
            }
          }
          sub_804D40C(stream);
          if ( v5 )
          {
            *((_BYTE *)v4 + v5) = 0;
            v2 = v4;
          }
          else
          {
            v2 = &unk_804F367;
          }
        }
        else
        {
          close(fd);
          v2 = &unk_804F367;
        }
      }
      else
      {
        v2 = &unk_804F367;
      }
      free(dest);
    }
    else
    {
      v2 = &unk_804F367;
    }
    dword_805236D = (int)v2;
  }
  return v2;
}
// 8048D30: using guessed type int __cdecl open64(_DWORD, _DWORD);
// 805236D: using guessed type int dword_805236D;

//----- (0804DC8F) --------------------------------------------------------
const char *sub_804DC8F()
{
  char *v0; // ST1C_4
  const char *s1; // [esp+18h] [ebp-10h]
  char *s2; // [esp+1Ch] [ebp-Ch]

  s1 = nl_langinfo(14);
  if ( !s1 )
    s1 = (const char *)&unk_804F367;
  for ( s2 = (char *)sub_804D817(); *s2; s2 = &v0[strlen(v0) + 1] )
  {
    if ( !strcmp(s1, s2) || *s2 == 42 && !s2[1] )
    {
      s1 = &s2[strlen(s2) + 1];
      break;
    }
    v0 = &s2[strlen(s2) + 1];
  }
  if ( !*s1 )
    s1 = "ASCII";
  return s1;
}

//----- (0804DF04) --------------------------------------------------------
int __cdecl sub_804DF04(int a1)
{
  int result; // eax

  if ( (unsigned int)(a1 - 65) > 0x19 )
    result = a1;
  else
    result = a1 + 32;
  return result;
}

//----- (0804DF3F) --------------------------------------------------------
signed __int64 __cdecl sub_804DF3F(unsigned __int64 a1, unsigned int a2, unsigned int a3)
{
  unsigned int v3; // esi
  signed __int64 result; // rax
  int v5; // ebp
  int v6; // ebp
  int v7; // ST08_4
  unsigned __int64 v8; // rtt
  unsigned int v9; // esi
  unsigned int v10; // edi
  unsigned __int64 v11; // rax

  if ( !a3 )
  {
    if ( a2 > HIDWORD(a1) )
      return (unsigned int)(a1 / a2);
    v3 = a2;
    if ( !a2 )
      v3 = 1 / 0u;
    LODWORD(result) = __PAIR__(HIDWORD(a1) % v3, (unsigned int)a1) / v3;
    HIDWORD(result) = HIDWORD(a1) / v3;
    return result;
  }
  if ( a3 > HIDWORD(a1) )
    return 0LL;
  _BitScanReverse((unsigned int *)&v5, a3);
  v6 = v5 ^ 0x1F;
  if ( !v6 )
  {
    if ( a2 <= (unsigned int)a1 || a3 < HIDWORD(a1) )
      return 1LL;
    return 0LL;
  }
  v7 = (a3 << v6) | (a2 >> (32 - v6));
  LODWORD(v8) = (HIDWORD(a1) << v6) | ((unsigned int)a1 >> (32 - v6));
  HIDWORD(v8) = HIDWORD(a1) >> (32 - v6);
  v9 = v8 % (unsigned int)v7;
  v10 = v8 / (unsigned int)v7;
  v11 = (a2 << v6) * (unsigned __int64)v10;
  if ( v9 < HIDWORD(v11) || (_DWORD)a1 << v6 < (unsigned int)v11 && v9 == (a2 << v6) * (unsigned __int64)v10 >> 32 )
    result = v10 - 1;
  else
    result = v10;
  return result;
}

//----- (0804E0CD) --------------------------------------------------------
int __cdecl sub_804E0CD(int a1)
{
  return __cxa_atexit(a1, 0, dword_8052110);
}
// 8048EB0: using guessed type int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD);
// 8052110: using guessed type int dword_8052110;

//----- (0804E100) --------------------------------------------------------
int (**sub_804E100())()
{
  int (**result)(); // eax
  int v1; // esi
  int v2; // edi

  init_proc();
  result = off_8051F04;
  v1 = &off_8051F08 - off_8051F04;
  if ( v1 )
  {
    v2 = 0;
    do
      result = (int (**)())off_8051F04[v2++]();
    while ( v1 != v2 );
  }
  return result;
}
// 8051F04: using guessed type int (*off_8051F04[2])();
// 8051F08: using guessed type int (*off_8051F08)();

//----- (0804E164) --------------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 85 function(s)"
