/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
int sub_8048FC0();
// int __cdecl freopen64(_DWORD, _DWORD, _DWORD); weak
// int dup2(int fd, int fd2);
// int strcmp(const char *s1, const char *s2);
// int __cdecl open64(_DWORD, _DWORD); weak
// int putc_unlocked(int c, FILE *stream);
// int printf(const char *format, ...);
// int fflush(FILE *stream);
// void _exit(int status);
// void *memmove(void *dest, const void *src, size_t n);
// void free(void *ptr);
// char *strdup(const char *s);
// void *memcpy(void *dest, const void *src, size_t n);
// int mbsinit(const mbstate_t *ps);
// int ferror(FILE *stream);
// int fclose(FILE *stream);
// int getc_unlocked(FILE *stream);
// intmax_t strtoimax(const char *nptr, char **endptr, int base);
// int memcmp(const void *s1, const void *s2, size_t n);
// int __cdecl stpcpy(_DWORD, _DWORD); weak
// char *textdomain(const char *domainname);
// int iswprint(wint_t wc);
// int __cdecl fopen64(_DWORD, _DWORD); weak
// int ferror_unlocked(FILE *stream);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// int __cdecl __fxstat64(_DWORD, _DWORD, _DWORD); weak
// size_t __ctype_get_mb_cur_max(void);
// size_t fread(void *ptr, size_t size, size_t n, FILE *stream);
// char *strcpy(char *dest, const char *src);
// size_t __fpending(FILE *fp);
// size_t mbrtowc(wchar_t *pwc, const char *s, size_t n, mbstate_t *p);
// int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD); weak
// void error(int status, int errnum, const char *format, ...);
// char *getenv(const char *name);
// void *realloc(void *ptr, size_t size);
// void *malloc(size_t size);
// int re_match(struct re_pattern_buffer *buffer, const char *string, int length, int start, struct re_registers *regs);
// int __freading(FILE *fp);
// int iswspace(wint_t wc);
// void exit(int status);
// int ftello64(void); weak
// char *gettext(const char *msgid);
// FILE *fdopen(int fd, const char *modes);
// int __cdecl fputs_unlocked(_DWORD, _DWORD); weak
// int getopt_long(int argc, char *const *argv, const char *shortopts, const struct option *longopts, int *longind);
// char *strchr(const char *s, int c);
// int fscanf(FILE *stream, const char *format, ...);
// size_t strlen(const char *s);
// size_t iconv(iconv_t cd, char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
// int iconv_close(iconv_t cd);
// int fprintf(FILE *stream, const char *format, ...);
// int re_search(struct re_pattern_buffer *buffer, const char *string, int length, int start, int range, struct re_registers *regs);
// int re_compile_fastmap(struct re_pattern_buffer *buffer);
// void *memset(void *s, int c, size_t n);
// int ungetc(int c, FILE *stream);
// int iswalnum(wint_t wc);
// int *__errno_location(void);
// void *memchr(const void *s, int c, size_t n);
// int fileno(FILE *stream);
// size_t fwrite_unlocked(const void *ptr, size_t size, size_t n, FILE *stream);
// char *nl_langinfo(nl_item item);
// char *setlocale(int category, const char *locale);
// int toupper(int c);
// char *strrchr(const char *s, int c);
// int sprintf(char *s, const char *format, ...);
// int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD); weak
// void qsort(void *base, size_t nmemb, size_t size, __compar_fn_t compar);
// const char *re_compile_pattern(const char *pattern, size_t length, struct re_pattern_buffer *buffer);
// char *bindtextdomain(const char *domainname, const char *dirname);
// int strncmp(const char *s1, const char *s2, size_t n);
// void abort(void);
// iconv_t iconv_open(const char *tocode, const char *fromcode);
// int close(int fd);
// void __assert_fail(const char *assertion, const char *file, unsigned int line, const char *function);
// const unsigned __int16 **__ctype_b_loc(void);
// int putchar_unlocked(int c);
// int _gmon_start__(void); weak
void sub_8049533();
void sub_8049550();
int sub_8049560();
int sub_80495D0();
int sub_80495F0();
void sub_804964F();
void sub_804966A();
int sub_804967A();
void sub_804975C();
void sub_8049777();
signed int sub_8049787();
void sub_8049869();
void sub_8049884();
void sub_804998F();
void sub_80499AA();
int sub_80499BA();
void sub_8049AB1();
void sub_8049ACC();
int sub_8049ADC();
void sub_8049BD7();
void sub_8049BF2();
int sub_8049C02();
void sub_8049CF9();
void sub_8049D14();
int sub_8049D24();
// int __usercall sub_8049DEF@<eax>(void (__cdecl *a1)(int *)@<eax>);
void sub_8049E3B();
void sub_8049E56();
int sub_8049E66();
int sub_8049EF0();
void sub_8049F64();
void sub_8049F7F();
signed int sub_8049F8F();
void sub_804A071();
void sub_804A08C();
int nullsub_3(void); // weak
int sub_804A113();
int __cdecl sub_804A1AC(unsigned __int8 a1);
int sub_804A1BE();
int sub_804A1E9();
int __cdecl sub_804A214(char *s1); // idb
char *__cdecl sub_804A3F8(char *a1);
char *__cdecl sub_804A428(char *s);
int __cdecl sub_804A7EA(int a1);
_DWORD sub_804A8D5(); // weak
int __cdecl sub_804AA57(char *s1, int); // idb
int sub_804AB3C(const void *, const void *); // idb
int compar(const void *, const void *); // idb
int __cdecl sub_804AD37(void *, int); // idb
void sub_804ADF9();
void __cdecl sub_804AE32(char *s1);
void __cdecl sub_804AEC5(char *s1, int a2);
unsigned __int8 *__cdecl sub_804B009(int a1);
int __cdecl sub_804B7FE(int a1);
_DWORD __cdecl sub_804B824(_DWORD, _DWORD); // weak
_DWORD sub_804BCDF(); // weak
int __cdecl sub_804C0BC(int a1);
int sub_804CCD5();
_DWORD sub_804CEF8(); // weak
int sub_804D1A7(void); // weak
_DWORD sub_804D648(); // weak
void __cdecl __noreturn sub_804D712(int status); // idb
int __cdecl main(int, char **, char **); // idb
void __noreturn sub_804E320();
int __cdecl sub_804E334(char *s, int a2);
// void __usercall sub_804E4BF(int a1@<edx>, int a2@<ecx>, int a3, int a4, int a5);
int __cdecl sub_804E570(int, int, size_t n); // idb
int __cdecl sub_804E6A9(int, char *s, int, int, size_t n, int); // idb
int sub_804E7F7();
signed int __cdecl sub_804E8DB(int a1);
FILE *__cdecl sub_804E93F(int a1, int a2, FILE *stream);
char *__cdecl sub_804EA99(char *s);
_DWORD __cdecl sub_804EB72(_DWORD, _DWORD); // weak
int __cdecl sub_804EBA8(int c, size_t n); // idb
int __cdecl sub_804F22E(char *msgid, char *); // idb
// int __usercall sub_804F582@<eax>(int a1@<edx>, int a2@<ecx>, int a3, unsigned __int8 a4, char a5);
int *__cdecl sub_804F661(int *a1, int a2, int a3);
int __cdecl sub_804F6A2(_DWORD, _DWORD); // weak
// const char *__usercall sub_804F789@<eax>(int a1@<ebx>, char *msgid, int a3);
_DWORD __cdecl sub_804F824(_DWORD); // weak
int __cdecl sub_804F853(void *s2, size_t n, mbstate_t *p, int, int, int, int, int); // idb
_DWORD __cdecl sub_80509E6();
int __cdecl sub_8050CCE();
int sub_8050D1C();
int __cdecl sub_8050D93(int a1, int a2);
int __cdecl sub_8050DD1(int a1, int a2);
// int __usercall sub_8050E69@<eax>(int a1@<edx>, int a2@<ecx>, int a3, int a4, unsigned __int8 a5);
// int __usercall sub_8050F43@<eax>(int a1@<edx>, int a2@<ecx>, int a3, unsigned __int8 a4);
// int __usercall sub_8050F7C@<eax>(int a1@<edx>, int a2@<ecx>, int a3);
int __cdecl sub_8050FB9(int a1, int a2, int a3);
int __cdecl sub_80510DF(int a1, int a2, int a3, int a4, int a5);
int __cdecl sub_805123E();
int __cdecl sub_8051299();
int sub_80512BB();
char *__cdecl sub_80512D6(FILE *stream, int a2);
char *__cdecl sub_80515BD(int a1, int a2, int a3);
char *__cdecl sub_8051644(int a1, int a2);
int __cdecl sub_8051AD2(FILE *stream, int, int, int, int, int); // idb
int __cdecl sub_8052243(FILE *stream, int, int, int, int); // idb
int sub_80522C9(int a1, int a2, int a3, int a4, ...);
void *__cdecl sub_8052389(unsigned int a1, unsigned int a2);
void *__cdecl sub_80523EC(void *ptr, int a2, int a3);
void *__cdecl sub_8052483(size_t size);
void *__cdecl sub_8052496(size_t size);
void *__cdecl sub_80524C0(void *ptr, size_t size);
void *__cdecl sub_8052598(void *src, size_t n);
void __noreturn sub_80525E6();
void *__cdecl sub_80526CB(char *s, char *fromcode, char *tocode);
_DWORD __cdecl sub_8052709(_DWORD); // weak
int __cdecl sub_8052838(int a1, int a2, int a3);
int __cdecl sub_805286E(char *nptr, int, int base, int, char *s); // idb
int __cdecl sub_8052CEC(FILE *stream); // idb
int __cdecl sub_8052DC1(_DWORD *a1);
int __cdecl sub_8052DFA(FILE *fp); // idb
_DWORD __cdecl sub_8052E53(_DWORD, _DWORD, _DWORD); // weak
int __cdecl sub_8052F97(wchar_t *pwc, char *s, size_t n, mbstate_t *p); // idb
int __cdecl sub_805301E(unsigned __int8 *a1, unsigned __int8 *a2);
int __cdecl sub_8053098(FILE *fp); // idb
int __cdecl sub_805314B(int category); // idb
// void *__usercall sub_80531A9@<eax>(int a1@<ebx>);
// const char *__usercall sub_80536FA@<eax>(int a1@<ebx>);
_DWORD __cdecl sub_80537AD(_DWORD); // weak
signed int __cdecl sub_8053B3E(_BYTE *a1, int a2, unsigned int a3, _DWORD *a4);
_DWORD sub_8053D82(); // weak
// int __usercall sub_8054183@<eax>(size_t n@<ecx>, void *s2, size_t n); idb
_DWORD __cdecl sub_8054F67(_DWORD); // weak
int __cdecl sub_80556F2(char *s, iconv_t cd); // idb
void *__cdecl sub_8055AA9(char *s, char *fromcode, char *tocode);
size_t __cdecl sub_8055BD1(void *s, size_t n);
int __cdecl sub_8055E2C(int a1);
unsigned int __cdecl sub_8055E62(unsigned int a1);
_DWORD __cdecl sub_8055F2B(_DWORD); // weak
int __cdecl sub_8056038(int a1, int a2);
bool __cdecl sub_80560D8(unsigned __int8 a1);
_DWORD __cdecl sub_805612F(_DWORD); // weak
// void __usercall sub_80563A8(unsigned __int64 a1@<edx:eax>, char a2@<dil>, unsigned int a3, int a4, unsigned int a5);
int __cdecl sub_8056498(int a1);
int __cdecl sub_80564C7(int a1, int a2);
int __fastcall sub_805663B(_DWORD, _DWORD, _DWORD, _DWORD);
int __stdcall sub_80566B5(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); // weak
int __fastcall sub_8056729(_DWORD, _DWORD); // weak
int __stdcall sub_80567A3(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); // weak
int __stdcall sub_805681B(_DWORD); // weak
int __fastcall sub_8056887(_DWORD, _DWORD); // weak
int __stdcall sub_80568F3(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); // weak
int (**sub_8056910())();
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN locret_8049AEB; // weak
_UNKNOWN locret_8049D33; // weak
_UNKNOWN loc_804A48C; // weak
_UNKNOWN loc_804A4EA; // weak
_UNKNOWN loc_804A561; // weak
_UNKNOWN loc_804A56F; // weak
_UNKNOWN loc_804A6B8; // weak
_UNKNOWN loc_804A6E1; // weak
_UNKNOWN loc_804A6E6; // weak
_UNKNOWN loc_804A75B; // weak
_UNKNOWN loc_804A7B4; // weak
_UNKNOWN loc_804ADE6; // weak
_UNKNOWN loc_804B0B2; // weak
_UNKNOWN loc_804B108; // weak
_UNKNOWN loc_804B201; // weak
_UNKNOWN loc_804B28D; // weak
_UNKNOWN loc_804B292; // weak
_UNKNOWN loc_804B32C; // weak
_UNKNOWN loc_804B370; // weak
_UNKNOWN loc_804B39D; // weak
_UNKNOWN loc_804B3A6; // weak
_UNKNOWN loc_804C42D; // weak
_UNKNOWN loc_804C5BD; // weak
_UNKNOWN loc_804C614; // weak
_UNKNOWN loc_804C79C; // weak
_UNKNOWN loc_804C7B6; // weak
_UNKNOWN loc_804C7BB; // weak
_UNKNOWN loc_804C7FA; // weak
_UNKNOWN loc_804CAB1; // weak
_UNKNOWN loc_804CBBE; // weak
_UNKNOWN loc_804CBC5; // weak
_UNKNOWN loc_804CE52; // weak
_UNKNOWN loc_804CE69; // weak
_UNKNOWN loc_804E35F; // weak
_UNKNOWN loc_804E494; // weak
_UNKNOWN loc_804E4BA; // weak
_UNKNOWN loc_804E4E5; // weak
_UNKNOWN loc_804E508; // weak
_UNKNOWN loc_804E514; // weak
_UNKNOWN loc_804E675; // weak
_UNKNOWN locret_804E93D; // weak
_UNKNOWN loc_804F5BB; // weak
_UNKNOWN loc_805133D; // weak
_UNKNOWN loc_80513A0; // weak
_UNKNOWN loc_80513A6; // weak
_UNKNOWN loc_80513C7; // weak
_UNKNOWN loc_805159B; // weak
_UNKNOWN locret_8052DBF; // weak
_UNKNOWN loc_8053085; // weak
_UNKNOWN loc_8053102; // weak
_UNKNOWN loc_8053127; // weak
_UNKNOWN loc_8053144; // weak
_UNKNOWN loc_805322E; // weak
_UNKNOWN loc_805323B; // weak
_UNKNOWN loc_80532B1; // weak
_UNKNOWN loc_80532B8; // weak
_UNKNOWN loc_805367C; // weak
_UNKNOWN loc_805367E; // weak
_UNKNOWN loc_8053683; // weak
_UNKNOWN loc_8053CE4; // weak
_UNKNOWN loc_8053CFE; // weak
_UNKNOWN loc_8055AFC; // weak
_UNKNOWN loc_8055B07; // weak
_UNKNOWN loc_8055BCC; // weak
_UNKNOWN locret_8055BCF; // weak
_UNKNOWN loc_80562AB; // weak
_UNKNOWN loc_80563FB; // weak
_UNKNOWN loc_8056406; // weak
char locale = '\0'; // idb
_UNKNOWN unk_80579E6; // weak
_UNKNOWN unk_80579EA; // weak
_UNKNOWN unk_80579F6; // weak
_UNKNOWN unk_80579FA; // weak
_UNKNOWN unk_80579FD; // weak
_UNKNOWN unk_8057D2C; // weak
_UNKNOWN unk_80582F7; // weak
int dword_80584B8[8] = { 6656, 4294967279, 4294967294, 2147483646, 0, 0, 0, 0 }; // idb
_UNKNOWN unk_80591FC; // weak
_UNKNOWN unk_80591FF; // weak
int dword_8059F04 = 28; // weak
_UNKNOWN unk_805A230; // weak
_UNKNOWN unk_805A233; // weak
int (*off_805BEE0[2])() = { &sub_80495F0, &sub_80495D0 }; // weak
int (*off_805BEE4)() = &sub_80495D0; // weak
int (*dword_805C008)(void) = NULL; // weak
int dword_805C160 = 0; // weak
int dword_805C174 = 0; // weak
int dword_805C188 = 0; // weak
int dword_805C19C = 0; // weak
int dword_805C1B0 = 0; // weak
int dword_805C1C4 = 0; // weak
int dword_805C1D8 = 0; // weak
int dword_805C208 = 0; // weak
char byte_805C20C = '\x01'; // weak
int dword_805C214 = 3; // weak
char *s = "/"; // idb
char *off_805C21C[2] = { "xx", "8.28" }; // weak
int status = 1; // idb
_UNKNOWN unk_805C280; // weak
_UNKNOWN unk_805C283; // weak
_UNKNOWN unk_805C294; // weak
_UNKNOWN unk_805C297; // weak
int program_invocation_short_name; // weak
FILE *stderr; // idb
int program_invocation_name; // weak
FILE *stdin; // idb
FILE *stdout; // idb
char byte_805C2EC; // weak
_UNKNOWN unk_805C2F0; // weak
char byte_805C554; // weak
char byte_805C602; // weak
char byte_805C603; // weak
char byte_805C60A; // weak
int dword_805C622; // weak
struct re_pattern_buffer buffer; // idb
int dword_805C762; // weak
struct re_pattern_buffer stru_805C766; // idb
char byte_805C8A2; // weak
struct re_registers regs; // idb
struct re_registers stru_805C9AE; // idb
char byte_805C9C2[9]; // idb
char byte_805C9CB; // weak
char byte_805C9CC; // weak
char byte_805C9E2; // weak
int dword_805CAC2; // weak
int dword_805CAF2; // weak
int dword_805CAF6; // weak
int dword_805CAFA; // weak
void *ptr; // idb
size_t nmemb; // idb
int dword_805CC22; // weak
int dword_805CC26; // weak
int dword_805CC2A; // weak
int dword_805CC32; // weak
int dword_805CC36; // weak
char byte_805CC3A; // weak
char *string; // idb
int dword_805CC42; // weak
char byte_805CC46; // weak
int dword_805CC4A; // weak
int dword_805CC4E; // weak
char byte_805CC52; // weak
char *dword_805CC56; // idb
int dword_805CC5A; // weak
char byte_805CC5E; // weak
int dword_805CC62; // weak
int dword_805CC66; // weak
int dword_805CC6A; // weak
char byte_805CC6E; // weak
int dword_805CC72; // weak
int dword_805CC82[]; // weak
int dword_805CC86; // weak
int dword_805CC8A; // weak
int dword_805CC8E; // weak
int dword_805CC92; // weak
int dword_805CC96; // weak
int dword_805CC9A; // weak
int dword_805CC9E; // weak
int dword_805CCA2; // weak
int dword_805CCA6; // weak
int dword_805CCAA; // weak
int dword_805CCAE; // weak
int dword_805CDC2; // weak
int dword_805CDE2[264]; // idb
// extern _UNKNOWN __gmon_start__; weak


//----- (08048F98) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 80494F0: using guessed type int _gmon_start__(void);

//----- (08048FC0) --------------------------------------------------------
int sub_8048FC0()
{
  return dword_805C008();
}
// 805C008: using guessed type int (*dword_805C008)(void);

//----- (08049500) --------------------------------------------------------
#error "8049503: positive sp value has been found (funcsize=2)"

//----- (08049533) --------------------------------------------------------
void sub_8049533()
{
  ;
}

//----- (08049550) --------------------------------------------------------
void sub_8049550()
{
  ;
}

//----- (08049560) --------------------------------------------------------
int sub_8049560()
{
  int result; // eax

  result = &unk_805C297 - &unk_805C294;
  if ( (unsigned int)(&unk_805C297 - &unk_805C294) > 6 )
    result = 0;
  return result;
}
// 8049560: could not find valid save-restore pair for ebp

//----- (080495D0) --------------------------------------------------------
int sub_80495D0()
{
  int result; // eax

  if ( !byte_805C2EC )
  {
    result = sub_8049560();
    byte_805C2EC = 1;
  }
  return result;
}
// 80495D0: could not find valid save-restore pair for ebp
// 805C2EC: using guessed type char byte_805C2EC;

//----- (080495F0) --------------------------------------------------------
int sub_80495F0()
{
  return 0;
}
// 80495F0: could not find valid save-restore pair for ebp

//----- (0804964F) --------------------------------------------------------
void sub_804964F()
{
  ;
}

//----- (0804966A) --------------------------------------------------------
void sub_804966A()
{
  ;
}

//----- (0804967A) --------------------------------------------------------
int sub_804967A()
{
  int result; // eax

  result = &unk_805C2F0 - (_UNKNOWN *)&program_invocation_short_name;
  if ( (unsigned int)(&unk_805C2F0 - (_UNKNOWN *)&program_invocation_short_name) > 6 )
    result = 0;
  return result;
}
// 804967A: could not find valid save-restore pair for ebp
// 805C2A0: using guessed type int program_invocation_short_name;

//----- (0804975C) --------------------------------------------------------
void sub_804975C()
{
  ;
}

//----- (08049777) --------------------------------------------------------
void sub_8049777()
{
  ;
}

//----- (08049787) --------------------------------------------------------
signed int sub_8049787()
{
  return 3;
}
// 8049787: could not find valid save-restore pair for ebp

//----- (08049869) --------------------------------------------------------
void sub_8049869()
{
  ;
}

//----- (08049884) --------------------------------------------------------
void sub_8049884()
{
  ;
}

//----- (08049894) --------------------------------------------------------
#error "80498C1: call analysis failed (funcsize=23)"

//----- (0804998F) --------------------------------------------------------
void sub_804998F()
{
  ;
}

//----- (080499AA) --------------------------------------------------------
void sub_80499AA()
{
  ;
}

//----- (080499BA) --------------------------------------------------------
int sub_80499BA()
{
  int result; // eax

  result = &unk_805C283 - &unk_805C280;
  if ( (unsigned int)(&unk_805C283 - &unk_805C280) > 6 )
    result = 0;
  return result;
}
// 80499BA: could not find valid save-restore pair for ebp

//----- (08049AB1) --------------------------------------------------------
void sub_8049AB1()
{
  ;
}

//----- (08049ACC) --------------------------------------------------------
void sub_8049ACC()
{
  ;
}

//----- (08049ADC) --------------------------------------------------------
#error "8049B09: call analysis failed (funcsize=23)"

//----- (08049BD7) --------------------------------------------------------
void sub_8049BD7()
{
  ;
}

//----- (08049BF2) --------------------------------------------------------
void sub_8049BF2()
{
  ;
}

//----- (08049C02) --------------------------------------------------------
int sub_8049C02()
{
  int result; // eax

  result = &unk_805C283 - &unk_805C280;
  if ( (unsigned int)(&unk_805C283 - &unk_805C280) > 6 )
    result = 0;
  return result;
}
// 8049C02: could not find valid save-restore pair for ebp

//----- (08049CF9) --------------------------------------------------------
void sub_8049CF9()
{
  ;
}

//----- (08049D14) --------------------------------------------------------
void sub_8049D14()
{
  ;
}

//----- (08049D24) --------------------------------------------------------
#error "8049D51: call analysis failed (funcsize=23)"

//----- (08049DEF) --------------------------------------------------------
int __usercall sub_8049DEF@<eax>(void (__cdecl *a1)(int *)@<eax>)
{
  a1(&dword_8059F04);
  return 0;
}
// 8059F04: using guessed type int dword_8059F04;

//----- (08049E3B) --------------------------------------------------------
void sub_8049E3B()
{
  ;
}

//----- (08049E56) --------------------------------------------------------
void sub_8049E56()
{
  ;
}

//----- (08049E66) --------------------------------------------------------
int sub_8049E66()
{
  int result; // eax

  result = &unk_80591FF - &unk_80591FC;
  if ( (unsigned int)(&unk_80591FF - &unk_80591FC) > 6 )
    result = 0;
  return result;
}
// 8049E66: could not find valid save-restore pair for ebp

//----- (08049EF0) --------------------------------------------------------
int sub_8049EF0()
{
  int result; // eax

  result = sub_8049E66();
  byte_805C554 = 1;
  return result;
}
// 805C554: using guessed type char byte_805C554;

//----- (08049F64) --------------------------------------------------------
void sub_8049F64()
{
  ;
}

//----- (08049F7F) --------------------------------------------------------
void sub_8049F7F()
{
  ;
}

//----- (08049F8F) --------------------------------------------------------
signed int sub_8049F8F()
{
  return 3;
}
// 8049F8F: could not find valid save-restore pair for ebp

//----- (0804A071) --------------------------------------------------------
void sub_804A071()
{
  ;
}

//----- (0804A08C) --------------------------------------------------------
void sub_804A08C()
{
  ;
}

//----- (0804A09C) --------------------------------------------------------
#error "804A0C9: call analysis failed (funcsize=23)"

//----- (0804A113) --------------------------------------------------------
int sub_804A113()
{
  return nullsub_3();
}
// 804A113: could not find valid save-restore pair for ebp
// 804A112: using guessed type int nullsub_3(void);

//----- (0804A180) --------------------------------------------------------
#error "804A10D: call analysis failed (funcsize=29)"

//----- (0804A1AC) --------------------------------------------------------
int __cdecl sub_804A1AC(unsigned __int8 a1)
{
  return a1;
}

//----- (0804A1BE) --------------------------------------------------------
int sub_804A1BE()
{
  FILE *v0; // ebx
  char *v1; // eax

  v0 = stdout;
  v1 = gettext("\nWith no FILE, or when FILE is -, read standard input.\n");
  return fputs_unlocked(v1, v0);
}
// 80492B0: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);

//----- (0804A1E9) --------------------------------------------------------
int sub_804A1E9()
{
  FILE *v0; // ebx
  char *v1; // eax

  v0 = stdout;
  v1 = gettext("\nMandatory arguments to long options are mandatory for short options too.\n");
  return fputs_unlocked(v1, v0);
}
// 80492B0: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);

//----- (0804A214) --------------------------------------------------------
#error "804A2FE: call analysis failed (funcsize=114)"

//----- (0804A3F8) --------------------------------------------------------
char *__cdecl sub_804A3F8(char *a1)
{
  char *v1; // ebx
  int *v2; // eax

  v1 = gettext("error in regular expression matcher");
  v2 = __errno_location();
  error(1, *v2, v1);
  return sub_804A428(a1);
}

//----- (0804A428) --------------------------------------------------------
#error "804A487: call analysis failed (funcsize=282)"

//----- (0804A7EA) --------------------------------------------------------
int __cdecl sub_804A7EA(int a1)
{
  unsigned __int8 *v1; // eax
  size_t v2; // eax
  int v3; // ebx
  char *v4; // eax
  char *v6; // [esp+0h] [ebp-38h]
  const char *v7; // [esp+Ch] [ebp-2Ch]
  int v8; // [esp+10h] [ebp-28h]
  struct re_pattern_buffer *buffer; // [esp+24h] [ebp-14h]
  char *s; // [esp+28h] [ebp-10h]
  const char *v11; // [esp+2Ch] [ebp-Ch]

  buffer = (struct re_pattern_buffer *)(a1 + 4);
  s = *(char **)a1;
  *(_DWORD *)(a1 + 4) = 0;
  buffer->allocated = 0;
  buffer->fastmap = (char *)(a1 + 36);
  if ( byte_805C60A )
    v1 = (unsigned __int8 *)&byte_805C8A2;
  else
    v1 = 0;
  buffer->translate = v1;
  v2 = strlen(s);
  v11 = re_compile_pattern(s, v2, buffer);
  if ( v11 )
  {
    v6 = s;
    v3 = sub_80512BB();
    v4 = gettext("%s (for regexp %s)");
    v8 = v3;
    v7 = v11;
    error(1, 0, v4, v11, v3);
  }
  return re_compile_fastmap(buffer);
}
// 805C60A: using guessed type char byte_805C60A;
// 805C8A2: using guessed type char byte_805C8A2;

//----- (0804A8D5) --------------------------------------------------------
#error "804A9BE: call analysis failed (funcsize=94)"

//----- (0804AA57) --------------------------------------------------------
int __cdecl sub_804AA57(char *s1, int a2)
{
  bool v2; // al
  char *v3; // eax
  char *v4; // eax
  int v5; // ebx
  int *v6; // eax
  int result; // eax
  bool v8; // [esp+1Bh] [ebp-Dh]
  int v9; // [esp+1Ch] [ebp-Ch]

  v2 = !s1 || !*s1 || !strcmp(s1, "-");
  v8 = v2;
  if ( v2 )
    v3 = sub_80512D6(stdin, (int)&v9);
  else
    v3 = sub_8051644((int)s1, (int)&v9);
  *(_DWORD *)a2 = v3;
  if ( !*(_DWORD *)a2 )
  {
    if ( v8 )
      v4 = "-";
    else
      v4 = s1;
    v5 = sub_8050FB9(0, 3, (int)v4);
    v6 = __errno_location();
    error(1, *v6, "%s", v5);
  }
  result = a2;
  *(_DWORD *)(a2 + 4) = v9 + *(_DWORD *)a2;
  return result;
}

//----- (0804AB3C) --------------------------------------------------------
#error "804AC3A: call analysis failed (funcsize=91)"

//----- (0804ACE8) --------------------------------------------------------
int __cdecl compar(const void *a1, const void *a2)
{
  int v3; // [esp+14h] [ebp-4h]

  v3 = sub_804AB3C(a1, a2);
  if ( v3 )
    return v3;
  if ( *(_DWORD *)a1 < *(_DWORD *)a2 )
    return -1;
  return *(_DWORD *)a1 > *(_DWORD *)a2;
}

//----- (0804AD37) --------------------------------------------------------
int __cdecl sub_804AD37(void *a1, int a2)
{
  int v3; // [esp+0h] [ebp-18h]
  int i; // [esp+Ch] [ebp-Ch]
  int v5; // [esp+14h] [ebp-4h]

  for ( i = *(_DWORD *)(a2 + 8) - 1; ; i = i / 2 - 1 )
  {
    if ( i < 0 )
      return 0;
    v5 = sub_804AB3C(a1, (const void *)(8 * (i / 2) + *(_DWORD *)a2));
    if ( v5 >= 0 )
      break;
  }
  if ( v5 > 0 )
  {
    dword_805C188 = (int)&loc_804ADE6;
    sub_805681B(v3);
  }
  return 1;
}
// 805681B: using guessed type int __stdcall sub_805681B(_DWORD);
// 805C188: using guessed type int dword_805C188;

//----- (0804ADF9) --------------------------------------------------------
void sub_804ADF9()
{
  if ( nmemb )
    qsort(ptr, nmemb, 0x1Cu, compar);
}

//----- (0804AE32) --------------------------------------------------------
void __cdecl sub_804AE32(char *s1)
{
  unsigned __int8 *i; // [esp+14h] [ebp-14h]
  void *ptr; // [esp+18h] [ebp-10h]
  unsigned int v3; // [esp+1Ch] [ebp-Ch]

  sub_804AA57(s1, (int)&ptr);
  memset(byte_805C9C2, 1, 0x100u);
  for ( i = (unsigned __int8 *)ptr; v3 > (unsigned int)i; ++i )
    byte_805C9C2[(unsigned __int8)sub_804A1AC(*i)] = 0;
  if ( byte_805C20C != 1 )
  {
    byte_805C9E2 = 0;
    byte_805C9CB = 0;
    byte_805C9CC = 0;
  }
  free(ptr);
}
// 805C20C: using guessed type char byte_805C20C;
// 805C9CB: using guessed type char byte_805C9CB;
// 805C9CC: using guessed type char byte_805C9CC;
// 805C9E2: using guessed type char byte_805C9E2;

//----- (0804AEC5) --------------------------------------------------------
void __cdecl sub_804AEC5(char *s1, int a2)
{
  _BYTE *v2; // [esp+10h] [ebp-18h]
  unsigned int v3; // [esp+14h] [ebp-14h]
  int v4; // [esp+18h] [ebp-10h]
  unsigned int v5; // [esp+1Ch] [ebp-Ch]

  sub_804AA57(s1, (int)&v4);
  *(_DWORD *)a2 = 0;
  *(_DWORD *)(a2 + 4) = 0;
  *(_DWORD *)(a2 + 8) = 0;
  v2 = (_BYTE *)v4;
  while ( v5 > (unsigned int)v2 )
  {
    v3 = (unsigned int)v2;
    while ( v5 > (unsigned int)v2 && *v2 != 10 )
      ++v2;
    if ( (unsigned int)v2 > v3 )
    {
      if ( *(_DWORD *)(a2 + 8) == *(_DWORD *)(a2 + 4) )
        *(_DWORD *)a2 = sub_80523EC(*(void **)a2, a2 + 4, 8);
      *(_DWORD *)(8 * *(_DWORD *)(a2 + 8) + *(_DWORD *)a2) = v3;
      *(_DWORD *)(*(_DWORD *)a2 + 8 * (*(_DWORD *)(a2 + 8))++ + 4) = &v2[-v3];
    }
    if ( v5 > (unsigned int)v2 )
      ++v2;
  }
  qsort(*(void **)a2, *(_DWORD *)(a2 + 8), 8u, sub_804AB3C);
}

//----- (0804B009) --------------------------------------------------------
unsigned __int8 *__cdecl sub_804B009(int a1)
{
  int v1; // ecx
  regoff_t v2; // edx
  const unsigned __int16 *v3; // ebx
  const unsigned __int16 *v4; // ebx
  bool v5; // zf
  int v6; // edx
  int v7; // ecx
  void *v8; // eax
  int v9; // eax
  const unsigned __int16 *v10; // ebx
  int v11; // eax
  void *v12; // eax
  char *v13; // ST08_4
  int v14; // edx
  int v15; // ecx
  void *v16; // eax
  void *v17; // eax
  unsigned __int8 *result; // eax
  char *v19; // [esp+0h] [ebp-68h]
  int v20; // [esp+0h] [ebp-68h]
  int v21; // [esp+0h] [ebp-68h]
  int v22; // [esp+4h] [ebp-64h]
  int v23; // [esp+8h] [ebp-60h]
  int v24; // [esp+Ch] [ebp-5Ch]
  int v25; // [esp+10h] [ebp-58h]
  int v26; // [esp+14h] [ebp-54h]
  int v27; // [esp+18h] [ebp-50h]
  int v28; // [esp+1Ch] [ebp-4Ch]
  int v29; // [esp+20h] [ebp-48h]
  char *string; // [esp+24h] [ebp-44h]
  unsigned __int8 *j; // [esp+28h] [ebp-40h]
  unsigned __int8 *v32; // [esp+2Ch] [ebp-3Ch]
  unsigned __int8 *v33; // [esp+30h] [ebp-38h]
  int v34; // [esp+34h] [ebp-34h]
  unsigned __int8 *i; // [esp+3Ch] [ebp-2Ch]
  int v36; // [esp+40h] [ebp-28h]
  int v37; // [esp+44h] [ebp-24h]
  int v38; // [esp+48h] [ebp-20h]
  unsigned __int8 **v39; // [esp+4Ch] [ebp-1Ch]
  int v40; // [esp+50h] [ebp-18h]
  int v41; // [esp+54h] [ebp-14h]
  int v42; // [esp+58h] [ebp-10h]

  v2 = 8 * a1;
  v39 = (unsigned __int8 **)(8 * a1 + dword_805CAFA);
  v34 = 0;
  v32 = *v39;
  v33 = *v39;
  if ( byte_805C603 )
  {
    while ( v39[1] > v33 )
    {
      v3 = *__ctype_b_loc();
      if ( v3[(unsigned __int8)sub_804A1AC(*v33)] & 0x2000 )
        break;
      ++v33;
    }
    v2 = v33 - v32;
    v34 = v33 - v32;
    if ( v39[1] > v33 )
    {
      v4 = *__ctype_b_loc();
      v5 = (v4[(unsigned __int8)sub_804A1AC(*v33)] & 0x2000) == 0;
      v8 = &loc_804B108;
      if ( !v5 )
        v8 = &loc_804B0B2;
      dword_805C1D8 = (int)v8;
      sub_805663B(v7, v6, v20, v22);
    }
  }
  for ( string = (char *)*v39; ; string = (char *)v38 )
  {
    result = v39[1];
    if ( result <= (unsigned __int8 *)string )
      break;
    v38 = (int)v39[1];
    if ( dword_805C622 )
    {
      v9 = re_search(&buffer, string, v39[1] - (unsigned __int8 *)string, 0, v39[1] - (unsigned __int8 *)string, &regs);
      if ( v9 == -2 )
      {
        sub_804A3F8(v19);
LABEL_16:
        v2 = *regs.end;
        v38 = (int)&string[*regs.end];
        goto LABEL_17;
      }
      if ( v9 != -1 )
        goto LABEL_16;
    }
LABEL_17:
    for ( i = (unsigned __int8 *)v38; i > (unsigned __int8 *)string; --i )
    {
      v10 = *__ctype_b_loc();
      if ( !(v10[(unsigned __int8)sub_804A1AC(*(i - 1))] & 0x2000) )
        break;
    }
    if ( dword_805C762 )
    {
      v11 = re_search(
              &stru_805C766,
              string,
              i - (unsigned __int8 *)string,
              0,
              i - (unsigned __int8 *)string,
              &stru_805C9AE);
      v40 = v11;
      v5 = v11 == -2;
      v12 = &loc_804B28D;
      if ( !v5 )
        v12 = &loc_804B292;
      dword_805C188 = (int)v12;
      sub_805681B(v21);
      sub_804A3F8(v13);
      if ( v40 != -1 )
      {
        v36 = (int)&string[*stru_805C9AE.start];
        v2 = *stru_805C9AE.end;
        v37 = (int)&string[*stru_805C9AE.end];
LABEL_36:
        v17 = &loc_804B39D;
        if ( v37 != v36 )
          v17 = &loc_804B3A6;
        dword_805C174 = (int)v17;
        sub_8056887(v1, v2);
        dword_805C1C4 = (int)&loc_804B201;
        sub_80566B5(
          v19,
          v22,
          v23,
          v24,
          v25,
          v26,
          v27,
          v28,
          v29,
          v36 + 1,
          j,
          v32,
          v33,
          v34,
          string,
          i,
          v36,
          v37,
          v38,
          v39,
          v40,
          v41,
          v42);
        continue;
      }
    }
    else
    {
      for ( j = (unsigned __int8 *)string; j < i && !byte_805C9C2[(unsigned __int8)sub_804A1AC(*j)]; ++j )
        ;
      if ( j != i )
      {
        v36 = (int)j;
        if ( j < i )
        {
          v5 = byte_805C9C2[(unsigned __int8)sub_804A1AC(*j)] == 0;
          v16 = &loc_804B370;
          if ( !v5 )
            v16 = &loc_804B32C;
          dword_805C1B0 = (int)v16;
          sub_8056729(v15, v14);
        }
        v37 = (int)j;
        goto LABEL_36;
      }
    }
  }
  return result;
}
// 80566B5: using guessed type int __stdcall sub_80566B5(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 8056729: using guessed type int __fastcall sub_8056729(_DWORD, _DWORD);
// 805681B: using guessed type int __stdcall sub_805681B(_DWORD);
// 8056887: using guessed type int __fastcall sub_8056887(_DWORD, _DWORD);
// 805C174: using guessed type int dword_805C174;
// 805C188: using guessed type int dword_805C188;
// 805C1B0: using guessed type int dword_805C1B0;
// 805C1C4: using guessed type int dword_805C1C4;
// 805C1D8: using guessed type int dword_805C1D8;
// 805C603: using guessed type char byte_805C603;
// 805C622: using guessed type int dword_805C622;
// 805C762: using guessed type int dword_805C762;
// 805CAFA: using guessed type int dword_805CAFA;

//----- (0804B7FE) --------------------------------------------------------
int __cdecl sub_804B7FE(int a1)
{
  int result; // eax
  int i; // [esp+1Ch] [ebp-Ch]

  result = a1;
  for ( i = a1; i > 0; --i )
    result = putchar_unlocked(32);
  return result;
}

//----- (0804B824) --------------------------------------------------------
#error "804B8C0: call analysis failed (funcsize=276)"

//----- (0804BCDF) --------------------------------------------------------
#error "804BD4C: call analysis failed (funcsize=192)"

//----- (0804C0BC) --------------------------------------------------------
#error "804C3BD: call analysis failed (funcsize=836)"

//----- (0804CCD5) --------------------------------------------------------
int sub_804CCD5()
{
  void *v0; // eax
  int v2; // [esp+0h] [ebp-18h]

  printf(".%s \"", off_805C21C[0]);
  sub_804B824(dword_805CC32, dword_805CC36);
  if ( byte_805CC3A )
    fputs_unlocked(s, stdout);
  putchar_unlocked(34);
  fwrite_unlocked(" \"", 1u, 2u, stdout);
  if ( byte_805CC46 )
    fputs_unlocked(s, stdout);
  sub_804B824(string, dword_805CC42);
  putchar_unlocked(34);
  fwrite_unlocked(" \"", 1u, 2u, stdout);
  sub_804B824(dword_805CC4A, dword_805CC4E);
  if ( byte_805CC52 )
    fputs_unlocked(s, stdout);
  putchar_unlocked(34);
  fwrite_unlocked(" \"", 1u, 2u, stdout);
  v0 = &loc_804CE52;
  if ( !byte_805CC5E )
    v0 = &loc_804CE69;
  dword_805C188 = (int)v0;
  sub_805681B(v2);
  fputs_unlocked(s, stdout);
  sub_804B824(dword_805CC56, dword_805CC5A);
  putchar_unlocked(34);
  if ( byte_805C602 || byte_805C603 )
  {
    fwrite_unlocked(" \"", 1u, 2u, stdout);
    sub_804B824(dword_805CC62, dword_805CC66);
    putchar_unlocked(34);
  }
  return putchar_unlocked(10);
}
// 80492B0: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);
// 804B824: using guessed type _DWORD __cdecl sub_804B824(_DWORD, _DWORD);
// 805681B: using guessed type int __stdcall sub_805681B(_DWORD);
// 805C188: using guessed type int dword_805C188;
// 805C21C: using guessed type char *off_805C21C[2];
// 805C602: using guessed type char byte_805C602;
// 805C603: using guessed type char byte_805C603;
// 805CC32: using guessed type int dword_805CC32;
// 805CC36: using guessed type int dword_805CC36;
// 805CC3A: using guessed type char byte_805CC3A;
// 805CC42: using guessed type int dword_805CC42;
// 805CC46: using guessed type char byte_805CC46;
// 805CC4A: using guessed type int dword_805CC4A;
// 805CC4E: using guessed type int dword_805CC4E;
// 805CC52: using guessed type char byte_805CC52;
// 805CC5A: using guessed type int dword_805CC5A;
// 805CC5E: using guessed type char byte_805CC5E;
// 805CC62: using guessed type int dword_805CC62;
// 805CC66: using guessed type int dword_805CC66;

//----- (0804CEF8) --------------------------------------------------------
#error "804D026: call analysis failed (funcsize=158)"

//----- (0804D1A7) --------------------------------------------------------
#error "804D3E3: call analysis failed (funcsize=280)"

//----- (0804D648) --------------------------------------------------------
#error "804D6E9: call analysis failed (funcsize=47)"

//----- (0804D712) --------------------------------------------------------
void __cdecl __noreturn sub_804D712(int status)
{
  int v1; // ebx
  char *v2; // eax
  int v3; // esi
  int v4; // ebx
  char *v5; // eax
  FILE *v6; // ebx
  char *v7; // eax
  FILE *v8; // ebx
  char *v9; // eax
  FILE *v10; // ebx
  char *v11; // eax
  FILE *v12; // ebx
  char *v13; // eax
  FILE *v14; // ebx
  char *v15; // eax
  FILE *v16; // ebx
  char *v17; // eax
  FILE *v18; // ebx
  char *v19; // eax
  FILE *v20; // ebx
  char *v21; // eax

  if ( status )
  {
    v1 = dword_805CC72;
    v2 = gettext("Try '%s --help' for more information.\n");
    fprintf(stderr, v2, v1);
  }
  else
  {
    v3 = dword_805CC72;
    v4 = dword_805CC72;
    v5 = gettext("Usage: %s [OPTION]... [INPUT]...   (without -G)\n  or:  %s -G [OPTION]... [INPUT [OUTPUT]]\n");
    printf(v5, v4, v3);
    v6 = stdout;
    v7 = gettext("Output a permuted index, including context, of the words in the input files.\n");
    fputs_unlocked(v7, v6);
    sub_804A1BE();
    sub_804A1E9();
    v8 = stdout;
    v9 = gettext(
           "  -A, --auto-reference           output automatically generated references\n"
           "  -G, --traditional              behave more like System V 'ptx'\n");
    fputs_unlocked(v9, v8);
    v10 = stdout;
    v11 = gettext(
            "  -F, --flag-truncation=STRING   use STRING for flagging line truncations.\n"
            "                                 The default is '/'\n");
    fputs_unlocked(v11, v10);
    v12 = stdout;
    v13 = gettext(
            "  -M, --macro-name=STRING        macro name to use instead of 'xx'\n"
            "  -O, --format=roff              generate output as roff directives\n"
            "  -R, --right-side-refs          put references at right, not counted in -w\n"
            "  -S, --sentence-regexp=REGEXP   for end of lines or end of sentences\n"
            "  -T, --format=tex               generate output as TeX directives\n");
    fputs_unlocked(v13, v12);
    v14 = stdout;
    v15 = gettext(
            "  -W, --word-regexp=REGEXP       use REGEXP to match each keyword\n"
            "  -b, --break-file=FILE          word break characters in this FILE\n"
            "  -f, --ignore-case              fold lower case to upper case for sorting\n"
            "  -g, --gap-size=NUMBER          gap size in columns between output fields\n"
            "  -i, --ignore-file=FILE         read ignore word list from FILE\n"
            "  -o, --only-file=FILE           read only word list from this FILE\n");
    fputs_unlocked(v15, v14);
    v16 = stdout;
    v17 = gettext(
            "  -r, --references               first field of each line is a reference\n"
            "  -t, --typeset-mode               - not implemented -\n"
            "  -w, --width=NUMBER             output width in columns, reference excluded\n");
    fputs_unlocked(v17, v16);
    v18 = stdout;
    v19 = gettext("      --help     display this help and exit\n");
    fputs_unlocked(v19, v18);
    v20 = stdout;
    v21 = gettext("      --version  output version information and exit\n");
    fputs_unlocked(v21, v20);
    sub_804A214("ptx");
  }
  exit(status);
}
// 80492B0: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);
// 805CC72: using guessed type int dword_805CC72;

//----- (0804D886) --------------------------------------------------------
#error "804D8FF: call analysis failed (funcsize=490)"

//----- (0804E320) --------------------------------------------------------
void __noreturn sub_804E320()
{
  sub_804D712(1);
}

//----- (0804E334) --------------------------------------------------------
int __cdecl sub_804E334(char *s, int a2)
{
  int v2; // ecx
  void *v3; // eax
  int v5; // [esp+0h] [ebp-28h]

  strlen(s);
  v3 = &loc_804E494;
  if ( *(_DWORD *)a2 )
    v3 = &loc_804E35F;
  dword_805C1B0 = (int)v3;
  sub_8056729(v2, 0);
  dword_805C188 = (int)&loc_804E4BA;
  sub_805681B(v5);
  return -2;
}
// 804E334: could not find valid save-restore pair for ebx
// 8056729: using guessed type int __fastcall sub_8056729(_DWORD, _DWORD);
// 805681B: using guessed type int __stdcall sub_805681B(_DWORD);
// 805C188: using guessed type int dword_805C188;
// 805C1B0: using guessed type int dword_805C1B0;

//----- (0804E4BF) --------------------------------------------------------
#error "804E4FF: call analysis failed (funcsize=46)"

//----- (0804E570) --------------------------------------------------------
int __cdecl sub_804E570(int a1, int a2, size_t n)
{
  FILE *v3; // ebx
  char *v4; // eax
  int v6; // [esp+0h] [ebp-28h]
  const void *v7; // [esp+4h] [ebp-24h]
  int v8; // [esp+8h] [ebp-20h]
  int v9; // [esp+18h] [ebp-10h]
  void *s1; // [esp+1Ch] [ebp-Ch]

  s1 = 0;
  v3 = stderr;
  v4 = gettext("Valid arguments are:");
  fputs_unlocked(v4, v3);
  v9 = 0;
  dword_805C188 = (int)&loc_804E675;
  sub_805681B(v6);
  do
  {
    if ( v9 && (v7 = (const void *)(a2 + v9 * n), !memcmp(s1, v7, n)) )
    {
      v6 = *(_DWORD *)(4 * v9 + a1);
      v8 = sub_80512BB();
      fprintf(stderr, ", %s", v8);
    }
    else
    {
      v6 = *(_DWORD *)(4 * v9 + a1);
      v8 = sub_80512BB();
      fprintf(stderr, "\n  - %s", v8);
      s1 = (void *)(v9 * n + a2);
    }
    ++v9;
  }
  while ( *(_DWORD *)(4 * v9 + a1) );
  return putc_unlocked(10, stderr);
}
// 80492B0: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);
// 805681B: using guessed type int __stdcall sub_805681B(_DWORD);
// 805C188: using guessed type int dword_805C188;

//----- (0804E6A9) --------------------------------------------------------
int __cdecl sub_804E6A9(int a1, char *s, int a3, int a4, size_t n, int a6)
{
  int v6; // edx
  int v7; // ecx
  int v9; // [esp+8h] [ebp-20h]
  size_t v10; // [esp+Ch] [ebp-1Ch]
  int v11; // [esp+1Ch] [ebp-Ch]

  v10 = n;
  v9 = a4;
  v11 = sub_804E334(s, a3);
  if ( v11 >= 0 )
    return v11;
  sub_804E4BF(v6, v7, a1, (int)s, v11);
  sub_804E570(a3, a4, n);
  ((void (*)(void))a6)();
  return -1;
}

//----- (0804E7F7) --------------------------------------------------------
int sub_804E7F7()
{
  int v0; // edx
  int v1; // ecx
  int v2; // ebx
  int *v3; // eax
  int *v4; // eax
  int result; // eax
  char *v6; // [esp+2Ch] [ebp-Ch]

  if ( sub_8053098(stdout) && (byte_805CC6E != 1 || *__errno_location() != 32) )
  {
    v6 = gettext("write error");
    if ( dword_805CC6A )
    {
      v2 = sub_8050F7C(v0, v1, dword_805CC6A);
      v3 = __errno_location();
      error(0, *v3, "%s: %s", v2, v6);
    }
    else
    {
      v4 = __errno_location();
      error(0, *v4, "%s", v6);
    }
    _exit(status);
  }
  result = sub_8053098(stderr);
  if ( result )
    _exit(status);
  return result;
}
// 805CC6A: using guessed type int dword_805CC6A;
// 805CC6E: using guessed type char byte_805CC6E;

//----- (0804E8DB) --------------------------------------------------------
signed int __cdecl sub_804E8DB(int a1)
{
  int v1; // edx
  int v2; // ecx
  int fd; // [esp+1Ch] [ebp-Ch]

  fd = open64("/dev/null", 0);
  if ( fd != a1 )
  {
    if ( fd >= 0 )
    {
      close(fd);
      *__errno_location() = 9;
    }
    dword_805C1B0 = (int)&locret_804E93D;
    sub_8056729(v2, v1);
  }
  return 1;
}
// 8049000: using guessed type int __cdecl open64(_DWORD, _DWORD);
// 8056729: using guessed type int __fastcall sub_8056729(_DWORD, _DWORD);
// 805C1B0: using guessed type int dword_805C1B0;

//----- (0804E93F) --------------------------------------------------------
FILE *__cdecl sub_804E93F(int a1, int a2, FILE *stream)
{
  int v3; // eax
  char v5; // [esp+19h] [ebp-Fh]
  char v6; // [esp+1Ah] [ebp-Eh]
  char v7; // [esp+1Bh] [ebp-Dh]
  int v8; // [esp+1Ch] [ebp-Ch]
  FILE *streama; // [esp+38h] [ebp+10h]

  v5 = 0;
  v6 = 0;
  v7 = 0;
  v3 = fileno(stream);
  if ( v3 != 1 )
  {
    if ( v3 != 2 )
    {
      if ( !v3 )
        goto LABEL_10;
      if ( dup2(2, 2) != 2 )
        v7 = 1;
    }
    if ( dup2(1, 1) != 1 )
      v6 = 1;
  }
  if ( dup2(0, 0) )
    v5 = 1;
LABEL_10:
  if ( v5 && (unsigned __int8)sub_804E8DB(0) ^ 1 )
  {
    streama = 0;
  }
  else if ( v6 && (unsigned __int8)sub_804E8DB(1) ^ 1 )
  {
    streama = 0;
  }
  else if ( v7 && (unsigned __int8)sub_804E8DB(2) ^ 1 )
  {
    streama = 0;
  }
  else
  {
    streama = (FILE *)freopen64(a1, a2, stream);
  }
  v8 = *__errno_location();
  if ( v7 )
    close(2);
  if ( v6 )
    close(1);
  if ( v5 )
    close(0);
  if ( !streama )
    *__errno_location() = v8;
  return streama;
}
// 8048FD0: using guessed type int __cdecl freopen64(_DWORD, _DWORD, _DWORD);

//----- (0804EA99) --------------------------------------------------------
char *__cdecl sub_804EA99(char *s)
{
  char *v1; // eax
  char *result; // eax
  char *v3; // [esp+18h] [ebp-10h]
  char *s1; // [esp+1Ch] [ebp-Ch]

  if ( !s )
  {
    fwrite("A NULL argv[0] was passed through an exec system call.\n", 1u, 0x37u, stderr);
    abort();
  }
  v3 = strrchr(s, 47);
  if ( v3 )
    v1 = v3 + 1;
  else
    v1 = s;
  s1 = v1;
  if ( v1 - s > 6 && !strncmp(v1 - 7, "/.libs/", 7u) )
  {
    s = s1;
    if ( !strncmp(s1, "lt-", 3u) )
    {
      s = s1 + 3;
      program_invocation_short_name = (int)(s1 + 3);
    }
  }
  dword_805CC72 = (int)s;
  result = s;
  program_invocation_name = (int)s;
  return result;
}
// 805C2A0: using guessed type int program_invocation_short_name;
// 805C2B0: using guessed type int program_invocation_name;
// 805CC72: using guessed type int dword_805CC72;

//----- (0804EB72) --------------------------------------------------------
#error "804EBA3: call analysis failed (funcsize=16)"

//----- (0804EBA8) --------------------------------------------------------
#error "804F185: positive sp value has been found (funcsize=385)"

//----- (0804F22E) --------------------------------------------------------
#error "804F356: call analysis failed (funcsize=208)"

//----- (0804F582) --------------------------------------------------------
int __usercall sub_804F582@<eax>(int a1@<edx>, int a2@<ecx>, int a3, unsigned __int8 a4, char a5)
{
  int *v5; // ST08_4
  int v6; // ST10_4

  if ( a3 )
  {
    dword_805C1B0 = (int)&loc_804F5BB;
    sub_8056729(a2, a1);
  }
  v5 = &dword_805CC82[(a4 >> 5) + 2];
  v6 = ((unsigned int)*v5 >> (a4 & 0x1F)) & 1;
  *v5 ^= (v6 ^ a5 & 1) << (a4 & 0x1F);
  return v6;
}
// 8056729: using guessed type int __fastcall sub_8056729(_DWORD, _DWORD);
// 805C1B0: using guessed type int dword_805C1B0;
// 805CC82: using guessed type int dword_805CC82[];

//----- (0804F661) --------------------------------------------------------
int *__cdecl sub_804F661(int *a1, int a2, int a3)
{
  int *result; // eax

  if ( !a1 )
    a1 = dword_805CC82;
  *a1 = 10;
  if ( !a2 || !a3 )
    abort();
  a1[10] = a2;
  result = a1;
  a1[11] = a3;
  return result;
}
// 805CC82: using guessed type int dword_805CC82[];

//----- (0804F6A2) --------------------------------------------------------
#error "804F6BF: call analysis failed (funcsize=11)"

//----- (0804F6C4) --------------------------------------------------------
#error "804F786: positive sp value has been found (funcsize=59)"

//----- (0804F789) --------------------------------------------------------
const char *__usercall sub_804F789@<eax>(int a1@<ebx>, char *msgid, int a3)
{
  const char *result; // eax
  char *v4; // [esp+18h] [ebp-10h]
  unsigned __int8 *v5; // [esp+1Ch] [ebp-Ch]

  v4 = gettext(msgid);
  if ( v4 != msgid )
    return v4;
  v5 = (unsigned __int8 *)sub_80536FA(a1);
  if ( sub_805301E(v5, "UTF-8") )
  {
    if ( sub_805301E(v5, "GB18030") )
    {
      if ( a3 == 9 )
        result = (const char *)&unk_80579FD;
      else
        result = "'";
    }
    else if ( *msgid == 96 )
    {
      result = (const char *)&unk_80579F6;
    }
    else
    {
      result = (const char *)&unk_80579FA;
    }
  }
  else if ( *msgid == 96 )
  {
    result = (const char *)&unk_80579E6;
  }
  else
  {
    result = (const char *)&unk_80579EA;
  }
  return result;
}

//----- (0804F824) --------------------------------------------------------
#error "804F84E: call analysis failed (funcsize=17)"

//----- (0804F853) --------------------------------------------------------
#error "80506DB: positive sp value has been found (funcsize=1009)"

//----- (080507C5) --------------------------------------------------------
#error "8050830: call analysis failed (funcsize=35)"

//----- (08050835) --------------------------------------------------------
#error "805087E: call analysis failed (funcsize=62)"

//----- (08050917) --------------------------------------------------------
#error "805094B: positive sp value has been found (funcsize=0)"

//----- (080509E6) --------------------------------------------------------
#error "8050B31: call analysis failed (funcsize=93)"

//----- (08050B36) --------------------------------------------------------
#error "8050CCB: positive sp value has been found (funcsize=56)"

//----- (08050CCE) --------------------------------------------------------
int __cdecl sub_8050CCE()
{
  return sub_80509E6();
}

//----- (08050CF8) --------------------------------------------------------
#error "8050D17: call analysis failed (funcsize=12)"

//----- (08050D1C) --------------------------------------------------------
int sub_8050D1C()
{
  return sub_80509E6();
}

//----- (08050D93) --------------------------------------------------------
int __cdecl sub_8050D93(int a1, int a2)
{
  char v3; // [esp+10h] [ebp-38h]

  sub_804F6A2(&v3, a2);
  return sub_80509E6();
}
// 804F6A2: using guessed type int __cdecl sub_804F6A2(_DWORD, _DWORD);

//----- (08050DD1) --------------------------------------------------------
int __cdecl sub_8050DD1(int a1, int a2)
{
  char v3; // [esp+10h] [ebp-38h]

  sub_804F6A2(&v3, a2);
  return sub_80509E6();
}
// 804F6A2: using guessed type int __cdecl sub_804F6A2(_DWORD, _DWORD);

//----- (08050E69) --------------------------------------------------------
int __usercall sub_8050E69@<eax>(int a1@<edx>, int a2@<ecx>, int a3, int a4, unsigned __int8 a5)
{
  int v6; // [esp+0h] [ebp-58h]
  int v7; // [esp+4h] [ebp-54h]
  int v8; // [esp+8h] [ebp-50h]
  int *v9; // [esp+Ch] [ebp-4Ch]
  unsigned __int8 v10; // [esp+1Ch] [ebp-3Ch]
  int v11; // [esp+20h] [ebp-38h]
  int v12; // [esp+24h] [ebp-34h]
  int v13; // [esp+28h] [ebp-30h]
  int v14; // [esp+2Ch] [ebp-2Ch]
  int v15; // [esp+30h] [ebp-28h]
  int v16; // [esp+34h] [ebp-24h]
  int v17; // [esp+38h] [ebp-20h]
  int v18; // [esp+3Ch] [ebp-1Ch]
  int v19; // [esp+40h] [ebp-18h]
  int v20; // [esp+44h] [ebp-14h]
  int v21; // [esp+48h] [ebp-10h]
  int v22; // [esp+4Ch] [ebp-Ch]

  v10 = a5;
  v11 = dword_805CC82[0];
  v12 = dword_805CC86;
  v13 = dword_805CC8A;
  v14 = dword_805CC8E;
  v15 = dword_805CC92;
  v16 = dword_805CC96;
  v17 = dword_805CC9A;
  v18 = dword_805CC9E;
  v19 = dword_805CCA2;
  v20 = dword_805CCA6;
  v21 = dword_805CCAA;
  v22 = dword_805CCAE;
  sub_804F582(a1, a2, (int)(&v6 - 14), a5, 1);
  v9 = &v11;
  v8 = a4;
  v7 = a3;
  v6 = 0;
  return sub_80509E6();
}
// 805CC82: using guessed type int dword_805CC82[];
// 805CC86: using guessed type int dword_805CC86;
// 805CC8A: using guessed type int dword_805CC8A;
// 805CC8E: using guessed type int dword_805CC8E;
// 805CC92: using guessed type int dword_805CC92;
// 805CC96: using guessed type int dword_805CC96;
// 805CC9A: using guessed type int dword_805CC9A;
// 805CC9E: using guessed type int dword_805CC9E;
// 805CCA2: using guessed type int dword_805CCA2;
// 805CCA6: using guessed type int dword_805CCA6;
// 805CCAA: using guessed type int dword_805CCAA;
// 805CCAE: using guessed type int dword_805CCAE;

//----- (08050F43) --------------------------------------------------------
int __usercall sub_8050F43@<eax>(int a1@<edx>, int a2@<ecx>, int a3, unsigned __int8 a4)
{
  return sub_8050E69(a1, a2, a3, -1, a4);
}

//----- (08050F7C) --------------------------------------------------------
int __usercall sub_8050F7C@<eax>(int a1@<edx>, int a2@<ecx>, int a3)
{
  return sub_8050F43(a1, a2, a3, 0x3Au);
}

//----- (08050FB9) --------------------------------------------------------
int __cdecl sub_8050FB9(int a1, int a2, int a3)
{
  int v3; // edx
  int v4; // ecx
  int v6; // [esp-4h] [ebp-7Ch]
  int v7; // [esp+0h] [ebp-78h]
  int v8; // [esp+4h] [ebp-74h]
  int *v9; // [esp+8h] [ebp-70h]
  int v10; // [esp+10h] [ebp-68h]
  int v11; // [esp+14h] [ebp-64h]
  int v12; // [esp+18h] [ebp-60h]
  int v13; // [esp+1Ch] [ebp-5Ch]
  int v14; // [esp+20h] [ebp-58h]
  int v15; // [esp+24h] [ebp-54h]
  int v16; // [esp+28h] [ebp-50h]
  int v17; // [esp+2Ch] [ebp-4Ch]
  int v18; // [esp+30h] [ebp-48h]
  int v19; // [esp+34h] [ebp-44h]
  int v20; // [esp+38h] [ebp-40h]
  int v21; // [esp+3Ch] [ebp-3Ch]
  int v22; // [esp+40h] [ebp-38h]
  int v23; // [esp+44h] [ebp-34h]
  int v24; // [esp+48h] [ebp-30h]
  int v25; // [esp+4Ch] [ebp-2Ch]
  int v26; // [esp+50h] [ebp-28h]
  int v27; // [esp+54h] [ebp-24h]
  int v28; // [esp+58h] [ebp-20h]
  int v29; // [esp+5Ch] [ebp-1Ch]
  int v30; // [esp+60h] [ebp-18h]
  int v31; // [esp+64h] [ebp-14h]
  int v32; // [esp+68h] [ebp-10h]
  int v33; // [esp+6Ch] [ebp-Ch]

  sub_804F6A2(&v10, a2);
  v22 = v10;
  v23 = v11;
  v24 = v12;
  v25 = v13;
  v26 = v14;
  v27 = v15;
  v28 = v16;
  v29 = v17;
  v30 = v18;
  v31 = v19;
  v32 = v20;
  v33 = v21;
  sub_804F582(v3, v4, (int)(&v6 - 14), 0x3Au, 1);
  v9 = &v22;
  v8 = -1;
  v7 = a3;
  v6 = a1;
  return sub_80509E6();
}
// 804F6A2: using guessed type int __cdecl sub_804F6A2(_DWORD, _DWORD);

//----- (0805107A) --------------------------------------------------------
#error "80510C9: call analysis failed (funcsize=23)"

//----- (080510CE) --------------------------------------------------------
#error "80510DE: positive sp value has been found (funcsize=0)"

//----- (080510DF) --------------------------------------------------------
int __cdecl sub_80510DF(int a1, int a2, int a3, int a4, int a5)
{
  int v6; // [esp+0h] [ebp-48h]
  int v7; // [esp+4h] [ebp-44h]
  int v8; // [esp+8h] [ebp-40h]
  int *v9; // [esp+Ch] [ebp-3Ch]
  int v10; // [esp+10h] [ebp-38h]
  int v11; // [esp+14h] [ebp-34h]
  int v12; // [esp+18h] [ebp-30h]
  int v13; // [esp+1Ch] [ebp-2Ch]
  int v14; // [esp+20h] [ebp-28h]
  int v15; // [esp+24h] [ebp-24h]
  int v16; // [esp+28h] [ebp-20h]
  int v17; // [esp+2Ch] [ebp-1Ch]
  int v18; // [esp+30h] [ebp-18h]
  int v19; // [esp+34h] [ebp-14h]
  int v20; // [esp+38h] [ebp-10h]
  int v21; // [esp+3Ch] [ebp-Ch]

  v10 = dword_805CC82[0];
  v11 = dword_805CC86;
  v12 = dword_805CC8A;
  v13 = dword_805CC8E;
  v14 = dword_805CC92;
  v15 = dword_805CC96;
  v16 = dword_805CC9A;
  v17 = dword_805CC9E;
  v18 = dword_805CCA2;
  v19 = dword_805CCA6;
  v20 = dword_805CCAA;
  v21 = dword_805CCAE;
  sub_804F661(&v6 - 14, a2, a3);
  v9 = &v10;
  v8 = a5;
  v7 = a4;
  v6 = a1;
  return sub_80509E6();
}
// 805CC82: using guessed type int dword_805CC82[];
// 805CC86: using guessed type int dword_805CC86;
// 805CC8A: using guessed type int dword_805CC8A;
// 805CC8E: using guessed type int dword_805CC8E;
// 805CC92: using guessed type int dword_805CC92;
// 805CC96: using guessed type int dword_805CC96;
// 805CC9A: using guessed type int dword_805CC9A;
// 805CC9E: using guessed type int dword_805CC9E;
// 805CCA2: using guessed type int dword_805CCA2;
// 805CCA6: using guessed type int dword_805CCA6;
// 805CCAA: using guessed type int dword_805CCAA;
// 805CCAE: using guessed type int dword_805CCAE;

//----- (0805123E) --------------------------------------------------------
int __cdecl sub_805123E()
{
  return sub_80509E6();
}

//----- (08051299) --------------------------------------------------------
int __cdecl sub_8051299()
{
  return sub_805123E();
}

//----- (080512BB) --------------------------------------------------------
int sub_80512BB()
{
  return sub_8051299();
}

//----- (080512D6) --------------------------------------------------------
char *__cdecl sub_80512D6(FILE *stream, int a2)
{
  int v2; // eax
  int v3; // edx
  int v4; // ecx
  void *v5; // eax
  __int64 v6; // rax
  int v7; // ecx
  __int64 v8; // rax
  size_t n; // ST28_4
  size_t v11; // ST2C_4
  int v12; // ST24_4
  int v13; // edx
  int v14; // ecx
  int v15; // [esp+0h] [ebp-A8h]
  int v16; // [esp+4h] [ebp-A4h]
  int v17; // [esp+4h] [ebp-A4h]
  char *ptr; // [esp+10h] [ebp-98h]
  unsigned int size; // [esp+14h] [ebp-94h]
  unsigned int v20; // [esp+18h] [ebp-90h]
  signed int v21; // [esp+1Ch] [ebp-8Ch]
  char *v22; // [esp+28h] [ebp-80h]
  char *v23; // [esp+2Ch] [ebp-7Ch]
  __int64 v24; // [esp+30h] [ebp-78h]
  __int64 v25; // [esp+38h] [ebp-70h]
  char v26; // [esp+40h] [ebp-68h]
  int v27; // [esp+50h] [ebp-58h]
  __int64 v28; // [esp+6Ch] [ebp-3Ch]

  size = 0x2000;
  v2 = fileno(stream);
  if ( sub_80564C7(v2, (int)&v26) >= 0 )
  {
    v5 = &loc_805133D;
    if ( (v27 & 0xF000) != 0x8000 )
      v5 = &loc_80513C7;
    dword_805C1D8 = (int)v5;
    sub_805663B(v4, v3, v15, v16);
    LODWORD(v6) = ftello64();
    v24 = v6;
    if ( v6 >= 0 && v28 > v6 )
    {
      v8 = v28 - v6;
      v25 = v28 - v24;
      if ( (((unsigned __int64)(v28 - v24) >> 32) & 0x80000000) == 0LL )
      {
        LODWORD(v8) = &loc_80513A0;
        if ( SHIDWORD(v25) > 0 )
          LODWORD(v8) = &loc_80513A6;
        dword_805C1D8 = v8;
        sub_805663B(v7, HIDWORD(v8), stream, v17);
        if ( (unsigned int)v25 > 0xFFFFFFFE )
        {
          *__errno_location() = 12;
          return 0;
        }
      }
      size = v25 + 1;
    }
  }
  ptr = (char *)malloc(size);
  if ( !ptr )
    return 0;
  v20 = 0;
  while ( 1 )
  {
    n = size - v20;
    v11 = fread(&ptr[v20], 1u, size - v20, stream);
    v20 += v11;
    if ( v11 != n )
      break;
    if ( size == -1 )
    {
      v21 = 12;
      goto LABEL_29;
    }
    if ( ~(size >> 1) <= size )
      size = -1;
    else
      size += size >> 1;
    v23 = (char *)realloc(ptr, size);
    if ( !v23 )
    {
      v12 = *__errno_location();
      dword_805C174 = (int)&loc_805159B;
      sub_8056887(v14, v13);
    }
    ptr = v23;
  }
  v21 = *__errno_location();
  if ( ferror(stream) )
  {
LABEL_29:
    free(ptr);
    *__errno_location() = v21;
    return 0;
  }
  if ( size - 1 > v20 )
  {
    v22 = (char *)realloc(ptr, v20 + 1);
    if ( v22 )
      ptr = v22;
  }
  ptr[v20] = 0;
  *(_DWORD *)a2 = v20;
  return ptr;
}
// 80512D6: could not find valid save-restore pair for ebx
// 8049280: using guessed type int ftello64(void);
// 8056887: using guessed type int __fastcall sub_8056887(_DWORD, _DWORD);
// 805C174: using guessed type int dword_805C174;
// 805C1D8: using guessed type int dword_805C1D8;

//----- (080515BD) --------------------------------------------------------
char *__cdecl sub_80515BD(int a1, int a2, int a3)
{
  int v4; // [esp+14h] [ebp-14h]
  FILE *stream; // [esp+18h] [ebp-10h]
  char *ptr; // [esp+1Ch] [ebp-Ch]

  stream = (FILE *)fopen64(a1, a3);
  if ( !stream )
    return 0;
  ptr = sub_80512D6(stream, a2);
  v4 = *__errno_location();
  if ( !sub_8052CEC(stream) )
    return ptr;
  if ( ptr )
  {
    v4 = *__errno_location();
    free(ptr);
  }
  *__errno_location() = v4;
  return 0;
}
// 8049160: using guessed type int __cdecl fopen64(_DWORD, _DWORD);

//----- (08051644) --------------------------------------------------------
char *__cdecl sub_8051644(int a1, int a2)
{
  return sub_80515BD(a1, a2, (int)&unk_8057D2C);
}

//----- (08051688) --------------------------------------------------------
#error "80519A2: call analysis failed (funcsize=323)"

//----- (08051AD2) --------------------------------------------------------
#error "8052121: call analysis failed (funcsize=431)"

//----- (08052243) --------------------------------------------------------
int __cdecl sub_8052243(FILE *stream, int a2, int a3, int a4, int a5)
{
  int *v5; // eax
  unsigned int i; // [esp+24h] [ebp-34h]
  int v8[12]; // [esp+28h] [ebp-30h]

  for ( i = 0; i <= 9; ++i )
  {
    v5 = (int *)a5;
    a5 += 4;
    v8[i] = *v5;
    if ( !v8[i] )
      break;
  }
  return sub_8051AD2(stream, a2, a3, a4, (int)v8, i);
}
// 8052243: using guessed type int var_30[12];

//----- (080522C9) --------------------------------------------------------
int sub_80522C9(int a1, int a2, int a3, int a4, ...)
{
  int v5; // [esp+14h] [ebp-28h]
  va_list va; // [esp+50h] [ebp+14h]

  va_start(va, a4);
  return sub_8052243((FILE *)va, v5, (int)va, v5, (int)va);
}

//----- (08052389) --------------------------------------------------------
void *__cdecl sub_8052389(unsigned int a1, unsigned int a2)
{
  if ( 0x7FFFFFFF / a2 < a1 )
    sub_80525E6();
  return sub_8052496(a2 * a1);
}

//----- (080523EC) --------------------------------------------------------
void *__cdecl sub_80523EC(void *ptr, int a2, int a3)
{
  unsigned int v4; // [esp+1Ch] [ebp-Ch]

  v4 = *(_DWORD *)a2;
  if ( ptr )
  {
    if ( 0x55555554u / a3 <= v4 )
      sub_80525E6();
    v4 += (v4 >> 1) + 1;
  }
  else
  {
    if ( !v4 )
      v4 = (0x40u / a3 == 0) + 0x40u / a3;
    if ( 0x7FFFFFFFu / a3 < v4 )
      sub_80525E6();
  }
  *(_DWORD *)a2 = v4;
  return sub_80524C0(ptr, a3 * v4);
}

//----- (08052483) --------------------------------------------------------
void *__cdecl sub_8052483(size_t size)
{
  return sub_8052496(size);
}

//----- (08052496) --------------------------------------------------------
void *__cdecl sub_8052496(size_t size)
{
  void *v2; // [esp+1Ch] [ebp-Ch]

  v2 = malloc(size);
  if ( !v2 && size )
    sub_80525E6();
  return v2;
}

//----- (080524C0) --------------------------------------------------------
void *__cdecl sub_80524C0(void *ptr, size_t size)
{
  void *result; // eax
  void *ptra; // [esp+20h] [ebp+8h]

  if ( size || !ptr )
  {
    ptra = realloc(ptr, size);
    if ( !ptra )
    {
      if ( size )
        sub_80525E6();
    }
    result = ptra;
  }
  else
  {
    free(ptr);
    result = 0;
  }
  return result;
}

//----- (08052598) --------------------------------------------------------
void *__cdecl sub_8052598(void *src, size_t n)
{
  void *v2; // eax

  v2 = sub_8052496(n);
  return memcpy(v2, src, n);
}

//----- (080525E6) --------------------------------------------------------
void __noreturn sub_80525E6()
{
  char *v0; // eax

  v0 = gettext("memory exhausted");
  error(status, 0, "%s", v0);
  abort();
}

//----- (080526CB) --------------------------------------------------------
void *__cdecl sub_80526CB(char *s, char *fromcode, char *tocode)
{
  void *v4; // [esp+1Ch] [ebp-Ch]

  v4 = sub_8055AA9(s, fromcode, tocode);
  if ( !v4 && *__errno_location() == 12 )
    sub_80525E6();
  return v4;
}

//----- (08052709) --------------------------------------------------------
#error "8052741: call analysis failed (funcsize=20)"

//----- (08052746) --------------------------------------------------------
#error "8052833: positive sp value has been found (funcsize=69)"

//----- (08052838) --------------------------------------------------------
int __cdecl sub_8052838(int a1, int a2, int a3)
{
  int v3; // eax
  int i; // [esp+1Ch] [ebp-Ch]

  for ( i = 0; ; i |= sub_8052709(a1) )
  {
    v3 = a3--;
    if ( !v3 )
      break;
  }
  return i;
}
// 8052709: using guessed type _DWORD __cdecl sub_8052709(_DWORD);

//----- (0805286E) --------------------------------------------------------
#error "8052A4C: call analysis failed (funcsize=318)"

//----- (08052CEC) --------------------------------------------------------
int __cdecl sub_8052CEC(FILE *stream)
{
  int v1; // edx
  int v2; // ecx
  int v3; // eax
  __int64 v4; // rax
  int v6; // [esp+14h] [ebp-14h]
  int v7; // [esp+18h] [ebp-10h]

  v6 = 0;
  if ( fileno(stream) < 0 )
  {
    fclose(stream);
    dword_805C1B0 = (int)&locret_8052DBF;
    sub_8056729(v2, v1);
  }
  if ( !__freading(stream) || (v3 = fileno(stream), LODWORD(v4) = lseek64(v3, 0, 0, 1), v4 != -1) )
  {
    if ( sub_8052DFA(stream) )
      v6 = *__errno_location();
  }
  v7 = fclose(stream);
  if ( v6 )
  {
    *__errno_location() = v6;
    v7 = -1;
  }
  return v7;
}
// 8049430: using guessed type int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD);
// 8056729: using guessed type int __fastcall sub_8056729(_DWORD, _DWORD);
// 805C1B0: using guessed type int dword_805C1B0;

//----- (08052DC1) --------------------------------------------------------
int __cdecl sub_8052DC1(_DWORD *a1)
{
  int result; // eax

  result = *a1 & 0x100;
  if ( result )
    result = sub_8052E53(a1, 0, 0);
  return result;
}
// 8052E53: using guessed type _DWORD __cdecl sub_8052E53(_DWORD, _DWORD, _DWORD);

//----- (08052DFA) --------------------------------------------------------
#error "8052E29: call analysis failed (funcsize=24)"

//----- (08052E53) --------------------------------------------------------
#error "8052E87: call analysis failed (funcsize=19)"

//----- (08052E8C) --------------------------------------------------------
#error "8052F96: positive sp value has been found (funcsize=77)"

//----- (08052F97) --------------------------------------------------------
#error "8053010: call analysis failed (funcsize=42)"

//----- (0805301E) --------------------------------------------------------
int __cdecl sub_805301E(unsigned __int8 *a1, unsigned __int8 *a2)
{
  unsigned __int8 *v2; // esi
  unsigned __int8 *v3; // ebx
  int v5; // edx
  int v6; // ecx
  unsigned __int8 v7; // [esp+1Eh] [ebp-Ah]
  unsigned __int8 v8; // [esp+1Fh] [ebp-9h]

  v2 = a1;
  v3 = a2;
  if ( a1 == a2 )
    return 0;
  do
  {
    v7 = sub_8055E2C(*v2);
    v8 = sub_8055E2C(*v3);
    if ( !v7 )
    {
      dword_805C1B0 = (int)&loc_8053085;
      sub_8056729(v6, v5);
    }
    ++v2;
    ++v3;
  }
  while ( v7 == v8 );
  return v7 - v8;
}
// 8056729: using guessed type int __fastcall sub_8056729(_DWORD, _DWORD);
// 805C1B0: using guessed type int dword_805C1B0;

//----- (08053098) --------------------------------------------------------
int __cdecl sub_8053098(FILE *fp)
{
  bool v1; // ST26_1
  bool v2; // al
  void *v3; // eax
  bool v4; // zf
  int v5; // edx
  int v6; // ecx
  void *v7; // eax
  int v9; // [esp+0h] [ebp-28h]
  bool v10; // [esp+1Dh] [ebp-Bh]
  bool v11; // [esp+1Fh] [ebp-9h]

  v10 = __fpending(fp) != 0;
  v1 = ferror_unlocked(fp) != 0;
  v2 = sub_8052CEC(fp) != 0;
  v11 = v2;
  if ( !v1 )
  {
    if ( !v2 )
      return 0;
    v3 = &loc_8053102;
    if ( v10 )
      v3 = &loc_8053127;
    dword_805C188 = (int)v3;
    sub_805681B(v9);
    v4 = *__errno_location() == 9;
    v7 = &loc_8053127;
    if ( v4 )
      v7 = &loc_8053144;
    dword_805C174 = (int)v7;
    sub_8056887(v6, v5);
  }
  if ( v11 != 1 )
    *__errno_location() = 0;
  return -1;
}
// 8053098: could not find valid save-restore pair for ebx
// 805681B: using guessed type int __stdcall sub_805681B(_DWORD);
// 8056887: using guessed type int __fastcall sub_8056887(_DWORD, _DWORD);
// 805C174: using guessed type int dword_805C174;
// 805C188: using guessed type int dword_805C188;

//----- (0805314B) --------------------------------------------------------
int __cdecl sub_805314B(int category)
{
  unsigned __int8 v2; // [esp+1Bh] [ebp-Dh]
  const char *s1; // [esp+1Ch] [ebp-Ch]

  v2 = 1;
  s1 = setlocale(category, 0);
  if ( s1 && (!strcmp(s1, "C") || !strcmp(s1, "POSIX")) )
    v2 = 0;
  return v2;
}

//----- (080531A9) --------------------------------------------------------
void *__usercall sub_80531A9@<eax>(int a1@<ebx>)
{
  char *v1; // eax
  bool v2; // zf
  void *v3; // eax
  int v4; // ebx
  int v5; // ecx
  void *v6; // eax
  signed int v7; // eax
  int v8; // edx
  int v9; // ecx
  int v10; // edx
  int v11; // ecx
  void *v12; // eax
  int v14; // [esp-8h] [ebp-D0h]
  int v15; // [esp-4h] [ebp-CCh]
  size_t v16; // [esp+0h] [ebp-C8h]
  int v17; // [esp+4h] [ebp-C4h]
  char *v18; // [esp+8h] [ebp-C0h]
  char *v19; // [esp+Ch] [ebp-BCh]
  void *ptr; // [esp+14h] [ebp-B4h]
  void *v21; // [esp+18h] [ebp-B0h]
  char *s; // [esp+1Ch] [ebp-ACh]
  void *v23; // [esp+20h] [ebp-A8h]
  size_t v24; // [esp+24h] [ebp-A4h]
  char *v25; // [esp+28h] [ebp-A0h]
  size_t n; // [esp+2Ch] [ebp-9Ch]
  size_t v27; // [esp+30h] [ebp-98h]
  int v28; // [esp+34h] [ebp-94h]
  void *dest; // [esp+38h] [ebp-90h]
  int fd; // [esp+3Ch] [ebp-8Ch]
  FILE *stream; // [esp+40h] [ebp-88h]
  int c; // [esp+44h] [ebp-84h]
  size_t v33; // [esp+48h] [ebp-80h]
  size_t v34; // [esp+4Ch] [ebp-7Ch]
  void *v35; // [esp+50h] [ebp-78h]
  char src; // [esp+56h] [ebp-72h]
  char v37; // [esp+89h] [ebp-3Fh]
  unsigned int v38; // [esp+BCh] [ebp-Ch]

  v38 = __readgsdword(0x14u);
  v21 = (void *)dword_805CDC2;
  if ( !dword_805CDC2 )
  {
    ptr = 0;
    v25 = "charset.alias";
    v1 = getenv("CHARSETALIASDIR");
    s = v1;
    v2 = v1 == 0;
    v15 = (int)v1;
    v14 = a1;
    v3 = &loc_805322E;
    if ( v2 )
      v3 = &loc_805323B;
    dword_805C188 = (int)v3;
    v4 = v14;
    sub_805681B(v16);
    if ( !*s )
    {
      ptr = 0;
      s = "/home/hwangdz/coreutils/coreutils-8.28/install_m32/lib";
    }
    n = strlen(s);
    v27 = strlen(v25);
    if ( n )
    {
      v2 = s[n - 1] == 47;
      v15 = (unsigned __int8)s[n - 1];
      v6 = &loc_80532B1;
      if ( v2 )
        v6 = &loc_80532B8;
      dword_805C1D8 = (int)v6;
      v4 = v14;
      sub_805663B(v5, n - 1, v16, v17);
      v7 = 1;
    }
    else
    {
      v7 = 0;
    }
    v28 = v7;
    v16 = n + v7 + v27 + 1;
    dest = malloc(v16);
    if ( dest )
    {
      memcpy(dest, s, n);
      if ( v28 )
        *((_BYTE *)dest + n) = 47;
      memcpy((char *)dest + n + v28, v25, v27 + 1);
    }
    free(ptr);
    if ( dest )
    {
      fd = open64(dest, 0x20000);
      if ( fd >= 0 )
      {
        stream = fdopen(fd, "r");
        if ( stream )
        {
          v23 = 0;
          v24 = 0;
          while ( 1 )
          {
            c = getc_unlocked(stream);
            if ( c == -1 )
              break;
            if ( c != 10 && c != 32 && c != 9 )
            {
              if ( c == 35 )
              {
                do
                  c = getc_unlocked(stream);
                while ( c != -1 && c != 10 );
                if ( c == -1 )
                  break;
                dword_805C1B0 = (int)&loc_805367E;
                sub_8056729(v9, v8);
              }
              ungetc(c, stream);
              v19 = &v37;
              v18 = &src;
              if ( fscanf(stream, "%50s %50s", &src, &v37) <= 1 )
                break;
              v33 = strlen(&src);
              v34 = strlen(&v37);
              v35 = v23;
              if ( v24 )
              {
                v24 += v34 + v33 + 2;
                v23 = realloc(v23, v24 + 1);
              }
              else
              {
                v24 = v33 + v34 + 2;
                v16 = v33 + v34 + 3;
                v23 = malloc(v16);
              }
              if ( !v23 )
              {
                v24 = 0;
                free(v35);
                break;
              }
              strcpy((char *)v23 + v24 - v34 - v33 - 2, (const char *)&v16 - 114);
              strcpy((char *)v23 + v24 - v34 - 1, &v37);
            }
          }
          v15 = sub_8052CEC(stream);
          v14 = v4;
          v12 = &loc_805367C;
          if ( !v24 )
            v12 = &loc_8053683;
          dword_805C1B0 = (int)v12;
          sub_8056729(v11, v10);
          *((_BYTE *)v23 + v24) = 0;
          v21 = v23;
        }
        else
        {
          close(fd);
          v21 = &unk_80582F7;
        }
      }
      else
      {
        v21 = &unk_80582F7;
      }
      free(dest);
    }
    else
    {
      v21 = &unk_80582F7;
    }
    dword_805CDC2 = (int)v21;
  }
  return v21;
}
// 8049000: using guessed type int __cdecl open64(_DWORD, _DWORD);
// 8056729: using guessed type int __fastcall sub_8056729(_DWORD, _DWORD);
// 805681B: using guessed type int __stdcall sub_805681B(_DWORD);
// 805C188: using guessed type int dword_805C188;
// 805C1B0: using guessed type int dword_805C1B0;
// 805C1D8: using guessed type int dword_805C1D8;
// 805CDC2: using guessed type int dword_805CDC2;

//----- (080536FA) --------------------------------------------------------
const char *__usercall sub_80536FA@<eax>(int a1@<ebx>)
{
  char *v1; // ST1C_4
  const char *s1; // [esp+18h] [ebp-10h]
  char *s2; // [esp+1Ch] [ebp-Ch]

  s1 = nl_langinfo(14);
  if ( !s1 )
    s1 = (const char *)&unk_80582F7;
  for ( s2 = (char *)sub_80531A9(a1); *s2; s2 = &v1[strlen(v1) + 1] )
  {
    if ( !strcmp(s1, s2) || *s2 == 42 && !s2[1] )
    {
      s1 = &s2[strlen(s2) + 1];
      break;
    }
    v1 = &s2[strlen(s2) + 1];
  }
  if ( !*s1 )
    s1 = "ASCII";
  return s1;
}

//----- (080537AD) --------------------------------------------------------
#error "80538DF: call analysis failed (funcsize=99)"

//----- (08053B3E) --------------------------------------------------------
signed int __cdecl sub_8053B3E(_BYTE *a1, int a2, unsigned int a3, _DWORD *a4)
{
  int v4; // ecx
  void *v5; // esp
  unsigned int v6; // eax
  int v8; // edx
  void *v9; // eax
  char v10; // [esp+13h] [ebp-25h]
  unsigned int i; // [esp+14h] [ebp-24h]
  int v12; // [esp+18h] [ebp-20h]
  int v13; // [esp+1Ch] [ebp-1Ch]
  _BYTE *v14; // [esp+20h] [ebp-18h]
  _BYTE *v15; // [esp+24h] [ebp-14h]
  unsigned int v16; // [esp+28h] [ebp-10h]
  unsigned int v17; // [esp+2Ch] [ebp-Ch]

  v16 = a3;
  if ( a3 > 0x1FFFFFFF )
  {
    v6 = 0;
  }
  else if ( 4 * v16 > 0xFB7 )
  {
    v6 = sub_8055E62(4 * v16);
  }
  else
  {
    v5 = alloca(16 * ((4 * (v16 + 2) + 30) / 0x10));
    v6 = 16 * ((unsigned int)&v10 >> 4) + 8;
  }
  v17 = v6;
  if ( !v6 )
    return 0;
  *(_DWORD *)(v17 + 4) = 1;
  v12 = 0;
  for ( i = 2; i < v16; ++i )
  {
    v10 = *(_BYTE *)(i - 1 + a2);
    while ( 1 )
    {
      if ( *(_BYTE *)(a2 + v12) == v10 )
      {
        v4 = i - ++v12;
        *(_DWORD *)(4 * i + v17) = i - v12;
        goto LABEL_15;
      }
      if ( !v12 )
        break;
      v12 -= *(_DWORD *)(4 * v12 + v17);
    }
    *(_DWORD *)(v17 + 4 * i) = i;
LABEL_15:
    ;
  }
  *a4 = 0;
  v13 = 0;
  v14 = a1;
  v15 = a1;
  while ( *v15 )
  {
    v8 = *(unsigned __int8 *)(a2 + v13);
    v9 = &loc_8053CE4;
    if ( (_BYTE)v8 != *v15 )
      v9 = &loc_8053CFE;
    dword_805C174 = (int)v9;
    sub_8056887(v4, v8);
    ++v13;
    ++v15;
    if ( v13 == v16 )
    {
      *a4 = v14;
      break;
    }
  }
  sub_8055F2B(v17);
  return 1;
}
// 8055F2B: using guessed type _DWORD __cdecl sub_8055F2B(_DWORD);
// 8056887: using guessed type int __fastcall sub_8056887(_DWORD, _DWORD);
// 805C174: using guessed type int dword_805C174;

//----- (08053D82) --------------------------------------------------------
#error "8053F86: call analysis failed (funcsize=221)"

//----- (08054119) --------------------------------------------------------
#error "8054170: call analysis failed (funcsize=34)"

//----- (08054183) --------------------------------------------------------
#error "80544A5: positive sp value has been found (funcsize=141)"

//----- (0805464D) --------------------------------------------------------
#error "8054C7B: call analysis failed (funcsize=541)"

//----- (08054F5E) --------------------------------------------------------
#error "8054F64: positive sp value has been found (funcsize=0)"

//----- (08054F67) --------------------------------------------------------
#error "80550B1: call analysis failed (funcsize=144)"

//----- (0805522E) --------------------------------------------------------
#error "8055324: call analysis failed (funcsize=105)"

//----- (080556F2) --------------------------------------------------------
#error "805581B: call analysis failed (funcsize=226)"

//----- (08055AA9) --------------------------------------------------------
void *__cdecl sub_8055AA9(char *s, char *fromcode, char *tocode)
{
  bool v3; // zf
  int v4; // edx
  int v5; // ecx
  void *v6; // eax
  int v7; // edx
  int v8; // ecx
  int v10; // ST2C_4
  int v11; // ST08_4
  int v12; // ST30_4
  int v13; // [esp+0h] [ebp-38h]
  int v14; // [esp+4h] [ebp-34h]
  iconv_t cd; // [esp+1Ch] [ebp-1Ch]
  void *ptr; // [esp+20h] [ebp-18h]

  if ( !*s || !sub_805301E((unsigned __int8 *)fromcode, (unsigned __int8 *)tocode) )
  {
    v3 = strdup(s) == 0;
    v6 = &loc_8055AFC;
    if ( !v3 )
      v6 = &loc_8055B07;
    dword_805C1D8 = (int)v6;
    sub_805663B(v5, v4, v13, v14);
    *__errno_location() = 12;
    dword_805C1B0 = (int)&locret_8055BCF;
    sub_8056729(v8, v7);
  }
  cd = iconv_open(tocode, fromcode);
  if ( cd == (iconv_t)-1 )
    return 0;
  ptr = (void *)sub_80556F2(s, cd);
  if ( !ptr )
  {
    v10 = *__errno_location();
    iconv_close(cd);
    *__errno_location() = v10;
    dword_805C188 = (int)&loc_8055BCC;
    sub_805681B(v11);
  }
  if ( iconv_close(cd) >= 0 )
    return ptr;
  v12 = *__errno_location();
  free(ptr);
  *__errno_location() = v12;
  return 0;
}
// 8056729: using guessed type int __fastcall sub_8056729(_DWORD, _DWORD);
// 805681B: using guessed type int __stdcall sub_805681B(_DWORD);
// 805C188: using guessed type int dword_805C188;
// 805C1B0: using guessed type int dword_805C1B0;
// 805C1D8: using guessed type int dword_805C1D8;

//----- (08055BD1) --------------------------------------------------------
size_t __cdecl sub_8055BD1(void *s, size_t n)
{
  size_t result; // eax
  _BYTE *v3; // [esp+1Ch] [ebp-Ch]

  v3 = memchr(s, 0, n);
  if ( v3 )
    result = v3 - (_BYTE *)s + 1;
  else
    result = n;
  return result;
}

//----- (08055E2C) --------------------------------------------------------
int __cdecl sub_8055E2C(int a1)
{
  int result; // eax

  if ( (unsigned int)(a1 - 65) > 0x19 )
    result = a1;
  else
    result = a1 + 32;
  return result;
}

//----- (08055E62) --------------------------------------------------------
unsigned int __cdecl sub_8055E62(unsigned int a1)
{
  _DWORD *v1; // ST18_4
  unsigned int v2; // ST14_4
  _DWORD *v4; // [esp+14h] [ebp-14h]

  if ( a1 + 8 < a1 )
    return 0;
  v4 = malloc(a1 + 8);
  if ( !v4 )
    return 0;
  v1 = v4;
  v2 = (unsigned int)(v4 + 2);
  v1[1] = 336984906;
  *v1 = dword_805CDE2[v2 % 0x101];
  dword_805CDE2[v2 % 0x101] = v2;
  return v2;
}

//----- (08055F2B) --------------------------------------------------------
#error "8055F6D: call analysis failed (funcsize=23)"

//----- (08056038) --------------------------------------------------------
int __cdecl sub_8056038(int a1, int a2)
{
  int result; // eax

  if ( *(_DWORD *)a2 == a2 + 16 )
  {
    memcpy((void *)(a1 + 16), (const void *)(a2 + 16), *(_DWORD *)(a2 + 4));
    *(_DWORD *)a1 = a1 + 16;
  }
  else
  {
    *(_DWORD *)a1 = *(_DWORD *)a2;
  }
  *(_DWORD *)(a1 + 4) = *(_DWORD *)(a2 + 4);
  *(_BYTE *)(a1 + 8) = *(_BYTE *)(a2 + 8);
  result = *(unsigned __int8 *)(a1 + 8);
  if ( (_BYTE)result )
  {
    result = a1;
    *(_DWORD *)(a1 + 12) = *(_DWORD *)(a2 + 12);
  }
  return result;
}

//----- (080560D8) --------------------------------------------------------
bool __cdecl sub_80560D8(unsigned __int8 a1)
{
  return (((unsigned int)dword_80584B8[a1 >> 5] >> (a1 & 0x1F)) & 1) != 0;
}

//----- (0805612F) --------------------------------------------------------
#error "80561F3: call analysis failed (funcsize=68)"

//----- (08056224) --------------------------------------------------------
#error "80563A3: call analysis failed (funcsize=133)"

//----- (080563A8) --------------------------------------------------------
void __usercall sub_80563A8(unsigned __int64 a1@<edx:eax>, char a2@<dil>, unsigned int a3, int a4, unsigned int a5)
{
  unsigned __int64 v5; // rax
  void *v6; // eax
  void *retaddr; // [esp+0h] [ebp+0h]

  v5 = a3 * (unsigned __int64)(unsigned int)(a1 / a5);
  if ( (unsigned int)&retaddr >= HIDWORD(v5) )
  {
    if ( a4 << a2 < (unsigned int)v5 )
    {
      LODWORD(v5) = &loc_80563FB;
      if ( &retaddr == (void **)HIDWORD(v5) )
        v6 = &loc_8056406;
      dword_805C1B0 = (int)v6;
      sub_8056729(a2, a4 << a2);
    }
    JUMPOUT(&loc_80562AB);
  }
  JUMPOUT(&loc_80562AB);
}
// 8056729: using guessed type int __fastcall sub_8056729(_DWORD, _DWORD);
// 805C1B0: using guessed type int dword_805C1B0;

//----- (08056498) --------------------------------------------------------
int __cdecl sub_8056498(int a1)
{
  return __cxa_atexit(a1, 0, dword_805C208);
}
// 80491F0: using guessed type int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD);
// 805C208: using guessed type int dword_805C208;

//----- (080564C7) --------------------------------------------------------
int __cdecl sub_80564C7(int a1, int a2)
{
  return __fxstat64(3, a1, a2);
}
// 8049190: using guessed type int __cdecl __fxstat64(_DWORD, _DWORD, _DWORD);

//----- (0805663B) --------------------------------------------------------
#error "8056641: positive sp value has been found (funcsize=0)"

//----- (080566B5) --------------------------------------------------------
#error "80566BB: positive sp value has been found (funcsize=0)"

//----- (08056729) --------------------------------------------------------
#error "805672F: positive sp value has been found (funcsize=0)"

//----- (080567A3) --------------------------------------------------------
#error "80567A9: positive sp value has been found (funcsize=0)"

//----- (0805681B) --------------------------------------------------------
#error "8056821: positive sp value has been found (funcsize=0)"

//----- (08056887) --------------------------------------------------------
#error "805688D: positive sp value has been found (funcsize=0)"

//----- (080568F3) --------------------------------------------------------
#error "80568F9: positive sp value has been found (funcsize=0)"

//----- (08056910) --------------------------------------------------------
int (**sub_8056910())()
{
  int (**result)(); // eax
  int v1; // esi
  int v2; // edi

  init_proc();
  result = off_805BEE0;
  v1 = &off_805BEE4 - off_805BEE0;
  if ( v1 )
  {
    v2 = 0;
    do
      result = (int (**)())off_805BEE0[v2++]();
    while ( v1 != v2 );
  }
  return result;
}
// 805BEE0: using guessed type int (*off_805BEE0[2])();
// 805BEE4: using guessed type int (*off_805BEE4)();

//----- (08056974) --------------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 61 decompilation failure(s) on 168 function(s)"
