/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
int sub_8048C20();
// int __cdecl freopen64(_DWORD, _DWORD, _DWORD); weak
// int dup2(int fd, int fd2);
// int strcmp(const char *s1, const char *s2);
// int __cdecl open64(_DWORD, _DWORD); weak
// int printf(const char *format, ...);
// int fflush(FILE *stream);
// void _exit(int status);
// void free(void *ptr);
// void *memcpy(void *dest, const void *src, size_t n);
// int fclose(FILE *stream);
// int getc_unlocked(FILE *stream);
// int __cdecl fseeko64(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int ferror_unlocked(FILE *stream);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// size_t __ctype_get_mb_cur_max(void);
// size_t __fpending(FILE *fp);
// size_t mbrtowc(wchar_t *pwc, const char *s, size_t n, mbstate_t *p);
// int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD); weak
// void error(int status, int errnum, const char *format, ...);
// char *getenv(const char *name);
// void *realloc(void *ptr, size_t size);
// void *malloc(size_t size);
// int puts(const char *s);
// int __freading(FILE *fp);
// void exit(int status);
// char *gettext(const char *msgid);
// FILE *fdopen(int fd, const char *modes);
// int __cdecl fputs_unlocked(_DWORD, _DWORD); weak
// int getopt_long(int argc, char *const *argv, const char *shortopts, const struct option *longopts, int *longind);
// size_t strlen(const char *s);
// int fprintf(FILE *stream, const char *format, ...);
// void *memset(void *s, int c, size_t n);
// int *__errno_location(void);
// int fileno(FILE *stream);
// char *nl_langinfo(nl_item item);
// char *setlocale(int category, const char *locale);
// int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __cdecl posix_fadvise64(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int strncmp(const char *s1, const char *s2, size_t n);
// void abort(void);
// int close(int fd);
// void __assert_fail(const char *assertion, const char *file, unsigned int line, const char *function);
// int _gmon_start__(void); weak
void sub_8048FE3();
void sub_8049000();
int sub_8049010();
int sub_8049080();
int sub_80490A0();
void sub_80490FF();
void sub_804911A();
int sub_804912A();
void sub_804920C();
void sub_8049227();
int sub_8049237();
void sub_8049319();
void sub_8049334();
signed int sub_8049344();
void sub_8049426();
void sub_8049441();
int sub_8049451();
// int __usercall sub_80494FC@<eax>(int (__cdecl *a1)(void *)@<eax>);
// int __usercall sub_804954A@<eax>(int a1@<eax>, int (__cdecl *a2)(void *, int)@<edx>);
void sub_80495E1();
void sub_80495FC();
int sub_804960C();
void sub_8049812();
void sub_804982D();
int sub_804983D();
int sub_80498F3();
int __cdecl sub_804991E(char *s1); // idb
void __cdecl __noreturn sub_8049AA4(int status); // idb
_DWORD *__cdecl sub_8049B72(char *s);
const char **__cdecl sub_8049C7A(int a1, char *s1);
int __cdecl sub_804A0ED(int a1, int a2);
int sub_804A14A();
int __cdecl sub_804A162(_DWORD *a1);
int __cdecl sub_804A1A6(int a1);
int __cdecl sub_804A36F(int a1);
int sub_804A411(); // weak
int __cdecl sub_804A552(int a1);
int __cdecl sub_804A579(char *s1); // idb
void __cdecl __noreturn main(int a1, char **a2);
int sub_804AA7F();
int __cdecl sub_804AB63(int a1, int a2, int a3, int a4, int a5, int a6);
void __cdecl sub_804ABB4(FILE *stream, int a2);
signed int __cdecl sub_804ABFC(int a1);
FILE *__cdecl sub_804AC4C(int a1, int a2, FILE *stream);
int sub_804ADA6(int argc, char **argv, int a3, int a4, int a5, int a6, ...);
void __cdecl __noreturn sub_804AE67(int a1);
int __cdecl sub_804AEB6(int c, size_t n); // idb
int __cdecl sub_804AFCC(int *a1, unsigned __int8 a2, char a3);
int *__cdecl sub_804B076(int *a1, int a2, int a3);
// _DWORD *__userpurge sub_804B0B7@<eax>(_DWORD *a1, int a2);
const char *__cdecl sub_804B13A(char *msgid, int a2);
void __cdecl sub_804B1D5(int a1, int a2, int a3, int a4, unsigned int a5, int a6, int a7, int a8, int a9);
void sub_804B5B9();
void *__cdecl sub_804C0C5(int a1, int a2, _DWORD *a3, int *a4);
void *__cdecl sub_804C26C(signed int a1, int a2, int a3, unsigned int *a4);
void *__cdecl sub_804C496(signed int a1, int a2);
void *__cdecl sub_804C4C0(signed int a1, int a2, int a3);
void *__cdecl sub_804C526(signed int a1, int a2, int a3);
void *__cdecl sub_804C564(signed int a1, int a2, int a3, int a4);
void *__cdecl sub_804C5EC(int a1, int a2, unsigned __int8 a3);
void *__cdecl sub_804C696(int a1, unsigned __int8 a2);
void *__cdecl sub_804C6BF(int a1);
void *__cdecl sub_804C6FC(signed int a1, int a2, int a3);
void *__cdecl sub_804C79D(signed int a1, int a2, int a3, int a4);
void *__cdecl sub_804C7CD(signed int a1, int a2, int a3, int a4, int a5);
void *__cdecl sub_804C8C7(signed int a1, int a2, int a3);
void *__cdecl sub_804C912(signed int a1, int a2);
void *__cdecl sub_804C934(int a1);
_DWORD *__cdecl sub_804C94F(_DWORD *a1);
bool __cdecl sub_804C967(unsigned int a1, int a2);
int __cdecl sub_804C994(unsigned int a1, int a2);
unsigned int __cdecl sub_804C9D9(FILE *stream, int a2, int a3, int a4);
int __cdecl sub_804CD5D(FILE *stream, int, int, int, int, int); // idb
int __cdecl sub_804D2C2(FILE *stream, int, int, int, int); // idb
void *__cdecl sub_804D3C8(unsigned int a1, unsigned int a2);
void *__cdecl sub_804D3F7(void *ptr, int a2, int a3);
void *__cdecl sub_804D42D(void *ptr, int a2, int a3);
void *__cdecl sub_804D4C7(size_t size);
void *__cdecl sub_804D4DA(size_t size);
void *__cdecl sub_804D504(void *ptr, size_t size);
void *__cdecl sub_804D5DE(void *src, size_t n);
void *__cdecl sub_804D607(char *s);
void __noreturn sub_804D62C();
int __cdecl sub_804D665(FILE *stream); // idb
int __cdecl sub_804D728(FILE *stream); // idb
int __cdecl sub_804D761(FILE *fp); // idb
int __cdecl sub_804D7A1(FILE *stream, int, int, int); // idb
size_t __cdecl sub_804D90A(wchar_t *pwc, char *s, size_t n, mbstate_t *p);
int __cdecl sub_804D97C(unsigned __int8 *a1, unsigned __int8 *a2);
int __cdecl sub_804D9E2(FILE *fp); // idb
int __cdecl sub_804DA7D(int category); // idb
void *sub_804DADB();
const char *sub_804E03C();
int __cdecl sub_804E337(int a1);
int __cdecl sub_804E3D7(int a1);
int sub_804E634(void); // weak
int sub_804E6C7(void); // weak
int (**sub_804E6E0())();
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN locret_8049460; // weak
_UNKNOWN loc_8049C28; // weak
_UNKNOWN loc_8049C32; // weak
_UNKNOWN loc_8049E69; // weak
_UNKNOWN loc_8049F01; // weak
_UNKNOWN loc_8049F30; // weak
_UNKNOWN loc_8049F58; // weak
_UNKNOWN loc_8049F71; // weak
_UNKNOWN loc_804A0D4; // weak
_UNKNOWN loc_804A0E0; // weak
_UNKNOWN loc_804A335; // weak
_UNKNOWN locret_804A36D; // weak
_UNKNOWN loc_804A42B; // weak
_UNKNOWN loc_804AE8C; // weak
_UNKNOWN loc_804B5D0; // weak
_UNKNOWN loc_804B6A7; // weak
_UNKNOWN loc_804D877; // weak
_UNKNOWN loc_804D8E8; // weak
_UNKNOWN loc_804DA40; // weak
_UNKNOWN loc_804DA58; // weak
_UNKNOWN loc_804DD7F; // weak
_UNKNOWN loc_804DD9C; // weak
_UNKNOWN unk_804E8F7; // weak
struct option longopts = { "help", 0, NULL, 104 }; // idb
_UNKNOWN unk_804ECD6; // weak
_UNKNOWN unk_804ECDA; // weak
_UNKNOWN unk_804ECE6; // weak
_UNKNOWN unk_804ECEA; // weak
_UNKNOWN unk_804ECED; // weak
_DWORD off_804ECF4[11] =
{
  134525866,
  134525790,
  134525809,
  134525786,
  134525794,
  134525554,
  134525543,
  134525611,
  134525624,
  134525624,
  134525624
}; // idb
void *off_804F27C = &loc_804CE16; // weak
_UNKNOWN unk_804F40B; // weak
int (*off_8051EF0[2])() = { &sub_80490A0, &sub_8049080 }; // weak
int (*off_8051EF4)() = &sub_8049080; // weak
int (*dword_8052008)(void) = NULL; // weak
int dword_80520F4 = 0; // weak
int dword_8052108 = 0; // weak
int dword_8052124 = 0; // weak
int (*dword_8052128)(void) = NULL; // weak
int dword_805214C = 0; // weak
int status = 1; // idb
int dword_8052168 = 1; // weak
int dword_805216C = 256; // weak
void *off_8052170 = &unk_805244E; // weak
int *off_8052174 = &dword_805216C; // weak
_UNKNOWN unk_8052188; // weak
_UNKNOWN unk_80521A4; // weak
_UNKNOWN unk_80521A7; // weak
_UNKNOWN unk_80521AC; // weak
_UNKNOWN unk_80521AF; // weak
_UNKNOWN unk_80521B8; // weak
_UNKNOWN unk_80521BB; // weak
FILE *stderr; // idb
int optind; // weak
FILE *stdin; // idb
FILE *stdout; // idb
int opterr; // weak
char byte_805220C; // weak
int dword_80523DE; // weak
int dword_80523E2; // weak
int dword_80523E6; // weak
int dword_80523EA; // weak
int dword_80523EE; // weak
char byte_80523F2; // weak
int dword_80523F6; // weak
int dword_805240E; // weak
int dword_8052412; // weak
int dword_8052416; // weak
int dword_805241A; // weak
int dword_805241E; // weak
int dword_8052422; // weak
int dword_8052426; // weak
int dword_805242A; // weak
int dword_805242E; // weak
int dword_8052432; // weak
int dword_8052436; // weak
int dword_805243A; // weak
_UNKNOWN unk_805244E; // weak
int dword_805254E; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (08048BF4) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 8048FA0: using guessed type int _gmon_start__(void);

//----- (08048C20) --------------------------------------------------------
int sub_8048C20()
{
  return dword_8052008();
}
// 8052008: using guessed type int (*dword_8052008)(void);

//----- (08048FB0) --------------------------------------------------------
#error "8048FB3: positive sp value has been found (funcsize=2)"

//----- (08048FE3) --------------------------------------------------------
void sub_8048FE3()
{
  ;
}

//----- (08049000) --------------------------------------------------------
void sub_8049000()
{
  ;
}

//----- (08049010) --------------------------------------------------------
int sub_8049010()
{
  int result; // eax

  result = &unk_80521BB - &unk_80521B8;
  if ( (unsigned int)(&unk_80521BB - &unk_80521B8) > 6 )
    result = 0;
  return result;
}
// 8049010: could not find valid save-restore pair for ebp

//----- (08049080) --------------------------------------------------------
int sub_8049080()
{
  int result; // eax

  if ( !byte_805220C )
  {
    result = sub_8049010();
    byte_805220C = 1;
  }
  return result;
}
// 8049080: could not find valid save-restore pair for ebp
// 805220C: using guessed type char byte_805220C;

//----- (080490A0) --------------------------------------------------------
int sub_80490A0()
{
  return 0;
}
// 80490A0: could not find valid save-restore pair for ebp

//----- (080490FF) --------------------------------------------------------
void sub_80490FF()
{
  ;
}

//----- (0804911A) --------------------------------------------------------
void sub_804911A()
{
  ;
}

//----- (0804912A) --------------------------------------------------------
int sub_804912A()
{
  int result; // eax

  result = &unk_80521A7 - &unk_80521A4;
  if ( (unsigned int)(&unk_80521A7 - &unk_80521A4) > 6 )
    result = 0;
  return result;
}
// 804912A: could not find valid save-restore pair for ebp

//----- (0804920C) --------------------------------------------------------
void sub_804920C()
{
  ;
}

//----- (08049227) --------------------------------------------------------
void sub_8049227()
{
  ;
}

//----- (08049237) --------------------------------------------------------
int sub_8049237()
{
  int result; // eax

  result = &unk_80521A7 - &unk_80521A4;
  if ( (unsigned int)(&unk_80521A7 - &unk_80521A4) > 6 )
    result = 0;
  return result;
}
// 8049237: could not find valid save-restore pair for ebp

//----- (08049319) --------------------------------------------------------
void sub_8049319()
{
  ;
}

//----- (08049334) --------------------------------------------------------
void sub_8049334()
{
  ;
}

//----- (08049344) --------------------------------------------------------
signed int sub_8049344()
{
  return 3;
}
// 8049344: could not find valid save-restore pair for ebp

//----- (08049426) --------------------------------------------------------
void sub_8049426()
{
  ;
}

//----- (08049441) --------------------------------------------------------
void sub_8049441()
{
  ;
}

//----- (08049451) --------------------------------------------------------
int sub_8049451()
{
  int result; // eax

  result = &unk_80521A7 - &unk_80521A4;
  if ( (unsigned int)(&unk_80521A7 - &unk_80521A4) > 6 )
  {
    dword_8052128 = (int (*)(void))&locret_8049460;
    dword_8052124 = (int)sub_80494FC;
    result = ((int (*)(void))locret_8049460)();
  }
  return result;
}
// 8052124: using guessed type int dword_8052124;
// 8052128: using guessed type int (*dword_8052128)(void);

//----- (080494FC) --------------------------------------------------------
int __usercall sub_80494FC@<eax>(int (__cdecl *a1)(void *)@<eax>)
{
  return a1(&unk_80521A4);
}

//----- (0804954A) --------------------------------------------------------
int __usercall sub_804954A@<eax>(int a1@<eax>, int (__cdecl *a2)(void *, int)@<edx>)
{
  return a2(&unk_80521A4, a1);
}

//----- (080495E1) --------------------------------------------------------
void sub_80495E1()
{
  ;
}

//----- (080495FC) --------------------------------------------------------
void sub_80495FC()
{
  ;
}

//----- (0804960C) --------------------------------------------------------
int sub_804960C()
{
  int result; // eax

  result = &unk_80521AF - &unk_80521AC;
  _CF = (unsigned int)(&unk_80521AF - &unk_80521AC) < 6;
  _OF = __OFSUB__(&unk_80521AF - &unk_80521AC, 6);
  _ZF = &unk_80521AF - &unk_80521AC == 6;
  _SF = &unk_80521AF - &unk_80521AC - 6 < 0;
  if ( (unsigned int)(&unk_80521AF - &unk_80521AC) > 6 )
  {
    __asm { pushfw }
    result = 0;
    __asm { popfw }
  }
  return result;
}
// 804960C: could not find valid save-restore pair for ebp

//----- (08049812) --------------------------------------------------------
void sub_8049812()
{
  ;
}

//----- (0804982D) --------------------------------------------------------
void sub_804982D()
{
  ;
}

//----- (0804983D) --------------------------------------------------------
int sub_804983D()
{
  int result; // eax

  result = &unk_80521A7 - &unk_80521A4;
  _CF = (unsigned int)(&unk_80521A7 - &unk_80521A4) < 6;
  _OF = __OFSUB__(&unk_80521A7 - &unk_80521A4, 6);
  _ZF = &unk_80521A7 - &unk_80521A4 == 6;
  _SF = &unk_80521A7 - &unk_80521A4 - 6 < 0;
  if ( (unsigned int)(&unk_80521A7 - &unk_80521A4) > 6 )
  {
    __asm { pushfw }
    result = 0;
    __asm { popfw }
  }
  return result;
}
// 804983D: could not find valid save-restore pair for ebp

//----- (080498F3) --------------------------------------------------------
int sub_80498F3()
{
  FILE *v0; // ebx
  char *v1; // eax

  v0 = stdout;
  v1 = gettext("\nWith no FILE, or when FILE is -, read standard input.\n");
  return fputs_unlocked(v1, v0);
}
// 8048E40: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);

//----- (0804991E) --------------------------------------------------------
int __cdecl sub_804991E(char *s1)
{
  char *v1; // eax
  char *v2; // eax
  char *v3; // eax
  const char *v4; // ebx
  char *v5; // eax
  char *v7; // [esp+1Ch] [ebp-4Ch]
  const char **i; // [esp+20h] [ebp-48h]
  const char *v9; // [esp+24h] [ebp-44h]
  const char *v10; // [esp+28h] [ebp-40h]
  const char *v11; // [esp+2Ch] [ebp-3Ch]
  const char *v12; // [esp+30h] [ebp-38h]
  const char *v13; // [esp+34h] [ebp-34h]
  const char *v14; // [esp+38h] [ebp-30h]
  const char *v15; // [esp+3Ch] [ebp-2Ch]
  const char *v16; // [esp+40h] [ebp-28h]
  const char *v17; // [esp+44h] [ebp-24h]
  const char *v18; // [esp+48h] [ebp-20h]
  const char *v19; // [esp+4Ch] [ebp-1Ch]
  const char *v20; // [esp+50h] [ebp-18h]
  const char *v21; // [esp+54h] [ebp-14h]
  int v22; // [esp+58h] [ebp-10h]
  int v23; // [esp+5Ch] [ebp-Ch]

  v10 = "[";
  v11 = "test invocation";
  v12 = "coreutils";
  v13 = "Multi-call invocation";
  v14 = "sha224sum";
  v15 = "sha2 utilities";
  v16 = "sha256sum";
  v17 = "sha2 utilities";
  v18 = "sha384sum";
  v19 = "sha2 utilities";
  v20 = "sha512sum";
  v21 = "sha2 utilities";
  v22 = 0;
  v23 = 0;
  v7 = s1;
  for ( i = &v10; *i && strcmp(s1, *i); i += 2 )
    ;
  if ( i[1] )
    v7 = (char *)i[1];
  v1 = gettext("\n%s online help: <%s>\n");
  printf(v1, "GNU coreutils", "http://www.gnu.org/software/coreutils/");
  v9 = setlocale(5, 0);
  if ( v9 && strncmp(v9, "en_", 3u) )
  {
    v2 = gettext("Report %s translation bugs to <http://translationproject.org/team/>\n");
    printf(v2, s1);
  }
  v3 = gettext("Full documentation at: <%s%s>\n");
  printf(v3, "http://www.gnu.org/software/coreutils/", s1);
  if ( v7 == s1 )
    v4 = " invocation";
  else
    v4 = (const char *)&unk_804E8F7;
  v5 = gettext("or available locally via: info '(coreutils) %s%s'\n");
  return printf(v5, v7, v4);
}

//----- (08049AA4) --------------------------------------------------------
void __cdecl __noreturn sub_8049AA4(int status)
{
  int v1; // ebx
  char *v2; // ST04_4
  int v3; // ebx
  char *v4; // eax
  FILE *v5; // ebx
  char *v6; // eax
  FILE *v7; // ebx
  char *v8; // eax
  FILE *v9; // ebx
  char *v10; // eax

  if ( status )
  {
    v1 = dword_80523F6;
    v2 = gettext("Try '%s --help' for more information.\n");
    fprintf(stderr, v2, v1);
  }
  else
  {
    v3 = dword_80523F6;
    v4 = gettext("Usage: %s [OPTION] [FILE]\nWrite totally ordered list consistent with the partial ordering in FILE.\n");
    printf(v4, v3);
    sub_80498F3();
    v5 = stdout;
    v6 = gettext("\n");
    fputs_unlocked(v6, v5);
    v7 = stdout;
    v8 = gettext("      --help     display this help and exit\n");
    fputs_unlocked(v8, v7);
    v9 = stdout;
    v10 = gettext("      --version  output version information and exit\n");
    fputs_unlocked(v10, v9);
    sub_804991E("tsort");
  }
  exit(status);
}
// 8048E40: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);
// 80523F6: using guessed type int dword_80523F6;

//----- (08049B72) --------------------------------------------------------
_DWORD *__cdecl sub_8049B72(char *s)
{
  _DWORD *result; // eax
  _DWORD *v2; // [esp+1Ch] [ebp-Ch]

  v2 = sub_804D4DA(0x1Cu);
  if ( s )
  {
    sub_804D607(s);
    dword_8052128 = (int (*)(void))&loc_8049C32;
    dword_8052124 = (int)&loc_8049C28;
    result = (_DWORD *)((int (*)(void))loc_8049C32)();
  }
  else
  {
    *v2 = 0;
    v2[2] = 0;
    v2[1] = v2[2];
    v2[3] = 0;
    v2[4] = 0;
    v2[5] = 0;
    v2[6] = 0;
    result = v2;
  }
  return result;
}
// 8052124: using guessed type int dword_8052124;
// 8052128: using guessed type int (*dword_8052128)(void);

//----- (08049C7A) --------------------------------------------------------
const char **__cdecl sub_8049C7A(int a1, char *s1)
{
  const char **result; // eax
  void *v3; // eax
  void *v4; // eax
  void *v5; // eax
  const char **v6; // [esp+18h] [ebp-20h]
  const char **v7; // [esp+1Ch] [ebp-1Ch]
  const char **v8; // [esp+20h] [ebp-18h]
  const char **v9; // [esp+24h] [ebp-14h]
  const char **v10; // [esp+28h] [ebp-10h]
  int v11; // [esp+2Ch] [ebp-Ch]

  if ( !a1 )
    __assert_fail("root", "src/tsort.c", 0x85u, "search_item");
  if ( *(_DWORD *)(a1 + 8) )
  {
    v10 = (const char **)a1;
    v6 = *(const char ***)(a1 + 8);
    v9 = v6;
    while ( 1 )
    {
      v11 = strcmp(s1, *v6);
      if ( !v11 )
        return v6;
      v7 = (const char **)(v11 >= 0 ? v6[2] : v6[1]);
      if ( !v7 )
        break;
      v5 = &loc_804A0D4;
      if ( !v7[3] )
        v5 = &loc_804A0E0;
      dword_8052108 = (int)v5;
      sub_804E634();
      v10 = v6;
      v9 = v7;
      v6 = v7;
    }
    v7 = (const char **)sub_8049B72(s1);
    if ( v11 >= 0 )
      v6[2] = (const char *)v7;
    else
      v6[1] = (const char *)v7;
    if ( !strcmp(s1, *v9) )
      __assert_fail("!STREQ (str, s->str)", "src/tsort.c", 0xA9u, "search_item");
    if ( strcmp(s1, *v9) >= 0 )
    {
      v6 = (const char **)v9[2];
      v8 = v6;
      v11 = 1;
      while ( v6 != v7 )
      {
        if ( !strcmp(s1, *v6) )
          __assert_fail("!STREQ (str, p->str)", "src/tsort.c", 0xB7u, "search_item");
        if ( strcmp(s1, *v6) >= 0 )
        {
          v6[3] = (const char *)1;
          v6 = (const char **)v6[2];
        }
        else
        {
          v6[3] = (const char *)-1;
          v6 = (const char **)v6[1];
        }
      }
      v3 = &loc_8049F30;
      if ( !v9[3] )
        v3 = &loc_8049F58;
      dword_80520F4 = (int)v3;
      sub_804E6C7();
      v4 = &loc_8049F58;
      if ( v9[3] != (const char *)-v11 )
        v4 = &loc_8049F71;
      dword_80520F4 = (int)v4;
      sub_804E6C7();
      v9[3] += v11;
      result = v7;
    }
    else
    {
      v6 = (const char **)v9[1];
      v8 = v6;
      v11 = -1;
      dword_8052128 = (int (*)(void))&loc_8049F01;
      dword_8052124 = (int)&loc_8049E69;
      result = (const char **)((int (*)(void))loc_8049F01)();
    }
  }
  else
  {
    *(_DWORD *)(a1 + 8) = sub_8049B72(s1);
    result = *(const char ***)(a1 + 8);
  }
  return result;
}
// 8049C7A: could not find valid save-restore pair for ebx
// 804E634: using guessed type int sub_804E634(void);
// 804E6C7: using guessed type int sub_804E6C7(void);
// 80520F4: using guessed type int dword_80520F4;
// 8052108: using guessed type int dword_8052108;
// 8052124: using guessed type int dword_8052124;
// 8052128: using guessed type int (*dword_8052128)(void);

//----- (0804A0ED) --------------------------------------------------------
int __cdecl sub_804A0ED(int a1, int a2)
{
  int result; // eax
  _DWORD *v3; // eax
  _DWORD *v4; // ST1C_4

  result = strcmp(*(const char **)a1, *(const char **)a2);
  if ( result )
  {
    ++*(_DWORD *)(a2 + 16);
    v3 = sub_804D4DA(8u);
    v4 = v3;
    *v3 = a2;
    v3[1] = *(_DWORD *)(a1 + 24);
    result = a1;
    *(_DWORD *)(a1 + 24) = v4;
  }
  return result;
}

//----- (0804A14A) --------------------------------------------------------
int sub_804A14A()
{
  int result; // eax

  _CF = __CFADD__(dword_80523EA, 1);
  _OF = __OFADD__(1, dword_80523EA);
  _ZF = dword_80523EA == -1;
  _SF = dword_80523EA++ + 1 < 0;
  __asm { pushfw }
  result = 0;
  __asm { popfw }
  return result;
}
// 80523EA: using guessed type int dword_80523EA;

//----- (0804A162) --------------------------------------------------------
int __cdecl sub_804A162(_DWORD *a1)
{
  int v1; // eax
  int result; // eax

  v1 = a1[4];
  _ZF = v1 == 0;
  _SF = v1 < 0;
  if ( !v1 )
  {
    _ZF = *a1 == 0;
    _SF = *a1 < 0;
    if ( *a1 )
    {
      _ZF = dword_80523DE == 0;
      _SF = dword_80523DE < 0;
      if ( dword_80523DE )
        *(_DWORD *)(dword_80523E2 + 20) = a1;
      else
        dword_80523DE = (int)a1;
      dword_80523E2 = (int)a1;
    }
  }
  __asm { pushfw }
  result = 0;
  __asm { popfw }
  return result;
}
// 80523DE: using guessed type int dword_80523DE;
// 80523E2: using guessed type int dword_80523E2;

//----- (0804A1A6) --------------------------------------------------------
int __cdecl sub_804A1A6(int a1)
{
  int v1; // eax
  int v4; // eax
  int result; // eax
  int v8; // [esp+Ch] [ebp-1Ch]
  int i; // [esp+14h] [ebp-14h]
  int v10; // [esp+18h] [ebp-10h]
  int v11; // [esp+1Ch] [ebp-Ch]

  v1 = *(_DWORD *)(a1 + 16);
  _ZF = v1 == 0;
  _SF = v1 < 0;
  if ( v1 )
  {
    _ZF = dword_80523E6 == 0;
    _SF = dword_80523E6 < 0;
    if ( dword_80523E6 )
    {
      for ( i = a1 + 24; ; i = *(_DWORD *)i + 4 )
      {
        _ZF = *(_DWORD *)i == 0;
        _SF = *(_DWORD *)i < 0;
        if ( !*(_DWORD *)i )
          break;
        if ( **(_DWORD **)i == dword_80523E6 )
        {
          v4 = *(_DWORD *)(a1 + 20);
          _ZF = v4 == 0;
          _SF = v4 < 0;
          if ( !v4 )
          {
            *(_DWORD *)(a1 + 20) = dword_80523E6;
            dword_80523E6 = a1;
            break;
          }
          while ( dword_80523E6 )
          {
            v10 = *(_DWORD *)(dword_80523E6 + 20);
            v8 = *(_DWORD *)dword_80523E6;
            error(0, 0, "%s", v8);
            if ( dword_80523E6 == a1 )
            {
              --*(_DWORD *)(**(_DWORD **)i + 16);
              *(_DWORD *)i = *(_DWORD *)(*(_DWORD *)i + 4);
              break;
            }
            *(_DWORD *)(dword_80523E6 + 20) = 0;
            dword_80523E6 = v10;
          }
          while ( dword_80523E6 )
          {
            v11 = *(_DWORD *)(dword_80523E6 + 20);
            *(_DWORD *)(dword_80523E6 + 20) = 0;
            dword_80523E6 = v11;
          }
          dword_8052128 = (int (*)(void))&locret_804A36D;
          dword_8052124 = (int)&loc_804A335;
          return ((int (*)(void))locret_804A36D)();
        }
      }
    }
    else
    {
      dword_80523E6 = a1;
    }
  }
  __asm { pushfw }
  result = 0;
  __asm { popfw }
  return result;
}
// 8052124: using guessed type int dword_8052124;
// 8052128: using guessed type int (*dword_8052128)(void);
// 80523E6: using guessed type int dword_80523E6;

//----- (0804A36F) --------------------------------------------------------
int __cdecl sub_804A36F(int a1)
{
  int (*v1)(void); // eax

  v1 = (int (*)(void))sub_804A411;
  if ( *(_DWORD *)(a1 + 4) )
    v1 = (int (*)(void))&loc_804A42B;
  dword_8052128 = v1;
  dword_8052124 = (int)sub_804A411;
  return v1();
}
// 804A411: using guessed type int sub_804A411();
// 8052124: using guessed type int dword_8052124;
// 8052128: using guessed type int (*dword_8052128)(void);

//----- (0804A552) --------------------------------------------------------
int __cdecl sub_804A552(int a1)
{
  int result; // eax

  result = *(_DWORD *)(a1 + 8);
  if ( result )
    result = sub_804A36F(*(_DWORD *)(a1 + 8));
  return result;
}

//----- (0804A579) --------------------------------------------------------
int __cdecl sub_804A579(char *s1)
{
  void *v1; // ebx
  int *v2; // eax
  void *v3; // ebx
  char *v4; // eax
  void *v5; // ebx
  char *v6; // eax
  void *v7; // ebx
  int *v8; // eax
  unsigned __int8 v10; // [esp+12h] [ebp-26h]
  _BYTE v11[5]; // [esp+13h] [ebp-25h]
  const char **v12; // [esp+18h] [ebp-20h]
  _DWORD *v13; // [esp+1Ch] [ebp-1Ch]
  _DWORD *v14; // [esp+20h] [ebp-18h]
  unsigned int v15; // [esp+24h] [ebp-14h]
  int v16; // [esp+28h] [ebp-10h]
  char *v17; // [esp+2Ch] [ebp-Ch]

  v10 = 1;
  v11[4] = 0;
  v12 = 0;
  *(_DWORD *)v11 = strcmp(s1, "-") == 0;
  v14 = sub_8049B72(0);
  if ( v11[0] != 1 && !sub_804AC4C((int)s1, (int)"r", stdin) )
  {
    v1 = sub_804C6FC(0, 3, (int)s1);
    v2 = __errno_location();
    error(1, *v2, "%s", v1);
  }
  sub_804ABB4(stdin, 2);
  sub_804C94F(&v16);
  while ( 1 )
  {
    v15 = sub_804C9D9(stdin, (int)" \t\n", 3, (int)&v16);
    if ( v15 == -1 )
      break;
    if ( !v15 )
      __assert_fail("len != 0", "src/tsort.c", 0x1CEu, "tsort");
    v12 = sub_8049C7A((int)v14, v17);
    if ( *(_DWORD *)&v11[1] )
    {
      sub_804A0ED(*(int *)&v11[1], (int)v12);
      v12 = 0;
    }
    *(_DWORD *)&v11[1] = v12;
  }
  if ( v12 )
  {
    v3 = sub_804C6FC(0, 3, (int)s1);
    v4 = gettext("%s: input contains an odd number of tokens");
    error(1, 0, v4, v3);
  }
  sub_804A552((int)v14);
  while ( dword_80523EA )
  {
    sub_804A552((int)v14);
    while ( dword_80523DE )
    {
      v13 = *(_DWORD **)(dword_80523DE + 24);
      puts(*(const char **)dword_80523DE);
      *(_DWORD *)dword_80523DE = 0;
      --dword_80523EA;
      while ( v13 )
      {
        if ( !--*(_DWORD *)(*v13 + 16) )
        {
          *(_DWORD *)(dword_80523E2 + 20) = *v13;
          dword_80523E2 = *v13;
        }
        v13 = (_DWORD *)v13[1];
      }
      dword_80523DE = *(_DWORD *)(dword_80523DE + 20);
    }
    if ( dword_80523EA )
    {
      v5 = sub_804C6FC(0, 3, (int)s1);
      v6 = gettext("%s: input contains a loop:");
      error(0, 0, v6, v5);
      v10 = 0;
      do
        sub_804A552((int)v14);
      while ( dword_80523E6 );
    }
  }
  if ( sub_804D665(stdin) )
  {
    if ( v11[0] )
      v7 = gettext("standard input");
    else
      v7 = sub_804C6FC(0, 3, (int)s1);
    v8 = __errno_location();
    error(1, *v8, "%s", v7);
  }
  return v10;
}
// 80523DE: using guessed type int dword_80523DE;
// 80523E2: using guessed type int dword_80523E2;
// 80523E6: using guessed type int dword_80523E6;
// 80523EA: using guessed type int dword_80523EA;

//----- (0804A8D8) --------------------------------------------------------
void __cdecl __noreturn main(int a1, char **a2)
{
  sub_804AE67((int)*a2);
}

//----- (0804AA7F) --------------------------------------------------------
int sub_804AA7F()
{
  void *v0; // ebx
  int *v1; // eax
  int *v2; // eax
  int result; // eax
  char *v4; // [esp+2Ch] [ebp-Ch]

  if ( sub_804D9E2(stdout) && (byte_80523F2 != 1 || *__errno_location() != 32) )
  {
    v4 = gettext("write error");
    if ( dword_80523EE )
    {
      v0 = sub_804C6BF(dword_80523EE);
      v1 = __errno_location();
      error(0, *v1, "%s: %s", v0, v4);
    }
    else
    {
      v2 = __errno_location();
      error(0, *v2, "%s", v4);
    }
    _exit(status);
  }
  result = sub_804D9E2(stderr);
  if ( result )
    _exit(status);
  return result;
}
// 80523EE: using guessed type int dword_80523EE;
// 80523F2: using guessed type char byte_80523F2;

//----- (0804AB63) --------------------------------------------------------
int __cdecl sub_804AB63(int a1, int a2, int a3, int a4, int a5, int a6)
{
  return posix_fadvise64(a1, a2, a3, a4, a5, a6);
}
// 8048F30: using guessed type int __cdecl posix_fadvise64(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804ABB4) --------------------------------------------------------
void __cdecl sub_804ABB4(FILE *stream, int a2)
{
  int v2; // eax

  if ( stream )
  {
    v2 = fileno(stream);
    sub_804AB63(v2, 0, 0, 0, 0, a2);
  }
}

//----- (0804ABFC) --------------------------------------------------------
signed int __cdecl sub_804ABFC(int a1)
{
  signed int result; // eax
  int fd; // [esp+1Ch] [ebp-Ch]

  fd = open64("/dev/null", 0);
  if ( fd == a1 )
    return 1;
  _CF = 0;
  _OF = 0;
  _ZF = fd == 0;
  _SF = fd < 0;
  if ( fd >= 0 )
  {
    close(fd);
    *__errno_location() = 9;
  }
  __asm { pushfw }
  result = 0;
  __asm { popfw }
  return result;
}
// 8048C60: using guessed type int __cdecl open64(_DWORD, _DWORD);

//----- (0804AC4C) --------------------------------------------------------
FILE *__cdecl sub_804AC4C(int a1, int a2, FILE *stream)
{
  int v3; // eax
  char v5; // [esp+19h] [ebp-Fh]
  char v6; // [esp+1Ah] [ebp-Eh]
  char v7; // [esp+1Bh] [ebp-Dh]
  int v8; // [esp+1Ch] [ebp-Ch]
  FILE *streama; // [esp+38h] [ebp+10h]

  v5 = 0;
  v6 = 0;
  v7 = 0;
  v3 = fileno(stream);
  if ( v3 != 1 )
  {
    if ( v3 != 2 )
    {
      if ( !v3 )
        goto LABEL_10;
      if ( dup2(2, 2) != 2 )
        v7 = 1;
    }
    if ( dup2(1, 1) != 1 )
      v6 = 1;
  }
  if ( dup2(0, 0) )
    v5 = 1;
LABEL_10:
  if ( v5 && (unsigned __int8)sub_804ABFC(0) ^ 1 )
  {
    streama = 0;
  }
  else if ( v6 && (unsigned __int8)sub_804ABFC(1) ^ 1 )
  {
    streama = 0;
  }
  else if ( v7 && (unsigned __int8)sub_804ABFC(2) ^ 1 )
  {
    streama = 0;
  }
  else
  {
    streama = (FILE *)freopen64(a1, a2, stream);
  }
  v8 = *__errno_location();
  if ( v7 )
    close(2);
  if ( v6 )
    close(1);
  if ( v5 )
    close(0);
  if ( !streama )
    *__errno_location() = v8;
  return streama;
}
// 8048C30: using guessed type int __cdecl freopen64(_DWORD, _DWORD, _DWORD);

//----- (0804ADA6) --------------------------------------------------------
int sub_804ADA6(int argc, char **argv, int a3, int a4, int a5, int a6, ...)
{
  int result; // eax
  int v7; // [esp+28h] [ebp-10h]
  int v8; // [esp+2Ch] [ebp-Ch]
  va_list va; // [esp+58h] [ebp+20h]

  va_start(va, a6);
  v7 = opterr;
  opterr = 0;
  if ( argc == 2 )
  {
    v8 = getopt_long(2, argv, "+", &longopts, 0);
    if ( v8 != -1 )
    {
      if ( v8 == 104 )
      {
        ((void (__cdecl *)(_DWORD))a6)(0);
      }
      else if ( v8 == 118 )
      {
        sub_804D2C2(stdout, a3, a4, a5, (int)va);
        exit(0);
      }
    }
  }
  result = v7;
  opterr = v7;
  optind = 0;
  return result;
}
// 80521E0: using guessed type int optind;
// 8052208: using guessed type int opterr;

//----- (0804AE67) --------------------------------------------------------
void __cdecl __noreturn sub_804AE67(int a1)
{
  int (__cdecl *v1)(int, size_t); // eax

  v1 = (int (__cdecl *)(int, size_t))&loc_804AE8C;
  if ( a1 )
    v1 = sub_804AEB6;
  dword_8052108 = (int)v1;
  sub_804E634();
  fwrite("A NULL argv[0] was passed through an exec system call.\n", 1u, 0x37u, stderr);
  abort();
}
// 804E634: using guessed type int sub_804E634(void);
// 8052108: using guessed type int dword_8052108;

//----- (0804AEB6) --------------------------------------------------------
#error "804AF58: positive sp value has been found (funcsize=0)"

//----- (0804AFCC) --------------------------------------------------------
int __cdecl sub_804AFCC(int *a1, unsigned __int8 a2, char a3)
{
  int *v3; // eax
  int v4; // ST10_4

  if ( a1 )
    v3 = a1;
  else
    v3 = &dword_805240E;
  v4 = ((unsigned int)v3[(a2 >> 5) + 2] >> (a2 & 0x1F)) & 1;
  v3[(a2 >> 5) + 2] ^= (v4 ^ a3 & 1) << (a2 & 0x1F);
  return v4;
}
// 805240E: using guessed type int dword_805240E;

//----- (0804B076) --------------------------------------------------------
int *__cdecl sub_804B076(int *a1, int a2, int a3)
{
  int *result; // eax

  if ( !a1 )
    a1 = &dword_805240E;
  *a1 = 10;
  if ( !a2 || !a3 )
    abort();
  a1[10] = a2;
  result = a1;
  a1[11] = a3;
  return result;
}
// 805240E: using guessed type int dword_805240E;

//----- (0804B0B7) --------------------------------------------------------
_DWORD *__userpurge sub_804B0B7@<eax>(_DWORD *a1, int a2)
{
  int v3; // [esp+0h] [ebp-38h]
  int v4; // [esp+4h] [ebp-34h]
  int v5; // [esp+8h] [ebp-30h]
  int v6; // [esp+Ch] [ebp-2Ch]
  int v7; // [esp+10h] [ebp-28h]
  int v8; // [esp+14h] [ebp-24h]
  int v9; // [esp+18h] [ebp-20h]
  int v10; // [esp+1Ch] [ebp-1Ch]
  int v11; // [esp+20h] [ebp-18h]
  int v12; // [esp+24h] [ebp-14h]
  int v13; // [esp+28h] [ebp-10h]
  int v14; // [esp+2Ch] [ebp-Ch]

  memset(&v3, 0, 0x30u);
  if ( a2 == 10 )
    abort();
  *a1 = a2;
  a1[1] = v4;
  a1[2] = v5;
  a1[3] = v6;
  a1[4] = v7;
  a1[5] = v8;
  a1[6] = v9;
  a1[7] = v10;
  a1[8] = v11;
  a1[9] = v12;
  a1[10] = v13;
  a1[11] = v14;
  return a1;
}

//----- (0804B13A) --------------------------------------------------------
const char *__cdecl sub_804B13A(char *msgid, int a2)
{
  const char *result; // eax
  char *v3; // [esp+18h] [ebp-10h]
  unsigned __int8 *v4; // [esp+1Ch] [ebp-Ch]

  v3 = gettext(msgid);
  if ( v3 != msgid )
    return v3;
  v4 = (unsigned __int8 *)sub_804E03C();
  if ( sub_804D97C(v4, "UTF-8") )
  {
    if ( sub_804D97C(v4, "GB18030") )
    {
      if ( a2 == 9 )
        result = (const char *)&unk_804ECED;
      else
        result = "'";
    }
    else if ( *msgid == 96 )
    {
      result = (const char *)&unk_804ECE6;
    }
    else
    {
      result = (const char *)&unk_804ECEA;
    }
  }
  else if ( *msgid == 96 )
  {
    result = (const char *)&unk_804ECD6;
  }
  else
  {
    result = (const char *)&unk_804ECDA;
  }
  return result;
}

//----- (0804B1D5) --------------------------------------------------------
void __cdecl sub_804B1D5(int a1, int a2, int a3, int a4, unsigned int a5, int a6, int a7, int a8, int a9)
{
  bool v9; // ST53_1

  v9 = __ctype_get_mb_cur_max() == 1;
  if ( a5 <= 0xA )
    JUMPOUT(__CS__, off_804ECF4[a5]);
  abort();
}

//----- (0804B5B9) --------------------------------------------------------
void sub_804B5B9()
{
  dword_80520F4 = (int)&loc_804B6A7;
  sub_804E6C7();
  JUMPOUT(loc_804B5D0);
}
// 804E6C7: using guessed type int sub_804E6C7(void);
// 80520F4: using guessed type int dword_80520F4;

//----- (0804C0C5) --------------------------------------------------------
void *__cdecl sub_804C0C5(int a1, int a2, _DWORD *a3, int *a4)
{
  int *v4; // eax
  int *v5; // ST3C_4
  int v6; // ST40_4
  int v7; // ST44_4
  int v8; // eax
  int size; // [esp+48h] [ebp-10h]
  void *v11; // [esp+4Ch] [ebp-Ch]

  if ( a4 )
    v4 = a4;
  else
    v4 = &dword_805240E;
  v5 = v4;
  v6 = *__errno_location();
  v7 = v5[1] | (a3 == 0);
  sub_804B1D5(0, 0, a1, a2, *v5, v7, (int)(v5 + 2), v5[10], v5[11]);
  size = v8 + 1;
  v11 = sub_804D4C7(v8 + 1);
  sub_804B1D5((int)v11, size, a1, a2, *v5, v7, (int)(v5 + 2), v5[10], v5[11]);
  *__errno_location() = v6;
  if ( a3 )
    *a3 = size - 1;
  return v11;
}
// 805240E: using guessed type int dword_805240E;

//----- (0804C26C) --------------------------------------------------------
void *__cdecl sub_804C26C(signed int a1, int a2, int a3, unsigned int *a4)
{
  int *v8; // eax
  void *v9; // edx
  size_t v10; // ST48_4
  size_t v11; // eax
  bool v13; // [esp+37h] [ebp-21h]
  int *v14; // [esp+38h] [ebp-20h]
  void *ptr; // [esp+3Ch] [ebp-1Ch]
  int v16; // [esp+40h] [ebp-18h]
  int size; // [esp+44h] [ebp-14h]
  int v18; // [esp+48h] [ebp-10h]

  v16 = *__errno_location();
  v14 = off_8052174;
  if ( a1 < 0 )
    abort();
  if ( dword_8052168 <= a1 )
  {
    v13 = off_8052174 == &dword_805216C;
    if ( (unsigned int)a1 > 0xFFFFFFE )
      sub_804D62C();
    _CF = 0;
    _OF = 0;
    _ZF = off_8052174 != &dword_805216C;
    _SF = v13 < 0;
    if ( v13 )
    {
      __asm { pushfw }
      v8 = 0;
      __asm { popfw }
    }
    else
    {
      v8 = off_8052174;
    }
    v14 = (int *)sub_804D504(v8, 8 * (a1 + 1));
    off_8052174 = v14;
    if ( v13 )
    {
      v9 = off_8052170;
      *v14 = dword_805216C;
      v14[1] = (int)v9;
    }
    memset(&v14[2 * dword_8052168], 0, 8 * (a1 + 1 - dword_8052168));
    dword_8052168 = a1 + 1;
  }
  v10 = v14[2 * a1];
  ptr = (void *)v14[2 * a1 + 1];
  v18 = a4[1] | 1;
  sub_804B1D5(v14[2 * a1 + 1], v14[2 * a1], a2, a3, *a4, v18, (int)(a4 + 2), a4[10], a4[11]);
  if ( v10 <= v11 )
  {
    size = v11 + 1;
    v14[2 * a1] = v11 + 1;
    if ( ptr != &unk_805244E )
      free(ptr);
    ptr = sub_804D4C7(size);
    v14[2 * a1 + 1] = (int)ptr;
    sub_804B1D5((int)ptr, size, a2, a3, *a4, v18, (int)(a4 + 2), a4[10], a4[11]);
  }
  *__errno_location() = v16;
  return ptr;
}
// 8052168: using guessed type int dword_8052168;
// 805216C: using guessed type int dword_805216C;
// 8052170: using guessed type void *off_8052170;
// 8052174: using guessed type int *off_8052174;

//----- (0804C496) --------------------------------------------------------
void *__cdecl sub_804C496(signed int a1, int a2)
{
  return sub_804C26C(a1, a2, -1, (unsigned int *)&dword_805240E);
}
// 805240E: using guessed type int dword_805240E;

//----- (0804C4C0) --------------------------------------------------------
void *__cdecl sub_804C4C0(signed int a1, int a2, int a3)
{
  return sub_804C26C(a1, a2, a3, (unsigned int *)&dword_805240E);
}
// 805240E: using guessed type int dword_805240E;

//----- (0804C526) --------------------------------------------------------
void *__cdecl sub_804C526(signed int a1, int a2, int a3)
{
  unsigned int v4[14]; // [esp+10h] [ebp-38h]

  sub_804B0B7(v4, a2);
  return sub_804C26C(a1, a3, -1, v4);
}

//----- (0804C564) --------------------------------------------------------
void *__cdecl sub_804C564(signed int a1, int a2, int a3, int a4)
{
  unsigned int v5[14]; // [esp+10h] [ebp-38h]

  sub_804B0B7(v5, a2);
  return sub_804C26C(a1, a3, a4, v5);
}

//----- (0804C5EC) --------------------------------------------------------
void *__cdecl sub_804C5EC(int a1, int a2, unsigned __int8 a3)
{
  int v4; // [esp+20h] [ebp-38h]
  int v5; // [esp+24h] [ebp-34h]
  int v6; // [esp+28h] [ebp-30h]
  int v7; // [esp+2Ch] [ebp-2Ch]
  int v8; // [esp+30h] [ebp-28h]
  int v9; // [esp+34h] [ebp-24h]
  int v10; // [esp+38h] [ebp-20h]
  int v11; // [esp+3Ch] [ebp-1Ch]
  int v12; // [esp+40h] [ebp-18h]
  int v13; // [esp+44h] [ebp-14h]
  int v14; // [esp+48h] [ebp-10h]
  int v15; // [esp+4Ch] [ebp-Ch]

  v4 = dword_805240E;
  v5 = dword_8052412;
  v6 = dword_8052416;
  v7 = dword_805241A;
  v8 = dword_805241E;
  v9 = dword_8052422;
  v10 = dword_8052426;
  v11 = dword_805242A;
  v12 = dword_805242E;
  v13 = dword_8052432;
  v14 = dword_8052436;
  v15 = dword_805243A;
  sub_804AFCC(&v4, a3, 1);
  return sub_804C26C(0, a1, a2, (unsigned int *)&v4);
}
// 805240E: using guessed type int dword_805240E;
// 8052412: using guessed type int dword_8052412;
// 8052416: using guessed type int dword_8052416;
// 805241A: using guessed type int dword_805241A;
// 805241E: using guessed type int dword_805241E;
// 8052422: using guessed type int dword_8052422;
// 8052426: using guessed type int dword_8052426;
// 805242A: using guessed type int dword_805242A;
// 805242E: using guessed type int dword_805242E;
// 8052432: using guessed type int dword_8052432;
// 8052436: using guessed type int dword_8052436;
// 805243A: using guessed type int dword_805243A;

//----- (0804C696) --------------------------------------------------------
void *__cdecl sub_804C696(int a1, unsigned __int8 a2)
{
  return sub_804C5EC(a1, -1, a2);
}

//----- (0804C6BF) --------------------------------------------------------
void *__cdecl sub_804C6BF(int a1)
{
  return sub_804C696(a1, 0x3Au);
}

//----- (0804C6FC) --------------------------------------------------------
void *__cdecl sub_804C6FC(signed int a1, int a2, int a3)
{
  int v4; // [esp+10h] [ebp-68h]
  int v5; // [esp+14h] [ebp-64h]
  int v6; // [esp+18h] [ebp-60h]
  int v7; // [esp+1Ch] [ebp-5Ch]
  int v8; // [esp+20h] [ebp-58h]
  int v9; // [esp+24h] [ebp-54h]
  int v10; // [esp+28h] [ebp-50h]
  int v11; // [esp+2Ch] [ebp-4Ch]
  int v12; // [esp+30h] [ebp-48h]
  int v13; // [esp+34h] [ebp-44h]
  int v14; // [esp+38h] [ebp-40h]
  int v15; // [esp+3Ch] [ebp-3Ch]
  int v16; // [esp+40h] [ebp-38h]
  int v17; // [esp+44h] [ebp-34h]
  int v18; // [esp+48h] [ebp-30h]
  int v19; // [esp+4Ch] [ebp-2Ch]
  int v20; // [esp+50h] [ebp-28h]
  int v21; // [esp+54h] [ebp-24h]
  int v22; // [esp+58h] [ebp-20h]
  int v23; // [esp+5Ch] [ebp-1Ch]
  int v24; // [esp+60h] [ebp-18h]
  int v25; // [esp+64h] [ebp-14h]
  int v26; // [esp+68h] [ebp-10h]
  int v27; // [esp+6Ch] [ebp-Ch]

  sub_804B0B7(&v4, a2);
  v16 = v4;
  v17 = v5;
  v18 = v6;
  v19 = v7;
  v20 = v8;
  v21 = v9;
  v22 = v10;
  v23 = v11;
  v24 = v12;
  v25 = v13;
  v26 = v14;
  v27 = v15;
  sub_804AFCC(&v16, 0x3Au, 1);
  return sub_804C26C(a1, a3, -1, (unsigned int *)&v16);
}

//----- (0804C79D) --------------------------------------------------------
void *__cdecl sub_804C79D(signed int a1, int a2, int a3, int a4)
{
  return sub_804C7CD(a1, a2, a3, a4, -1);
}

//----- (0804C7CD) --------------------------------------------------------
void *__cdecl sub_804C7CD(signed int a1, int a2, int a3, int a4, int a5)
{
  int v6; // [esp+10h] [ebp-38h]
  int v7; // [esp+14h] [ebp-34h]
  int v8; // [esp+18h] [ebp-30h]
  int v9; // [esp+1Ch] [ebp-2Ch]
  int v10; // [esp+20h] [ebp-28h]
  int v11; // [esp+24h] [ebp-24h]
  int v12; // [esp+28h] [ebp-20h]
  int v13; // [esp+2Ch] [ebp-1Ch]
  int v14; // [esp+30h] [ebp-18h]
  int v15; // [esp+34h] [ebp-14h]
  int v16; // [esp+38h] [ebp-10h]
  int v17; // [esp+3Ch] [ebp-Ch]

  v6 = dword_805240E;
  v7 = dword_8052412;
  v8 = dword_8052416;
  v9 = dword_805241A;
  v10 = dword_805241E;
  v11 = dword_8052422;
  v12 = dword_8052426;
  v13 = dword_805242A;
  v14 = dword_805242E;
  v15 = dword_8052432;
  v16 = dword_8052436;
  v17 = dword_805243A;
  sub_804B076(&v6, a2, a3);
  return sub_804C26C(a1, a4, a5, (unsigned int *)&v6);
}
// 805240E: using guessed type int dword_805240E;
// 8052412: using guessed type int dword_8052412;
// 8052416: using guessed type int dword_8052416;
// 805241A: using guessed type int dword_805241A;
// 805241E: using guessed type int dword_805241E;
// 8052422: using guessed type int dword_8052422;
// 8052426: using guessed type int dword_8052426;
// 805242A: using guessed type int dword_805242A;
// 805242E: using guessed type int dword_805242E;
// 8052432: using guessed type int dword_8052432;
// 8052436: using guessed type int dword_8052436;
// 805243A: using guessed type int dword_805243A;

//----- (0804C8C7) --------------------------------------------------------
void *__cdecl sub_804C8C7(signed int a1, int a2, int a3)
{
  return sub_804C26C(a1, a2, a3, (unsigned int *)&unk_8052188);
}

//----- (0804C912) --------------------------------------------------------
void *__cdecl sub_804C912(signed int a1, int a2)
{
  return sub_804C8C7(a1, a2, -1);
}

//----- (0804C934) --------------------------------------------------------
void *__cdecl sub_804C934(int a1)
{
  return sub_804C912(0, a1);
}

//----- (0804C94F) --------------------------------------------------------
_DWORD *__cdecl sub_804C94F(_DWORD *a1)
{
  _DWORD *result; // eax

  *a1 = 0;
  result = a1;
  a1[1] = 0;
  return result;
}

//----- (0804C967) --------------------------------------------------------
bool __cdecl sub_804C967(unsigned int a1, int a2)
{
  return ((*(_DWORD *)(4 * (a1 >> 5) + a2) >> (a1 & 0x1F)) & 1) != 0;
}

//----- (0804C994) --------------------------------------------------------
int __cdecl sub_804C994(unsigned int a1, int a2)
{
  int result; // eax

  result = (1 << (a1 & 0x1F)) | *(_DWORD *)(4 * (a1 >> 5) + a2);
  *(_DWORD *)(4 * (a1 >> 5) + a2) = result;
  return result;
}

//----- (0804C9D9) --------------------------------------------------------
unsigned int __cdecl sub_804C9D9(FILE *stream, int a2, int a3, int a4)
{
  int v5; // eax
  int v6; // [esp+20h] [ebp-38h]
  void *ptr; // [esp+24h] [ebp-34h]
  int j; // [esp+28h] [ebp-30h]
  unsigned int i; // [esp+2Ch] [ebp-2Ch]
  char s; // [esp+30h] [ebp-28h]

  memset(&s, 0, 0x20u);
  for ( i = 0; i < a3; ++i )
    sub_804C994(*(unsigned __int8 *)(a2 + i), (int)&s);
  for ( j = getc_unlocked(stream); j >= 0 && sub_804C967(j, (int)&s); j = getc_unlocked(stream) )
    ;
  ptr = *(void **)(a4 + 4);
  v6 = *(_DWORD *)a4;
  i = 0;
  while ( 1 )
  {
    if ( j < 0 && !i )
      return -1;
    if ( i == v6 )
      ptr = sub_804D42D(ptr, (int)&v6, 1);
    if ( j < 0 )
    {
      *((_BYTE *)ptr + i) = 0;
      goto LABEL_19;
    }
    if ( sub_804C967(j, (int)&s) )
      break;
    v5 = i++;
    *((_BYTE *)ptr + v5) = j;
    j = getc_unlocked(stream);
  }
  *((_BYTE *)ptr + i) = 0;
LABEL_19:
  *(_DWORD *)(a4 + 4) = ptr;
  *(_DWORD *)a4 = v6;
  return i;
}

//----- (0804CD5D) --------------------------------------------------------
int __cdecl sub_804CD5D(FILE *stream, int a2, int a3, int a4, int a5, int a6)
{
  char *v6; // eax
  char *v7; // eax
  int v8; // edi
  int v9; // ST4C_4
  int v10; // ST48_4
  int v11; // ST44_4
  int v12; // ST40_4
  int v13; // ST3C_4
  int v14; // ST38_4
  int v15; // esi
  int v16; // ebx
  char *v17; // eax

  if ( a2 )
    fprintf(stream, "%s (%s) %s\n", a2, a3, a4);
  else
    fprintf(stream, "%s %s\n", a3, a4);
  v6 = gettext("(C)");
  fprintf(stream, "Copyright %s %d Free Software Foundation, Inc.", v6, 2017);
  v7 = gettext(
         "\n"
         "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.\n"
         "This is free software: you are free to change and redistribute it.\n"
         "There is NO WARRANTY, to the extent permitted by law.\n"
         "\n");
  fputs_unlocked(v7, stream);
  if ( (unsigned int)a6 <= 9 )
    JUMPOUT(__CS__, *(&off_804F27C + a6));
  v8 = *(_DWORD *)(a5 + 32);
  v9 = *(_DWORD *)(a5 + 28);
  v10 = *(_DWORD *)(a5 + 24);
  v11 = *(_DWORD *)(a5 + 20);
  v12 = *(_DWORD *)(a5 + 16);
  v13 = *(_DWORD *)(a5 + 12);
  v14 = *(_DWORD *)(a5 + 8);
  v15 = *(_DWORD *)(a5 + 4);
  v16 = *(_DWORD *)a5;
  v17 = gettext("Written by %s, %s, %s,\n%s, %s, %s, %s,\n%s, %s, and others.\n");
  return fprintf(stream, v17, v16, v15, v14, v13, v12, v11, v10, v9, v8);
}
// 8048E40: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);
// 804F27C: using guessed type void *;

//----- (0804D2C2) --------------------------------------------------------
int __cdecl sub_804D2C2(FILE *stream, int a2, int a3, int a4, int a5)
{
  int *v5; // eax
  unsigned int i; // [esp+24h] [ebp-34h]
  int v8[12]; // [esp+28h] [ebp-30h]

  for ( i = 0; i <= 9; ++i )
  {
    v5 = (int *)a5;
    a5 += 4;
    v8[i] = *v5;
    if ( !v8[i] )
      break;
  }
  return sub_804CD5D(stream, a2, a3, a4, (int)v8, i);
}
// 804D2C2: using guessed type int var_30[12];

//----- (0804D3C8) --------------------------------------------------------
void *__cdecl sub_804D3C8(unsigned int a1, unsigned int a2)
{
  if ( 0x7FFFFFFF / a2 < a1 )
    sub_804D62C();
  return sub_804D4DA(a2 * a1);
}

//----- (0804D3F7) --------------------------------------------------------
void *__cdecl sub_804D3F7(void *ptr, int a2, int a3)
{
  if ( 0x7FFFFFFFu / a3 < a2 )
    sub_804D62C();
  return sub_804D504(ptr, a3 * a2);
}

//----- (0804D42D) --------------------------------------------------------
void *__cdecl sub_804D42D(void *ptr, int a2, int a3)
{
  unsigned int v4; // [esp+1Ch] [ebp-Ch]

  v4 = *(_DWORD *)a2;
  if ( ptr )
  {
    if ( 0x55555554u / a3 <= v4 )
      sub_804D62C();
    v4 += (v4 >> 1) + 1;
  }
  else
  {
    if ( !v4 )
      v4 = (0x40u / a3 == 0) + 0x40u / a3;
    if ( 0x7FFFFFFFu / a3 < v4 )
      sub_804D62C();
  }
  *(_DWORD *)a2 = v4;
  return sub_804D504(ptr, a3 * v4);
}

//----- (0804D4C7) --------------------------------------------------------
void *__cdecl sub_804D4C7(size_t size)
{
  return sub_804D4DA(size);
}

//----- (0804D4DA) --------------------------------------------------------
void *__cdecl sub_804D4DA(size_t size)
{
  void *v2; // [esp+1Ch] [ebp-Ch]

  v2 = malloc(size);
  if ( !v2 && size )
    sub_804D62C();
  return v2;
}

//----- (0804D504) --------------------------------------------------------
void *__cdecl sub_804D504(void *ptr, size_t size)
{
  void *result; // eax
  void *ptra; // [esp+20h] [ebp+8h]

  if ( size || !ptr )
  {
    ptra = realloc(ptr, size);
    if ( !ptra )
    {
      if ( size )
        sub_804D62C();
    }
    result = ptra;
  }
  else
  {
    free(ptr);
    __asm { pushfw }
    result = 0;
    __asm { popfw }
  }
  return result;
}

//----- (0804D5DE) --------------------------------------------------------
void *__cdecl sub_804D5DE(void *src, size_t n)
{
  void *v2; // eax

  v2 = sub_804D4DA(n);
  return memcpy(v2, src, n);
}

//----- (0804D607) --------------------------------------------------------
void *__cdecl sub_804D607(char *s)
{
  size_t v1; // eax

  v1 = strlen(s);
  return sub_804D5DE(s, v1 + 1);
}

//----- (0804D62C) --------------------------------------------------------
void __noreturn sub_804D62C()
{
  char *v0; // eax

  v0 = gettext("memory exhausted");
  error(status, 0, "%s", v0);
  abort();
}

//----- (0804D665) --------------------------------------------------------
int __cdecl sub_804D665(FILE *stream)
{
  int v2; // eax
  __int64 v3; // rax
  int v4; // [esp+14h] [ebp-14h]
  int v5; // [esp+18h] [ebp-10h]

  v4 = 0;
  if ( fileno(stream) < 0 )
    return fclose(stream);
  if ( !__freading(stream) || (v2 = fileno(stream), LODWORD(v3) = lseek64(v2, 0, 0, 1), v3 != -1) )
  {
    if ( sub_804D761(stream) )
      v4 = *__errno_location();
  }
  v5 = fclose(stream);
  if ( v4 )
  {
    *__errno_location() = v4;
    v5 = -1;
  }
  return v5;
}
// 8048F10: using guessed type int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804D728) --------------------------------------------------------
int __cdecl sub_804D728(FILE *stream)
{
  int result; // eax

  result = stream->_flags & 0x100;
  if ( result )
    result = sub_804D7A1(stream, 0, 0, 1);
  return result;
}

//----- (0804D761) --------------------------------------------------------
int __cdecl sub_804D761(FILE *fp)
{
  if ( !fp || !__freading(fp) )
    return fflush(fp);
  sub_804D728(fp);
  return fflush(fp);
}

//----- (0804D7A1) --------------------------------------------------------
int __cdecl sub_804D7A1(FILE *stream, int a2, int a3, int a4)
{
  int (*v4)(void); // eax
  int v6; // [esp+18h] [ebp-20h]
  int v7; // [esp+1Ch] [ebp-1Ch]

  v6 = a2;
  v7 = a3;
  if ( stream->_IO_read_end != stream->_IO_read_ptr || stream->_IO_write_ptr != stream->_IO_write_base )
    return fseeko64(stream, v6, v7, a4);
  v4 = (int (*)(void))&loc_804D877;
  if ( stream->_IO_save_base )
    v4 = (int (*)(void))&loc_804D8E8;
  dword_8052128 = v4;
  dword_8052124 = (int)&loc_804D877;
  return v4();
}
// 8048CF0: using guessed type int __cdecl fseeko64(_DWORD, _DWORD, _DWORD, _DWORD);
// 8052124: using guessed type int dword_8052124;
// 8052128: using guessed type int (*dword_8052128)(void);

//----- (0804D90A) --------------------------------------------------------
size_t __cdecl sub_804D90A(wchar_t *pwc, char *s, size_t n, mbstate_t *p)
{
  char v5; // [esp+18h] [ebp-10h]
  size_t v6; // [esp+1Ch] [ebp-Ch]

  if ( !pwc )
    pwc = (wchar_t *)&v5;
  v6 = mbrtowc(pwc, s, n, p);
  if ( v6 <= 0xFFFFFFFD || !n || !((unsigned __int8)sub_804DA7D(0) ^ 1) )
    return v6;
  *pwc = (unsigned __int8)*s;
  return 1;
}

//----- (0804D97C) --------------------------------------------------------
int __cdecl sub_804D97C(unsigned __int8 *a1, unsigned __int8 *a2)
{
  unsigned __int8 *v2; // esi
  unsigned __int8 *v3; // ebx
  int result; // eax
  unsigned __int8 v9; // [esp+1Eh] [ebp-Ah]
  unsigned __int8 v10; // [esp+1Fh] [ebp-9h]

  v2 = a1;
  v3 = a2;
  _CF = a1 < a2;
  _OF = __OFSUB__(a1, a2);
  _ZF = a1 == a2;
  _SF = a1 - a2 < 0;
  if ( a1 == a2 )
  {
    __asm { pushfw }
    result = 0;
    __asm { popfw }
  }
  else
  {
    do
    {
      v9 = sub_804E337(*v2);
      v10 = sub_804E337(*v3);
      if ( !v9 )
        break;
      ++v2;
      ++v3;
    }
    while ( v9 == v10 );
    result = v9 - v10;
  }
  return result;
}

//----- (0804D9E2) --------------------------------------------------------
int __cdecl sub_804D9E2(FILE *fp)
{
  bool v1; // ST26_1
  void *v2; // eax
  unsigned int v7; // eax
  int result; // eax
  bool v9; // [esp+1Dh] [ebp-Bh]
  bool v10; // [esp+1Fh] [ebp-9h]

  v9 = __fpending(fp) != 0;
  v1 = ferror_unlocked(fp) != 0;
  v10 = sub_804D665(fp) != 0;
  v2 = &loc_804DA40;
  if ( v1 )
    v2 = &loc_804DA58;
  dword_80520F4 = (int)v2;
  sub_804E6C7();
  _CF = 0;
  _OF = 0;
  _ZF = v10 == 0;
  _SF = v10 < 0;
  if ( v10
    && (v9
     || (v7 = *__errno_location(),
         _CF = v7 < 9,
         _OF = __OFSUB__(v7, 9),
         _ZF = v7 == 9,
         _SF = (signed int)(v7 - 9) < 0,
         v7 != 9)) )
  {
    if ( v10 != 1 )
      *__errno_location() = 0;
    result = -1;
  }
  else
  {
    __asm { pushfw }
    result = 0;
    __asm { popfw }
  }
  return result;
}
// 804E6C7: using guessed type int sub_804E6C7(void);
// 80520F4: using guessed type int dword_80520F4;

//----- (0804DA7D) --------------------------------------------------------
int __cdecl sub_804DA7D(int category)
{
  unsigned __int8 v2; // [esp+1Bh] [ebp-Dh]
  const char *s1; // [esp+1Ch] [ebp-Ch]

  v2 = 1;
  s1 = setlocale(category, 0);
  if ( s1 && (!strcmp(s1, "C") || !strcmp(s1, "POSIX")) )
    v2 = 0;
  return v2;
}

//----- (0804DADB) --------------------------------------------------------
void *sub_804DADB()
{
  char v4; // al
  signed int v5; // eax
  FILE *v6; // eax
  int (*v7)(void); // eax
  void *ptr; // [esp+14h] [ebp-B4h]
  void *v10; // [esp+18h] [ebp-B0h]
  char *s; // [esp+1Ch] [ebp-ACh]
  char *v12; // [esp+28h] [ebp-A0h]
  size_t n; // [esp+2Ch] [ebp-9Ch]
  size_t v14; // [esp+30h] [ebp-98h]
  int v15; // [esp+34h] [ebp-94h]
  void *dest; // [esp+38h] [ebp-90h]
  int fd; // [esp+3Ch] [ebp-8Ch]
  FILE *stream; // [esp+40h] [ebp-88h]
  unsigned int v19; // [esp+BCh] [ebp-Ch]

  v19 = __readgsdword(0x14u);
  v10 = (void *)dword_805254E;
  if ( dword_805254E )
    return v10;
  ptr = 0;
  v12 = "charset.alias";
  s = getenv("CHARSETALIASDIR");
  if ( !s || !*s )
  {
    ptr = 0;
    s = "/home/hwangdz/coreutils/coreutils-8.28/install_m32/lib";
  }
  n = strlen(s);
  v14 = strlen(v12);
  _CF = 0;
  _OF = 0;
  _ZF = n == 0;
  _SF = (n & 0x80000000) != 0;
  if ( n
    && (v4 = s[n - 1],
        _CF = (unsigned __int8)v4 < 0x2Fu,
        _OF = __OFSUB__(v4, 47),
        _ZF = v4 == 47,
        _SF = (char)(v4 - 47) < 0,
        v4 != 47) )
  {
    v5 = 1;
  }
  else
  {
    __asm { pushfw }
    v5 = 0;
    __asm { popfw }
  }
  v15 = v5;
  dest = malloc(n + v5 + v14 + 1);
  if ( dest )
  {
    memcpy(dest, s, n);
    if ( v15 )
      *((_BYTE *)dest + n) = 47;
    memcpy((char *)dest + n + v15, v12, v14 + 1);
  }
  free(ptr);
  if ( !dest )
  {
    v10 = &unk_804F40B;
LABEL_20:
    dword_805254E = (int)v10;
    return v10;
  }
  fd = open64(dest, 0x20000);
  if ( fd < 0 )
  {
    v10 = &unk_804F40B;
    free(dest);
    goto LABEL_20;
  }
  v6 = fdopen(fd, "r");
  stream = v6;
  _ZF = v6 == 0;
  v7 = (int (*)(void))&loc_804DD7F;
  if ( !_ZF )
    v7 = (int (*)(void))&loc_804DD9C;
  dword_8052128 = v7;
  dword_8052124 = (int)&loc_804DD7F;
  return (void *)v7();
}
// 8048C60: using guessed type int __cdecl open64(_DWORD, _DWORD);
// 8052124: using guessed type int dword_8052124;
// 8052128: using guessed type int (*dword_8052128)(void);
// 805254E: using guessed type int dword_805254E;

//----- (0804E03C) --------------------------------------------------------
const char *sub_804E03C()
{
  char *v0; // ST1C_4
  const char *s1; // [esp+18h] [ebp-10h]
  char *s2; // [esp+1Ch] [ebp-Ch]

  s1 = nl_langinfo(14);
  if ( !s1 )
    s1 = (const char *)&unk_804F40B;
  for ( s2 = (char *)sub_804DADB(); *s2; s2 = &v0[strlen(v0) + 1] )
  {
    if ( !strcmp(s1, s2) || *s2 == 42 && !s2[1] )
    {
      s1 = &s2[strlen(s2) + 1];
      break;
    }
    v0 = &s2[strlen(s2) + 1];
  }
  if ( !*s1 )
    s1 = "ASCII";
  return s1;
}

//----- (0804E337) --------------------------------------------------------
int __cdecl sub_804E337(int a1)
{
  int result; // eax

  if ( (unsigned int)(a1 - 65) > 0x19 )
    result = a1;
  else
    result = a1 + 32;
  return result;
}

//----- (0804E3D7) --------------------------------------------------------
int __cdecl sub_804E3D7(int a1)
{
  return __cxa_atexit(a1, 0, dword_805214C);
}
// 8048DA0: using guessed type int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD);
// 805214C: using guessed type int dword_805214C;

//----- (0804E634) --------------------------------------------------------
#error "804E63A: positive sp value has been found (funcsize=0)"

//----- (0804E686) --------------------------------------------------------
#error "804E6BF: positive sp value has been found (funcsize=18)"

//----- (0804E6C7) --------------------------------------------------------
#error "804E6CD: positive sp value has been found (funcsize=0)"

//----- (0804E6E0) --------------------------------------------------------
int (**sub_804E6E0())()
{
  int (**result)(); // eax
  int v1; // esi
  int v2; // edi

  init_proc();
  result = off_8051EF0;
  v1 = &off_8051EF4 - off_8051EF0;
  if ( v1 )
  {
    v2 = 0;
    do
      result = (int (**)())off_8051EF0[v2++]();
    while ( v1 != v2 );
  }
  return result;
}
// 8051EF0: using guessed type int (*off_8051EF0[2])();
// 8051EF4: using guessed type int (*off_8051EF4)();

//----- (0804E744) --------------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 5 decompilation failure(s) on 102 function(s)"
