/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
int sub_8048C30();
// int strcmp(const char *s1, const char *s2);
// int __cdecl open64(_DWORD, _DWORD); weak
// ssize_t read(int fd, void *buf, size_t nbytes);
// int printf(const char *format, ...);
// int fflush(FILE *stream);
// void _exit(int status);
// void *memmove(void *dest, const void *src, size_t n);
// void free(void *ptr);
// void *memcpy(void *dest, const void *src, size_t n);
// int fclose(FILE *stream);
// int getc_unlocked(FILE *stream);
// int __cdecl fseeko64(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __cdecl stpcpy(_DWORD, _DWORD); weak
// char *textdomain(const char *domainname);
// int ioctl(int fd, unsigned int request, ...);
// int ferror_unlocked(FILE *stream);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// int __cdecl __fxstat64(_DWORD, _DWORD, _DWORD); weak
// size_t __ctype_get_mb_cur_max(void);
// char *strcpy(char *dest, const char *src);
// size_t __fpending(FILE *fp);
// size_t mbrtowc(wchar_t *pwc, const char *s, size_t n, mbstate_t *p);
// int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD); weak
// void error(int status, int errnum, const char *format, ...);
// char *getenv(const char *name);
// void *realloc(void *ptr, size_t size);
// void *malloc(size_t size);
// int __freading(FILE *fp);
// void exit(int status);
// char *gettext(const char *msgid);
// FILE *fdopen(int fd, const char *modes);
// int __cdecl fputs_unlocked(_DWORD, _DWORD); weak
// int getopt_long(int argc, char *const *argv, const char *shortopts, const struct option *longopts, int *longind);
// int fscanf(FILE *stream, const char *format, ...);
// size_t strlen(const char *s);
// int fprintf(FILE *stream, const char *format, ...);
// ssize_t write(int fd, const void *buf, size_t n);
// int getpagesize(void);
// void *memset(void *s, int c, size_t n);
// int ungetc(int c, FILE *stream);
// int *__errno_location(void);
// int fileno(FILE *stream);
// char *nl_langinfo(nl_item item);
// char *setlocale(int category, const char *locale);
// char *strrchr(const char *s, int c);
// int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD); weak
// char *bindtextdomain(const char *domainname, const char *dirname);
// int __cdecl posix_fadvise64(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int strncmp(const char *s1, const char *s2, size_t n);
// void abort(void);
// int close(int fd);
// int _gmon_start__(void); weak
void sub_8049023();
void sub_8049040();
int sub_8049050();
int sub_80490C0();
int sub_80490E0();
void sub_804913F();
void sub_804915A();
signed int sub_804916A();
void sub_804924C();
void sub_8049267();
int sub_8049277();
int sub_8049303();
void sub_8049378();
void sub_8049393();
int sub_80493A3();
void sub_804948B();
void sub_80494A6();
int sub_80494B6();
unsigned int __cdecl sub_804956C(int a1, unsigned int a2);
int sub_804959F();
int __cdecl sub_80495CA(char *s1); // idb
signed int __cdecl sub_8049750(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, signed int a14);
void __cdecl __noreturn sub_8049792(int status); // idb
char *sub_80498C5();
int __cdecl sub_8049945(void *buf, size_t nbytes); // idb
int __cdecl sub_8049A39(int a1, _DWORD *a2);
int __cdecl sub_8049AAD(void *buf, size_t nbytes, void *dest, size_t, int, int, int, int, int, int); // idb
int __cdecl main(int argc, char **argv);
int sub_804A92C();
int __cdecl sub_804AA10(int a1, int a2, int a3, int a4, int a5, int a6);
int __cdecl sub_804AAA9(int fd, int, size_t n); // idb
char *__cdecl sub_804AB27(char *s);
int __cdecl sub_804AC73(int *a1, unsigned __int8 a2, char a3);
int *__cdecl sub_804AD1D(int *a1, int a2, int a3);
// _DWORD *__userpurge sub_804AD5E@<eax>(_DWORD *a1, int a2);
const char *__cdecl sub_804ADE1(char *msgid, int a2);
void __cdecl sub_804AE7C(int a1, int a2, int a3, int a4, unsigned int a5, int a6, int a7, int a8, int a9);
void *__cdecl sub_804BB49(int a1, int a2, _DWORD *a3, int *a4);
void *__cdecl sub_804BCF0(signed int a1, int a2, int a3, unsigned int *a4);
void *__cdecl sub_804BF2F(signed int a1, int a2);
void *__cdecl sub_804BF59(signed int a1, int a2, int a3);
void *__cdecl sub_804BFBF(signed int a1, int a2, int a3);
void *__cdecl sub_804BFFD(signed int a1, int a2, int a3, int a4);
void *__cdecl sub_804C03A(int a1, int a2);
void *__cdecl sub_804C085(int a1, int a2, unsigned __int8 a3);
void *__cdecl sub_804C12F(int a1, unsigned __int8 a2);
void *__cdecl sub_804C158(int a1);
void *__cdecl sub_804C195(signed int a1, int a2, int a3);
void *__cdecl sub_804C236(signed int a1, int a2, int a3, int a4);
void *__cdecl sub_804C266(signed int a1, int a2, int a3, int a4, int a5);
void *__cdecl sub_804C360(signed int a1, int a2, int a3);
void *__cdecl sub_804C3AB(signed int a1, int a2);
ssize_t __cdecl sub_804C3E8(int fd, void *buf, size_t nbytes);
int __cdecl sub_804C44A(int fd, void *buf, size_t n, int a4);
int __cdecl sub_804C49A(int a1, int a2, int a3, int a4);
int __cdecl sub_804C4CB(int a1, int a2, int a3, unsigned int a4);
// int __usercall sub_804C51E@<eax>(int a1@<ebp>, int a2, int a3, int a4, int a5);
int __cdecl sub_804C534(int a1, int a2, int a3, int a4);
int sub_804C547(); // weak
int __cdecl sub_804C549(FILE *stream, int, int, int, int, int); // idb
int __cdecl sub_804CAC0(FILE *stream, int, int, int, int); // idb
int sub_804CB26(FILE *stream, int a2, int a3, int a4, ...);
void *__cdecl sub_804CC35(void *ptr, int a2, int a3);
void *__cdecl sub_804CCCF(size_t size);
void *__cdecl sub_804CCE2(size_t size);
void *__cdecl sub_804CD0C(void *ptr, size_t size);
void *__cdecl sub_804CDE6(void *src, size_t n);
void __noreturn sub_804CE34();
void sub_804CE6D();
void sub_804CE72();
size_t __cdecl sub_804CE95(wchar_t *pwc, char *s, size_t n, mbstate_t *p);
int sub_804CF07();
int sub_804CF12();
int sub_804CF1D();
int __cdecl sub_804CF50(unsigned __int8 *a1, unsigned __int8 *a2);
int __cdecl sub_804CFB6(FILE *fp); // idb
int __cdecl sub_804D038(int category); // idb
void *sub_804D096();
const char *sub_804D50F();
int __cdecl sub_804D5C2(FILE *stream); // idb
int __cdecl sub_804D685(FILE *stream); // idb
int __cdecl sub_804D6BE(FILE *fp); // idb
int __cdecl sub_804D6FE(FILE *stream, int, int, int); // idb
int __cdecl sub_804D9BD(int a1);
int __cdecl sub_804DA6B(int a1);
int __cdecl sub_804DA9A(int a1, int a2);
int sub_804DBD5(void); // weak
int (**sub_804DBF0())();
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_8049A05; // weak
_UNKNOWN loc_8049A2E; // weak
_UNKNOWN loc_804A217; // weak
_UNKNOWN loc_804AB1C; // weak
_UNKNOWN loc_804BD37; // weak
_UNKNOWN loc_804BDE7; // weak
_UNKNOWN loc_804C450; // weak
_UNKNOWN loc_804D75B; // weak
_UNKNOWN loc_804D7CC; // weak
char locale = '\0'; // idb
struct option longopts = { "number-nonblank", 0, NULL, 98 }; // idb
_UNKNOWN unk_804E4F6; // weak
_UNKNOWN unk_804E4FA; // weak
_UNKNOWN unk_804E506; // weak
_UNKNOWN unk_804E50A; // weak
_UNKNOWN unk_804E50D; // weak
_DWORD off_804E514[11] =
{
  134524984,
  134524908,
  134524927,
  134524904,
  134524912,
  134524697,
  134524686,
  134524754,
  134524767,
  134524767,
  134524767
}; // idb
void *off_804EA9C = &loc_804C602; // weak
_UNKNOWN unk_804EC2B; // weak
int (*off_8051EF8[2])() = { &sub_80490E0, &sub_80490C0 }; // weak
int (*off_8051EFC)() = &sub_80490C0; // weak
int (*dword_8052008)(void) = NULL; // weak
int dword_8052100 = 0; // weak
int (__cdecl *dword_805211C)(_DWORD, _DWORD, _DWORD, _DWORD) = NULL; // weak
int dword_8052134 = 0; // weak
char byte_8052138 = ' '; // weak
char *off_805214C = "     0\t"; // weak
void *off_8052150 = (void *)0x8052149; // weak
void *off_8052154 = (void *)0x8052149; // weak
int off_8052158 = 134538184; // idb
int status = 1; // idb
int dword_8052170 = 1; // weak
int dword_8052174 = 256; // weak
void *off_8052178 = &unk_8052304; // weak
int *off_805217C = &dword_8052174; // weak
_UNKNOWN unk_8052190; // weak
int program_invocation_short_name; // weak
FILE *stderr; // idb
int program_invocation_name; // weak
int optind; // weak
FILE *stdout; // idb
char byte_80521E8; // weak
_UNKNOWN unk_8052215; // weak
char byte_805223A; // weak
_UNKNOWN unk_805223E; // weak
char *s1; // idb
int fd; // idb
int dword_8052298; // weak
int dword_805229C; // weak
char byte_80522A0; // weak
int dword_80522A4; // weak
int dword_80522C4; // weak
int dword_80522C8; // weak
int dword_80522CC; // weak
int dword_80522D0; // weak
int dword_80522D4; // weak
int dword_80522D8; // weak
int dword_80522DC; // weak
int dword_80522E0; // weak
int dword_80522E4; // weak
int dword_80522E8; // weak
int dword_80522EC; // weak
int dword_80522F0; // weak
_UNKNOWN unk_8052304; // weak
int dword_8052404; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (08048C0C) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 8048FE0: using guessed type int _gmon_start__(void);

//----- (08048C30) --------------------------------------------------------
int sub_8048C30()
{
  return dword_8052008();
}
// 8052008: using guessed type int (*dword_8052008)(void);

//----- (08048FF0) --------------------------------------------------------
#error "8048FF3: positive sp value has been found (funcsize=2)"

//----- (08049023) --------------------------------------------------------
void sub_8049023()
{
  ;
}

//----- (08049040) --------------------------------------------------------
void sub_8049040()
{
  ;
}

//----- (08049050) --------------------------------------------------------
int sub_8049050()
{
  int result; // eax

  result = 134554051 - (_DWORD)&program_invocation_short_name;
  if ( (unsigned int)(134554051 - (_DWORD)&program_invocation_short_name) > 6 )
    result = 0;
  return result;
}
// 8049050: could not find valid save-restore pair for ebp
// 80521C0: using guessed type int program_invocation_short_name;

//----- (080490C0) --------------------------------------------------------
int sub_80490C0()
{
  int result; // eax

  if ( !byte_80521E8 )
  {
    result = sub_8049050();
    byte_80521E8 = 1;
  }
  return result;
}
// 80490C0: could not find valid save-restore pair for ebp
// 80521E8: using guessed type char byte_80521E8;

//----- (080490E0) --------------------------------------------------------
int sub_80490E0()
{
  return 0;
}
// 80490E0: could not find valid save-restore pair for ebp

//----- (0804913F) --------------------------------------------------------
void sub_804913F()
{
  ;
}

//----- (0804915A) --------------------------------------------------------
void sub_804915A()
{
  ;
}

//----- (0804916A) --------------------------------------------------------
signed int sub_804916A()
{
  return 3;
}
// 804916A: could not find valid save-restore pair for ebp

//----- (0804924C) --------------------------------------------------------
void sub_804924C()
{
  ;
}

//----- (08049267) --------------------------------------------------------
void sub_8049267()
{
  ;
}

//----- (08049277) --------------------------------------------------------
int sub_8049277()
{
  int result; // eax

  result = &unk_8052215 - (_UNKNOWN *)&program_invocation_short_name;
  _CF = (unsigned int)(&unk_8052215 - (_UNKNOWN *)&program_invocation_short_name) < 6;
  _OF = __OFSUB__(&unk_8052215 - (_UNKNOWN *)&program_invocation_short_name, 6);
  _ZF = &unk_8052215 - (_UNKNOWN *)&program_invocation_short_name == 6;
  _SF = &unk_8052215 - (_UNKNOWN *)&program_invocation_short_name - 6 < 0;
  if ( (unsigned int)(&unk_8052215 - (_UNKNOWN *)&program_invocation_short_name) > 6 )
  {
    __asm { pushfw }
    result = 0;
    __asm { popfw }
  }
  return result;
}
// 8049277: could not find valid save-restore pair for ebp
// 80521C0: using guessed type int program_invocation_short_name;

//----- (08049303) --------------------------------------------------------
int sub_8049303()
{
  int result; // eax

  result = sub_8049277();
  byte_805223A = 1;
  return result;
}
// 805223A: using guessed type char byte_805223A;

//----- (08049378) --------------------------------------------------------
void sub_8049378()
{
  ;
}

//----- (08049393) --------------------------------------------------------
void sub_8049393()
{
  ;
}

//----- (080493A3) --------------------------------------------------------
int sub_80493A3()
{
  int result; // eax

  result = &unk_805223E - (_UNKNOWN *)&program_invocation_short_name;
  _CF = (unsigned int)(&unk_805223E - (_UNKNOWN *)&program_invocation_short_name) < 6;
  _OF = __OFSUB__(&unk_805223E - (_UNKNOWN *)&program_invocation_short_name, 6);
  _ZF = &unk_805223E - (_UNKNOWN *)&program_invocation_short_name == 6;
  _SF = &unk_805223E - (_UNKNOWN *)&program_invocation_short_name - 6 < 0;
  if ( (unsigned int)(&unk_805223E - (_UNKNOWN *)&program_invocation_short_name) > 6 )
  {
    __asm { pushfw }
    result = 0;
    __asm { popfw }
  }
  return result;
}
// 80493A3: could not find valid save-restore pair for ebp
// 80521C0: using guessed type int program_invocation_short_name;

//----- (0804948B) --------------------------------------------------------
void sub_804948B()
{
  ;
}

//----- (080494A6) --------------------------------------------------------
void sub_80494A6()
{
  ;
}

//----- (080494B6) --------------------------------------------------------
int sub_80494B6()
{
  int result; // eax

  result = &unk_805223E - (_UNKNOWN *)&program_invocation_short_name;
  _CF = (unsigned int)(&unk_805223E - (_UNKNOWN *)&program_invocation_short_name) < 6;
  _OF = __OFSUB__(&unk_805223E - (_UNKNOWN *)&program_invocation_short_name, 6);
  _ZF = &unk_805223E - (_UNKNOWN *)&program_invocation_short_name == 6;
  _SF = &unk_805223E - (_UNKNOWN *)&program_invocation_short_name - 6 < 0;
  if ( (unsigned int)(&unk_805223E - (_UNKNOWN *)&program_invocation_short_name) > 6 )
  {
    __asm { pushfw }
    result = 0;
    __asm { popfw }
  }
  return result;
}
// 80494B6: could not find valid save-restore pair for ebp
// 80521C0: using guessed type int program_invocation_short_name;

//----- (0804956C) --------------------------------------------------------
unsigned int __cdecl sub_804956C(int a1, unsigned int a2)
{
  return a2 - 1 + a1 - (a2 - 1 + a1) % a2;
}

//----- (0804959F) --------------------------------------------------------
int sub_804959F()
{
  FILE *v0; // ebx
  char *v1; // eax

  v0 = stdout;
  v1 = gettext("\nWith no FILE, or when FILE is -, read standard input.\n");
  return fputs_unlocked(v1, v0);
}
// 8048E70: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);

//----- (080495CA) --------------------------------------------------------
int __cdecl sub_80495CA(char *s1)
{
  char *v1; // eax
  char *v2; // eax
  char *v3; // eax
  char *v4; // ebx
  char *v5; // eax
  char *v7; // [esp+1Ch] [ebp-4Ch]
  const char **i; // [esp+20h] [ebp-48h]
  const char *v9; // [esp+24h] [ebp-44h]
  const char *v10; // [esp+28h] [ebp-40h]
  const char *v11; // [esp+2Ch] [ebp-3Ch]
  const char *v12; // [esp+30h] [ebp-38h]
  const char *v13; // [esp+34h] [ebp-34h]
  const char *v14; // [esp+38h] [ebp-30h]
  const char *v15; // [esp+3Ch] [ebp-2Ch]
  const char *v16; // [esp+40h] [ebp-28h]
  const char *v17; // [esp+44h] [ebp-24h]
  const char *v18; // [esp+48h] [ebp-20h]
  const char *v19; // [esp+4Ch] [ebp-1Ch]
  const char *v20; // [esp+50h] [ebp-18h]
  const char *v21; // [esp+54h] [ebp-14h]
  int v22; // [esp+58h] [ebp-10h]
  int v23; // [esp+5Ch] [ebp-Ch]

  v10 = "[";
  v11 = "test invocation";
  v12 = "coreutils";
  v13 = "Multi-call invocation";
  v14 = "sha224sum";
  v15 = "sha2 utilities";
  v16 = "sha256sum";
  v17 = "sha2 utilities";
  v18 = "sha384sum";
  v19 = "sha2 utilities";
  v20 = "sha512sum";
  v21 = "sha2 utilities";
  v22 = 0;
  v23 = 0;
  v7 = s1;
  for ( i = &v10; *i && strcmp(s1, *i); i += 2 )
    ;
  if ( i[1] )
    v7 = (char *)i[1];
  v1 = gettext("\n%s online help: <%s>\n");
  printf(v1, "GNU coreutils", "http://www.gnu.org/software/coreutils/");
  v9 = setlocale(5, 0);
  if ( v9 && strncmp(v9, "en_", 3u) )
  {
    v2 = gettext("Report %s translation bugs to <http://translationproject.org/team/>\n");
    printf(v2, s1);
  }
  v3 = gettext("Full documentation at: <%s%s>\n");
  printf(v3, "http://www.gnu.org/software/coreutils/", s1);
  if ( v7 == s1 )
    v4 = " invocation";
  else
    v4 = &locale;
  v5 = gettext("or available locally via: info '(coreutils) %s%s'\n");
  return printf(v5, v7, v4);
}

//----- (08049750) --------------------------------------------------------
signed int __cdecl sub_8049750(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, signed int a14)
{
  if ( a14 <= 0 || (unsigned int)a14 > 0x20000000 || a14 <= 0x1FFFF )
    return 0x20000;
  if ( a14 <= 0 || (unsigned int)a14 > 0x20000000 )
    return 512;
  return a14;
}

//----- (08049792) --------------------------------------------------------
void __cdecl __noreturn sub_8049792(int status)
{
  int v1; // ebx
  char *v2; // eax
  int v3; // ebx
  char *v4; // eax
  FILE *v5; // ebx
  char *v6; // eax
  FILE *v7; // ebx
  char *v8; // eax
  FILE *v9; // ebx
  char *v10; // eax
  FILE *v11; // ebx
  char *v12; // eax
  FILE *v13; // ebx
  char *v14; // eax
  int v15; // esi
  int v16; // ebx
  char *v17; // eax

  if ( status )
  {
    v1 = dword_80522A4;
    v2 = gettext("Try '%s --help' for more information.\n");
    fprintf(stderr, v2, v1);
  }
  else
  {
    v3 = dword_80522A4;
    v4 = gettext("Usage: %s [OPTION]... [FILE]...\n");
    printf(v4, v3);
    v5 = stdout;
    v6 = gettext("Concatenate FILE(s) to standard output.\n");
    fputs_unlocked(v6, v5);
    sub_804959F();
    v7 = stdout;
    v8 = gettext(
           "\n"
           "  -A, --show-all           equivalent to -vET\n"
           "  -b, --number-nonblank    number nonempty output lines, overrides -n\n"
           "  -e                       equivalent to -vE\n"
           "  -E, --show-ends          display $ at end of each line\n"
           "  -n, --number             number all output lines\n"
           "  -s, --squeeze-blank      suppress repeated empty output lines\n");
    fputs_unlocked(v8, v7);
    v9 = stdout;
    v10 = gettext(
            "  -t                       equivalent to -vT\n"
            "  -T, --show-tabs          display TAB characters as ^I\n"
            "  -u                       (ignored)\n"
            "  -v, --show-nonprinting   use ^ and M- notation, except for LFD and TAB\n");
    fputs_unlocked(v10, v9);
    v11 = stdout;
    v12 = gettext("      --help     display this help and exit\n");
    fputs_unlocked(v12, v11);
    v13 = stdout;
    v14 = gettext("      --version  output version information and exit\n");
    fputs_unlocked(v14, v13);
    v15 = dword_80522A4;
    v16 = dword_80522A4;
    v17 = gettext(
            "\n"
            "Examples:\n"
            "  %s f - g  Output f's contents, then standard input, then g's contents.\n"
            "  %s        Copy standard input to standard output.\n");
    printf(v17, v16, v15);
    sub_80495CA("cat");
  }
  exit(status);
}
// 8048E70: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);
// 80522A4: using guessed type int dword_80522A4;

//----- (080498C5) --------------------------------------------------------
char *sub_80498C5()
{
  char *result; // eax
  _BYTE *v1; // eax
  _BYTE *v2; // [esp+Ch] [ebp-4h]

  v2 = off_8052154;
  while ( 1 )
  {
    result = (char *)(unsigned __int8)*v2;
    *v2 = (_BYTE)result + 1;
    if ( (char)result <= 56 )
      break;
    v1 = v2--;
    *v1 = 48;
    if ( v2 < off_8052150 )
    {
      if ( off_8052150 <= &byte_8052138 )
      {
        byte_8052138 = 62;
      }
      else
      {
        off_8052150 = (char *)off_8052150 - 1;
        *(_BYTE *)off_8052150 = 49;
      }
      result = off_805214C;
      if ( off_8052150 < off_805214C )
        result = off_805214C-- - 1;
      return result;
    }
  }
  return result;
}
// 8052138: using guessed type char byte_8052138;
// 805214C: using guessed type char *off_805214C;
// 8052150: using guessed type void *off_8052150;
// 8052154: using guessed type void *off_8052154;

//----- (08049945) --------------------------------------------------------
int __cdecl sub_8049945(void *buf, size_t nbytes)
{
  void *v2; // ebx
  int *v3; // eax
  int result; // eax
  void *v9; // eax
  char *v10; // ebx
  int *v11; // eax
  size_t v12; // [esp+18h] [ebp-10h]

  while ( 1 )
  {
    v12 = sub_804C3E8(fd, buf, nbytes);
    if ( v12 == -1 )
    {
      v2 = sub_804C195(0, 3, (int)s1);
      v3 = __errno_location();
      error(0, *v3, "%s", v2);
      __asm { pushfw }
      result = 0;
      __asm { popfw }
      return result;
    }
    if ( !v12 )
      break;
    _ZF = sub_804AAA9(1, (int)buf, v12) == v12;
    v9 = &loc_8049A05;
    if ( _ZF )
      v9 = &loc_8049A2E;
    dword_8052100 = (int)v9;
    sub_804DBD5();
    v10 = gettext("write error");
    v11 = __errno_location();
    error(1, *v11, v10);
  }
  return 1;
}
// 804DBD5: using guessed type int sub_804DBD5(void);
// 8052100: using guessed type int dword_8052100;

//----- (08049A39) --------------------------------------------------------
int __cdecl sub_8049A39(int a1, _DWORD *a2)
{
  int result; // eax
  int n; // ST1C_4
  char *v4; // ebx
  int *v5; // eax

  result = *a2 - a1;
  if ( *a2 != a1 )
  {
    n = *a2 - a1;
    if ( sub_804AAA9(1, a1, n) != n )
    {
      v4 = gettext("write error");
      v5 = __errno_location();
      error(1, *v5, v4);
    }
    result = (int)a2;
    *a2 = a1;
  }
  return result;
}

//----- (08049AAD) --------------------------------------------------------
int __cdecl sub_8049AAD(void *buf, size_t nbytes, void *dest, size_t a4, int a5, int a6, int a7, int a8, int a9, int a10)
{
  char *v10; // ebx
  int *v11; // eax
  void *v12; // esi
  char *v13; // ebx
  int *v14; // eax
  int result; // eax
  void *v20; // ebx
  int *v21; // eax
  char *v22; // eax
  char *v23; // eax
  char *v24; // eax
  char *v25; // eax
  char *v26; // eax
  char *v27; // eax
  char *v28; // eax
  char *v29; // eax
  char *v30; // eax
  char *v31; // eax
  char *v32; // eax
  char *v33; // eax
  char *v34; // eax
  char *v35; // eax
  char *v36; // eax
  char *v37; // eax
  char *v38; // eax
  char *v39; // eax
  char *v40; // eax
  char *v41; // eax
  char *v42; // eax
  char *v43; // eax
  char v44; // [esp+3Dh] [ebp-3Bh]
  char v45; // [esp+3Eh] [ebp-3Ah]
  char v46; // [esp+3Fh] [ebp-39h]
  char *v47; // [esp+40h] [ebp-38h]
  int v48; // [esp+44h] [ebp-34h]
  char *v49; // [esp+48h] [ebp-30h]
  char *v50; // [esp+4Ch] [ebp-2Ch]
  int v51; // [esp+50h] [ebp-28h]
  void *src; // [esp+54h] [ebp-24h]
  size_t n; // [esp+58h] [ebp-20h]
  ssize_t v54; // [esp+5Ch] [ebp-1Ch]

  v51 = dword_8052298;
  v45 = 1;
  v50 = (char *)buf;
  v49 = (char *)buf + 1;
  v47 = (char *)dest;
LABEL_2:
  while ( 2 )
  {
    if ( (char *)dest + a4 <= v47 )
    {
      src = dest;
      do
      {
        if ( sub_804AAA9(1, (int)src, a4) != a4 )
        {
          v10 = gettext("write error");
          v11 = __errno_location();
          error(1, *v11, v10);
        }
        src = (char *)src + a4;
        n = v47 - (_BYTE *)src;
      }
      while ( a4 <= v47 - (_BYTE *)src );
      memmove(dest, src, n);
      v47 = (char *)dest + n;
    }
    if ( v49 <= v50 )
    {
      if ( ++v51 > 0 )
      {
        if ( v51 > 1 )
        {
          v51 = 2;
          if ( (_BYTE)a10 )
          {
            v22 = v49++;
            v44 = *v22;
            goto LABEL_38;
          }
        }
        if ( (_BYTE)a7 && (_BYTE)a8 != 1 )
        {
          sub_80498C5();
          v47 = (char *)stpcpy(v47, off_805214C);
        }
      }
      if ( (_BYTE)a9 )
      {
        v23 = v47++;
        *v23 = 36;
      }
      v24 = v47++;
      *v24 = 10;
LABEL_37:
      v25 = v49++;
      v44 = *v25;
LABEL_38:
      if ( v44 == 10 )
        continue;
      if ( v51 >= 0 && (_BYTE)a7 )
      {
        sub_80498C5();
        v47 = (char *)stpcpy(v47, off_805214C);
      }
      if ( (_BYTE)a5 )
      {
        while ( 1 )
        {
          if ( (unsigned __int8)v44 <= 0x1Fu )
          {
            if ( v44 != 9 || (_BYTE)a6 == 1 )
            {
              if ( v44 == 10 )
              {
                v51 = -1;
                goto LABEL_2;
              }
              v37 = v47++;
              *v37 = 94;
              v38 = v47++;
              *v38 = v44 + 64;
            }
            else
            {
              v36 = v47++;
              *v36 = 9;
            }
          }
          else if ( (unsigned __int8)v44 > 0x7Eu )
          {
            if ( v44 == 127 )
            {
              v27 = v47++;
              *v27 = 94;
              v28 = v47++;
              *v28 = 63;
            }
            else
            {
              v29 = v47++;
              *v29 = 77;
              v30 = v47++;
              *v30 = 45;
              if ( (unsigned __int8)v44 <= 0x9Fu )
              {
                v34 = v47++;
                *v34 = 94;
                v35 = v47++;
                *v35 = v44 - 64;
              }
              else if ( v44 == -1 )
              {
                v32 = v47++;
                *v32 = 94;
                v33 = v47++;
                *v33 = 63;
              }
              else
              {
                v31 = v47++;
                *v31 = v44 + -128;
              }
            }
          }
          else
          {
            v26 = v47++;
            *v26 = v44;
          }
          v39 = v49++;
          v44 = *v39;
        }
      }
      while ( 1 )
      {
        if ( v44 == 9 && (_BYTE)a6 )
        {
          v40 = v47++;
          *v40 = 94;
          v41 = v47++;
          *v41 = 73;
        }
        else
        {
          if ( v44 == 10 )
          {
            v51 = -1;
            goto LABEL_2;
          }
          v42 = v47++;
          *v42 = v44;
        }
        v43 = v49++;
        v44 = *v43;
      }
    }
    break;
  }
  v46 = 0;
  v48 = 0;
  if ( v45 && ioctl(fd, 0x541Bu, &v48) < 0 )
  {
    if ( *__errno_location() != 95
      && *__errno_location() != 25
      && *__errno_location() != 22
      && *__errno_location() != 19
      && *__errno_location() != 38 )
    {
      v12 = sub_804C03A(4, (int)s1);
      v13 = gettext("cannot do ioctl on %s");
      v14 = __errno_location();
      error(0, *v14, v13, v12);
      dword_8052298 = v51;
      __asm { pushfw }
      result = 0;
      __asm { popfw }
      return result;
    }
    v45 = 0;
  }
  if ( v48 )
    v46 = 1;
  if ( v46 != 1 )
    sub_8049A39((int)dest, &v47);
  v54 = sub_804C3E8(fd, buf, nbytes);
  if ( v54 == -1 )
  {
    v20 = sub_804C195(0, 3, (int)s1);
    v21 = __errno_location();
    error(0, *v21, "%s", v20);
    sub_8049A39((int)dest, &v47);
    dword_8052298 = v51;
    __asm { pushfw }
    result = 0;
    __asm { popfw }
    return result;
  }
  if ( v54 )
  {
    v49 = (char *)buf;
    v50 = (char *)buf + v54;
    *((_BYTE *)buf + v54) = 10;
    goto LABEL_37;
  }
  sub_8049A39((int)dest, &v47);
  dword_8052298 = v51;
  return 1;
}
// 8048D20: using guessed type int __cdecl stpcpy(_DWORD, _DWORD);
// 805214C: using guessed type char *off_805214C;
// 8052298: using guessed type int dword_8052298;

//----- (08049FCB) --------------------------------------------------------
int __cdecl main(int argc, char **argv)
{
  char *v2; // ebx
  int *v3; // eax
  void *v4; // ebx
  int v5; // eax
  void *v6; // ebx
  int v7; // eax
  __int64 v8; // rax
  void *v9; // ebx
  char *v10; // eax
  unsigned int v11; // eax
  void *v12; // eax
  bool v13; // bl
  void *v14; // eax
  int v15; // esi
  int v16; // edi
  void *v17; // ebx
  void *v18; // eax
  char v19; // al
  void *v20; // ebx
  int v21; // eax
  char *v22; // ebx
  int *v23; // eax
  int result; // eax
  int v29; // [esp+0h] [ebp-12Ch]
  int v30; // [esp+4h] [ebp-128h]
  int v31; // [esp+8h] [ebp-124h]
  int v32; // [esp+Ch] [ebp-120h]
  int v33; // [esp+10h] [ebp-11Ch]
  int v34; // [esp+14h] [ebp-118h]
  int v35; // [esp+18h] [ebp-114h]
  int v36; // [esp+1Ch] [ebp-110h]
  int v37; // [esp+20h] [ebp-10Ch]
  int v38; // [esp+24h] [ebp-108h]
  int v39; // [esp+28h] [ebp-104h]
  int v40; // [esp+2Ch] [ebp-100h]
  int v41; // [esp+30h] [ebp-FCh]
  int v42; // [esp+34h] [ebp-F8h]
  int v43; // [esp+6Ch] [ebp-C0h]
  int v44; // [esp+70h] [ebp-BCh]
  int v45; // [esp+74h] [ebp-B8h]
  int v46; // [esp+78h] [ebp-B4h]
  _BOOL4 v47; // [esp+7Ch] [ebp-B0h]
  bool v48; // [esp+87h] [ebp-A5h]
  char v49; // [esp+88h] [ebp-A4h]
  unsigned __int8 v50; // [esp+89h] [ebp-A3h]
  unsigned __int8 v51; // [esp+8Ah] [ebp-A2h]
  unsigned __int8 v52; // [esp+8Bh] [ebp-A1h]
  unsigned __int8 v53; // [esp+8Ch] [ebp-A0h]
  unsigned __int8 v54; // [esp+8Dh] [ebp-9Fh]
  unsigned __int8 v55; // [esp+8Eh] [ebp-9Eh]
  bool v56; // [esp+8Fh] [ebp-9Dh]
  void *v57; // [esp+90h] [ebp-9Ch]
  int v58; // [esp+94h] [ebp-98h]
  int v59; // [esp+98h] [ebp-94h]
  int v60; // [esp+9Ch] [ebp-90h]
  int v61; // [esp+A0h] [ebp-8Ch]
  unsigned int v62; // [esp+A4h] [ebp-88h]
  unsigned int v63; // [esp+A8h] [ebp-84h]
  void *v64; // [esp+ACh] [ebp-80h]
  __int64 v65; // [esp+B0h] [ebp-7Ch]
  __int64 v66; // [esp+B8h] [ebp-74h]
  __int64 v67; // [esp+C0h] [ebp-6Ch]
  __int16 v68; // [esp+D0h] [ebp-5Ch]
  __int64 v69; // [esp+ECh] [ebp-40h]
  __int64 v70; // [esp+118h] [ebp-14h]

  v60 = getpagesize();
  v48 = 1;
  v49 = 0;
  v50 = 0;
  v51 = 0;
  v52 = 0;
  v53 = 0;
  v54 = 0;
  v55 = 0;
  v59 = 0;
  sub_804AB27(*argv);
  setlocale(6, &locale);
  bindtextdomain("coreutils", "/home/hwangdz/coreutils/coreutils-8.28/install_m32/share/locale");
  textdomain("coreutils");
  sub_804DA6B((int)sub_804A92C);
  while ( 1 )
  {
    v61 = getopt_long(argc, argv, "benstuvAET", &longopts, 0);
    if ( v61 == -1 )
      break;
    if ( v61 == 98 )
    {
      v50 = 1;
      v51 = 1;
    }
    else if ( v61 > 98 )
    {
      if ( v61 == 115 )
      {
        v52 = 1;
      }
      else if ( v61 > 115 )
      {
        if ( v61 != 117 )
        {
          if ( v61 < 117 )
          {
            v55 = 1;
            v54 = 1;
          }
          else
          {
            if ( v61 != 118 )
              goto LABEL_33;
            v54 = 1;
          }
        }
      }
      else if ( v61 == 101 )
      {
        v53 = 1;
        v54 = 1;
      }
      else
      {
        if ( v61 != 110 )
          goto LABEL_33;
        v50 = 1;
      }
    }
    else if ( v61 == 65 )
    {
      v54 = 1;
      v53 = 1;
      v55 = 1;
    }
    else
    {
      if ( v61 <= 65 )
      {
        if ( v61 == -131 )
        {
          sub_804CB26(
            stdout,
            (int)"cat",
            (int)"GNU coreutils",
            off_8052158,
            "Torbjorn Granlund",
            "Richard M. Stallman",
            0);
          exit(0);
        }
        if ( v61 != -130 )
LABEL_33:
          sub_8049792(1);
        goto LABEL_30;
      }
      if ( v61 != 69 )
      {
        if ( v61 != 84 )
          goto LABEL_33;
        v55 = 1;
        dword_8052100 = (int)&loc_804A217;
        sub_804DBD5();
LABEL_30:
        sub_8049792(0);
      }
      v53 = 1;
    }
  }
  if ( sub_804DA9A(1, (int)&v67) < 0 )
  {
    v2 = gettext("standard output");
    v3 = __errno_location();
    error(1, *v3, v2);
  }
  qmemcpy(&v29, &v67, 0x60u);
  v62 = sub_8049750(v29, v30, v31, v32, v33, v34, v35, v36, v37, v38, v39, v40, v41, v42);
  v65 = v67;
  v66 = v70;
  v56 = (unsigned __int16)(v68 & 0xF000) == 0x8000;
  if ( v50 != 1 && v53 != 1 && v52 != 1 )
  {
    v30 = 0;
    v29 = 1;
    sub_804CE72();
  }
  s1 = "-";
  v58 = optind;
  do
  {
    if ( v58 < argc )
      s1 = argv[v58];
    if ( !strcmp(s1, "-") )
    {
      v49 = 1;
      fd = 0;
    }
    else
    {
      fd = open64(s1, v59);
      if ( fd < 0 )
      {
        v4 = sub_804C195(0, 3, (int)s1);
        v5 = *__errno_location();
        v32 = (int)v4;
        error(0, v5, "%s", v4);
        v48 = 0;
        goto LABEL_68;
      }
    }
    if ( sub_804DA9A(fd, (int)&v67) >= 0 )
    {
      qmemcpy(&v29, &v67, 0x60u);
      v63 = sub_8049750(v29, v30, v31, v32, v33, v34, v35, v36, v37, v38, v39, v40, v41, v42);
      sub_804AA10(fd, 0, 0, 0, 0, 2);
      if ( v56 && v65 == v67 && v66 == v70 && (LODWORD(v8) = lseek64(fd, 0, 0, 1), v8 < v69) )
      {
        v9 = sub_804C195(0, 3, (int)s1);
        v10 = gettext("%s: input file is output file");
        v32 = (int)v9;
        error(0, 0, v10, v9);
        v48 = 0;
      }
      else
      {
        if ( v50 == 1 || v53 == 1 || v54 == 1 || v55 == 1 || v52 == 1 )
        {
          v57 = sub_804CCE2(v63 + v60);
          v29 = v62 + 4 * v63 + v60 + 18;
          v64 = sub_804CCE2(v29);
          v47 = v48;
          v15 = v52;
          v16 = v53;
          v46 = v51;
          v45 = v50;
          v44 = v55;
          v43 = v54;
          v17 = (void *)sub_804956C((int)v64, v60);
          v18 = (void *)sub_804956C((int)v57, v60);
          v19 = sub_8049AAD(v18, v63, v17, v62, v43, v44, v45, v46, v16, v15);
          v48 = (unsigned __int8)(v47 & v19) != 0;
          free(v64);
        }
        else
        {
          v11 = v63;
          if ( v62 >= v63 )
            v11 = v62;
          v63 = v11;
          v29 = v11 + v60 - 1;
          v12 = sub_804CCE2(v29);
          v57 = v12;
          v13 = v48;
          v14 = (void *)sub_804956C((int)v12, v60);
          v48 = (v13 & (unsigned __int8)sub_8049945(v14, v63)) != 0;
        }
        free(v57);
      }
    }
    else
    {
      v6 = sub_804C195(0, 3, (int)s1);
      v7 = *__errno_location();
      v32 = (int)v6;
      error(0, v7, "%s", v6);
      v48 = 0;
    }
    if ( strcmp(s1, "-") && close(fd) < 0 )
    {
      v20 = sub_804C195(0, 3, (int)s1);
      v21 = *__errno_location();
      v32 = (int)v20;
      error(0, v21, "%s", v20);
      v48 = 0;
    }
LABEL_68:
    ++v58;
  }
  while ( v58 < argc );
  if ( v49 && close(0) < 0 )
  {
    v22 = gettext("closing standard input");
    v23 = __errno_location();
    error(1, *v23, v22);
  }
  _CF = 0;
  _OF = 0;
  _ZF = v48 == 0;
  _SF = v48 < 0;
  if ( !v48 )
    return 1;
  __asm { pushfw }
  result = 0;
  __asm { popfw }
  return result;
}
// 8048C50: using guessed type int __cdecl open64(_DWORD, _DWORD);
// 8048F60: using guessed type int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD);
// 804DBD5: using guessed type int sub_804DBD5(void);
// 8052100: using guessed type int dword_8052100;
// 80521E0: using guessed type int optind;

//----- (0804A92C) --------------------------------------------------------
int sub_804A92C()
{
  void *v0; // ebx
  int *v1; // eax
  int *v2; // eax
  int result; // eax
  char *v4; // [esp+2Ch] [ebp-Ch]

  if ( sub_804CFB6(stdout) && (byte_80522A0 != 1 || *__errno_location() != 32) )
  {
    v4 = gettext("write error");
    if ( dword_805229C )
    {
      v0 = sub_804C158(dword_805229C);
      v1 = __errno_location();
      error(0, *v1, "%s: %s", v0, v4);
    }
    else
    {
      v2 = __errno_location();
      error(0, *v2, "%s", v4);
    }
    _exit(status);
  }
  result = sub_804CFB6(stderr);
  if ( result )
    _exit(status);
  return result;
}
// 805229C: using guessed type int dword_805229C;
// 80522A0: using guessed type char byte_80522A0;

//----- (0804AA10) --------------------------------------------------------
int __cdecl sub_804AA10(int a1, int a2, int a3, int a4, int a5, int a6)
{
  return posix_fadvise64(a1, a2, a3, a4, a5, a6);
}
// 8048F80: using guessed type int __cdecl posix_fadvise64(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804AAA9) --------------------------------------------------------
int __cdecl sub_804AAA9(int fd, int a2, size_t n)
{
  int v4; // [esp+Ch] [ebp-1Ch]
  int v5; // [esp+14h] [ebp-14h]
  void *buf; // [esp+18h] [ebp-10h]
  int v7; // [esp+1Ch] [ebp-Ch]

  v5 = 0;
  buf = (void *)a2;
  dword_8052100 = (int)&loc_804AB1C;
  sub_804DBD5();
  do
  {
    v7 = sub_804C44A(fd, buf, n, v4);
    if ( v7 == -1 )
      break;
    if ( !v7 )
    {
      *__errno_location() = 28;
      return v5;
    }
    v5 += v7;
    buf = (char *)buf + v7;
    n -= v7;
  }
  while ( n );
  return v5;
}
// 804DBD5: using guessed type int sub_804DBD5(void);
// 8052100: using guessed type int dword_8052100;

//----- (0804AB27) --------------------------------------------------------
char *__cdecl sub_804AB27(char *s)
{
  char *v1; // eax
  char *result; // eax
  char *v3; // [esp+18h] [ebp-10h]
  char *s1; // [esp+1Ch] [ebp-Ch]

  if ( !s )
  {
    fwrite("A NULL argv[0] was passed through an exec system call.\n", 1u, 0x37u, stderr);
    abort();
  }
  v3 = strrchr(s, 47);
  if ( v3 )
    v1 = v3 + 1;
  else
    v1 = s;
  s1 = v1;
  if ( v1 - s > 6 && !strncmp(v1 - 7, "/.libs/", 7u) )
  {
    s = s1;
    if ( !strncmp(s1, "lt-", 3u) )
    {
      s = s1 + 3;
      program_invocation_short_name = (int)(s1 + 3);
    }
  }
  dword_80522A4 = (int)s;
  result = s;
  program_invocation_name = (int)s;
  return result;
}
// 80521C0: using guessed type int program_invocation_short_name;
// 80521D0: using guessed type int program_invocation_name;
// 80522A4: using guessed type int dword_80522A4;

//----- (0804AC73) --------------------------------------------------------
int __cdecl sub_804AC73(int *a1, unsigned __int8 a2, char a3)
{
  int *v3; // eax
  int v4; // ST10_4

  if ( a1 )
    v3 = a1;
  else
    v3 = &dword_80522C4;
  v4 = ((unsigned int)v3[(a2 >> 5) + 2] >> (a2 & 0x1F)) & 1;
  v3[(a2 >> 5) + 2] ^= (v4 ^ a3 & 1) << (a2 & 0x1F);
  return v4;
}
// 80522C4: using guessed type int dword_80522C4;

//----- (0804AD1D) --------------------------------------------------------
int *__cdecl sub_804AD1D(int *a1, int a2, int a3)
{
  int *result; // eax

  if ( !a1 )
    a1 = &dword_80522C4;
  *a1 = 10;
  if ( !a2 || !a3 )
    abort();
  a1[10] = a2;
  result = a1;
  a1[11] = a3;
  return result;
}
// 80522C4: using guessed type int dword_80522C4;

//----- (0804AD5E) --------------------------------------------------------
_DWORD *__userpurge sub_804AD5E@<eax>(_DWORD *a1, int a2)
{
  int v3; // [esp+0h] [ebp-38h]
  int v4; // [esp+4h] [ebp-34h]
  int v5; // [esp+8h] [ebp-30h]
  int v6; // [esp+Ch] [ebp-2Ch]
  int v7; // [esp+10h] [ebp-28h]
  int v8; // [esp+14h] [ebp-24h]
  int v9; // [esp+18h] [ebp-20h]
  int v10; // [esp+1Ch] [ebp-1Ch]
  int v11; // [esp+20h] [ebp-18h]
  int v12; // [esp+24h] [ebp-14h]
  int v13; // [esp+28h] [ebp-10h]
  int v14; // [esp+2Ch] [ebp-Ch]

  memset(&v3, 0, 0x30u);
  if ( a2 == 10 )
    abort();
  *a1 = a2;
  a1[1] = v4;
  a1[2] = v5;
  a1[3] = v6;
  a1[4] = v7;
  a1[5] = v8;
  a1[6] = v9;
  a1[7] = v10;
  a1[8] = v11;
  a1[9] = v12;
  a1[10] = v13;
  a1[11] = v14;
  return a1;
}

//----- (0804ADE1) --------------------------------------------------------
const char *__cdecl sub_804ADE1(char *msgid, int a2)
{
  const char *result; // eax
  char *v3; // [esp+18h] [ebp-10h]
  unsigned __int8 *v4; // [esp+1Ch] [ebp-Ch]

  v3 = gettext(msgid);
  if ( v3 != msgid )
    return v3;
  v4 = (unsigned __int8 *)sub_804D50F();
  if ( sub_804CF50(v4, "UTF-8") )
  {
    if ( sub_804CF50(v4, "GB18030") )
    {
      if ( a2 == 9 )
        result = (const char *)&unk_804E50D;
      else
        result = "'";
    }
    else if ( *msgid == 96 )
    {
      result = (const char *)&unk_804E506;
    }
    else
    {
      result = (const char *)&unk_804E50A;
    }
  }
  else if ( *msgid == 96 )
  {
    result = (const char *)&unk_804E4F6;
  }
  else
  {
    result = (const char *)&unk_804E4FA;
  }
  return result;
}

//----- (0804AE7C) --------------------------------------------------------
void __cdecl sub_804AE7C(int a1, int a2, int a3, int a4, unsigned int a5, int a6, int a7, int a8, int a9)
{
  bool v9; // ST53_1

  v9 = __ctype_get_mb_cur_max() == 1;
  if ( a5 <= 0xA )
    JUMPOUT(__CS__, off_804E514[a5]);
  abort();
}

//----- (0804B7B8) --------------------------------------------------------
#error "804B9A2: call analysis failed (funcsize=202)"

//----- (0804BB49) --------------------------------------------------------
void *__cdecl sub_804BB49(int a1, int a2, _DWORD *a3, int *a4)
{
  int *v4; // eax
  int *v5; // ST3C_4
  int v6; // ST40_4
  int v7; // ST44_4
  int v8; // eax
  int size; // [esp+48h] [ebp-10h]
  void *v11; // [esp+4Ch] [ebp-Ch]

  if ( a4 )
    v4 = a4;
  else
    v4 = &dword_80522C4;
  v5 = v4;
  v6 = *__errno_location();
  v7 = v5[1] | (a3 == 0);
  sub_804AE7C(0, 0, a1, a2, *v5, v7, (int)(v5 + 2), v5[10], v5[11]);
  size = v8 + 1;
  v11 = sub_804CCCF(v8 + 1);
  sub_804AE7C((int)v11, size, a1, a2, *v5, v7, (int)(v5 + 2), v5[10], v5[11]);
  *__errno_location() = v6;
  if ( a3 )
    *a3 = size - 1;
  return v11;
}
// 80522C4: using guessed type int dword_80522C4;

//----- (0804BCF0) --------------------------------------------------------
void *__cdecl sub_804BCF0(signed int a1, int a2, int a3, unsigned int *a4)
{
  void *v4; // eax
  int *v9; // eax
  void *v10; // edx
  size_t v11; // ST4C_4
  size_t v12; // eax
  bool v14; // [esp+37h] [ebp-21h]
  int *v15; // [esp+38h] [ebp-20h]
  int *v16; // [esp+38h] [ebp-20h]
  void *ptr; // [esp+3Ch] [ebp-1Ch]
  int v18; // [esp+40h] [ebp-18h]
  int size; // [esp+44h] [ebp-14h]
  int v20; // [esp+48h] [ebp-10h]

  v18 = *__errno_location();
  v15 = off_805217C;
  if ( a1 < 0 )
    abort();
  v4 = &loc_804BD37;
  if ( dword_8052170 > a1 )
    v4 = &loc_804BDE7;
  dword_8052100 = (int)v4;
  sub_804DBD5();
  v14 = v15 == &dword_8052174;
  if ( (unsigned int)a1 > 0xFFFFFFE )
    sub_804CE34();
  _CF = 0;
  _OF = 0;
  _ZF = v15 != &dword_8052174;
  _SF = v14 < 0;
  if ( v14 )
  {
    __asm { pushfw }
    v9 = 0;
    __asm { popfw }
  }
  else
  {
    v9 = v15;
  }
  v16 = (int *)sub_804CD0C(v9, 8 * (a1 + 1));
  off_805217C = v16;
  if ( v14 )
  {
    v10 = off_8052178;
    *v16 = dword_8052174;
    v16[1] = (int)v10;
  }
  memset(&v16[2 * dword_8052170], 0, 8 * (a1 + 1 - dword_8052170));
  dword_8052170 = a1 + 1;
  v11 = v16[2 * a1];
  ptr = (void *)v16[2 * a1 + 1];
  v20 = a4[1] | 1;
  sub_804AE7C(v16[2 * a1 + 1], v16[2 * a1], a2, a3, *a4, v20, (int)(a4 + 2), a4[10], a4[11]);
  if ( v11 <= v12 )
  {
    size = v12 + 1;
    v16[2 * a1] = v12 + 1;
    if ( ptr != &unk_8052304 )
      free(ptr);
    ptr = sub_804CCCF(size);
    v16[2 * a1 + 1] = (int)ptr;
    sub_804AE7C((int)ptr, size, a2, a3, *a4, v20, (int)(a4 + 2), a4[10], a4[11]);
  }
  *__errno_location() = v18;
  return ptr;
}
// 804DBD5: using guessed type int sub_804DBD5(void);
// 8052100: using guessed type int dword_8052100;
// 8052170: using guessed type int dword_8052170;
// 8052174: using guessed type int dword_8052174;
// 8052178: using guessed type void *off_8052178;
// 805217C: using guessed type int *off_805217C;

//----- (0804BF2F) --------------------------------------------------------
void *__cdecl sub_804BF2F(signed int a1, int a2)
{
  return sub_804BCF0(a1, a2, -1, (unsigned int *)&dword_80522C4);
}
// 80522C4: using guessed type int dword_80522C4;

//----- (0804BF59) --------------------------------------------------------
void *__cdecl sub_804BF59(signed int a1, int a2, int a3)
{
  return sub_804BCF0(a1, a2, a3, (unsigned int *)&dword_80522C4);
}
// 80522C4: using guessed type int dword_80522C4;

//----- (0804BFBF) --------------------------------------------------------
void *__cdecl sub_804BFBF(signed int a1, int a2, int a3)
{
  unsigned int v4[14]; // [esp+10h] [ebp-38h]

  sub_804AD5E(v4, a2);
  return sub_804BCF0(a1, a3, -1, v4);
}

//----- (0804BFFD) --------------------------------------------------------
void *__cdecl sub_804BFFD(signed int a1, int a2, int a3, int a4)
{
  unsigned int v5[14]; // [esp+10h] [ebp-38h]

  sub_804AD5E(v5, a2);
  return sub_804BCF0(a1, a3, a4, v5);
}

//----- (0804C03A) --------------------------------------------------------
void *__cdecl sub_804C03A(int a1, int a2)
{
  return sub_804BFBF(0, a1, a2);
}

//----- (0804C085) --------------------------------------------------------
void *__cdecl sub_804C085(int a1, int a2, unsigned __int8 a3)
{
  int v4; // [esp+20h] [ebp-38h]
  int v5; // [esp+24h] [ebp-34h]
  int v6; // [esp+28h] [ebp-30h]
  int v7; // [esp+2Ch] [ebp-2Ch]
  int v8; // [esp+30h] [ebp-28h]
  int v9; // [esp+34h] [ebp-24h]
  int v10; // [esp+38h] [ebp-20h]
  int v11; // [esp+3Ch] [ebp-1Ch]
  int v12; // [esp+40h] [ebp-18h]
  int v13; // [esp+44h] [ebp-14h]
  int v14; // [esp+48h] [ebp-10h]
  int v15; // [esp+4Ch] [ebp-Ch]

  v4 = dword_80522C4;
  v5 = dword_80522C8;
  v6 = dword_80522CC;
  v7 = dword_80522D0;
  v8 = dword_80522D4;
  v9 = dword_80522D8;
  v10 = dword_80522DC;
  v11 = dword_80522E0;
  v12 = dword_80522E4;
  v13 = dword_80522E8;
  v14 = dword_80522EC;
  v15 = dword_80522F0;
  sub_804AC73(&v4, a3, 1);
  return sub_804BCF0(0, a1, a2, (unsigned int *)&v4);
}
// 80522C4: using guessed type int dword_80522C4;
// 80522C8: using guessed type int dword_80522C8;
// 80522CC: using guessed type int dword_80522CC;
// 80522D0: using guessed type int dword_80522D0;
// 80522D4: using guessed type int dword_80522D4;
// 80522D8: using guessed type int dword_80522D8;
// 80522DC: using guessed type int dword_80522DC;
// 80522E0: using guessed type int dword_80522E0;
// 80522E4: using guessed type int dword_80522E4;
// 80522E8: using guessed type int dword_80522E8;
// 80522EC: using guessed type int dword_80522EC;
// 80522F0: using guessed type int dword_80522F0;

//----- (0804C12F) --------------------------------------------------------
void *__cdecl sub_804C12F(int a1, unsigned __int8 a2)
{
  return sub_804C085(a1, -1, a2);
}

//----- (0804C158) --------------------------------------------------------
void *__cdecl sub_804C158(int a1)
{
  return sub_804C12F(a1, 0x3Au);
}

//----- (0804C195) --------------------------------------------------------
void *__cdecl sub_804C195(signed int a1, int a2, int a3)
{
  int v4; // [esp+10h] [ebp-68h]
  int v5; // [esp+14h] [ebp-64h]
  int v6; // [esp+18h] [ebp-60h]
  int v7; // [esp+1Ch] [ebp-5Ch]
  int v8; // [esp+20h] [ebp-58h]
  int v9; // [esp+24h] [ebp-54h]
  int v10; // [esp+28h] [ebp-50h]
  int v11; // [esp+2Ch] [ebp-4Ch]
  int v12; // [esp+30h] [ebp-48h]
  int v13; // [esp+34h] [ebp-44h]
  int v14; // [esp+38h] [ebp-40h]
  int v15; // [esp+3Ch] [ebp-3Ch]
  int v16; // [esp+40h] [ebp-38h]
  int v17; // [esp+44h] [ebp-34h]
  int v18; // [esp+48h] [ebp-30h]
  int v19; // [esp+4Ch] [ebp-2Ch]
  int v20; // [esp+50h] [ebp-28h]
  int v21; // [esp+54h] [ebp-24h]
  int v22; // [esp+58h] [ebp-20h]
  int v23; // [esp+5Ch] [ebp-1Ch]
  int v24; // [esp+60h] [ebp-18h]
  int v25; // [esp+64h] [ebp-14h]
  int v26; // [esp+68h] [ebp-10h]
  int v27; // [esp+6Ch] [ebp-Ch]

  sub_804AD5E(&v4, a2);
  v16 = v4;
  v17 = v5;
  v18 = v6;
  v19 = v7;
  v20 = v8;
  v21 = v9;
  v22 = v10;
  v23 = v11;
  v24 = v12;
  v25 = v13;
  v26 = v14;
  v27 = v15;
  sub_804AC73(&v16, 0x3Au, 1);
  return sub_804BCF0(a1, a3, -1, (unsigned int *)&v16);
}

//----- (0804C236) --------------------------------------------------------
void *__cdecl sub_804C236(signed int a1, int a2, int a3, int a4)
{
  return sub_804C266(a1, a2, a3, a4, -1);
}

//----- (0804C266) --------------------------------------------------------
void *__cdecl sub_804C266(signed int a1, int a2, int a3, int a4, int a5)
{
  int v6; // [esp+10h] [ebp-38h]
  int v7; // [esp+14h] [ebp-34h]
  int v8; // [esp+18h] [ebp-30h]
  int v9; // [esp+1Ch] [ebp-2Ch]
  int v10; // [esp+20h] [ebp-28h]
  int v11; // [esp+24h] [ebp-24h]
  int v12; // [esp+28h] [ebp-20h]
  int v13; // [esp+2Ch] [ebp-1Ch]
  int v14; // [esp+30h] [ebp-18h]
  int v15; // [esp+34h] [ebp-14h]
  int v16; // [esp+38h] [ebp-10h]
  int v17; // [esp+3Ch] [ebp-Ch]

  v6 = dword_80522C4;
  v7 = dword_80522C8;
  v8 = dword_80522CC;
  v9 = dword_80522D0;
  v10 = dword_80522D4;
  v11 = dword_80522D8;
  v12 = dword_80522DC;
  v13 = dword_80522E0;
  v14 = dword_80522E4;
  v15 = dword_80522E8;
  v16 = dword_80522EC;
  v17 = dword_80522F0;
  sub_804AD1D(&v6, a2, a3);
  return sub_804BCF0(a1, a4, a5, (unsigned int *)&v6);
}
// 80522C4: using guessed type int dword_80522C4;
// 80522C8: using guessed type int dword_80522C8;
// 80522CC: using guessed type int dword_80522CC;
// 80522D0: using guessed type int dword_80522D0;
// 80522D4: using guessed type int dword_80522D4;
// 80522D8: using guessed type int dword_80522D8;
// 80522DC: using guessed type int dword_80522DC;
// 80522E0: using guessed type int dword_80522E0;
// 80522E4: using guessed type int dword_80522E4;
// 80522E8: using guessed type int dword_80522E8;
// 80522EC: using guessed type int dword_80522EC;
// 80522F0: using guessed type int dword_80522F0;

//----- (0804C360) --------------------------------------------------------
void *__cdecl sub_804C360(signed int a1, int a2, int a3)
{
  return sub_804BCF0(a1, a2, a3, (unsigned int *)&unk_8052190);
}

//----- (0804C3AB) --------------------------------------------------------
void *__cdecl sub_804C3AB(signed int a1, int a2)
{
  return sub_804C360(a1, a2, -1);
}

//----- (0804C3E8) --------------------------------------------------------
ssize_t __cdecl sub_804C3E8(int fd, void *buf, size_t nbytes)
{
  ssize_t v4; // [esp+1Ch] [ebp-Ch]

  while ( 1 )
  {
    do
    {
      v4 = read(fd, buf, nbytes);
      if ( v4 >= 0 )
        return v4;
    }
    while ( *__errno_location() == 4 );
    if ( *__errno_location() != 22 || nbytes <= 0x7FFFE000 )
      break;
    nbytes = 2147475456;
  }
  return v4;
}

//----- (0804C44A) --------------------------------------------------------
int __cdecl sub_804C44A(int fd, void *buf, size_t n, int a4)
{
  ssize_t v4; // ST1C_4

  v4 = write(fd, buf, n);
  dword_805211C = sub_804C49A;
  if ( v4 >= 0 )
    dword_805211C = (int (__cdecl *)(_DWORD, _DWORD, _DWORD, _DWORD))sub_804C547;
  return dword_805211C(fd, buf, n, a4);
}
// 804C547: using guessed type int sub_804C547();
// 805211C: using guessed type int (__cdecl *dword_805211C)(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804C49A) --------------------------------------------------------
int __cdecl sub_804C49A(int a1, int a2, int a3, int a4)
{
  int v4; // eax

  v4 = *__errno_location();
  dword_805211C = sub_804C4CB;
  if ( v4 == 4 )
    dword_805211C = sub_804C534;
  return dword_805211C(a1, a2, a3, a4);
}
// 805211C: using guessed type int (__cdecl *dword_805211C)(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804C4CB) --------------------------------------------------------
int __cdecl sub_804C4CB(int a1, int a2, int a3, unsigned int a4)
{
  int v4; // eax

  v4 = *__errno_location();
  dword_805211C = (int (__cdecl *)(_DWORD, _DWORD, _DWORD, _DWORD))sub_804C51E;
  if ( v4 == 22 )
  {
    dword_805211C = (int (__cdecl *)(_DWORD, _DWORD, _DWORD, _DWORD))sub_804C51E;
    if ( a4 > 0x7FFFE000 )
    {
      a4 = 2147475456;
      dword_805211C = sub_804C534;
    }
  }
  return dword_805211C(a1, a2, a3, a4);
}
// 805211C: using guessed type int (__cdecl *dword_805211C)(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804C51E) --------------------------------------------------------
int __usercall sub_804C51E@<eax>(int a1@<ebp>, int a2, int a3, int a4, int a5)
{
  int v5; // eax

  v5 = *(_DWORD *)(a1 - 12);
  dword_805211C = (int (__cdecl *)(_DWORD, _DWORD, _DWORD, _DWORD))sub_804C547;
  return ((int (__cdecl *)(int, int, int, int))sub_804C547)(a2, a3, a4, a5);
}
// 804C547: using guessed type int sub_804C547();
// 805211C: using guessed type int (__cdecl *dword_805211C)(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804C534) --------------------------------------------------------
int __cdecl sub_804C534(int a1, int a2, int a3, int a4)
{
  dword_805211C = (int (__cdecl *)(_DWORD, _DWORD, _DWORD, _DWORD))&loc_804C450;
  return ((int (__cdecl *)(int, int, int, int))loc_804C450)(a1, a2, a3, a4);
}
// 805211C: using guessed type int (__cdecl *dword_805211C)(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804C547) --------------------------------------------------------
#error "804C548: positive sp value has been found (funcsize=0)"

//----- (0804C549) --------------------------------------------------------
int __cdecl sub_804C549(FILE *stream, int a2, int a3, int a4, int a5, int a6)
{
  char *v6; // eax
  char *v7; // eax
  int v8; // edi
  int v9; // ST4C_4
  int v10; // ST48_4
  int v11; // ST44_4
  int v12; // ST40_4
  int v13; // ST3C_4
  int v14; // ST38_4
  int v15; // esi
  int v16; // ebx
  char *v17; // eax

  if ( a2 )
    fprintf(stream, "%s (%s) %s\n", a2, a3, a4);
  else
    fprintf(stream, "%s %s\n", a3, a4);
  v6 = gettext("(C)");
  fprintf(stream, "Copyright %s %d Free Software Foundation, Inc.", v6, 2017);
  v7 = gettext(
         "\n"
         "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.\n"
         "This is free software: you are free to change and redistribute it.\n"
         "There is NO WARRANTY, to the extent permitted by law.\n"
         "\n");
  fputs_unlocked(v7, stream);
  if ( (unsigned int)a6 <= 9 )
    JUMPOUT(__CS__, *(&off_804EA9C + a6));
  v8 = *(_DWORD *)(a5 + 32);
  v9 = *(_DWORD *)(a5 + 28);
  v10 = *(_DWORD *)(a5 + 24);
  v11 = *(_DWORD *)(a5 + 20);
  v12 = *(_DWORD *)(a5 + 16);
  v13 = *(_DWORD *)(a5 + 12);
  v14 = *(_DWORD *)(a5 + 8);
  v15 = *(_DWORD *)(a5 + 4);
  v16 = *(_DWORD *)a5;
  v17 = gettext("Written by %s, %s, %s,\n%s, %s, %s, %s,\n%s, %s, and others.\n");
  return fprintf(stream, v17, v16, v15, v14, v13, v12, v11, v10, v9, v8);
}
// 8048E70: using guessed type int __cdecl fputs_unlocked(_DWORD, _DWORD);
// 804EA9C: using guessed type void *;

//----- (0804CAC0) --------------------------------------------------------
int __cdecl sub_804CAC0(FILE *stream, int a2, int a3, int a4, int a5)
{
  int *v5; // eax
  unsigned int i; // [esp+24h] [ebp-34h]
  int v8[12]; // [esp+28h] [ebp-30h]

  for ( i = 0; i <= 9; ++i )
  {
    v5 = (int *)a5;
    a5 += 4;
    v8[i] = *v5;
    if ( !v8[i] )
      break;
  }
  return sub_804C549(stream, a2, a3, a4, (int)v8, i);
}
// 804CAC0: using guessed type int var_30[12];

//----- (0804CB26) --------------------------------------------------------
int sub_804CB26(FILE *stream, int a2, int a3, int a4, ...)
{
  va_list va; // [esp+50h] [ebp+18h]

  va_start(va, a4);
  return sub_804CAC0(stream, a2, a3, a4, (int)va);
}

//----- (0804CC35) --------------------------------------------------------
void *__cdecl sub_804CC35(void *ptr, int a2, int a3)
{
  unsigned int v4; // [esp+1Ch] [ebp-Ch]

  v4 = *(_DWORD *)a2;
  if ( ptr )
  {
    if ( 0x55555554u / a3 <= v4 )
      sub_804CE34();
    v4 += (v4 >> 1) + 1;
  }
  else
  {
    if ( !v4 )
      v4 = (0x40u / a3 == 0) + 0x40u / a3;
    if ( 0x7FFFFFFFu / a3 < v4 )
      sub_804CE34();
  }
  *(_DWORD *)a2 = v4;
  return sub_804CD0C(ptr, a3 * v4);
}

//----- (0804CCCF) --------------------------------------------------------
void *__cdecl sub_804CCCF(size_t size)
{
  return sub_804CCE2(size);
}

//----- (0804CCE2) --------------------------------------------------------
void *__cdecl sub_804CCE2(size_t size)
{
  void *v2; // [esp+1Ch] [ebp-Ch]

  v2 = malloc(size);
  if ( !v2 && size )
    sub_804CE34();
  return v2;
}

//----- (0804CD0C) --------------------------------------------------------
void *__cdecl sub_804CD0C(void *ptr, size_t size)
{
  void *result; // eax
  void *ptra; // [esp+20h] [ebp+8h]

  if ( size || !ptr )
  {
    ptra = realloc(ptr, size);
    if ( !ptra )
    {
      if ( size )
        sub_804CE34();
    }
    result = ptra;
  }
  else
  {
    free(ptr);
    __asm { pushfw }
    result = 0;
    __asm { popfw }
  }
  return result;
}

//----- (0804CDE6) --------------------------------------------------------
void *__cdecl sub_804CDE6(void *src, size_t n)
{
  void *v2; // eax

  v2 = sub_804CCE2(n);
  return memcpy(v2, src, n);
}

//----- (0804CE34) --------------------------------------------------------
void __noreturn sub_804CE34()
{
  char *v0; // eax

  v0 = gettext("memory exhausted");
  error(status, 0, "%s", v0);
  abort();
}

//----- (0804CE6D) --------------------------------------------------------
void sub_804CE6D()
{
  ;
}

//----- (0804CE72) --------------------------------------------------------
void sub_804CE72()
{
  if ( sub_804CF1D() < 0 )
    sub_804CE6D();
}

//----- (0804CE95) --------------------------------------------------------
size_t __cdecl sub_804CE95(wchar_t *pwc, char *s, size_t n, mbstate_t *p)
{
  char v5; // [esp+18h] [ebp-10h]
  size_t v6; // [esp+1Ch] [ebp-Ch]

  if ( !pwc )
    pwc = (wchar_t *)&v5;
  v6 = mbrtowc(pwc, s, n, p);
  if ( v6 <= 0xFFFFFFFD || !n || !((unsigned __int8)sub_804D038(0) ^ 1) )
    return v6;
  *pwc = (unsigned __int8)*s;
  return 1;
}

//----- (0804CF07) --------------------------------------------------------
int sub_804CF07()
{
  int result; // eax

  __asm { pushfw }
  result = 0;
  __asm { popfw }
  return result;
}

//----- (0804CF12) --------------------------------------------------------
int sub_804CF12()
{
  int result; // eax

  __asm { pushfw }
  result = 0;
  __asm { popfw }
  return result;
}

//----- (0804CF1D) --------------------------------------------------------
int sub_804CF1D()
{
  int result; // eax
  int v1; // [esp+14h] [ebp-4h]

  v1 = sub_804CF12();
  if ( v1 )
    result = v1;
  else
    result = sub_804CF07();
  return result;
}

//----- (0804CF50) --------------------------------------------------------
int __cdecl sub_804CF50(unsigned __int8 *a1, unsigned __int8 *a2)
{
  unsigned __int8 *v2; // esi
  unsigned __int8 *v3; // ebx
  int result; // eax
  unsigned __int8 v9; // [esp+1Eh] [ebp-Ah]
  unsigned __int8 v10; // [esp+1Fh] [ebp-9h]

  v2 = a1;
  v3 = a2;
  _CF = a1 < a2;
  _OF = __OFSUB__(a1, a2);
  _ZF = a1 == a2;
  _SF = a1 - a2 < 0;
  if ( a1 == a2 )
  {
    __asm { pushfw }
    result = 0;
    __asm { popfw }
  }
  else
  {
    do
    {
      v9 = sub_804D9BD(*v2);
      v10 = sub_804D9BD(*v3);
      if ( !v9 )
        break;
      ++v2;
      ++v3;
    }
    while ( v9 == v10 );
    result = v9 - v10;
  }
  return result;
}

//----- (0804CFB6) --------------------------------------------------------
int __cdecl sub_804CFB6(FILE *fp)
{
  bool v1; // ST22_1
  unsigned int v6; // eax
  int result; // eax
  bool v8; // [esp+1Dh] [ebp-Bh]
  bool v9; // [esp+1Fh] [ebp-9h]

  v8 = __fpending(fp) != 0;
  v1 = ferror_unlocked(fp) != 0;
  v9 = sub_804D5C2(fp) != 0;
  if ( v1 )
    goto LABEL_11;
  _CF = 0;
  _OF = 0;
  _ZF = v9 == 0;
  _SF = v9 < 0;
  if ( !v9 )
    goto LABEL_12;
  if ( v8
    || (v6 = *__errno_location(),
        _CF = v6 < 9,
        _OF = __OFSUB__(v6, 9),
        _ZF = v6 == 9,
        _SF = (signed int)(v6 - 9) < 0,
        v6 != 9) )
  {
LABEL_11:
    if ( v9 != 1 )
      *__errno_location() = 0;
    result = -1;
  }
  else
  {
LABEL_12:
    __asm { pushfw }
    result = 0;
    __asm { popfw }
  }
  return result;
}

//----- (0804D038) --------------------------------------------------------
int __cdecl sub_804D038(int category)
{
  unsigned __int8 v2; // [esp+1Bh] [ebp-Dh]
  const char *s1; // [esp+1Ch] [ebp-Ch]

  v2 = 1;
  s1 = setlocale(category, 0);
  if ( s1 && (!strcmp(s1, "C") || !strcmp(s1, "POSIX")) )
    v2 = 0;
  return v2;
}

//----- (0804D096) --------------------------------------------------------
void *sub_804D096()
{
  char v4; // al
  signed int v5; // eax
  void *v7; // [esp+18h] [ebp-B0h]
  const char *s; // [esp+1Ch] [ebp-ACh]
  void *v9; // [esp+20h] [ebp-A8h]
  int v10; // [esp+24h] [ebp-A4h]
  signed int n; // [esp+2Ch] [ebp-9Ch]
  size_t v12; // [esp+30h] [ebp-98h]
  signed int v13; // [esp+34h] [ebp-94h]
  char *dest; // [esp+38h] [ebp-90h]
  int fd; // [esp+3Ch] [ebp-8Ch]
  FILE *stream; // [esp+40h] [ebp-88h]
  int c; // [esp+44h] [ebp-84h]
  int ca; // [esp+44h] [ebp-84h]
  size_t v19; // [esp+48h] [ebp-80h]
  size_t v20; // [esp+4Ch] [ebp-7Ch]
  void *v21; // [esp+50h] [ebp-78h]
  char src; // [esp+56h] [ebp-72h]
  char v23; // [esp+89h] [ebp-3Fh]
  unsigned int v24; // [esp+BCh] [ebp-Ch]

  v24 = __readgsdword(0x14u);
  v7 = (void *)dword_8052404;
  if ( !dword_8052404 )
  {
    s = getenv("CHARSETALIASDIR");
    if ( !s || !*s )
      s = "/home/hwangdz/coreutils/coreutils-8.28/install_m32/lib";
    n = strlen(s);
    v12 = strlen("charset.alias");
    _CF = 0;
    _OF = 0;
    _ZF = n == 0;
    _SF = n < 0;
    if ( n
      && (v4 = s[n - 1],
          _CF = (unsigned __int8)v4 < 0x2Fu,
          _OF = __OFSUB__(v4, 47),
          _ZF = v4 == 47,
          _SF = (char)(v4 - 47) < 0,
          v4 != 47) )
    {
      v5 = 1;
    }
    else
    {
      __asm { pushfw }
      v5 = 0;
      __asm { popfw }
    }
    v13 = v5;
    dest = (char *)malloc(n + v5 + v12 + 1);
    if ( dest )
    {
      memcpy(dest, s, n);
      if ( v13 )
        dest[n] = 47;
      memcpy(&dest[n + v13], "charset.alias", v12 + 1);
    }
    free(0);
    if ( dest )
    {
      fd = open64(dest, 0x20000);
      if ( fd >= 0 )
      {
        stream = fdopen(fd, "r");
        if ( stream )
        {
          v9 = 0;
          v10 = 0;
          while ( 1 )
          {
            c = getc_unlocked(stream);
            if ( c == -1 )
              break;
            if ( c != 10 && c != 32 && c != 9 )
            {
              if ( c == 35 )
              {
                do
                  ca = getc_unlocked(stream);
                while ( ca != -1 && ca != 10 );
                if ( ca == -1 )
                  break;
              }
              else
              {
                ungetc(c, stream);
                if ( fscanf(stream, "%50s %50s", &src, &v23) <= 1 )
                  break;
                v19 = strlen(&src);
                v20 = strlen(&v23);
                v21 = v9;
                if ( v10 )
                {
                  v10 += v20 + v19 + 2;
                  v9 = realloc(v9, v10 + 1);
                }
                else
                {
                  v10 = v19 + v20 + 2;
                  v9 = malloc(v19 + v20 + 3);
                }
                if ( !v9 )
                {
                  v10 = 0;
                  free(v21);
                  break;
                }
                strcpy((char *)v9 + v10 - v20 - v19 - 2, &src);
                strcpy((char *)v9 + v10 - v20 - 1, &v23);
              }
            }
          }
          sub_804D5C2(stream);
          if ( v10 )
          {
            *((_BYTE *)v9 + v10) = 0;
            v7 = v9;
          }
          else
          {
            v7 = &unk_804EC2B;
          }
        }
        else
        {
          close(fd);
          v7 = &unk_804EC2B;
        }
      }
      else
      {
        v7 = &unk_804EC2B;
      }
      free(dest);
    }
    else
    {
      v7 = &unk_804EC2B;
    }
    dword_8052404 = (int)v7;
  }
  return v7;
}
// 8048C50: using guessed type int __cdecl open64(_DWORD, _DWORD);
// 8052404: using guessed type int dword_8052404;

//----- (0804D50F) --------------------------------------------------------
const char *sub_804D50F()
{
  char *v0; // ST1C_4
  const char *s1; // [esp+18h] [ebp-10h]
  char *s2; // [esp+1Ch] [ebp-Ch]

  s1 = nl_langinfo(14);
  if ( !s1 )
    s1 = (const char *)&unk_804EC2B;
  for ( s2 = (char *)sub_804D096(); *s2; s2 = &v0[strlen(v0) + 1] )
  {
    if ( !strcmp(s1, s2) || *s2 == 42 && !s2[1] )
    {
      s1 = &s2[strlen(s2) + 1];
      break;
    }
    v0 = &s2[strlen(s2) + 1];
  }
  if ( !*s1 )
    s1 = "ASCII";
  return s1;
}

//----- (0804D5C2) --------------------------------------------------------
int __cdecl sub_804D5C2(FILE *stream)
{
  int v2; // eax
  __int64 v3; // rax
  int v4; // [esp+14h] [ebp-14h]
  int v5; // [esp+18h] [ebp-10h]

  v4 = 0;
  if ( fileno(stream) < 0 )
    return fclose(stream);
  if ( !__freading(stream) || (v2 = fileno(stream), LODWORD(v3) = lseek64(v2, 0, 0, 1), v3 != -1) )
  {
    if ( sub_804D6BE(stream) )
      v4 = *__errno_location();
  }
  v5 = fclose(stream);
  if ( v4 )
  {
    *__errno_location() = v4;
    v5 = -1;
  }
  return v5;
}
// 8048F60: using guessed type int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (0804D685) --------------------------------------------------------
int __cdecl sub_804D685(FILE *stream)
{
  int result; // eax

  result = stream->_flags & 0x100;
  if ( result )
    result = sub_804D6FE(stream, 0, 0, 1);
  return result;
}

//----- (0804D6BE) --------------------------------------------------------
int __cdecl sub_804D6BE(FILE *fp)
{
  if ( !fp || !__freading(fp) )
    return fflush(fp);
  sub_804D685(fp);
  return fflush(fp);
}

//----- (0804D6FE) --------------------------------------------------------
int __cdecl sub_804D6FE(FILE *stream, int a2, int a3, int a4)
{
  void *v4; // eax
  int v5; // eax
  __off64_t v6; // rax
  int result; // eax

  if ( stream->_IO_read_end != stream->_IO_read_ptr || stream->_IO_write_ptr != stream->_IO_write_base )
    return fseeko64(stream, a2, a3, a4);
  v4 = &loc_804D75B;
  if ( stream->_IO_save_base )
    v4 = &loc_804D7CC;
  dword_8052100 = (int)v4;
  sub_804DBD5();
  v5 = fileno(stream);
  LODWORD(v6) = lseek64(v5, a2, a3, a4);
  if ( v6 == -1 )
    return -1;
  _CF = 0;
  _OF = 0;
  _ZF = (stream->_flags & 0xFFFFFFEF) == 0;
  _SF = (stream->_flags & 0xFFFFFFEF & 0x80000000) != 0;
  stream->_flags &= 0xFFFFFFEF;
  stream->_offset = v6;
  __asm { pushfw }
  result = 0;
  __asm { popfw }
  return result;
}
// 8048D00: using guessed type int __cdecl fseeko64(_DWORD, _DWORD, _DWORD, _DWORD);
// 8048F60: using guessed type int __cdecl lseek64(_DWORD, _DWORD, _DWORD, _DWORD);
// 804DBD5: using guessed type int sub_804DBD5(void);
// 8052100: using guessed type int dword_8052100;

//----- (0804D9BD) --------------------------------------------------------
int __cdecl sub_804D9BD(int a1)
{
  int result; // eax

  if ( (unsigned int)(a1 - 65) > 0x19 )
    result = a1;
  else
    result = a1 + 32;
  return result;
}

//----- (0804DA6B) --------------------------------------------------------
int __cdecl sub_804DA6B(int a1)
{
  return __cxa_atexit(a1, 0, dword_8052134);
}
// 8048DE0: using guessed type int __cdecl __cxa_atexit(_DWORD, _DWORD, _DWORD);
// 8052134: using guessed type int dword_8052134;

//----- (0804DA9A) --------------------------------------------------------
int __cdecl sub_804DA9A(int a1, int a2)
{
  return __fxstat64(3, a1, a2);
}
// 8048D90: using guessed type int __cdecl __fxstat64(_DWORD, _DWORD, _DWORD);

//----- (0804DBD5) --------------------------------------------------------
#error "804DBDB: positive sp value has been found (funcsize=0)"

//----- (0804DBF0) --------------------------------------------------------
int (**sub_804DBF0())()
{
  int (**result)(); // eax
  int v1; // esi
  int v2; // edi

  init_proc();
  result = off_8051EF8;
  v1 = &off_8051EFC - off_8051EF8;
  if ( v1 )
  {
    v2 = 0;
    do
      result = (int (**)())off_8051EF8[v2++]();
    while ( v1 != v2 );
  }
  return result;
}
// 8051EF8: using guessed type int (*off_8051EF8[2])();
// 8051EFC: using guessed type int (*off_8051EFC)();

//----- (0804DC54) --------------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 4 decompilation failure(s) on 93 function(s)"
